INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '9d78af40-3638-42c3-995f-ffb61ca55a0c',
      'Definition of Module Pattern',
      'What is the Module Pattern in JavaScript and why is it used?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The Module Pattern is a design pattern that uses closures to create private and public encapsulation. It is used to avoid polluting the global scope and to create reusable, maintainable code structures.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-41","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'd7cbfd0d-20a5-49c9-9de2-ef4006f5f7b5',
      'Basic Module Syntax',
      'Which of the following correctly implements a simple Module Pattern in JavaScript?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"function Module() { var x = 10; return x; }","isCorrect":false,"explanation":""},{"id":"b","text":"var Module = (function(){ var privateVar = 10; return { get: function(){ return privateVar; } }; })();","isCorrect":true,"explanation":""},{"id":"c","text":"let Module = class { constructor(){ this.x = 10; } }","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: var Module = (function(){ var privateVar = 10; return { get: function(){ return privateVar; } }; })();',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-42","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '913131d6-9cc0-4ea3-af3a-1f3ad2c236dd',
      'Encapsulation in Module Pattern',
      'How does the Module Pattern achieve encapsulation?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'By using an Immediately Invoked Function Expression (IIFE) to create a private scope. Only the returned object exposes public members, while variables/functions inside the closure remain private.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-43","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '4ae99cf3-2dc0-4f1b-9465-4f5f4cb0b55e',
      'Drawback of Module Pattern',
      'Which of the following is a drawback of the Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"It makes code modular and organized","isCorrect":false,"explanation":""},{"id":"b","text":"Private members cannot be accessed or modified without changing the original module","isCorrect":true,"explanation":""},{"id":"c","text":"It always requires classes","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: Private members cannot be accessed or modified without changing the original module',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-44","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'd6b4f27d-1bf5-42bf-8ddd-2945c2be1348',
      'Revealing Module Pattern',
      'What is the difference between the classic Module Pattern and the Revealing Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The Revealing Module Pattern maps private functions/variables to a returned object explicitly, improving readability. It makes it clear which functions are public and which remain private.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-45","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '5a35f2dc-ea34-4b91-b752-4800eb53e5ce',
      'Debugging Modules',
      'If you forget to return a method in your Module Pattern, what will happen?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"The method is still accessible globally","isCorrect":false,"explanation":""},{"id":"b","text":"The method remains private and cannot be accessed outside","isCorrect":true,"explanation":""},{"id":"c","text":"JavaScript throws a syntax error","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: The method remains private and cannot be accessed outside',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-46","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '26448ae5-99b4-4207-86d5-19f582dd119d',
      'Module Pattern vs ES6 Modules',
      'How does the Module Pattern differ from ES6 Modules?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Module Pattern relies on closures and IIFEs for encapsulation, while ES6 Modules are built-in language features with `import` and `export`. ES6 Modules are statically analyzed at compile time, while Module Pattern modules are runtime constructs.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-47","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '8f5d0c12-4d72-44e6-9229-623f126ddd78',
      'Use Case of Module Pattern',
      'Which scenario is best suited for the Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"When you want to encapsulate private state in legacy JavaScript without ES6 support","isCorrect":true,"explanation":""},{"id":"b","text":"When you need dynamic imports and tree-shaking","isCorrect":false,"explanation":""},{"id":"c","text":"When you only work with classes","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: When you want to encapsulate private state in legacy JavaScript without ES6 support',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-module-pattern-48","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.690Z',
      '2025-10-21T22:21:12.690Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '835ea354-8e45-4b91-a80f-51254ccece3e',
      'Definition of Observer Pattern',
      'What is the Observer Pattern and why is it useful in JavaScript applications?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The Observer Pattern allows objects (observers) to subscribe to another object (observable) so they get notified when events occur. It’s useful because it enables decoupling and supports event-driven programming.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-49","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.691Z',
      '2025-10-21T22:21:12.691Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '1706eeac-35f9-43f3-ab05-dc56de36d233',
      'Core Components of Observer Pattern',
      'Which three components are essential in the Observer Pattern implementation?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Publisher, renderer, transformer","isCorrect":false,"explanation":""},{"id":"b","text":"Observers, subscribe/unsubscribe, notify","isCorrect":true,"explanation":""},{"id":"c","text":"State, reducer, dispatcher","isCorrect":false,"explanation":""},{"id":"d","text":"Model, view, controller","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: Observers, subscribe/unsubscribe, notify',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-50","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.691Z',
      '2025-10-21T22:21:12.691Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'a8b8a796-bb49-41c9-a1cc-9cb3a79bac7f',
      'Observer Pattern in React',
      'In the example provided, which functions act as observers when subscribed to the observable?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"handleClick and handleToggle","isCorrect":false,"explanation":""},{"id":"b","text":"logger and toastify","isCorrect":true,"explanation":""},{"id":"c","text":"Button and Switch components","isCorrect":false,"explanation":""},{"id":"d","text":"React lifecycle methods","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: logger and toastify',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-51","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.691Z',
      '2025-10-21T22:21:12.691Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '1e4ebd6b-18f9-46a8-b5df-a31c3b6bdea9',
      'Observable Notifications',
      'What happens when the observable''s notify() method is called?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It loops through the observers list and invokes each subscribed function with the provided data. All observers receive the event data at the same time.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-52","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.691Z',
      '2025-10-21T22:21:12.691Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'fa1858c4-80eb-4351-a713-875bb7ea0d11',
      'Practical Use Case',
      'Which scenario is a good use case for the Observer Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Notifying multiple UI components when new messages arrive","isCorrect":true,"explanation":""},{"id":"b","text":"Rendering static content with no user interaction","isCorrect":false,"explanation":""},{"id":"c","text":"Compiling JavaScript code to ES5","isCorrect":false,"explanation":""},{"id":"d","text":"Sorting a list of numbers","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: Notifying multiple UI components when new messages arrive',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-53","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '275e6a10-3bb0-46cb-850b-6b0442b25682',
      'Observer Pattern vs Pub/Sub',
      'What is the key difference between the Observer Pattern and the Publish/Subscribe (Pub/Sub) pattern?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'In Observer, observers subscribe directly to the observable, creating tight coupling. In Pub/Sub, a mediator (event bus) manages communication, decoupling publishers and subscribers.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-54","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '73c5569a-33f3-4766-b1ab-ffa7b9f777e7',
      'Observer Pattern in RxJS',
      'Which popular JavaScript library uses the Observer Pattern extensively?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Redux","isCorrect":false,"explanation":""},{"id":"b","text":"Axios","isCorrect":false,"explanation":""},{"id":"c","text":"RxJS","isCorrect":true,"explanation":""},{"id":"d","text":"Styled Components","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: RxJS',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-55","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'cb645945-6f66-4c66-a407-be239662f367',
      'Performance Concern',
      'What is one potential drawback of the Observer Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Observers cannot be removed once added","isCorrect":false,"explanation":""},{"id":"b","text":"Too many or complex observers can cause performance issues during notifications","isCorrect":true,"explanation":""},{"id":"c","text":"Observable cannot notify multiple observers at once","isCorrect":false,"explanation":""},{"id":"d","text":"It cannot work with asynchronous data","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: Too many or complex observers can cause performance issues during notifications',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-observer-pattern-56","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'b757c98d-0c44-4ed5-9c1e-6e17ab4cfc07',
      'Definition of Prototype Pattern',
      'What is the Prototype Pattern and why is it useful in JavaScript?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The Prototype Pattern allows objects to share properties and methods through the prototype chain. It avoids duplication and reduces memory usage by letting instances inherit methods from the prototype instead of redefining them.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-prototype-pattern-57","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '1e6aa7c6-2e73-4f94-bb7d-1b2371534b17',
      'Prototype vs Instance Properties',
      'In the Dog class example, where is the bark() method stored?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"On each Dog instance","isCorrect":false,"explanation":""},{"id":"b","text":"On Dog.prototype, shared by all instances","isCorrect":true,"explanation":""},{"id":"c","text":"Inside the Dog constructor","isCorrect":false,"explanation":""},{"id":"d","text":"In the global window object","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: On Dog.prototype, shared by all instances',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-prototype-pattern-58","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e5e255cb-6475-4fd4-b242-694e775c78ee',
      'Adding Properties Dynamically',
      'If you add Dog.prototype.play after creating instances, will existing instances have access to play()?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Yes, because all instances reference the same prototype","isCorrect":true,"explanation":""},{"id":"b","text":"No, only future instances get it","isCorrect":false,"explanation":""},{"id":"c","text":"It depends on whether the object was frozen","isCorrect":false,"explanation":""},{"id":"d","text":"JavaScript throws an error","isCorrect":false,"explanation":""}]',
      'c',
      'The correct answer is: Yes, because all instances reference the same prototype',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-prototype-pattern-59","original_type":"multiple-choice","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '24e17cf9-025c-4d41-ad7f-afcb4dd68b19',
      'Prototype Chain',
      'How does JavaScript resolve a property that isn’t found directly on an object?',
      'multiple-choice',
      'beginner',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It traverses the prototype chain via __proto__ until it finds the property or reaches null. This process is called prototype chaining.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-prototype-pattern-60","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.692Z',
      '2025-10-21T22:21:12.692Z'
    );;
