const fs = require('fs');
const path = require('path');

const questionsFile = path.join(__dirname, '../../final-questions-v01/performance-patterns-questions.json');

const newQuestions = [
  {
    "id": "performance-patterns-loading-sequence-1",
    "title": "Understanding Loading Sequence",
    "content": "What is the primary goal of optimizing the loading sequence in web performance?",
    "type": "multiple-choice",
    "category": "Performance Patterns",
    "topic": "Web Performance",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-10T00:00:00Z",
    "updatedAt": "2025-11-11T18:50:32.217Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "performance-patterns",
      "web-performance",
      "beginner",
      "intermediate"
    ],
    "explanation": "Optimizing the loading sequence ensures that critical resources load at the right time, improving perceived performance and metrics like FCP and LCP.",
    "points": 10,
    "options": [
      {
        "0": "T",
        "1": "o",
        "2": " ",
        "3": "i",
        "4": "m",
        "5": "p",
        "6": "r",
        "7": "o",
        "8": "v",
        "9": "e",
        "10": " ",
        "11": "S",
        "12": "E",
        "13": "O",
        "14": " ",
        "15": "r",
        "16": "a",
        "17": "n",
        "18": "k",
        "19": "i",
        "20": "n",
        "21": "g",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "o",
        "2": " ",
        "3": "e",
        "4": "n",
        "5": "h",
        "6": "a",
        "7": "n",
        "8": "c",
        "9": "e",
        "10": " ",
        "11": "p",
        "12": "e",
        "13": "r",
        "14": "c",
        "15": "e",
        "16": "i",
        "17": "v",
        "18": "e",
        "19": "d",
        "20": " ",
        "21": "p",
        "22": "e",
        "23": "r",
        "24": "f",
        "25": "o",
        "26": "r",
        "27": "m",
        "28": "a",
        "29": "n",
        "30": "c",
        "31": "e",
        "32": " ",
        "33": "a",
        "34": "n",
        "35": "d",
        "36": " ",
        "37": "a",
        "38": "c",
        "39": "h",
        "40": "i",
        "41": "e",
        "42": "v",
        "43": "e",
        "44": " ",
        "45": "b",
        "46": "e",
        "47": "t",
        "48": "t",
        "49": "e",
        "50": "r",
        "51": " ",
        "52": "C",
        "53": "o",
        "54": "r",
        "55": "e",
        "56": " ",
        "57": "W",
        "58": "e",
        "59": "b",
        "60": " ",
        "61": "V",
        "62": "i",
        "63": "t",
        "64": "a",
        "65": "l",
        "66": "s",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "o",
        "2": " ",
        "3": "r",
        "4": "e",
        "5": "d",
        "6": "u",
        "7": "c",
        "8": "e",
        "9": " ",
        "10": "t",
        "11": "h",
        "12": "e",
        "13": " ",
        "14": "n",
        "15": "u",
        "16": "m",
        "17": "b",
        "18": "e",
        "19": "r",
        "20": " ",
        "21": "o",
        "22": "f",
        "23": " ",
        "24": "n",
        "25": "e",
        "26": "t",
        "27": "w",
        "28": "o",
        "29": "r",
        "30": "k",
        "31": " ",
        "32": "r",
        "33": "e",
        "34": "q",
        "35": "u",
        "36": "e",
        "37": "s",
        "38": "t",
        "39": "s",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "o",
        "2": " ",
        "3": "p",
        "4": "r",
        "5": "e",
        "6": "v",
        "7": "e",
        "8": "n",
        "9": "t",
        "10": " ",
        "11": "C",
        "12": "S",
        "13": "S",
        "14": " ",
        "15": "a",
        "16": "n",
        "17": "d",
        "18": " ",
        "19": "J",
        "20": "S",
        "21": " ",
        "22": "c",
        "23": "o",
        "24": "n",
        "25": "f",
        "26": "l",
        "27": "i",
        "28": "c",
        "29": "t",
        "30": "s",
        "explanation": ""
      }
    ],
    "sampleAnswers": [
      "To enhance perceived performance and achieve better Core Web Vitals"
    ],
    "hints": [],
    "metadata": {}
  }
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(`✅ Added ${newQuestions.length} questions for Web Performance (Batch 1)`);
console.log(`📝 Total questions: ${existingQuestions.length}`);
