const fs = require('fs');
const path = require('path');

const questionsFile = path.join(__dirname, '../../final-questions-v01/performance-patterns-questions.json');

const newQuestions = [
  {
    "id": "performance-patterns-loading-sequence-4",
    "title": "Third-Party Scripts Impact",
    "content": "How do third-party scripts usually affect page load performance?",
    "type": "multiple-choice",
    "category": "Performance Patterns",
    "topic": "Third-Party Performance",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-10T00:00:00Z",
    "updatedAt": "2025-11-11T18:50:32.217Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "performance-patterns",
      "third-party-performance",
      null,
      "intermediate"
    ],
    "explanation": "Third-party scripts like ads or analytics often block rendering or delay other resources, harming metrics like FID and LCP.",
    "points": 10,
    "options": [
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "y",
        "4": " ",
        "5": "o",
        "6": "p",
        "7": "t",
        "8": "i",
        "9": "m",
        "10": "i",
        "11": "z",
        "12": "e",
        "13": " ",
        "14": "t",
        "15": "h",
        "16": "e",
        "17": " ",
        "18": "s",
        "19": "e",
        "20": "q",
        "21": "u",
        "22": "e",
        "23": "n",
        "24": "c",
        "25": "e",
        "26": " ",
        "27": "a",
        "28": "u",
        "29": "t",
        "30": "o",
        "31": "m",
        "32": "a",
        "33": "t",
        "34": "i",
        "35": "c",
        "36": "a",
        "37": "l",
        "38": "l",
        "39": "y",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "y",
        "4": " ",
        "5": "o",
        "6": "f",
        "7": "t",
        "8": "e",
        "9": "n",
        "10": " ",
        "11": "b",
        "12": "l",
        "13": "o",
        "14": "c",
        "15": "k",
        "16": " ",
        "17": "r",
        "18": "e",
        "19": "n",
        "20": "d",
        "21": "e",
        "22": "r",
        "23": "i",
        "24": "n",
        "25": "g",
        "26": " ",
        "27": "a",
        "28": "n",
        "29": "d",
        "30": " ",
        "31": "d",
        "32": "e",
        "33": "l",
        "34": "a",
        "35": "y",
        "36": " ",
        "37": "c",
        "38": "r",
        "39": "i",
        "40": "t",
        "41": "i",
        "42": "c",
        "43": "a",
        "44": "l",
        "45": " ",
        "46": "r",
        "47": "e",
        "48": "s",
        "49": "o",
        "50": "u",
        "51": "r",
        "52": "c",
        "53": "e",
        "54": " ",
        "55": "l",
        "56": "o",
        "57": "a",
        "58": "d",
        "59": "i",
        "60": "n",
        "61": "g",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "y",
        "4": " ",
        "5": "i",
        "6": "m",
        "7": "p",
        "8": "r",
        "9": "o",
        "10": "v",
        "11": "e",
        "12": " ",
        "13": "C",
        "14": "P",
        "15": "U",
        "16": " ",
        "17": "u",
        "18": "t",
        "19": "i",
        "20": "l",
        "21": "i",
        "22": "z",
        "23": "a",
        "24": "t",
        "25": "i",
        "26": "o",
        "27": "n",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "h",
        "2": "e",
        "3": "y",
        "4": " ",
        "5": "l",
        "6": "o",
        "7": "a",
        "8": "d",
        "9": " ",
        "10": "a",
        "11": "f",
        "12": "t",
        "13": "e",
        "14": "r",
        "15": " ",
        "16": "a",
        "17": "l",
        "18": "l",
        "19": " ",
        "20": "f",
        "21": "i",
        "22": "r",
        "23": "s",
        "24": "t",
        "25": "-",
        "26": "p",
        "27": "a",
        "28": "r",
        "29": "t",
        "30": "y",
        "31": " ",
        "32": "s",
        "33": "c",
        "34": "r",
        "35": "i",
        "36": "p",
        "37": "t",
        "38": "s",
        "39": " ",
        "40": "b",
        "41": "y",
        "42": " ",
        "43": "d",
        "44": "e",
        "45": "f",
        "46": "a",
        "47": "u",
        "48": "l",
        "49": "t",
        "explanation": ""
      }
    ],
    "sampleAnswers": [
      "They often block rendering and delay critical resource loading"
    ],
    "hints": [],
    "metadata": {}
  }
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(`✅ Added ${newQuestions.length} questions for Third-Party Performance (Batch 1)`);
console.log(`📝 Total questions: ${existingQuestions.length}`);
