const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/performance-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'performance-patterns-dynamic-import-20',
    title: 'Why does dynamic import improve the user experience?',
    content:
      'It lets the app load faster by deferring non-critical resources, making the UI interactive sooner.',
    type: 'mcq',
    category: 'Performance Patterns',
    topic: 'Performance UX',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.188Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: ['performance-patterns', 'performance-ux', null, 'intermediate'],
    explanation:
      'By deferring low-priority code, dynamic imports shorten Time to Interactive (TTI) and improve perceived performance.',
    points: 10,
    options: [
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'p',
        4: 'r',
        5: 'e',
        6: 'l',
        7: 'o',
        8: 'a',
        9: 'd',
        10: 's',
        11: ' ',
        12: 'e',
        13: 'v',
        14: 'e',
        15: 'r',
        16: 'y',
        17: 't',
        18: 'h',
        19: 'i',
        20: 'n',
        21: 'g',
        22: ' ',
        23: 'a',
        24: 't',
        25: ' ',
        26: 'o',
        27: 'n',
        28: 'c',
        29: 'e',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'b',
        4: 'l',
        5: 'o',
        6: 'c',
        7: 'k',
        8: 's',
        9: ' ',
        10: 'r',
        11: 'e',
        12: 'n',
        13: 'd',
        14: 'e',
        15: 'r',
        16: 'i',
        17: 'n',
        18: 'g',
        19: ' ',
        20: 'u',
        21: 'n',
        22: 't',
        23: 'i',
        24: 'l',
        25: ' ',
        26: 'a',
        27: 'l',
        28: 'l',
        29: ' ',
        30: 'f',
        31: 'i',
        32: 'l',
        33: 'e',
        34: 's',
        35: ' ',
        36: 'a',
        37: 'r',
        38: 'e',
        39: ' ',
        40: 'l',
        41: 'o',
        42: 'a',
        43: 'd',
        44: 'e',
        45: 'd',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'r',
        4: 'e',
        5: 'd',
        6: 'u',
        7: 'c',
        8: 'e',
        9: 's',
        10: ' ',
        11: 'i',
        12: 'n',
        13: 'i',
        14: 't',
        15: 'i',
        16: 'a',
        17: 'l',
        18: ' ',
        19: 'b',
        20: 'u',
        21: 'n',
        22: 'd',
        23: 'l',
        24: 'e',
        25: ' ',
        26: 's',
        27: 'i',
        28: 'z',
        29: 'e',
        30: ' ',
        31: 'a',
        32: 'n',
        33: 'd',
        34: ' ',
        35: 'i',
        36: 'm',
        37: 'p',
        38: 'r',
        39: 'o',
        40: 'v',
        41: 'e',
        42: 's',
        43: ' ',
        44: 'i',
        45: 'n',
        46: 't',
        47: 'e',
        48: 'r',
        49: 'a',
        50: 'c',
        51: 't',
        52: 'i',
        53: 'v',
        54: 'i',
        55: 't',
        56: 'y',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'd',
        4: 'i',
        5: 's',
        6: 'a',
        7: 'b',
        8: 'l',
        9: 'e',
        10: 's',
        11: ' ',
        12: 'a',
        13: 'n',
        14: 'i',
        15: 'm',
        16: 'a',
        17: 't',
        18: 'i',
        19: 'o',
        20: 'n',
        21: 's',
        22: ' ',
        23: 't',
        24: 'o',
        25: ' ',
        26: 's',
        27: 'p',
        28: 'e',
        29: 'e',
        30: 'd',
        31: ' ',
        32: 'u',
        33: 'p',
        34: ' ',
        35: 'U',
        36: 'I',
        explanation: '',
      },
    ],
    sampleAnswers: [
      'It reduces initial bundle size and improves interactivity',
    ],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Performance UX (Batch 1)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
