const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/performance-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'performance-patterns-compression-3',
    title: 'Which compression algorithm provides better compression ratios?',
    content:
      'Brotli typically provides smaller file sizes compared to Gzip at similar compression levels.',
    type: 'mcq',
    category: 'Performance Patterns',
    topic: 'Compression Comparison',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.172Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'performance-patterns',
      'compression-comparison',
      null,
      'intermediate',
    ],
    explanation:
      'Brotli achieves denser compression through context modeling and larger dictionary windows, reducing file size effectively.',
    points: 10,
    options: [
      {
        0: 'G',
        1: 'z',
        2: 'i',
        3: 'p',
        4: ' ',
        5: 'h',
        6: 'a',
        7: 's',
        8: ' ',
        9: 'a',
        10: ' ',
        11: 'h',
        12: 'i',
        13: 'g',
        14: 'h',
        15: 'e',
        16: 'r',
        17: ' ',
        18: 'c',
        19: 'o',
        20: 'm',
        21: 'p',
        22: 'r',
        23: 'e',
        24: 's',
        25: 's',
        26: 'i',
        27: 'o',
        28: 'n',
        29: ' ',
        30: 'r',
        31: 'a',
        32: 't',
        33: 'i',
        34: 'o',
        35: ' ',
        36: 't',
        37: 'h',
        38: 'a',
        39: 'n',
        40: ' ',
        41: 'B',
        42: 'r',
        43: 'o',
        44: 't',
        45: 'l',
        46: 'i',
        explanation: '',
      },
      {
        0: 'B',
        1: 'r',
        2: 'o',
        3: 't',
        4: 'l',
        5: 'i',
        6: ' ',
        7: 'h',
        8: 'a',
        9: 's',
        10: ' ',
        11: 'a',
        12: ' ',
        13: 'b',
        14: 'e',
        15: 't',
        16: 't',
        17: 'e',
        18: 'r',
        19: ' ',
        20: 'c',
        21: 'o',
        22: 'm',
        23: 'p',
        24: 'r',
        25: 'e',
        26: 's',
        27: 's',
        28: 'i',
        29: 'o',
        30: 'n',
        31: ' ',
        32: 'r',
        33: 'a',
        34: 't',
        35: 'i',
        36: 'o',
        37: ' ',
        38: 'a',
        39: 't',
        40: ' ',
        41: 's',
        42: 'i',
        43: 'm',
        44: 'i',
        45: 'l',
        46: 'a',
        47: 'r',
        48: ' ',
        49: 'l',
        50: 'e',
        51: 'v',
        52: 'e',
        53: 'l',
        54: 's',
        explanation: '',
      },
      {
        0: 'B',
        1: 'o',
        2: 't',
        3: 'h',
        4: ' ',
        5: 'p',
        6: 'e',
        7: 'r',
        8: 'f',
        9: 'o',
        10: 'r',
        11: 'm',
        12: ' ',
        13: 't',
        14: 'h',
        15: 'e',
        16: ' ',
        17: 's',
        18: 'a',
        19: 'm',
        20: 'e',
        21: ' ',
        22: 'a',
        23: 't',
        24: ' ',
        25: 'a',
        26: 'l',
        27: 'l',
        28: ' ',
        29: 'l',
        30: 'e',
        31: 'v',
        32: 'e',
        33: 'l',
        34: 's',
        explanation: '',
      },
      {
        0: 'B',
        1: 'r',
        2: 'o',
        3: 't',
        4: 'l',
        5: 'i',
        6: ' ',
        7: 'c',
        8: 'o',
        9: 'm',
        10: 'p',
        11: 'r',
        12: 'e',
        13: 's',
        14: 's',
        15: 'e',
        16: 's',
        17: ' ',
        18: 's',
        19: 'l',
        20: 'o',
        21: 'w',
        22: 'e',
        23: 'r',
        24: ' ',
        25: 'w',
        26: 'i',
        27: 't',
        28: 'h',
        29: ' ',
        30: 'w',
        31: 'o',
        32: 'r',
        33: 's',
        34: 'e',
        35: ' ',
        36: 'r',
        37: 'a',
        38: 't',
        39: 'i',
        40: 'o',
        41: 's',
        explanation: '',
      },
    ],
    sampleAnswers: ['Brotli has a better compression ratio at similar levels'],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Compression Comparison (Batch 1)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
