const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/performance-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'performance-patterns-import-on-interaction-3',
    title: 'What is a facade in Import On Interaction?',
    content:
      'A facade is a lightweight placeholder or preview that mimics a heavy component until the user interacts with it.',
    type: 'mcq',
    category: 'Performance Patterns',
    topic: 'Facades and Placeholders',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.201Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'performance-patterns',
      'facades-and-placeholders',
      null,
      'intermediate',
    ],
    explanation:
      'A facade prevents heavy resources from loading immediately by displaying a placeholder (like a thumbnail or fake button) until the user interacts.',
    points: 10,
    options: [
      {
        0: 'A',
        1: ' ',
        2: 'p',
        3: 'l',
        4: 'a',
        5: 'c',
        6: 'e',
        7: 'h',
        8: 'o',
        9: 'l',
        10: 'd',
        11: 'e',
        12: 'r',
        13: ' ',
        14: 'e',
        15: 'l',
        16: 'e',
        17: 'm',
        18: 'e',
        19: 'n',
        20: 't',
        21: ' ',
        22: 's',
        23: 'h',
        24: 'o',
        25: 'w',
        26: 'n',
        27: ' ',
        28: 'b',
        29: 'e',
        30: 'f',
        31: 'o',
        32: 'r',
        33: 'e',
        34: ' ',
        35: 'r',
        36: 'e',
        37: 'a',
        38: 'l',
        39: ' ',
        40: 'c',
        41: 'o',
        42: 'n',
        43: 't',
        44: 'e',
        45: 'n',
        46: 't',
        47: ' ',
        48: 'l',
        49: 'o',
        50: 'a',
        51: 'd',
        52: 's',
        explanation: '',
      },
      {
        0: 'A',
        1: ' ',
        2: 't',
        3: 'y',
        4: 'p',
        5: 'e',
        6: ' ',
        7: 'o',
        8: 'f',
        9: ' ',
        10: 'R',
        11: 'e',
        12: 'a',
        13: 'c',
        14: 't',
        15: ' ',
        16: 'c',
        17: 'o',
        18: 'm',
        19: 'p',
        20: 'o',
        21: 'n',
        22: 'e',
        23: 'n',
        24: 't',
        explanation: '',
      },
      {
        0: 'A',
        1: ' ',
        2: 't',
        3: 'h',
        4: 'i',
        5: 'r',
        6: 'd',
        7: '-',
        8: 'p',
        9: 'a',
        10: 'r',
        11: 't',
        12: 'y',
        13: ' ',
        14: 'A',
        15: 'P',
        16: 'I',
        17: ' ',
        18: 'o',
        19: 'p',
        20: 't',
        21: 'i',
        22: 'm',
        23: 'i',
        24: 'z',
        25: 'a',
        26: 't',
        27: 'i',
        28: 'o',
        29: 'n',
        30: ' ',
        31: 't',
        32: 'o',
        33: 'o',
        34: 'l',
        explanation: '',
      },
      {
        0: 'A',
        1: ' ',
        2: 'p',
        3: 'e',
        4: 'r',
        5: 'f',
        6: 'o',
        7: 'r',
        8: 'm',
        9: 'a',
        10: 'n',
        11: 'c',
        12: 'e',
        13: ' ',
        14: 'm',
        15: 'o',
        16: 'n',
        17: 'i',
        18: 't',
        19: 'o',
        20: 'r',
        21: 'i',
        22: 'n',
        23: 'g',
        24: ' ',
        25: 't',
        26: 'e',
        27: 'c',
        28: 'h',
        29: 'n',
        30: 'i',
        31: 'q',
        32: 'u',
        33: 'e',
        explanation: '',
      },
    ],
    sampleAnswers: ['A placeholder element shown before real content loads'],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Facades and Placeholders (Batch 1)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
