const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/performance-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'performance-patterns-import-on-interaction-10',
    title:
      'What is a common use case for Import On Interaction with third-party widgets?',
    content:
      'Loading chat widgets, video players, or authentication SDKs only after user interaction to save initial load time.',
    type: 'mcq',
    category: 'Performance Patterns',
    topic: 'Third-Party Optimization',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.201Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'performance-patterns',
      'third-party-optimization',
      null,
      'intermediate',
    ],
    explanation:
      'Deferring third-party widget code until interaction avoids blocking critical rendering and reduces main-thread congestion.',
    points: 10,
    options: [
      {
        0: 'P',
        1: 'r',
        2: 'e',
        3: 'l',
        4: 'o',
        5: 'a',
        6: 'd',
        7: 'i',
        8: 'n',
        9: 'g',
        10: ' ',
        11: 'a',
        12: 'l',
        13: 'l',
        14: ' ',
        15: 'e',
        16: 'x',
        17: 't',
        18: 'e',
        19: 'r',
        20: 'n',
        21: 'a',
        22: 'l',
        23: ' ',
        24: 'S',
        25: 'D',
        26: 'K',
        27: 's',
        explanation: '',
      },
      {
        0: 'L',
        1: 'a',
        2: 'z',
        3: 'y',
        4: '-',
        5: 'l',
        6: 'o',
        7: 'a',
        8: 'd',
        9: 'i',
        10: 'n',
        11: 'g',
        12: ' ',
        13: 'n',
        14: 'o',
        15: 'n',
        16: '-',
        17: 'c',
        18: 'r',
        19: 'i',
        20: 't',
        21: 'i',
        22: 'c',
        23: 'a',
        24: 'l',
        25: ' ',
        26: 't',
        27: 'h',
        28: 'i',
        29: 'r',
        30: 'd',
        31: '-',
        32: 'p',
        33: 'a',
        34: 'r',
        35: 't',
        36: 'y',
        37: ' ',
        38: 'w',
        39: 'i',
        40: 'd',
        41: 'g',
        42: 'e',
        43: 't',
        44: 's',
        explanation: '',
      },
      {
        0: 'L',
        1: 'o',
        2: 'a',
        3: 'd',
        4: 'i',
        5: 'n',
        6: 'g',
        7: ' ',
        8: 'a',
        9: 'l',
        10: 'l',
        11: ' ',
        12: 'w',
        13: 'i',
        14: 'd',
        15: 'g',
        16: 'e',
        17: 't',
        18: 's',
        19: ' ',
        20: 's',
        21: 'y',
        22: 'n',
        23: 'c',
        24: 'h',
        25: 'r',
        26: 'o',
        27: 'n',
        28: 'o',
        29: 'u',
        30: 's',
        31: 'l',
        32: 'y',
        explanation: '',
      },
      {
        0: 'D',
        1: 'i',
        2: 's',
        3: 'a',
        4: 'b',
        5: 'l',
        6: 'i',
        7: 'n',
        8: 'g',
        9: ' ',
        10: 'w',
        11: 'i',
        12: 'd',
        13: 'g',
        14: 'e',
        15: 't',
        16: 's',
        17: ' ',
        18: 'f',
        19: 'o',
        20: 'r',
        21: ' ',
        22: 'p',
        23: 'e',
        24: 'r',
        25: 'f',
        26: 'o',
        27: 'r',
        28: 'm',
        29: 'a',
        30: 'n',
        31: 'c',
        32: 'e',
        explanation: '',
      },
    ],
    sampleAnswers: ['Lazy-loading non-critical third-party widgets'],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Third-Party Optimization (Batch 1)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
