const fs = require('fs');
const path = require('path');

const questionsFile = path.join(__dirname, '../../final-questions-v01/performance-patterns-questions.json');

const newQuestions = [
  {
    "id": "performance-patterns-import-on-interaction-5",
    "title": "Which metrics can Import On Interaction improve?",
    "content": "By reducing blocking resources, it improves First Input Delay (FID), Total Blocking Time (TBT), and Time to Interactive (TTI).",
    "type": "mcq",
    "category": "Performance Patterns",
    "topic": "Web Vitals",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-10T00:00:00Z",
    "updatedAt": "2025-11-11T18:50:32.201Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "performance-patterns",
      "web-vitals",
      null,
      "intermediate"
    ],
    "explanation": "Deferring heavy scripts helps the browser respond to user input faster, improving FID, TBT, and TTI metrics.",
    "points": 10,
    "options": [
      {
        "0": "L",
        "1": "a",
        "2": "r",
        "3": "g",
        "4": "e",
        "5": "s",
        "6": "t",
        "7": " ",
        "8": "C",
        "9": "o",
        "10": "n",
        "11": "t",
        "12": "e",
        "13": "n",
        "14": "t",
        "15": "f",
        "16": "u",
        "17": "l",
        "18": " ",
        "19": "P",
        "20": "a",
        "21": "i",
        "22": "n",
        "23": "t",
        "24": " ",
        "25": "(",
        "26": "L",
        "27": "C",
        "28": "P",
        "29": ")",
        "30": " ",
        "31": "a",
        "32": "n",
        "33": "d",
        "34": " ",
        "35": "C",
        "36": "u",
        "37": "m",
        "38": "u",
        "39": "l",
        "40": "a",
        "41": "t",
        "42": "i",
        "43": "v",
        "44": "e",
        "45": " ",
        "46": "L",
        "47": "a",
        "48": "y",
        "49": "o",
        "50": "u",
        "51": "t",
        "52": " ",
        "53": "S",
        "54": "h",
        "55": "i",
        "56": "f",
        "57": "t",
        "58": " ",
        "59": "(",
        "60": "C",
        "61": "L",
        "62": "S",
        "63": ")",
        "explanation": ""
      },
      {
        "0": "F",
        "1": "i",
        "2": "r",
        "3": "s",
        "4": "t",
        "5": " ",
        "6": "I",
        "7": "n",
        "8": "p",
        "9": "u",
        "10": "t",
        "11": " ",
        "12": "D",
        "13": "e",
        "14": "l",
        "15": "a",
        "16": "y",
        "17": " ",
        "18": "(",
        "19": "F",
        "20": "I",
        "21": "D",
        "22": ")",
        "23": ",",
        "24": " ",
        "25": "T",
        "26": "o",
        "27": "t",
        "28": "a",
        "29": "l",
        "30": " ",
        "31": "B",
        "32": "l",
        "33": "o",
        "34": "c",
        "35": "k",
        "36": "i",
        "37": "n",
        "38": "g",
        "39": " ",
        "40": "T",
        "41": "i",
        "42": "m",
        "43": "e",
        "44": " ",
        "45": "(",
        "46": "T",
        "47": "B",
        "48": "T",
        "49": ")",
        "50": ",",
        "51": " ",
        "52": "T",
        "53": "i",
        "54": "m",
        "55": "e",
        "56": " ",
        "57": "t",
        "58": "o",
        "59": " ",
        "60": "I",
        "61": "n",
        "62": "t",
        "63": "e",
        "64": "r",
        "65": "a",
        "66": "c",
        "67": "t",
        "68": "i",
        "69": "v",
        "70": "e",
        "71": " ",
        "72": "(",
        "73": "T",
        "74": "T",
        "75": "I",
        "76": ")",
        "explanation": ""
      },
      {
        "0": "B",
        "1": "o",
        "2": "u",
        "3": "n",
        "4": "c",
        "5": "e",
        "6": " ",
        "7": "r",
        "8": "a",
        "9": "t",
        "10": "e",
        "11": " ",
        "12": "a",
        "13": "n",
        "14": "d",
        "15": " ",
        "16": "S",
        "17": "E",
        "18": "O",
        "19": " ",
        "20": "r",
        "21": "a",
        "22": "n",
        "23": "k",
        "24": "i",
        "25": "n",
        "26": "g",
        "explanation": ""
      },
      {
        "0": "S",
        "1": "e",
        "2": "r",
        "3": "v",
        "4": "e",
        "5": "r",
        "6": " ",
        "7": "r",
        "8": "e",
        "9": "s",
        "10": "p",
        "11": "o",
        "12": "n",
        "13": "s",
        "14": "e",
        "15": " ",
        "16": "t",
        "17": "i",
        "18": "m",
        "19": "e",
        "20": " ",
        "21": "a",
        "22": "n",
        "23": "d",
        "24": " ",
        "25": "b",
        "26": "a",
        "27": "n",
        "28": "d",
        "29": "w",
        "30": "i",
        "31": "d",
        "32": "t",
        "33": "h",
        "explanation": ""
      }
    ],
    "sampleAnswers": [
      "First Input Delay (FID), Total Blocking Time (TBT), Time to Interactive (TTI)"
    ],
    "hints": [],
    "metadata": {}
  }
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(`✅ Added ${newQuestions.length} questions for Web Vitals (Batch 1)`);
console.log(`📝 Total questions: ${existingQuestions.length}`);
