const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/performance-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'performance-patterns-loading-sequence-10',
    title: 'Avoiding Preload Overuse',
    content: 'Why should developers avoid overusing the preload directive?',
    type: 'multiple-choice',
    category: 'Performance Patterns',
    topic: 'Browser Optimization',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.218Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'performance-patterns',
      'browser-optimization',
      null,
      'intermediate',
    ],
    explanation:
      'Overusing preload can cause browsers to fetch unnecessary resources too early, increasing network congestion and reducing performance.',
    points: 10,
    options: [
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'c',
        4: 'a',
        5: 'n',
        6: ' ',
        7: 'c',
        8: 'a',
        9: 'u',
        10: 's',
        11: 'e',
        12: ' ',
        13: 't',
        14: 'h',
        15: 'e',
        16: ' ',
        17: 'b',
        18: 'r',
        19: 'o',
        20: 'w',
        21: 's',
        22: 'e',
        23: 'r',
        24: ' ',
        25: 't',
        26: 'o',
        27: ' ',
        28: 'd',
        29: 'o',
        30: 'w',
        31: 'n',
        32: 'l',
        33: 'o',
        34: 'a',
        35: 'd',
        36: ' ',
        37: 'u',
        38: 'n',
        39: 'n',
        40: 'e',
        41: 'c',
        42: 'e',
        43: 's',
        44: 's',
        45: 'a',
        46: 'r',
        47: 'y',
        48: ' ',
        49: 'r',
        50: 'e',
        51: 's',
        52: 'o',
        53: 'u',
        54: 'r',
        55: 'c',
        56: 'e',
        57: 's',
        58: ' ',
        59: 'e',
        60: 'a',
        61: 'r',
        62: 'l',
        63: 'y',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'i',
        4: 'm',
        5: 'p',
        6: 'r',
        7: 'o',
        8: 'v',
        9: 'e',
        10: 's',
        11: ' ',
        12: 'c',
        13: 'a',
        14: 'c',
        15: 'h',
        16: 'i',
        17: 'n',
        18: 'g',
        19: ' ',
        20: 't',
        21: 'o',
        22: 'o',
        23: ' ',
        24: 'm',
        25: 'u',
        26: 'c',
        27: 'h',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'a',
        4: 'u',
        5: 't',
        6: 'o',
        7: 'm',
        8: 'a',
        9: 't',
        10: 'i',
        11: 'c',
        12: 'a',
        13: 'l',
        14: 'l',
        15: 'y',
        16: ' ',
        17: 'p',
        18: 'r',
        19: 'i',
        20: 'o',
        21: 'r',
        22: 'i',
        23: 't',
        24: 'i',
        25: 'z',
        26: 'e',
        27: 's',
        28: ' ',
        29: 'r',
        30: 'e',
        31: 's',
        32: 'o',
        33: 'u',
        34: 'r',
        35: 'c',
        36: 'e',
        37: 's',
        38: ' ',
        39: 'c',
        40: 'o',
        41: 'r',
        42: 'r',
        43: 'e',
        44: 'c',
        45: 't',
        46: 'l',
        47: 'y',
        explanation: '',
      },
      {
        0: 'I',
        1: 't',
        2: ' ',
        3: 'b',
        4: 'l',
        5: 'o',
        6: 'c',
        7: 'k',
        8: 's',
        9: ' ',
        10: 'a',
        11: 'l',
        12: 'l',
        13: ' ',
        14: 'a',
        15: 's',
        16: 'y',
        17: 'n',
        18: 'c',
        19: ' ',
        20: 's',
        21: 'c',
        22: 'r',
        23: 'i',
        24: 'p',
        25: 't',
        26: 's',
        explanation: '',
      },
    ],
    sampleAnswers: [
      'It can cause the browser to download unnecessary resources early',
    ],
    hints: [],
    metadata: {},
  },
  {
    id: 'performance-patterns-pre-load-7',
    title: 'Preload in Chrome 95+',
    content: 'How did Chrome 95+ improve the safety of using preload?',
    type: 'multiple-choice',
    category: 'Performance Patterns',
    topic: 'Browser Optimization',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-11-11T18:50:32.240Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'performance-patterns',
      'browser-optimization',
      null,
      'intermediate',
    ],
    explanation:
      'Chrome 95+ fixed queue-jumping behavior, making preload order more predictable relative to other resources.',
    points: 10,
    options: [
      {
        id: 'o1',
        text: 'It made preload ordering more consistent and less likely to block critical resources.',
        isCorrect: true,
        explanation:
          'Chrome 95+ fixed queue-jumping behavior, making preload order more predictable relative to other resources.',
      },
      {
        id: 'o2',
        text: 'This is not correct. Please refer to the explanation.',
        isCorrect: false,
        explanation: '',
      },
      {
        id: 'o3',
        text: 'Incorrect. Review performance optimization concepts.',
        isCorrect: false,
        explanation: '',
      },
      {
        id: 'o4',
        text: 'This is a common misconception. The correct answer is different.',
        isCorrect: false,
        explanation: '',
      },
      {
        id: 'o5',
        text: 'Not quite. Consider web performance best practices.',
        isCorrect: false,
        explanation: '',
      },
    ],
    sampleAnswers: [
      'It made preload ordering more consistent and less likely to block critical resources.',
    ],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Browser Optimization (Batch 1)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
