const fs = require('fs');
const path = require('path');

const questionsFile = path.join(__dirname, '../../final-questions-v01/performance-patterns-questions.json');

const newQuestions = [
  {
    "id": "performance-patterns-dynamic-import-13",
    "title": "Which React function is used to dynamically import components?",
    "content": "React.lazy is used to dynamically import components at runtime.",
    "type": "mcq",
    "category": "Performance Patterns",
    "topic": "React Lazy Loading",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-10T00:00:00Z",
    "updatedAt": "2025-11-11T18:50:32.188Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "performance-patterns",
      "react-lazy-loading",
      "beginner",
      "intermediate"
    ],
    "explanation": "<code>React.lazy(() =&gt; import('./Component'))</code> loads a component only when it is rendered for the first time.",
    "points": 10,
    "options": [
      {
        "0": "R",
        "1": "e",
        "2": "a",
        "3": "c",
        "4": "t",
        "5": ".",
        "6": "u",
        "7": "s",
        "8": "e",
        "9": "M",
        "10": "e",
        "11": "m",
        "12": "o",
        "explanation": ""
      },
      {
        "0": "R",
        "1": "e",
        "2": "a",
        "3": "c",
        "4": "t",
        "5": ".",
        "6": "l",
        "7": "a",
        "8": "z",
        "9": "y",
        "explanation": ""
      },
      {
        "0": "R",
        "1": "e",
        "2": "a",
        "3": "c",
        "4": "t",
        "5": ".",
        "6": "l",
        "7": "o",
        "8": "a",
        "9": "d",
        "explanation": ""
      },
      {
        "0": "R",
        "1": "e",
        "2": "a",
        "3": "c",
        "4": "t",
        "5": ".",
        "6": "d",
        "7": "e",
        "8": "f",
        "9": "e",
        "10": "r",
        "explanation": ""
      }
    ],
    "sampleAnswers": [
      "React.lazy"
    ],
    "hints": [],
    "metadata": {}
  },
  {
    "id": "performance-patterns-import-on-interaction-7",
    "title": "How does React support Import On Interaction?",
    "content": "React supports lazy-loading components using React.lazy and Suspense, or by dynamically importing a component on user interaction.",
    "type": "mcq",
    "category": "Performance Patterns",
    "topic": "React Lazy Loading",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-10T00:00:00Z",
    "updatedAt": "2025-11-11T18:50:32.201Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "performance-patterns",
      "react-lazy-loading",
      null,
      "intermediate"
    ],
    "explanation": "React’s <code>lazy()</code> and <code>Suspense</code> make it easy to defer loading non-critical components until interaction occurs.",
    "points": 10,
    "options": [
      {
        "0": "B",
        "1": "y",
        "2": " ",
        "3": "c",
        "4": "o",
        "5": "m",
        "6": "p",
        "7": "i",
        "8": "l",
        "9": "i",
        "10": "n",
        "11": "g",
        "12": " ",
        "13": "c",
        "14": "o",
        "15": "m",
        "16": "p",
        "17": "o",
        "18": "n",
        "19": "e",
        "20": "n",
        "21": "t",
        "22": "s",
        "23": " ",
        "24": "o",
        "25": "n",
        "26": " ",
        "27": "t",
        "28": "h",
        "29": "e",
        "30": " ",
        "31": "s",
        "32": "e",
        "33": "r",
        "34": "v",
        "35": "e",
        "36": "r",
        "explanation": ""
      },
      {
        "0": "U",
        "1": "s",
        "2": "i",
        "3": "n",
        "4": "g",
        "5": " ",
        "6": "R",
        "7": "e",
        "8": "a",
        "9": "c",
        "10": "t",
        "11": ".",
        "12": "l",
        "13": "a",
        "14": "z",
        "15": "y",
        "16": " ",
        "17": "a",
        "18": "n",
        "19": "d",
        "20": " ",
        "21": "S",
        "22": "u",
        "23": "s",
        "24": "p",
        "25": "e",
        "26": "n",
        "27": "s",
        "28": "e",
        "29": " ",
        "30": "o",
        "31": "r",
        "32": " ",
        "33": "d",
        "34": "y",
        "35": "n",
        "36": "a",
        "37": "m",
        "38": "i",
        "39": "c",
        "40": " ",
        "41": "i",
        "42": "m",
        "43": "p",
        "44": "o",
        "45": "r",
        "46": "t",
        "47": " ",
        "48": "o",
        "49": "n",
        "50": " ",
        "51": "c",
        "52": "l",
        "53": "i",
        "54": "c",
        "55": "k",
        "explanation": ""
      },
      {
        "0": "B",
        "1": "y",
        "2": " ",
        "3": "u",
        "4": "s",
        "5": "i",
        "6": "n",
        "7": "g",
        "8": " ",
        "9": "R",
        "10": "e",
        "11": "a",
        "12": "c",
        "13": "t",
        "14": ".",
        "15": "u",
        "16": "s",
        "17": "e",
        "18": "M",
        "19": "e",
        "20": "m",
        "21": "o",
        "22": " ",
        "23": "f",
        "24": "o",
        "25": "r",
        "26": " ",
        "27": "c",
        "28": "a",
        "29": "c",
        "30": "h",
        "31": "i",
        "32": "n",
        "33": "g",
        "explanation": ""
      },
      {
        "0": "T",
        "1": "h",
        "2": "r",
        "3": "o",
        "4": "u",
        "5": "g",
        "6": "h",
        "7": " ",
        "8": "h",
        "9": "y",
        "10": "d",
        "11": "r",
        "12": "a",
        "13": "t",
        "14": "i",
        "15": "o",
        "16": "n",
        "17": " ",
        "18": "d",
        "19": "e",
        "20": "l",
        "21": "a",
        "22": "y",
        "23": " ",
        "24": "A",
        "25": "P",
        "26": "I",
        "27": "s",
        "explanation": ""
      }
    ],
    "sampleAnswers": [
      "Using React.lazy and Suspense or dynamic import on click"
    ],
    "hints": [],
    "metadata": {}
  }
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(`✅ Added ${newQuestions.length} questions for React Lazy Loading (Batch 1)`);
console.log(`📝 Total questions: ${existingQuestions.length}`);
