openapi: 3.0.3
info:
  title: Admin App API
  description: API contract for the Admin application after migration
  version: 1.0.0
  contact:
    name: Elzatona Team

servers:
  - url: http://localhost:3001
    description: Development server
  - url: https://admin.elzatona.com
    description: Production server

tags:
  - name: Auth
    description: Authentication endpoints
  - name: Questions
    description: Question management
  - name: Users
    description: User management
  - name: LearningCards
    description: Learning card management
  - name: Logs
    description: Activity logs
  - name: Dashboard
    description: Dashboard statistics

paths:
  /api/admin/auth/login:
    post:
      tags: [Auth]
      summary: Admin login
      operationId: adminLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/admin/auth/logout:
    post:
      tags: [Auth]
      summary: Admin logout
      operationId: adminLogout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful logout
        '401':
          description: Unauthorized

  /api/admin/questions:
    get:
      tags: [Questions]
      summary: List all questions
      operationId: listQuestions
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          schema:
            type: string
            enum: [draft, published, archived]
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of questions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionListResponse'
        '401':
          description: Unauthorized

    post:
      tags: [Questions]
      summary: Create a new question
      operationId: createQuestion
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuestionRequest'
      responses:
        '201':
          description: Question created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '400':
          description: Validation error
        '401':
          description: Unauthorized

  /api/admin/questions/{id}:
    get:
      tags: [Questions]
      summary: Get question by ID
      operationId: getQuestion
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Question details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: Question not found

    put:
      tags: [Questions]
      summary: Update question
      operationId: updateQuestion
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateQuestionRequest'
      responses:
        '200':
          description: Question updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: Question not found

    delete:
      tags: [Questions]
      summary: Delete question
      operationId: deleteQuestion
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Question deleted
        '404':
          description: Question not found

  /api/admin/users:
    get:
      tags: [Users]
      summary: List all users
      operationId: listUsers
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: role
          in: query
          schema:
            type: string
            enum: [admin, user, moderator]
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'

    post:
      tags: [Users]
      summary: Create a new user
      operationId: createUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /api/admin/users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      operationId: getUser
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      tags: [Users]
      summary: Update user
      operationId: updateUser
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated

    delete:
      tags: [Users]
      summary: Delete user
      operationId: deleteUser
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: User deleted

  /api/admin/learning-cards:
    get:
      tags: [LearningCards]
      summary: List all learning cards
      operationId: listLearningCards
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: category
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of learning cards
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningCardListResponse'

    post:
      tags: [LearningCards]
      summary: Create a new learning card
      operationId: createLearningCard
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLearningCardRequest'
      responses:
        '201':
          description: Learning card created

  /api/admin/learning-cards/{id}:
    get:
      tags: [LearningCards]
      summary: Get learning card by ID
      operationId: getLearningCard
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Learning card details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningCard'

    put:
      tags: [LearningCards]
      summary: Update learning card
      operationId: updateLearningCard
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLearningCardRequest'
      responses:
        '200':
          description: Learning card updated

    delete:
      tags: [LearningCards]
      summary: Delete learning card
      operationId: deleteLearningCard
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Learning card deleted

  /api/admin/logs:
    get:
      tags: [Logs]
      summary: Get activity logs
      operationId: getLogs
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: userId
          in: query
          schema:
            type: string
            format: uuid
        - name: action
          in: query
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Activity logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogListResponse'

  /api/admin/dashboard/stats:
    get:
      tags: [Dashboard]
      summary: Get dashboard statistics
      operationId: getDashboardStats
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardStats'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'
        expiresAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        statusCode:
          type: integer

    Question:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        category:
          type: string
        difficulty:
          type: string
          enum: [easy, medium, hard]
        status:
          type: string
          enum: [draft, published, archived]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateQuestionRequest:
      type: object
      required: [title, content, category]
      properties:
        title:
          type: string
          minLength: 1
        content:
          type: string
        category:
          type: string
        difficulty:
          type: string
          enum: [easy, medium, hard]
          default: medium

    UpdateQuestionRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        category:
          type: string
        difficulty:
          type: string
          enum: [easy, medium, hard]
        status:
          type: string
          enum: [draft, published, archived]

    QuestionListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Question'
        pagination:
          $ref: '#/components/schemas/Pagination'

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [admin, user, moderator]
        createdAt:
          type: string
          format: date-time

    CreateUserRequest:
      type: object
      required: [email, name, password]
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        password:
          type: string
          minLength: 8
        role:
          type: string
          enum: [admin, user, moderator]
          default: user

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [admin, user, moderator]

    UserListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'
        pagination:
          $ref: '#/components/schemas/Pagination'

    LearningCard:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateLearningCardRequest:
      type: object
      required: [title, content]
      properties:
        title:
          type: string
        content:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string

    UpdateLearningCardRequest:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string

    LearningCardListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/LearningCard'
        pagination:
          $ref: '#/components/schemas/Pagination'

    LogEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        action:
          type: string
        resource:
          type: string
        resourceId:
          type: string
        details:
          type: object
        createdAt:
          type: string
          format: date-time

    LogListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/LogEntry'
        pagination:
          $ref: '#/components/schemas/Pagination'

    DashboardStats:
      type: object
      properties:
        totalQuestions:
          type: integer
        totalUsers:
          type: integer
        totalLearningCards:
          type: integer
        recentActivity:
          type: array
          items:
            $ref: '#/components/schemas/LogEntry'
        questionsByCategory:
          type: object
          additionalProperties:
            type: integer
        usersByRole:
          type: object
          additionalProperties:
            type: integer

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer
