const fs = require('fs');
const path = require('path');

const questionsFile = path.join(__dirname, '../../final-questions-v01/design-patterns-questions.json');

const newQuestions = [
  {
    "id": "design-patterns-static-import-60",
    "title": "What is the main drawback of using only static imports in a React app?",
    "content": "If every component and dependency is statically imported, the initial bundle can become very large. This delays rendering since the browser must download and parse all modules before showing any content.",
    "type": "multiple-choice",
    "category": "Design Patterns",
    "topic": "Performance Patterns",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-15T00:47:17.209Z",
    "updatedAt": "2025-11-11T18:36:58.309Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "design-patterns",
      "general-design-patterns",
      "intermediate"
    ],
    "explanation": "Slower initial load due to larger bundle size. Worse performance on mobile or slow networks. Even components not immediately needed are still loaded upfront.",
    "points": 10,
    "sampleAnswers": [
      "Slower initial load due to larger bundle size.",
      "Worse performance on mobile or slow networks.",
      "Even components not immediately needed are still loaded upfront."
    ],
    "hints": [],
    "metadata": {},
    "options": [
      {
        "id": "o1",
        "text": "Slower initial load due to larger bundle size.",
        "isCorrect": true,
        "explanation": "Slower initial load due to larger bundle size. Worse performance on mobile or slow networks. Even components not immediately needed are still loaded upfront."
      },
      {
        "id": "o2",
        "text": "This is not correct. Please refer to the explanation.",
        "isCorrect": false,
        "explanation": ""
      },
      {
        "id": "o3",
        "text": "Incorrect. Review the design pattern concepts.",
        "isCorrect": false,
        "explanation": ""
      },
      {
        "id": "o4",
        "text": "This is a common misconception. The correct answer is different.",
        "isCorrect": false,
        "explanation": ""
      }
    ]
  },
  {
    "id": "design-patterns-static-import-61",
    "title": "How does Webpack handle static imports?",
    "content": "Webpack bundles all statically imported modules into the main bundle file. For example, <code>main.bundle.js</code> might include every statically imported component from the source code.",
    "type": "mcq",
    "category": "Design Patterns",
    "topic": "Performance Patterns",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-15T00:47:17.209Z",
    "updatedAt": "2025-11-11T18:36:58.309Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "design-patterns",
      "general-design-patterns",
      "intermediate"
    ],
    "explanation": "No explanation provided.",
    "points": 10,
    "options": [
      {
        "0": "I",
        "1": "t",
        "2": " ",
        "3": "b",
        "4": "u",
        "5": "n",
        "6": "d",
        "7": "l",
        "8": "e",
        "9": "s",
        "10": " ",
        "11": "t",
        "12": "h",
        "13": "e",
        "14": "m",
        "15": " ",
        "16": "o",
        "17": "n",
        "18": "l",
        "19": "y",
        "20": " ",
        "21": "w",
        "22": "h",
        "23": "e",
        "24": "n",
        "25": " ",
        "26": "u",
        "27": "s",
        "28": "e",
        "29": "d",
        "30": " ",
        "31": "a",
        "32": "t",
        "33": " ",
        "34": "r",
        "35": "u",
        "36": "n",
        "37": "t",
        "38": "i",
        "39": "m",
        "40": "e",
        "explanation": ""
      },
      {
        "0": "I",
        "1": "t",
        "2": " ",
        "3": "s",
        "4": "p",
        "5": "l",
        "6": "i",
        "7": "t",
        "8": "s",
        "9": " ",
        "10": "t",
        "11": "h",
        "12": "e",
        "13": "m",
        "14": " ",
        "15": "i",
        "16": "n",
        "17": "t",
        "18": "o",
        "19": " ",
        "20": "s",
        "21": "e",
        "22": "p",
        "23": "a",
        "24": "r",
        "25": "a",
        "26": "t",
        "27": "e",
        "28": " ",
        "29": "f",
        "30": "i",
        "31": "l",
        "32": "e",
        "33": "s",
        "34": " ",
        "35": "a",
        "36": "u",
        "37": "t",
        "38": "o",
        "39": "m",
        "40": "a",
        "41": "t",
        "42": "i",
        "43": "c",
        "44": "a",
        "45": "l",
        "46": "l",
        "47": "y",
        "explanation": ""
      },
      {
        "0": "I",
        "1": "t",
        "2": " ",
        "3": "i",
        "4": "n",
        "5": "c",
        "6": "l",
        "7": "u",
        "8": "d",
        "9": "e",
        "10": "s",
        "11": " ",
        "12": "a",
        "13": "l",
        "14": "l",
        "15": " ",
        "16": "s",
        "17": "t",
        "18": "a",
        "19": "t",
        "20": "i",
        "21": "c",
        "22": "a",
        "23": "l",
        "24": "l",
        "25": "y",
        "26": " ",
        "27": "i",
        "28": "m",
        "29": "p",
        "30": "o",
        "31": "r",
        "32": "t",
        "33": "e",
        "34": "d",
        "35": " ",
        "36": "m",
        "37": "o",
        "38": "d",
        "39": "u",
        "40": "l",
        "41": "e",
        "42": "s",
        "43": " ",
        "44": "i",
        "45": "n",
        "46": "t",
        "47": "o",
        "48": " ",
        "49": "t",
        "50": "h",
        "51": "e",
        "52": " ",
        "53": "m",
        "54": "a",
        "55": "i",
        "56": "n",
        "57": " ",
        "58": "b",
        "59": "u",
        "60": "n",
        "61": "d",
        "62": "l",
        "63": "e",
        "explanation": ""
      },
      {
        "0": "I",
        "1": "t",
        "2": " ",
        "3": "i",
        "4": "g",
        "5": "n",
        "6": "o",
        "7": "r",
        "8": "e",
        "9": "s",
        "10": " ",
        "11": "t",
        "12": "h",
        "13": "e",
        "14": "m",
        "15": " ",
        "16": "u",
        "17": "n",
        "18": "l",
        "19": "e",
        "20": "s",
        "21": "s",
        "22": " ",
        "23": "e",
        "24": "x",
        "25": "p",
        "26": "l",
        "27": "i",
        "28": "c",
        "29": "i",
        "30": "t",
        "31": "l",
        "32": "y",
        "33": " ",
        "34": "c",
        "35": "o",
        "36": "n",
        "37": "f",
        "38": "i",
        "39": "g",
        "40": "u",
        "41": "r",
        "42": "e",
        "43": "d",
        "explanation": ""
      }
    ],
    "hints": [],
    "metadata": {}
  },
  {
    "id": "design-patterns-static-import-62",
    "title": "When should you avoid static imports?",
    "content": "Avoid static imports for components that are not immediately necessary on page load, such as modals, tooltips, or rarely used features. Instead, load them dynamically to improve performance.",
    "type": "multiple-choice",
    "category": "Design Patterns",
    "topic": "Performance Patterns",
    "difficulty": "intermediate",
    "learningCardId": "system-design",
    "isActive": true,
    "createdAt": "2025-10-15T00:47:17.209Z",
    "updatedAt": "2025-11-11T18:36:58.309Z",
    "createdBy": "admin",
    "updatedBy": "admin",
    "tags": [
      "design-patterns",
      "general-design-patterns",
      "intermediate"
    ],
    "explanation": "When the component is behind a user action (e.g., clicking a button). When the component is not critical for the initial render. When optimizing for smaller bundle sizes and faster loads.",
    "points": 10,
    "sampleAnswers": [
      "When the component is behind a user action (e.g., clicking a button).",
      "When the component is not critical for the initial render.",
      "When optimizing for smaller bundle sizes and faster loads."
    ],
    "hints": [],
    "metadata": {},
    "options": [
      {
        "id": "o1",
        "text": "When the component is behind a user action (e.g., clicking a button).",
        "isCorrect": true,
        "explanation": "When the component is behind a user action (e.g., clicking a button). When the component is not critical for the initial render. When optimizing for smaller bundle sizes and faster loads."
      },
      {
        "id": "o2",
        "text": "This is not correct. Please refer to the explanation.",
        "isCorrect": false,
        "explanation": ""
      },
      {
        "id": "o3",
        "text": "Incorrect. Review the design pattern concepts.",
        "isCorrect": false,
        "explanation": ""
      },
      {
        "id": "o4",
        "text": "This is a common misconception. The correct answer is different.",
        "isCorrect": false,
        "explanation": ""
      }
    ]
  }
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(`✅ Added ${newQuestions.length} questions for Performance Patterns (Batch 2)`);
console.log(`📝 Total questions: ${existingQuestions.length}`);
