const fs = require('fs');
const path = require('path');

const questionsFile = path.join(
  __dirname,
  '../../final-questions-v01/design-patterns-questions.json'
);

const newQuestions = [
  {
    id: 'design-patterns-proxy-pattern-69',
    title: 'Validation with Proxies',
    content:
      'How can the Proxy pattern help with data validation? Give an example.',
    type: 'multiple-choice',
    category: 'Design Patterns',
    topic: 'Structural Patterns',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-15T00:47:17.208Z',
    updatedAt: '2025-11-11T18:36:58.284Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: ['design-patterns', 'general-design-patterns', 'intermediate'],
    explanation: 'No explanation provided.',
    points: 10,
    hints: [],
    metadata: {},
    options: [
      {
        id: 'o1',
        text: 'No explanation provided',
        isCorrect: true,
        explanation: 'No explanation provided.',
      },
      {
        id: 'o2',
        text: 'This is not correct. Please refer to the explanation.',
        isCorrect: false,
        explanation: '',
      },
      {
        id: 'o3',
        text: 'Incorrect. Review the design pattern concepts.',
        isCorrect: false,
        explanation: '',
      },
      {
        id: 'o4',
        text: 'This is a common misconception. The correct answer is different.',
        isCorrect: false,
        explanation: '',
      },
    ],
  },
  {
    id: 'design-patterns-proxy-pattern-70',
    title: 'Logging Changes',
    content:
      'Write a proxy that prevents setting <code>age</code> to a non-numeric value and logs attempts with an error message.',
    type: 'code',
    category: 'Design Patterns',
    topic: 'Structural Patterns',
    difficulty: 'advanced',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-15T00:47:17.208Z',
    updatedAt: '2025-11-11T18:36:58.284Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: [
      'design-patterns',
      'general-design-patterns',
      'advanced',
      'advanced',
    ],
    explanation: 'No explanation provided.',
    points: 10,
    hints: [],
    metadata: {},
  },
  {
    id: 'design-patterns-proxy-pattern-71',
    title: 'Proxy and Non-Existent Properties',
    content:
      'When trying to access a property that does not exist, how can a Proxy handler respond?',
    type: 'multiple-choice',
    category: 'Design Patterns',
    topic: 'Structural Patterns',
    difficulty: 'intermediate',
    learningCardId: 'system-design',
    isActive: true,
    createdAt: '2025-10-15T00:47:17.208Z',
    updatedAt: '2025-11-11T18:36:58.284Z',
    createdBy: 'admin',
    updatedBy: 'admin',
    tags: ['design-patterns', 'general-design-patterns', 'intermediate'],
    explanation: 'No explanation provided.',
    points: 10,
    options: [
      {
        0: 'T',
        1: 'h',
        2: 'r',
        3: 'o',
        4: 'w',
        5: ' ',
        6: 'a',
        7: 'n',
        8: ' ',
        9: 'e',
        10: 'r',
        11: 'r',
        12: 'o',
        13: 'r',
        explanation: '',
      },
      {
        0: 'R',
        1: 'e',
        2: 't',
        3: 'u',
        4: 'r',
        5: 'n',
        6: ' ',
        7: 'u',
        8: 'n',
        9: 'd',
        10: 'e',
        11: 'f',
        12: 'i',
        13: 'n',
        14: 'e',
        15: 'd',
        explanation: '',
      },
      {
        0: 'L',
        1: 'o',
        2: 'g',
        3: ' ',
        4: 'a',
        5: ' ',
        6: 'c',
        7: 'u',
        8: 's',
        9: 't',
        10: 'o',
        11: 'm',
        12: ' ',
        13: 'm',
        14: 'e',
        15: 's',
        16: 's',
        17: 'a',
        18: 'g',
        19: 'e',
        explanation: '',
      },
      {
        0: 'A',
        1: 'n',
        2: 'y',
        3: ' ',
        4: 'o',
        5: 'f',
        6: ' ',
        7: 't',
        8: 'h',
        9: 'e',
        10: ' ',
        11: 'a',
        12: 'b',
        13: 'o',
        14: 'v',
        15: 'e',
        16: ',',
        17: ' ',
        18: 'd',
        19: 'e',
        20: 'p',
        21: 'e',
        22: 'n',
        23: 'd',
        24: 'i',
        25: 'n',
        26: 'g',
        27: ' ',
        28: 'o',
        29: 'n',
        30: ' ',
        31: 't',
        32: 'h',
        33: 'e',
        34: ' ',
        35: 'h',
        36: 'a',
        37: 'n',
        38: 'd',
        39: 'l',
        40: 'e',
        41: 'r',
        42: ' ',
        43: 'l',
        44: 'o',
        45: 'g',
        46: 'i',
        47: 'c',
        explanation: '',
      },
    ],
    hints: [],
    metadata: {},
  },
];

// Read existing questions
let existingQuestions = [];
if (fs.existsSync(questionsFile)) {
  existingQuestions = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));
}

// Add new questions
existingQuestions.push(...newQuestions);

// Write back
fs.writeFileSync(questionsFile, JSON.stringify(existingQuestions, null, 2));

console.log(
  `✅ Added ${newQuestions.length} questions for Structural Patterns (Batch 10)`
);
console.log(`📝 Total questions: ${existingQuestions.length}`);
