INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '58077c09-1f0d-43b2-a6f6-0cde2af7421e',
      'Compare Static Import vs Dynamic Import.',
      'Static import loads all modules upfront at build time, increasing initial bundle size. Dynamic import (`import()`) loads modules only when needed (e.g., on user interaction), improving load performance but adding runtime overhead.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Static imports are eager, dynamic imports are lazy. Static imports bundle everything, dynamic imports support code-splitting. Static imports run immediately, dynamic imports return a promise.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-static-import-63","original_type":"open-ended","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.695Z',
      '2025-10-21T22:21:12.695Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '0fe47939-e7c0-4ce0-af89-2a37915a8aff',
      'What performance optimization can replace some static imports in the chat app example?',
      'Instead of statically importing the `EmojiPicker`, we can dynamically import it when the user opens the emoji panel. This reduces initial bundle size and speeds up app load.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'No explanation provided.',
      ARRAY[]::text[],
      ARRAY[]::text[],
      ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"design-patterns-static-import-64","original_type":"mcq","topic":"General Design Patterns","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Design Patterns"}',
      '2d6223f9-020c-45e7-a3bd-6aa9b0a6af3c',
      true,
      '2025-10-21T22:21:12.695Z',
      '2025-10-21T22:21:12.695Z'
    );;
