INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '2d43c17e-0ea6-4424-b6ba-33264b190096',
      'List display property values in CSS?',
      'The `display` property controls how an element is rendered. Common values: `block`, `inline`, `inline-block`, `flex`, `grid`, `none`, `table`, etc.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"`block`, `inline`, `inline-block`, `flex`, `grid`, `none`, `table`","isCorrect":true,"explanation":""},{"id":"b","text":"Only `block` and `inline`","isCorrect":false,"explanation":""},{"id":"c","text":"`display` has no effect on layout","isCorrect":false,"explanation":""},{"id":"d","text":"`display: hidden` is valid","isCorrect":false,"explanation":""}]',
      'c',
      '`display` defines the outer and inner display type of an element, controlling layout behavior and flow.',
      NULL,
      NULL,
      '[\"css\",\"display-property\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q61","original_type":"multiple-choice","topic":"Display Property","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'c42a8beb-faee-4839-b7a5-abd7595e0961',
      'How is responsive design different from adaptive design?',
      'Responsive design uses fluid grids and media queries to adapt continuously. Adaptive design uses fixed layouts for specific breakpoints.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Responsive: fluid, continuous adaptation; Adaptive: fixed layouts at breakpoints","isCorrect":true,"explanation":""},{"id":"b","text":"They are identical","isCorrect":false,"explanation":""},{"id":"c","text":"Adaptive uses only percentages","isCorrect":false,"explanation":""},{"id":"d","text":"Responsive requires JavaScript","isCorrect":false,"explanation":""}]',
      'c',
      'Responsive is fluid and flexible; adaptive serves predefined layouts based on device detection or viewport size.',
      NULL,
      NULL,
      '[\"css\",\"responsive-design\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q62","original_type":"multiple-choice","topic":"Responsive Design","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '2fbca2eb-9f19-47f4-9f3c-f98ee48296e8',
      'What is retina graphics? How to handle images for retina screens?',
      'Retina displays have high pixel density. Use `srcset`, `picture`, or media queries to serve higher-resolution images conditionally.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Serving 2x images to high-DPR devices improves sharpness without bloating bandwidth for standard screens.',
      NULL,
      NULL,
      '[\"css\",\"images\",\"advanced\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q63","original_type":"open-ended","topic":"Images","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'a80a17c7-f21f-4058-ba9e-9f075cce3327',
      'Is there any reason to use translate() instead of absolute positioning?',
      'Yes. `translate()` triggers compositing (GPU) without reflow/repaint, making animations smoother. Absolute positioning triggers layout recalculations.',
      'true-false',
      'advanced',
      8,
      '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
      'false',
      '`transform: translate()` is compositor-only; `position: absolute` with `top/left` triggers layout, paint, and composite.',
      NULL,
      NULL,
      '[\"css\",\"css-performance\",\"advanced\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q64","original_type":"true-false","topic":"CSS Performance","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '6ddc246f-62d5-4f44-af0e-b8954850d0c7',
      'Can the translate() function move an element on the z-axis?',
      'No. `translate()` is 2D. Use `translateZ()` or `translate3d()` for z-axis movement.',
      'true-false',
      'intermediate',
      5,
      '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
      'false',
      '`translate(x, y)` is shorthand for 2D. For 3D, use `translate3d(x, y, z)` or `translateZ(z)`.',
      NULL,
      NULL,
      '[\"css\",\"css-transforms\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q65","original_type":"true-false","topic":"CSS Transforms","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'c8291175-1df6-4ca7-a52f-190c1ac8c1aa',
      'What is an At-Rule in CSS?',
      'At-rules (`@...`) instruct CSS on how to behave. Examples: `@media`, `@import`, `@font-face`, `@keyframes`.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"`@media`, `@import`, `@font-face`, `@keyframes`","isCorrect":true,"explanation":""},{"id":"b","text":"At-rules are invalid in modern CSS","isCorrect":false,"explanation":""},{"id":"c","text":"`@rule` is the correct syntax","isCorrect":false,"explanation":""},{"id":"d","text":"Only `@media` is an at-rule","isCorrect":false,"explanation":""}]',
      'c',
      'At-rules begin with `@` and define conditional or structural behavior in CSS.',
      NULL,
      NULL,
      '[\"css\",\"css-fundamentals\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q66","original_type":"multiple-choice","topic":"CSS Fundamentals","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '5c62d334-3a5a-42b2-a9e5-5767eb274895',
      'How can the gap under an image be removed?',
      'Images are inline by default, causing a gap for descenders. Fix with `display: block` or `vertical-align: top/bottom`.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The gap is reserved for text descenders (like ''g'', ''y''). Making the image block-level removes it.',
      NULL,
      NULL,
      '[\"css\",\"css-box-model\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q67","original_type":"open-ended","topic":"CSS Box Model","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '8047a28b-5e4d-4230-8d01-c9cbf981ad4a',
      'What is progressive rendering?',
      'Progressive rendering improves perceived load time by displaying content as it becomes available (e.g., lazy loading, above-the-fold first).',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It prioritizes critical content to give users immediate feedback while non-critical assets load later.',
      NULL,
      NULL,
      '[\"css\",\"css-performance\",\"advanced\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q68","original_type":"open-ended","topic":"CSS Performance","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'd950090a-4a41-43de-acc0-2ab33bf9e25c',
      'What is mobile-first CSS? How does it differ from responsive design?',
      'Mobile-first is a responsive strategy that starts with base styles for mobile, then enhances for larger screens using `min-width` media queries.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Mobile-first reduces unnecessary styles on mobile and improves performance by avoiding overrides.',
      NULL,
      NULL,
      '[\"css\",\"responsive-design\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q69","original_type":"open-ended","topic":"Responsive Design","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'c0dc434d-456f-4710-a9f6-2124788ba9fa',
      'Which property changes the font face?',
      'The `font-family` property specifies the font face.',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"`font-family`","isCorrect":true,"explanation":""},{"id":"b","text":"`font-face`","isCorrect":false,"explanation":""},{"id":"c","text":"`font-style`","isCorrect":false,"explanation":""},{"id":"d","text":"`font`","isCorrect":false,"explanation":""}]',
      'c',
      '`font-family` defines a prioritized list of fonts, with fallbacks to system fonts.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"beginner\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q70","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '176a2b84-ab44-446e-8965-77cf039e84fe',
      'Which property makes text italic or oblique?',
      'The `font-style` property makes text italic (`italic`) or oblique (`oblique`).',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"`font-style`","isCorrect":true,"explanation":""},{"id":"b","text":"`font-variant`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-transform`","isCorrect":false,"explanation":""},{"id":"d","text":"`font-weight`","isCorrect":false,"explanation":""}]',
      'c',
      '`font-style: italic` uses true italic fonts; `oblique` slants the regular font.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"beginner\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q71","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'dca28655-f1cb-4f3a-9903-d065241c9d4c',
      'Which property creates a small-caps effect?',
      'The `font-variant` property with `small-caps` creates small capital letters.',
      'multiple-choice',
      'intermediate',
      5,
      '[{"id":"a","text":"`font-variant`","isCorrect":true,"explanation":""},{"id":"b","text":"`text-transform: capitalize`","isCorrect":false,"explanation":""},{"id":"c","text":"`font-style: small-caps`","isCorrect":false,"explanation":""},{"id":"d","text":"`text-variant`","isCorrect":false,"explanation":""}]',
      'c',
      '`font-variant: small-caps` renders lowercase letters as smaller uppercase glyphs.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q72","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '3fd0a2cc-6e04-4552-8281-fa9f8b28b95f',
      'Which property controls font boldness?',
      'The `font-weight` property controls how bold or light a font appears (e.g., `normal`, `bold`, `400`, `700`).',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"`font-weight`","isCorrect":true,"explanation":""},{"id":"b","text":"`font-style`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-bold`","isCorrect":false,"explanation":""},{"id":"d","text":"`font-emphasis`","isCorrect":false,"explanation":""}]',
      'c',
      'Values range from 100 (thin) to 900 (black); `normal` = 400, `bold` = 700.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"beginner\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q73","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '843a6980-3a89-440d-b4b8-1da471c28639',
      'Which property adjusts space between letters?',
      'The `letter-spacing` property adds or subtracts space between characters.',
      'multiple-choice',
      'intermediate',
      5,
      '[{"id":"a","text":"`letter-spacing`","isCorrect":true,"explanation":""},{"id":"b","text":"`word-spacing`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-spacing`","isCorrect":false,"explanation":""},{"id":"d","text":"`char-spacing`","isCorrect":false,"explanation":""}]',
      'c',
      'Positive values increase spacing; negative values tighten it (use cautiously).',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q74","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '22918239-2cba-4b19-ba60-613f046bed69',
      'Which property adjusts space between words?',
      'The `word-spacing` property adds or subtracts space between words.',
      'multiple-choice',
      'intermediate',
      5,
      '[{"id":"a","text":"`word-spacing`","isCorrect":true,"explanation":""},{"id":"b","text":"`letter-spacing`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-indent`","isCorrect":false,"explanation":""},{"id":"d","text":"`line-height`","isCorrect":false,"explanation":""}]',
      'c',
      'Useful for adjusting readability in justified text or tight layouts.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q75","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '9cb192c3-a02f-4ebc-9da6-73e95f3ce255',
      'Which property indents the first line of a paragraph?',
      'The `text-indent` property indents the first line of text.',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"`text-indent`","isCorrect":true,"explanation":""},{"id":"b","text":"`margin-left`","isCorrect":false,"explanation":""},{"id":"c","text":"`padding-left`","isCorrect":false,"explanation":""},{"id":"d","text":"`first-line-indent`","isCorrect":false,"explanation":""}]',
      'c',
      'Commonly used in print-style layouts to indicate new paragraphs.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"beginner\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q76","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '003f9795-5b51-4abd-b3c6-463c6b4db476',
      'Which property aligns text?',
      'The `text-align` property aligns text horizontally (`left`, `right`, `center`, `justify`).',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"`text-align`","isCorrect":true,"explanation":""},{"id":"b","text":"`align-text`","isCorrect":false,"explanation":""},{"id":"c","text":"`horizontal-align`","isCorrect":false,"explanation":""},{"id":"d","text":"`justify`","isCorrect":false,"explanation":""}]',
      'c',
      'Applies to block-level elements; aligns inline content within the block.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"beginner\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q77","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '2b5912e3-84c1-4a09-8589-121bf5c6633b',
      'Which property underlines, overlines, or strikes through text?',
      'The `text-decoration` property controls underline, overline, line-through, and blink effects.',
      'multiple-choice',
      'intermediate',
      5,
      '[{"id":"a","text":"`text-decoration`","isCorrect":true,"explanation":""},{"id":"b","text":"`font-decoration`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-style`","isCorrect":false,"explanation":""},{"id":"d","text":"`underline`","isCorrect":false,"explanation":""}]',
      'c',
      'Modern syntax allows control over style, color, and thickness of the decoration line.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q78","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '5c00ba62-5e35-4e1b-80dc-6c898ca1575b',
      'Which property capitalizes or changes text case?',
      'The `text-transform` property converts text to uppercase, lowercase, or capitalized form.',
      'multiple-choice',
      'intermediate',
      5,
      '[{"id":"a","text":"`text-transform`","isCorrect":true,"explanation":""},{"id":"b","text":"`font-case`","isCorrect":false,"explanation":""},{"id":"c","text":"`text-case`","isCorrect":false,"explanation":""},{"id":"d","text":"`transform-text`","isCorrect":false,"explanation":""}]',
      'c',
      'Useful for ensuring consistent casing without changing HTML content.',
      NULL,
      NULL,
      '[\"css\",\"css-typography\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q79","original_type":"multiple-choice","topic":"CSS Typography","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'aecac396-e4c5-4d67-8800-eabaa85c4ccb',
      'Which property controls list marker appearance?',
      'The `list-style-type` property sets the marker shape for list items (e.g., `disc`, `circle`, `square`, `decimal`).',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"`list-style-type`","isCorrect":true,"explanation":""},{"id":"b","text":"`marker-type`","isCorrect":false,"explanation":""},{"id":"c","text":"`list-marker`","isCorrect":false,"explanation":""},{"id":"d","text":"`bullet-style`","isCorrect":false,"explanation":""}]',
      'c',
      'Also supports custom images via `list-style-image` and position via `list-style-position`.',
      NULL,
      NULL,
      '[\"css\",\"lists\",\"intermediate\"]',
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-16-80-css-q80","original_type":"multiple-choice","topic":"Lists","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.364Z',
      '2025-10-21T22:01:49.364Z'
    );;
