-- Batch 6: Questions 101-120
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES
('ed4e3560-6365-486d-98d8-d20f3799ddd1', 'Give a simple example of Jest test case', 'Let''s write a test for a function that adds two numbers in `sum.js` file:

```javascript
const sum = (a, b) => a + b;

export default sum;
```

Create a file named `sum.test.js` which contains actual test:

```javascript
import sum from "./sum";

test("adds 1 + 2 to equal 3", () => {
  expect(sum(1, 2)).toBe(3);
});
```

And then add the following section to your `package.json`:

```json
{
  "scripts": {
    "test": "jest"
  }
}
```

Finally, run `yarn test` or `npm test` and Jest will print a result.', 'multiple-choice', 'beginner', 5, NULL, NULL, 'This is a basic Jest test case demonstrating how to test a pure function using `expect().toBe()`. Jest automatically finds files ending in `.test.js` and runs them when the `test` script is executed.', NULL, ARRAY[]::text[], ARRAY['jest','testing','unit-testing','javascript'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q101","original_type":"open-ended","topic":"Unit Testing","subcategory":"Jest","sample_answers":["A Jest test file imports the function to test, uses `test()` to define a test case, and asserts expected behavior with `expect().toBe()`.","The test verifies that `sum(1, 2)` returns `3`, and Jest runs it via `npm test` after configuring the script in `package.json`."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('7cfeef90-42e0-4628-8c62-ccc9b9fd60a1', 'What is Flux?', 'Flux is an application architecture (not a framework or library) designed by Facebook to manage data flow in React applications. It emphasizes a unidirectional data flow using four key components: Actions, Dispatcher, Stores, and Views (React Components).', 'multiple-choice', 'intermediate', 8, NULL, NULL, 'Flux enforces unidirectional data flow: Views trigger Actions → Dispatcher broadcasts Actions → Stores update → Views re-render. This makes state changes predictable and easier to debug.', NULL, ARRAY[]::text[], ARRAY['flux','react','architecture','state-management'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q102","original_type":"open-ended","topic":"Flux Architecture","subcategory":"Design Patterns","sample_answers":["Flux is an architecture that uses a unidirectional data flow with Actions, a central Dispatcher, Stores for state, and React Views that respond to store changes.","Unlike MVC, Flux avoids two-way binding and ensures data flows in one direction, improving traceability and reducing side effects."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('46a4521d-076d-42d7-88a1-776636434b1f', 'What is Redux?', 'Redux is a predictable state container for JavaScript applications, most commonly used with React. It helps manage and centralize application state in a single source of truth.', 'multiple-choice', 'beginner', 5, NULL, NULL, 'Redux provides a centralized store for application state, updated only via pure reducer functions in response to dispatched actions. It enables time-travel debugging and predictable state changes.', NULL, ARRAY[]::text[], ARRAY['redux','state-management','react','javascript'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q103","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Redux is a state management library that stores the entire app state in a single immutable object tree, updated only by dispatching actions to pure reducer functions.","It offers a single source of truth, read-only state, and changes via pure functions—making apps easier to test, debug, and scale."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('b6761c98-5edf-4ae8-8450-448e2b68bab0', 'What are the core principles of Redux?', 'Redux follows three fundamental principles:
1. Single source of truth
2. State is read-only
3. Changes are made with pure functions (Reducers)', 'multiple-choice', 'beginner', 6, '[{"id":"a","text":"Single store, mutable state, async reducers","isCorrect":false},{"id":"b","text":"Multiple stores, read-only state, impure reducers","isCorrect":false},{"id":"c","text":"Single source of truth, read-only state, pure reducer functions","isCorrect":true},{"id":"d","text":"Global state, two-way binding, side-effectful reducers","isCorrect":false}]', NULL, 'The three principles ensure predictability: (1) all state in one store, (2) state changed only by dispatching actions, (3) reducers are pure functions that return new state.', NULL, ARRAY[]::text[], ARRAY['redux','principles','state-management'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q104","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('3d79362a-4750-444b-943a-078852bc31dd', 'What are the downsides of Redux compared to Flux?', 'While Redux offers a powerful state management solution, it comes with trade-offs compared to Flux, including strict immutability, need for complementary packages, and less seamless static type integration.', 'multiple-choice', 'intermediate', 7, '[{"id":"a","text":"Redux allows mutable state by default","isCorrect":false},{"id":"b","text":"Redux requires immutability, careful package selection, and has less mature static type support","isCorrect":true},{"id":"c","text":"Flux is more minimal than Redux","isCorrect":false},{"id":"d","text":"Redux uses two-way data binding","isCorrect":false}]', NULL, 'Redux requires immutability discipline, careful middleware selection, and historically had weaker static typing support than Flux with Flow.', NULL, ARRAY[]::text[], ARRAY['redux','flux','comparison','state-management'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q105","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('888c0805-9b5e-4795-bf93-69a2e51aba9c', 'What is the difference between `mapStateToProps()` and `mapDispatchToProps()`?', '`mapStateToProps()` connects Redux state to component props. `mapDispatchToProps()` connects action dispatchers to component props.', 'multiple-choice', 'intermediate', 6, '[{"id":"a","text":"`mapStateToProps` dispatches actions; `mapDispatchToProps` reads state","isCorrect":false},{"id":"b","text":"`mapStateToProps` reads state; `mapDispatchToProps` dispatches actions","isCorrect":true},{"id":"c","text":"Both are used only for async logic","isCorrect":false},{"id":"d","text":"They are identical in functionality","isCorrect":false}]', NULL, '`mapStateToProps` reads from the store; `mapDispatchToProps` dispatches actions. The object shorthand form is preferred for `mapDispatchToProps`.', NULL, ARRAY[]::text[], ARRAY['react-redux','connect','mapstatetoprops','mapdispatchtoprops'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q106","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('db086192-0bf9-41ff-b7cf-8f8fde936b9c', 'Can I dispatch an action in a reducer?', 'Dispatching an action within a reducer is an anti-pattern. Reducers should be pure functions without side effects.', 'multiple-choice', 'intermediate', 4, '[{"id":"a","text":"True","isCorrect":false},{"id":"b","text":"False","isCorrect":true}]', NULL, 'Reducers must be pure: no side effects, no API calls, no dispatching. Dispatching inside a reducer breaks predictability and can cause infinite loops.', NULL, ARRAY[]::text[], ARRAY['redux','reducers','side-effects','anti-pattern'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q107","original_type":"true-false","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('85e57da9-fa59-46b2-94ce-26e54a5d1010', 'How to access Redux store outside a component?', 'You can export the store instance from the module where it was created using `createStore()`.', 'multiple-choice', 'intermediate', 5, NULL, NULL, 'Export the store from its creation file and import it where needed. Avoid attaching it to `window` in production.', NULL, ARRAY[]::text[], ARRAY['redux','store','outside-component'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q108","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Export the store from the file where `createStore()` is called, then import it in other modules to use `store.dispatch()` or `store.getState()`.","Example: `export default createStore(reducer);` then `import store from ''./store'';`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('5192d0fa-f351-4825-b2fc-301bde1f298f', 'What are the drawbacks of MVW pattern?', 'Drawbacks include expensive DOM manipulation, circular dependencies, difficulty handling collaborative data changes, and lack of easy undo functionality.', 'multiple-choice', 'intermediate', 6, '[{"id":"a","text":"Easy undo, cheap DOM updates, no circular dependencies","isCorrect":false},{"id":"b","text":"Expensive DOM manipulation, circular dependencies, no easy undo","isCorrect":true},{"id":"c","text":"Built-in time-travel debugging","isCorrect":false},{"id":"d","text":"Unidirectional data flow by default","isCorrect":false}]', NULL, 'MVW (Model-View-Whatever) inherits MVC’s issues: tight coupling, hard-to-debug state, and no built-in time-travel or undo.', NULL, ARRAY[]::text[], ARRAY['mvc','mvvm','mvw','architecture'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q109","original_type":"multiple-choice","topic":"MVC & MVVM","subcategory":"Design Patterns","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('43d2c45f-3838-4b58-bca6-dd99ca442f9b', 'Are there any similarities between Redux and RxJS?', 'Both use reactive programming concepts, but Redux is for state management architecture, while RxJS is a library for asynchronous programming with Observables.', 'multiple-choice', 'advanced', 5, '[{"id":"a","text":"True","isCorrect":true},{"id":"b","text":"False","isCorrect":false}]', NULL, 'Both are reactive: Redux store reacts to actions; RxJS streams react to events. But Redux is architectural; RxJS is a utility library.', NULL, ARRAY[]::text[], ARRAY['redux','rxjs','reactive','observables'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q110","original_type":"true-false","topic":"Reactive Programming","subcategory":"Functional Programming","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('3b852d63-30f2-4522-ad34-377f5350cbf1', 'How to reset state in Redux?', 'Use a root reducer that returns `undefined` state on a logout action, causing reducers to return initial state.', 'multiple-choice', 'advanced', 8, NULL, NULL, 'Wrap the combined reducer in a root reducer that sets state to `undefined` on `USER_LOGOUT`, triggering all reducers to return initial state.', NULL, ARRAY[]::text[], ARRAY['redux','reset-state','logout','root-reducer'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q111","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Create a root reducer that checks for a ''USER_LOGOUT'' action and passes `undefined` as state to the main reducer, which then returns initial state.","If using `redux-persist`, also clear persisted storage keys before resetting state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('0e2ab727-b4ce-4a3b-9247-7664559442f9', 'What is the difference between React Context and React Redux?', 'Context is for passing data to deeply nested components; Redux is a full state management solution with dev tools, middleware, and time-travel debugging.', 'multiple-choice', 'intermediate', 7, '[{"id":"a","text":"Context provides middleware and time-travel debugging","isCorrect":false},{"id":"b","text":"Redux is simpler and built into React","isCorrect":false},{"id":"c","text":"Context is for simple prop drilling; Redux is a full state management library with advanced tooling","isCorrect":true},{"id":"d","text":"They are functionally identical","isCorrect":false}]', NULL, 'Context is built-in but lacks Redux’s ecosystem (middleware, DevTools, etc.). Redux uses Context internally but offers more features.', NULL, ARRAY[]::text[], ARRAY['react','context','redux','state-management'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q112","original_type":"multiple-choice","topic":"Context API vs Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('a00086e9-59c9-4acd-8f39-382e51d8af0e', 'Why are Redux state functions called reducers?', 'Because they reduce a collection of actions and an initial state to a final state, similar to the `reduce()` array method.', 'multiple-choice', 'intermediate', 6, NULL, NULL, 'Like `Array.prototype.reduce()`, Redux reducers accumulate state by applying each action to the previous state.', NULL, ARRAY[]::text[], ARRAY['redux','reducers','functional-programming'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q113","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Reducers ''reduce'' a sequence of actions and an initial state into a final state, just like the reduce() function in functional programming.","Each action is applied to the current state to produce the next state, accumulating the result over time."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('207a491b-902a-4512-b67b-e0e563cdf4ba', 'How to make AJAX request in Redux?', 'Use middleware like `redux-thunk` to write async action creators that dispatch actions based on API responses.', 'multiple-choice', 'intermediate', 8, NULL, NULL, 'With `redux-thunk`, action creators return a function that receives `dispatch` and can perform async logic before dispatching actions.', NULL, ARRAY[]::text[], ARRAY['redux','ajax','async','redux-thunk'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q114","original_type":"open-ended","topic":"Async Actions","subcategory":"State Management","sample_answers":["Use `redux-thunk` middleware to return a function from an action creator. Inside, dispatch a ''loading'' action, make the API call, then dispatch success or error actions.","Example: `export const fetchUser = (id) => async (dispatch) => { dispatch({type: ''LOADING''}); const res = await fetch(...); dispatch({type: ''SUCCESS'', payload: res}); }`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('fb83885a-1ee2-4480-b901-edd8c077e92e', 'Should I keep all component''s state in Redux store?', 'No. Keep global or shared state in Redux; keep UI or local state (e.g., form inputs, dropdown open state) in the component.', 'multiple-choice', 'beginner', 4, '[{"id":"a","text":"True","isCorrect":false},{"id":"b","text":"False","isCorrect":true}]', NULL, 'Only put state in Redux if it’s shared across components or needs to persist. Local UI state should stay in the component.', NULL, ARRAY[]::text[], ARRAY['redux','state','best-practices'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q115","original_type":"true-false","topic":"Redux Best Practices","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('494428e1-729f-4357-ba9a-83a03a1570de', 'What is the proper way to access Redux store in a component?', 'Use the `connect()` function from `react-redux` to create a higher-order component that injects state and dispatch props.', 'multiple-choice', 'intermediate', 6, '[{"id":"a","text":"Access `this.context.store` directly","isCorrect":false},{"id":"b","text":"Use `connect()` from `react-redux`","isCorrect":true},{"id":"c","text":"Import the store and call `store.getState()` in render","isCorrect":false},{"id":"d","text":"Use `useContext(StoreContext)` always","isCorrect":false}]', NULL, '`connect()` is the recommended way—it’s optimized and avoids direct store access via context.', NULL, ARRAY[]::text[], ARRAY['react-redux','connect','hoc'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q116","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('c2f568ef-5eab-43dd-840c-d6a5ca557df0', 'What is the difference between component and container in React Redux?', 'Components are presentational (dumb); containers are connected to Redux (smart) and handle data fetching and dispatching.', 'multiple-choice', 'beginner', 5, '[{"id":"a","text":"Components handle logic; containers render UI","isCorrect":false},{"id":"b","text":"Components are presentational; containers are connected to Redux","isCorrect":true},{"id":"c","text":"They are the same","isCorrect":false},{"id":"d","text":"Containers cannot have children","isCorrect":false}]', NULL, 'Containers are connected to Redux; components are pure UI. Modern React often uses hooks instead of this pattern.', NULL, ARRAY[]::text[], ARRAY['react','redux','container','presentational'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q117","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('0b9b8796-0e05-4bf2-848d-d7276b791392', 'What is the purpose of constants in Redux?', 'Constants (action types) prevent typos, enable IDE search, and centralize action type definitions.', 'multiple-choice', 'beginner', 5, '[{"id":"a","text":"They increase bundle size unnecessarily","isCorrect":false},{"id":"b","text":"They prevent typos and enable better tooling","isCorrect":true},{"id":"c","text":"They are required by the Redux library","isCorrect":false},{"id":"d","text":"They make reducers slower","isCorrect":false}]', NULL, 'Using constants like `ADD_TODO` instead of string literals avoids bugs from typos and makes refactoring easier.', NULL, ARRAY[]::text[], ARRAY['redux','constants','action-types'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q118","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('183743f5-9b13-4d9f-82d8-d69e5d3d8ab3', 'What are the different ways to write `mapDispatchToProps()`?', 'You can write it as a function with `dispatch`, use `bindActionCreators`, or use the object shorthand.', 'multiple-choice', 'intermediate', 6, '[{"id":"a","text":"Only the function form is valid","isCorrect":false},{"id":"b","text":"Function with dispatch, bindActionCreators, or object shorthand","isCorrect":true},{"id":"c","text":"You must always use `bindActionCreators`","isCorrect":false},{"id":"d","text":"Object shorthand doesn’t work with `connect`","isCorrect":false}]', NULL, 'The object shorthand `{ action }` is preferred—it’s concise and automatically binds dispatch.', NULL, ARRAY[]::text[], ARRAY['react-redux','mapdispatchtoprops','bindactioncreators'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q119","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('b5d5d145-5431-4ec2-bcd5-9a025d6f41c6', 'What is the use of `ownProps` in `mapStateToProps` and `mapDispatchToProps`?', '`ownProps` contains the props passed to the connected component, allowing conditional mapping based on those props.', 'multiple-choice', 'intermediate', 6, NULL, NULL, 'If your component is used as `<MyComp id={5} />`, then `ownProps` will be `{ id: 5 }` inside the `map` functions.', NULL, ARRAY[]::text[], ARRAY['react-redux','ownprops','connect'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q120","original_type":"open-ended","topic":"React Redux","subcategory":"State Management","sample_answers":["`ownProps` lets you access the original props passed to the connected component, so you can filter state or bind actions based on those props.","Example: `mapStateToProps = (state, ownProps) => ({ user: state.users[ownProps.userId] })`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z');
