INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES ((gen_random_uuid(),
      'What is Critical CSS? How does it improve page load performance?',
      'Performance optimization requires understanding Critical CSS. Explain its purpose and implementation.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Above-the-fold styles inlined in head; improves First Contentful Paint","isCorrect":true,"explanation":"Correct. Critical CSS reduces render-blocking."},{"id":"o2","text":"All CSS in one file","isCorrect":false,"explanation":"Incorrect. Critical CSS is only above-the-fold styles."},{"id":"o3","text":"CSS loaded after page render","isCorrect":false,"explanation":"Incorrect. Critical CSS loads first, inline."},{"id":"o4","text":"Only needed for mobile","isCorrect":false,"explanation":"Incorrect. Critical CSS helps on all devices."}]',
      'Above-the-fold styles inlined in head; improves First Contentful Paint',
      'Critical CSS: above-the-fold styles needed for initial render. Inline in <head> to avoid render-blocking. Remaining CSS loads asynchronously. Improves First Contentful Paint (FCP), reduces render-blocking. Essential for performance.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'critical-css', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Which techniques reduce CSS file size? (Select all that apply)',
      'Smaller CSS files load faster. Identify techniques that reduce CSS file size.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Minification (remove whitespace, comments)","isCorrect":true,"explanation":"Correct. Minification reduces file size."},{"id":"o2","text":"Unused CSS removal (PurgeCSS)","isCorrect":true,"explanation":"Correct. Removing unused CSS reduces size."},{"id":"o3","text":"Compression (gzip, brotli)","isCorrect":true,"explanation":"Correct. Compression reduces transfer size."},{"id":"o4","text":"Adding more comments","isCorrect":false,"explanation":"Incorrect. Comments increase file size."}]',
      'Minification (remove whitespace, comments)',
      'Minification (remove whitespace, comments), unused CSS removal (PurgeCSS), compression (gzip/brotli), code splitting, removing duplicate rules, using shorthand properties, avoiding !important overuse.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'optimization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Explain CSS loading strategies. What is the difference between render-blocking and non-blocking CSS?',
      'CSS loading affects page performance. Explain render-blocking vs non-blocking CSS and optimization strategies.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Render-blocking: blocks parsing (default); Non-blocking: async loading for non-critical CSS","isCorrect":true,"explanation":"Correct. Non-blocking improves performance."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They affect performance differently."},{"id":"o3","text":"All CSS should be render-blocking","isCorrect":false,"explanation":"Incorrect. Non-critical CSS should load async."},{"id":"o4","text":"Non-blocking CSS doesn''t work","isCorrect":false,"explanation":"Incorrect. Non-blocking CSS is a valid optimization."}]',
      'Render-blocking: blocks parsing (default); Non-blocking: async loading for non-critical CSS',
      'Render-blocking: CSS in <head> blocks HTML parsing until loaded (default). Non-blocking: load asynchronously (media=''print'' then switch, or load via JS). Critical CSS inline, non-critical async. Improves Time to First Byte, FCP.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'loading', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'What is the purpose of ''content-visibility'' property? How does it improve rendering performance?',
      'Modern CSS provides rendering optimizations. Explain content-visibility and its performance benefits.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Skips rendering off-screen content until needed; improves initial render performance","isCorrect":true,"explanation":"Correct. content-visibility optimizes rendering."},{"id":"o2","text":"Hides content permanently","isCorrect":false,"explanation":"Incorrect. It defers rendering, doesn''t hide."},{"id":"o3","text":"Only works with JavaScript","isCorrect":false,"explanation":"Incorrect. content-visibility is pure CSS."},{"id":"o4","text":"Increases rendering time","isCorrect":false,"explanation":"Incorrect. It reduces rendering time."}]',
      'Skips rendering off-screen content until needed; improves initial render performance',
      '<code>content-visibility:</code> auto skips rendering off-screen content until needed. Significantly improves initial render for long pages. Similar to lazy loading but for rendering. Use on sections that are initially off-screen. Limited browser support.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'content-visibility', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Which CSS properties trigger expensive layout recalculations? (Select all that apply)',
      'Layout performance matters. Identify properties that trigger layout (reflow) and should be avoided in animations.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"width / height (triggers layout)","isCorrect":true,"explanation":"Correct. These trigger expensive layout."},{"id":"o2","text":"margin / padding (triggers layout)","isCorrect":true,"explanation":"Correct. These trigger layout recalculation."},{"id":"o3","text":"transform (GPU-accelerated, no layout)","isCorrect":false,"explanation":"Incorrect. transform doesn''t trigger layout."},{"id":"o4","text":"opacity (GPU-accelerated, no layout)","isCorrect":false,"explanation":"Incorrect. opacity doesn''t trigger layout."}]',
      'width / height (triggers layout)',
      'Layout-triggering properties: width, height, margin, padding, border, display, position (static/relative), top/left/right/bottom, font-size, line-height. These cause reflow (expensive). Use transform/opacity for animations instead.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'layout', 'reflow', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Explain CSS containment. How does ''contain'' property optimize rendering?',
      'CSS containment is a performance feature. Explain the contain property and its optimization benefits.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Isolates element rendering; prevents changes from affecting outside; optimizes layout/paint","isCorrect":true,"explanation":"Correct. Containment optimizes rendering scope."},{"id":"o2","text":"Hides the element","isCorrect":false,"explanation":"Incorrect. contain optimizes, doesn''t hide."},{"id":"o3","text":"Only works with Flexbox","isCorrect":false,"explanation":"Incorrect. contain works with any layout."},{"id":"o4","text":"Increases rendering cost","isCorrect":false,"explanation":"Incorrect. contain reduces rendering cost."}]',
      'Isolates element rendering; prevents changes from affecting outside; optimizes layout/paint',
      '<code>contain:</code> isolates element''s rendering (layout, style, paint, size). Prevents changes from affecting outside. Optimizes: layout (<code>contain:</code> layout), paint (<code>contain:</code> paint), style recalculation. Use on isolated components. Improves performance for complex pages.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'containment', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'What is the difference between ''will-change'' and ''contain'' for performance optimization?',
      'Both properties optimize performance. Explain when to use will-change vs contain and their different purposes.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"<code>will-change:</code> animation optimization; <code>contain:</code> rendering isolation for components","isCorrect":true,"explanation":"Correct. They optimize different aspects."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They serve different optimization purposes."},{"id":"o3","text":"contain is deprecated","isCorrect":false,"explanation":"Incorrect. Both are modern features."},{"id":"o4","text":"will-change isolates rendering","isCorrect":false,"explanation":"Incorrect. That''s contain''s purpose."}]',
      '<code>will-change:</code> animation optimization; <code>contain:</code> rendering isolation for components',
      '<code>will-change:</code> hints about upcoming changes, promotes to GPU layer, use for animations about to start. <code>contain:</code> isolates rendering scope, prevents cascade effects, use for isolated components. Different purposes: will-change for animations, contain for isolation.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'will-change', 'contain', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Which strategies improve CSS delivery performance? (Select all that apply)',
      'CSS delivery affects page load. Identify strategies that improve CSS loading and rendering performance.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Critical CSS inline in <head>","isCorrect":true,"explanation":"Correct. Inline critical CSS reduces render-blocking."},{"id":"o2","text":"Preload for critical CSS files","isCorrect":true,"explanation":"Correct. Preload prioritizes critical resources."},{"id":"o3","text":"Code splitting (separate CSS per route)","isCorrect":true,"explanation":"Correct. Code splitting reduces initial payload."},{"id":"o4","text":"Load all CSS synchronously","isCorrect":false,"explanation":"Incorrect. Async loading is better for non-critical CSS."}]',
      'Critical CSS inline in <head>',
      'Critical CSS inline, non-critical async, HTTP/2 server push, preload for critical CSS, code splitting, CDN delivery, compression (gzip/brotli), remove unused CSS, minification.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'delivery', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'Explain ''font-display'' property. How does it affect font loading performance?',
      'Web fonts can block rendering. Explain font-display and its impact on performance and user experience.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Controls font rendering strategy; swap shows fallback immediately (best for performance)","isCorrect":true,"explanation":"Correct. swap prevents invisible text."},{"id":"o2","text":"Controls font file size","isCorrect":false,"explanation":"Incorrect. font-display controls rendering, not file size."},{"id":"o3","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. font-display is a modern, important feature."},{"id":"o4","text":"Only works with system fonts","isCorrect":false,"explanation":"Incorrect. font-display works with web fonts."}]',
      'Controls font rendering strategy; swap shows fallback immediately (best for performance)',
      'font-display controls font rendering: block (invisible until loaded, FOIT), swap (show fallback immediately, FOUT), fallback (short block then swap), optional (only if cached). swap is best for performance, prevents invisible text.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'fonts', 'font-display', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300),
    (gen_random_uuid(),
      'What is the purpose of CSS ''<code>contain:</code> layout''? How does it optimize layout calculations?',
      'Layout containment is a performance feature. Explain <code>contain:</code> layout and its optimization benefits.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Isolates layout calculations; changes inside don''t affect outside; optimizes performance","isCorrect":true,"explanation":"Correct. Layout containment optimizes calculations."},{"id":"o2","text":"Prevents layout from working","isCorrect":false,"explanation":"Incorrect. It optimizes layout, doesn''t prevent it."},{"id":"o3","text":"Only works with Grid","isCorrect":false,"explanation":"Incorrect. contain works with any layout method."},{"id":"o4","text":"Increases layout calculations","isCorrect":false,"explanation":"Incorrect. It reduces layout calculations."}]',
      'Isolates layout calculations; changes inside don''t affect outside; optimizes performance',
      '<code>contain:</code> layout isolates element''s layout calculations. Changes inside don''t affect outside layout. Browser can skip layout calculations for outside elements. Use on isolated components. Improves performance for complex layouts.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'containment', 'layout', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300));