-- Batch 10: Questions 91-100
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES
('fd7262e6-b892-40bc-8092-b7012fbf0e24', 'What are the main features of React Intl?', 'React Intl features include:
1. Formatting numbers with separators
2. Displaying dates/times correctly
3. Relative time formatting (e.g., "2 hours ago")
4. Pluralization support
5. 150+ language support
6. Works in browser and Node
7. Built on Unicode standards', 'multiple-choice', 'intermediate', 3, '[{"id":"a","text":"State management and routing","isCorrect":false},{"id":"b","text":"Number/date formatting, plurals, relative time, 150+ languages","isCorrect":true},{"id":"c","text":"Only string translation","isCorrect":false},{"id":"d","text":"CSS-in-JS theming","isCorrect":false}]', NULL, 'React Intl handles all common i18n needs: number/date formatting, plurals, relative time, and multi-language support.', NULL, ARRAY[], ARRAY['react','intl','i18n','formatting','localization'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"react-q-091","original_type":"multiple-choice","topic":"React Intl","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"system","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('ac3e67bf-b463-4f75-a446-9e64019944d3', 'What are the two ways of formatting in React Intl?', 'React Intl provides two formatting approaches:
1. **Components**: `<FormattedMessage id="msg" defaultMessage="Hello" />`
2. **API**: `formatMessage({ id: ''msg'', defaultMessage: ''Hello'' })` via `injectIntl` or `useIntl` hook', 'multiple-choice', 'intermediate', 3, '[{"id":"a","text":"Only components are supported","isCorrect":false},{"id":"b","text":"Components (`<FormattedMessage>`) and API (`formatMessage`)","isCorrect":true},{"id":"c","text":"Only the API is supported","isCorrect":false},{"id":"d","text":"Use `Intl` global object only","isCorrect":false}]', NULL, 'Use components for JSX; use the API (`formatMessage`) for placeholders, alt text, or dynamic values.', NULL, ARRAY[], ARRAY['react','intl','formatmessage','useintl','components','api'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"react-q-092","original_type":"multiple-choice","topic":"React Intl","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"system","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('c0bea7b6-c857-468a-a591-fe3243f2dc1d', 'How to use FormattedMessage as a placeholder with React Intl?', '`<Formatted... />` components return elements, not strings, so they can’t be used for placeholders or alt text. Instead, use the `formatMessage` API from the `intl` object (via `injectIntl` or `useIntl`).

Example:
```jsx
const MyComponent = ({ intl }) => (
  <input placeholder={intl.formatMessage({ id: ''msg'' })} />
);
```', 'multiple-choice', 'advanced', 4, '[{"id":"a","text":"Use `<FormattedMessage>` directly in placeholder","isCorrect":false},{"id":"b","text":"Use `intl.formatMessage()` for placeholders and alt text","isCorrect":true},{"id":"c","text":"Placeholders don’t support i18n","isCorrect":false},{"id":"d","text":"Use `dangerouslySetInnerHTML`","isCorrect":false}]', NULL, 'For non-JSX contexts (placeholders, alt), use `intl.formatMessage()` instead of `<FormattedMessage>`.', NULL, ARRAY[], ARRAY['react','intl','placeholder','formatmessage','useintl'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"react-q-093","original_type":"multiple-choice","topic":"React Intl","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"system","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('3869c2ea-77ee-4868-8cc6-d0ce7c679f0d', 'How to access the current locale with React Intl?', 'Access the current locale using the `intl` object from `injectIntl` (HOC) or `useIntl` (hook):
```jsx
const MyComponent = ({ intl }) => (
  <div>Current locale: {intl.locale}</div>
);
export default injectIntl(MyComponent);
// or with hook:
// const { locale } = useIntl();
```', 'multiple-choice', 'intermediate', 3, '[{"id":"a","text":"`navigator.language`","isCorrect":false},{"id":"b","text":"`intl.locale` from `injectIntl` or `useIntl`","isCorrect":true},{"id":"c","text":"`process.env.LOCALE`","isCorrect":false},{"id":"d","text":"Locale is not accessible","isCorrect":false}]', NULL, 'The `intl` object (from HOC or hook) provides access to the current locale via `intl.locale`.', NULL, ARRAY[], ARRAY['react','intl','locale','useintl','injectintl'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"react-q-094","original_type":"multiple-choice","topic":"React Intl","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"system","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('c9b420e0-3047-4c88-8f95-9e6ad3954d53', 'How to format date using React Intl?', 'Use the `injectIntl()` HOC to access `formatDate()` via props. It returns a string representation of the formatted date.

```jsx
import { injectIntl, intlShape } from "react-intl";

const MyComponent = ({ intl }) => {
  const stringDate = intl.formatDate(new Date(), {
    year: "numeric",
    month: "numeric",
    day: "numeric"
  });
  return <div>{`The formatted date is ${stringDate}`}</div>;
};

MyComponent.propTypes = { intl: intlShape.isRequired };
export default injectIntl(MyComponent);
```', 'multiple-choice', 'intermediate', 6, NULL, NULL, '`injectIntl` injects the `intl` object into a component’s props, which includes `formatDate`, `formatNumber`, and other localization utilities.', NULL, ARRAY[], ARRAY['react','react-intl','i18n','date-formatting','internationalization'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q95","original_type":"open-ended","topic":"Internationalization (i18n)","subcategory":"Internationalization (i18n)","sample_answers":["Use `injectIntl` to wrap your component and access `intl.formatDate()` with options like `{ year: ''numeric'', month: ''short'' }`.","Alternatively, in modern React, use the `useIntl()` hook instead of `injectIntl` for function components."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('9b84a8ec-a2da-4bb6-a562-32ded3c2de3a', 'What is Shallow Renderer in React testing?', 'Shallow rendering renders a component one level deep without rendering child components, useful for unit testing isolated behavior.', 'multiple-choice', 'intermediate', 6, NULL, NULL, 'Shallow rendering lets you test a component’s output without instantiating or rendering its children, isolating the unit under test.', NULL, ARRAY[], ARRAY['react','testing','shallow-rendering','unit-test'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q96","original_type":"open-ended","topic":"React Testing","subcategory":"Unit Testing","sample_answers":["Shallow rendering tests only the current component’s render output, ignoring child component logic—ideal for pure unit tests.","It’s provided by `react-test-renderer/shallow` and useful for asserting structure without DOM or side effects."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('18e73c5e-f7d7-402e-b410-f14ee18bdda4', 'What is the `TestRenderer` package in React?', '`TestRenderer` renders React components to plain JavaScript objects (not DOM), enabling snapshot testing without a browser or jsdom.', 'multiple-choice', 'intermediate', 7, NULL, NULL, 'It converts a React element tree into a serializable JavaScript object, perfect for snapshot comparisons in Jest.', NULL, ARRAY[], ARRAY['react','testrenderer','snapshot-testing','testing'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q97","original_type":"open-ended","topic":"React Testing","subcategory":"Unit Testing","sample_answers":["`TestRenderer.create(<MyComponent />)` returns a renderer whose `.toJSON()` output can be snapshotted and compared across test runs.","Unlike DOM-based testing, it works in Node.js environments and supports both ReactDOM and React Native components."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('e764cbcd-5180-47a5-976f-86d23df6eb65', 'What is the purpose of ReactTestUtils package?', '`ReactTestUtils` provides utilities to simulate DOM interactions and inspect component behavior in unit tests.', 'multiple-choice', 'intermediate', 6, NULL, NULL, 'It includes methods like `Simulate.click()` and `findRenderedDOMComponentWithTag()` for testing event handling and component structure.', NULL, ARRAY[], ARRAY['react','reacttestutils','testing','dom-simulation'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q98","original_type":"open-ended","topic":"React Testing","subcategory":"Unit Testing","sample_answers":["`ReactTestUtils` allows you to trigger synthetic events (e.g., clicks) and traverse rendered component trees for assertions.","Though largely superseded by React Testing Library and `@testing-library/react`, it was foundational in early React testing."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('20b21e15-af8d-42b5-9b56-2ab2c014bdd6', 'What is Jest?', 'Jest is a JavaScript testing framework created by Facebook, based on Jasmine, with built-in mocking, snapshot testing, and jsdom support.', 'multiple-choice', 'beginner', 5, NULL, NULL, 'Jest requires minimal configuration, runs tests in parallel, and integrates seamlessly with React via `@testing-library/react` or snapshot testing.', NULL, ARRAY[], ARRAY['jest','testing','facebook','javascript','unit-testing'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q99","original_type":"open-ended","topic":"Jest","subcategory":"Unit Testing","sample_answers":["Jest is a zero-config test runner with built-in assertion library, mocking, coverage reports, and snapshot capabilities.","It uses `jsdom` to simulate a browser environment, enabling DOM-based tests to run in Node.js."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z'),
('6ff540a6-c37d-4187-b648-058218b5b674', 'What are the advantages of Jest over Jasmine?', 'Jest offers automatic test discovery, auto-mocking, better async support, jsdom integration, and parallel test execution.', 'multiple-choice', 'intermediate', 6, '[{"id":"a","text":"Jest requires more configuration than Jasmine","isCorrect":false},{"id":"b","text":"Jest has no mocking support","isCorrect":false},{"id":"c","text":"Jest auto-discovers tests, mocks dependencies, supports async, uses jsdom, and runs tests in parallel","isCorrect":true},{"id":"d","text":"Jasmine runs tests faster than Jest","isCorrect":false}]', NULL, 'Jest builds on Jasmine’s syntax but adds modern DX features like auto-mocking, snapshot testing, and zero-config setup.', NULL, ARRAY[], ARRAY['jest','jasmine','testing','comparison'], '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}', '{"original_id":"q100","original_type":"multiple-choice","topic":"Jest","subcategory":"Unit Testing","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","topic_id":null}', 'ca612436-af48-4e3f-a7fd-f9a9b2c52374', true, '2024-01-01T00:00:00.000Z', '2024-01-01T00:00:00.000Z');
