INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7257b23f-dec4-43f2-80ec-e474c8a9eb46',
          'Give a simple example of Jest test case',
          'Let''s write a test for a function that adds two numbers in `sum.js` file:

```javascript
const sum = (a, b) => a + b;

export default sum;
```

Create a file named `sum.test.js` which contains actual test:

```javascript
import sum from "./sum";

test("adds 1 + 2 to equal 3", () => {
  expect(sum(1, 2)).toBe(3);
});
```

And then add the following section to your `package.json`:

```json
{
  "scripts": {
    "test": "jest"
  }
}
```

Finally, run `yarn test` or `npm test` and Jest will print a result.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'This is a basic Jest test case demonstrating how to test a pure function using `expect().toBe()`. Jest automatically finds files ending in `.test.js` and runs them when the `test` script is executed.',
          NULL,
          ARRAY[]::text[],
          '["jest","testing","unit-testing","javascript"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q101","original_type":"open-ended","topic":"Unit Testing","subcategory":"Jest","sample_answers":["A Jest test file imports the function to test, uses `test()` to define a test case, and asserts expected behavior with `expect().toBe()`.","The test verifies that `sum(1, 2)` returns `3`, and Jest runs it via `npm test` after configuring the script in `package.json`."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '87630ce3-f525-406b-a7c2-e35fea9253fe',
          'What is Flux?',
          'Flux is an application architecture (not a framework or library) designed by Facebook to manage data flow in React applications. It emphasizes a unidirectional data flow using four key components: Actions, Dispatcher, Stores, and Views (React Components).',
          'multiple-choice',
          'intermediate',
          8,
          NULL,
          NULL,
          'Flux enforces unidirectional data flow: Views trigger Actions → Dispatcher broadcasts Actions → Stores update → Views re-render. This makes state changes predictable and easier to debug.',
          NULL,
          ARRAY[]::text[],
          '["flux","react","architecture","state-management"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q102","original_type":"open-ended","topic":"Flux Architecture","subcategory":"Design Patterns","sample_answers":["Flux is an architecture that uses a unidirectional data flow with Actions, a central Dispatcher, Stores for state, and React Views that respond to store changes.","Unlike MVC, Flux avoids two-way binding and ensures data flows in one direction, improving traceability and reducing side effects."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '41c4765b-93e8-4d2a-948f-d1bb7189c3cb',
          'What is Redux?',
          'Redux is a predictable state container for JavaScript applications, most commonly used with React. It helps manage and centralize application state in a single source of truth.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'Redux provides a centralized store for application state, updated only via pure reducer functions in response to dispatched actions. It enables time-travel debugging and predictable state changes.',
          NULL,
          ARRAY[]::text[],
          '["redux","state-management","react","javascript"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q103","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Redux is a state management library that stores the entire app state in a single immutable object tree, updated only by dispatching actions to pure reducer functions.","It offers a single source of truth, read-only state, and changes via pure functions—making apps easier to test, debug, and scale."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f8e38705-a044-4a77-af90-d6352e64e931',
          'What are the core principles of Redux?',
          'Redux follows three fundamental principles:
1. Single source of truth
2. State is read-only
3. Changes are made with pure functions (Reducers)',
          'multiple-choice',
          'beginner',
          6,
          '[{"id":"a","text":"Single store, mutable state, async reducers","isCorrect":false},{"id":"b","text":"Multiple stores, read-only state, impure reducers","isCorrect":false},{"id":"c","text":"Single source of truth, read-only state, pure reducer functions","isCorrect":true},{"id":"d","text":"Global state, two-way binding, side-effectful reducers","isCorrect":false}]',
          NULL,
          'The three principles ensure predictability: (1) all state in one store, (2) state changed only by dispatching actions, (3) reducers are pure functions that return new state.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','principles','state-management']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q104","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8ff80a6b-9319-4688-8313-4d7378b1cd55',
          'What are the downsides of Redux compared to Flux?',
          'While Redux offers a powerful state management solution, it comes with trade-offs compared to Flux, including strict immutability, need for complementary packages, and less seamless static type integration.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Redux allows mutable state by default","isCorrect":false},{"id":"b","text":"Redux requires immutability, careful package selection, and has less mature static type support","isCorrect":true},{"id":"c","text":"Flux is more minimal than Redux","isCorrect":false},{"id":"d","text":"Redux uses two-way data binding","isCorrect":false}]',
          NULL,
          'Redux requires immutability discipline, careful middleware selection, and historically had weaker static typing support than Flux with Flow.',
          NULL,
          ARRAY[]::text[],
          '["redux","flux","comparison","state-management"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q105","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2edcfca7-1909-4ad0-8ea9-ef9fcc955dc4',
          'What is the difference between `mapStateToProps()` and `mapDispatchToProps()`?',
          '`mapStateToProps()` connects Redux state to component props. `mapDispatchToProps()` connects action dispatchers to component props.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"`mapStateToProps` dispatches actions; `mapDispatchToProps` reads state","isCorrect":false},{"id":"b","text":"`mapStateToProps` reads state; `mapDispatchToProps` dispatches actions","isCorrect":true},{"id":"c","text":"Both are used only for async logic","isCorrect":false},{"id":"d","text":"They are identical in functionality","isCorrect":false}]',
          NULL,
          '`mapStateToProps` reads from the store; `mapDispatchToProps` dispatches actions. The object shorthand form is preferred for `mapDispatchToProps`.',
          NULL,
          ARRAY[]::text[],
          '["react-redux","connect","mapstatetoprops","mapdispatchtoprops"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q106","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2b11b91e-c76b-4423-b769-0615df376625',
          'Can I dispatch an action in a reducer?',
          'Dispatching an action within a reducer is an anti-pattern. Reducers should be pure functions without side effects.',
          'true-false',
          'intermediate',
          4,
          '[{"id":"a","text":"True","isCorrect":false},{"id":"b","text":"False","isCorrect":true}]',
          NULL,
          'Reducers must be pure: no side effects, no API calls, no dispatching. Dispatching inside a reducer breaks predictability and can cause infinite loops.',
          NULL,
          ARRAY[]::text[],
          '["redux","reducers","side-effects","anti-pattern"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q107","original_type":"true-false","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fd659b62-69e7-4a46-94b4-c2ab8e92eb50',
          'How to access Redux store outside a component?',
          'You can export the store instance from the module where it was created using `createStore()`.',
          'multiple-choice',
          'intermediate',
          5,
          NULL,
          NULL,
          'Export the store from its creation file and import it where needed. Avoid attaching it to `window` in production.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','store','outside-component']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q108","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Export the store from the file where `createStore()` is called, then import it in other modules to use `store.dispatch()` or `store.getState()`.","Example: `export default createStore(reducer);` then `import store from ''./store'';`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '068ab690-f48e-4052-96a3-a5b33f92de25',
          'What are the drawbacks of MVW pattern?',
          'Drawbacks include expensive DOM manipulation, circular dependencies, difficulty handling collaborative data changes, and lack of easy undo functionality.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Easy undo, cheap DOM updates, no circular dependencies","isCorrect":false},{"id":"b","text":"Expensive DOM manipulation, circular dependencies, no easy undo","isCorrect":true},{"id":"c","text":"Built-in time-travel debugging","isCorrect":false},{"id":"d","text":"Unidirectional data flow by default","isCorrect":false}]',
          NULL,
          'MVW (Model-View-Whatever) inherits MVC’s issues: tight coupling, hard-to-debug state, and no built-in time-travel or undo.',
          NULL,
          ARRAY[]::text[],
          '["mvc","mvvm","mvw","architecture"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q109","original_type":"multiple-choice","topic":"MVC & MVVM","subcategory":"Design Patterns","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd0a541a1-7a4d-4bf9-83f2-856ecddfd273',
          'Are there any similarities between Redux and RxJS?',
          'Both use reactive programming concepts, but Redux is for state management architecture, while RxJS is a library for asynchronous programming with Observables.',
          'true-false',
          'advanced',
          5,
          '[{"id":"a","text":"True","isCorrect":true},{"id":"b","text":"False","isCorrect":false}]',
          NULL,
          'Both are reactive: Redux store reacts to actions; RxJS streams react to events. But Redux is architectural; RxJS is a utility library.',
          NULL,
          ARRAY[]::text[],
          '["redux","rxjs","reactive","observables"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q110","original_type":"true-false","topic":"Reactive Programming","subcategory":"Functional Programming","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e8474089-df0e-4c44-82b8-849700137d70',
          'How to reset state in Redux?',
          'Use a root reducer that returns `undefined` state on a logout action, causing reducers to return initial state.',
          'multiple-choice',
          'advanced',
          8,
          NULL,
          NULL,
          'Wrap the combined reducer in a root reducer that sets state to `undefined` on `USER_LOGOUT`, triggering all reducers to return initial state.',
          NULL,
          ARRAY[]::text[],
          '["redux","reset-state","logout","root-reducer"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q111","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Create a root reducer that checks for a ''USER_LOGOUT'' action and passes `undefined` as state to the main reducer, which then returns initial state.","If using `redux-persist`, also clear persisted storage keys before resetting state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '10414396-201c-4b6a-b036-30b79db8cea1',
          'What is the difference between React Context and React Redux?',
          'Context is for passing data to deeply nested components; Redux is a full state management solution with dev tools, middleware, and time-travel debugging.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Context provides middleware and time-travel debugging","isCorrect":false},{"id":"b","text":"Redux is simpler and built into React","isCorrect":false},{"id":"c","text":"Context is for simple prop drilling; Redux is a full state management library with advanced tooling","isCorrect":true},{"id":"d","text":"They are functionally identical","isCorrect":false}]',
          NULL,
          'Context is built-in but lacks Redux’s ecosystem (middleware, DevTools, etc.). Redux uses Context internally but offers more features.',
          NULL,
          ARRAY[]::text[],
          '["react","context","redux","state-management"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q112","original_type":"multiple-choice","topic":"Context API vs Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'df78c843-66e4-446d-bd1b-57a062860663',
          'Why are Redux state functions called reducers?',
          'Because they reduce a collection of actions and an initial state to a final state, similar to the `reduce()` array method.',
          'multiple-choice',
          'intermediate',
          6,
          NULL,
          NULL,
          'Like `Array.prototype.reduce()`, Redux reducers accumulate state by applying each action to the previous state.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','reducers','functional-programming']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q113","original_type":"open-ended","topic":"Redux","subcategory":"State Management","sample_answers":["Reducers ''reduce'' a sequence of actions and an initial state into a final state, just like the reduce() function in functional programming.","Each action is applied to the current state to produce the next state, accumulating the result over time."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '535b4746-3576-4cfa-91e1-2834c38dad84',
          'How to make AJAX request in Redux?',
          'Use middleware like `redux-thunk` to write async action creators that dispatch actions based on API responses.',
          'multiple-choice',
          'intermediate',
          8,
          NULL,
          NULL,
          'With `redux-thunk`, action creators return a function that receives `dispatch` and can perform async logic before dispatching actions.',
          NULL,
          ARRAY[]::text[],
          '["redux","ajax","async","redux-thunk"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q114","original_type":"open-ended","topic":"Async Actions","subcategory":"State Management","sample_answers":["Use `redux-thunk` middleware to return a function from an action creator. Inside, dispatch a ''loading'' action, make the API call, then dispatch success or error actions.","Example: `export const fetchUser = (id) => async (dispatch) => { dispatch({type: ''LOADING''}); const res = await fetch(...); dispatch({type: ''SUCCESS'', payload: res}); }`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4aac3cf8-93f1-440d-bf20-8f605e8c9843',
          'Should I keep all component''s state in Redux store?',
          'No. Keep global or shared state in Redux; keep UI or local state (e.g., form inputs, dropdown open state) in the component.',
          'true-false',
          'beginner',
          4,
          '[{"id":"a","text":"True","isCorrect":false},{"id":"b","text":"False","isCorrect":true}]',
          NULL,
          'Only put state in Redux if it’s shared across components or needs to persist. Local UI state should stay in the component.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','state','best-practices']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q115","original_type":"true-false","topic":"Redux Best Practices","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6838be93-e712-427b-a11b-9c8eff29ef3f',
          'What is the proper way to access Redux store in a component?',
          'Use the `connect()` function from `react-redux` to create a higher-order component that injects state and dispatch props.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Access `this.context.store` directly","isCorrect":false},{"id":"b","text":"Use `connect()` from `react-redux`","isCorrect":true},{"id":"c","text":"Import the store and call `store.getState()` in render","isCorrect":false},{"id":"d","text":"Use `useContext(StoreContext)` always","isCorrect":false}]',
          NULL,
          '`connect()` is the recommended way—it’s optimized and avoids direct store access via context.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-redux','connect','hoc']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q116","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e1de4154-ca13-4df2-a73d-82ac24782b6c',
          'What is the difference between component and container in React Redux?',
          'Components are presentational (dumb); containers are connected to Redux (smart) and handle data fetching and dispatching.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Components handle logic; containers render UI","isCorrect":false},{"id":"b","text":"Components are presentational; containers are connected to Redux","isCorrect":true},{"id":"c","text":"They are the same","isCorrect":false},{"id":"d","text":"Containers cannot have children","isCorrect":false}]',
          NULL,
          'Containers are connected to Redux; components are pure UI. Modern React often uses hooks instead of this pattern.',
          NULL,
          ARRAY[]::text[],
          '["react","redux","container","presentational"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q117","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5379e35d-707f-405e-b38f-d26587783738',
          'What is the purpose of constants in Redux?',
          'Constants (action types) prevent typos, enable IDE search, and centralize action type definitions.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"They increase bundle size unnecessarily","isCorrect":false},{"id":"b","text":"They prevent typos and enable better tooling","isCorrect":true},{"id":"c","text":"They are required by the Redux library","isCorrect":false},{"id":"d","text":"They make reducers slower","isCorrect":false}]',
          NULL,
          'Using constants like `ADD_TODO` instead of string literals avoids bugs from typos and makes refactoring easier.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','constants','action-types']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q118","original_type":"multiple-choice","topic":"Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c7415093-df6f-4ace-b0ff-c4a432e2d070',
          'What are the different ways to write `mapDispatchToProps()`?',
          'You can write it as a function with `dispatch`, use `bindActionCreators`, or use the object shorthand.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Only the function form is valid","isCorrect":false},{"id":"b","text":"Function with dispatch, bindActionCreators, or object shorthand","isCorrect":true},{"id":"c","text":"You must always use `bindActionCreators`","isCorrect":false},{"id":"d","text":"Object shorthand doesn’t work with `connect`","isCorrect":false}]',
          NULL,
          'The object shorthand `{ action }` is preferred—it’s concise and automatically binds dispatch.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-redux','mapdispatchtoprops','bindactioncreators']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q119","original_type":"multiple-choice","topic":"React Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5cbe85c8-24d5-4cf5-9a40-baddfc76afd5',
          'What is the use of `ownProps` in `mapStateToProps` and `mapDispatchToProps`?',
          '`ownProps` contains the props passed to the connected component, allowing conditional mapping based on those props.',
          'multiple-choice',
          'intermediate',
          6,
          NULL,
          NULL,
          'If your component is used as `<MyComp id={5} />`, then `ownProps` will be `{ id: 5 }` inside the `map` functions.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-redux','ownprops','connect']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q120","original_type":"open-ended","topic":"React Redux","subcategory":"State Management","sample_answers":["`ownProps` lets you access the original props passed to the connected component, so you can filter state or bind actions based on those props.","Example: `mapStateToProps = (state, ownProps) => ({ user: state.users[ownProps.userId] })`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c0891389-5f09-4e32-af53-fff1f75504c1',
          'How to structure Redux top-level directories?',
          'Common structure: `components/`, `containers/`, `actions/`, `reducers/`, `store/`.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"All files in one folder","isCorrect":false},{"id":"b","text":"`components/`, `containers/`, `actions/`, `reducers/`, `store/`","isCorrect":true},{"id":"c","text":"Only `src/` and `test/`","isCorrect":false},{"id":"d","text":"No standard structure exists","isCorrect":false}]',
          NULL,
          'This structure separates concerns: dumb components, smart containers, action creators, reducers, and store setup.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','structure','project-organization']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q121","original_type":"multiple-choice","topic":"Redux Project Structure","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7cc4d3ab-36c5-40cb-be40-b50708abb4d5',
          'What is redux-saga?',
          '`redux-saga` is a middleware for handling side effects in Redux using generator functions.',
          'multiple-choice',
          'intermediate',
          7,
          NULL,
          NULL,
          'It uses ES6 generators to manage complex async flows (e.g., cancellable requests, race conditions) in a declarative way.',
          NULL,
          ARRAY[]::text[],
          '["redux","saga","middleware","side-effects"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q122","original_type":"open-ended","topic":"Redux Saga","subcategory":"State Management","sample_answers":["`redux-saga` is a Redux middleware that uses generator functions to handle side effects like API calls, allowing complex async logic to be testable and cancellable.","It treats side effects as separate ''sagas'' that listen for actions and perform tasks using effects like `call()` and `put()`."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '82fe1a37-a6e5-4701-a37c-791501472af6',
          'What is the mental model of redux-saga?',
          'A saga is like a background thread that handles side effects, started/paused/cancelled via Redux actions.',
          'multiple-choice',
          'advanced',
          8,
          NULL,
          NULL,
          'Sagas run in the background, watch for actions, and can dispatch new actions—all while being testable and cancellable.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux-saga','generators','side-effects']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q123","original_type":"open-ended","topic":"Redux Saga","subcategory":"State Management","sample_answers":["Think of a saga as a daemon process that lives alongside your app, listening for dispatched actions and performing side effects in response.","It’s a separate thread of execution managed by Redux middleware, using generators for async control flow."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7ea6cc97-13f5-439e-9ceb-cbdf060babbf',
          'What are the differences between `call()` and `put()` in redux-saga?',
          '`call()` invokes a function (e.g., API call); `put()` dispatches an action to the store.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"`call()` dispatches actions; `put()` makes API calls","isCorrect":false},{"id":"b","text":"`call()` invokes functions; `put()` dispatches actions","isCorrect":true},{"id":"c","text":"Both are used only for logging","isCorrect":false},{"id":"d","text":"`put()` is for database queries","isCorrect":false}]',
          NULL,
          '`call(fn, ...args)` is for invoking functions; `put(action)` is for dispatching actions.',
          NULL,
          ARRAY[]::text[],
          '["redux-saga","call","put","effects"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q124","original_type":"multiple-choice","topic":"Redux Saga","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd807c666-85e7-4bb2-ac06-7a04cd4789e8',
          'What is Redux Thunk?',
          'Redux Thunk is middleware that allows action creators to return a function instead of an action object, enabling async logic.',
          'multiple-choice',
          'beginner',
          6,
          NULL,
          NULL,
          'The thunk function receives `dispatch` and `getState`, allowing conditional or delayed dispatch.',
          NULL,
          ARRAY[]::text[],
          '["redux","thunk","middleware","async"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q125","original_type":"open-ended","topic":"Redux Thunk","subcategory":"State Management","sample_answers":["Redux Thunk lets you write action creators that return a function, which can perform async operations and dispatch actions when needed.","It’s the simplest way to handle async logic in Redux, using functions instead of plain action objects."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3bead1cd-282f-473a-aaa5-24ff38511ca2',
          'What are the differences between `redux-saga` and `redux-thunk`?',
          'Thunk uses Promises and is simple; Saga uses Generators and is powerful for complex flows.',
          'multiple-choice',
          'intermediate',
          8,
          '[{"id":"a","text":"Saga uses Promises; Thunk uses Generators","isCorrect":false},{"id":"b","text":"Thunk uses Promises; Saga uses Generators","isCorrect":true},{"id":"c","text":"Both are identical","isCorrect":false},{"id":"d","text":"Saga is deprecated","isCorrect":false}]',
          NULL,
          'Thunk is easier for simple cases; Saga is better for complex async logic (cancellation, race conditions, etc.).',
          NULL,
          ARRAY[]::text[],
          '["redux","thunk","saga","middleware"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q126","original_type":"multiple-choice","topic":"Redux Middleware","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3f083a86-36b0-4037-aa32-fc80767cf212',
          'What is Redux DevTools?',
          'Redux DevTools is a time-travel debugging environment for Redux with action replay and hot reloading.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'It lets you inspect every action and state change, rewind, and replay actions—great for debugging.',
          NULL,
          ARRAY[]::text[],
          '["redux","devtools","debugging","time-travel"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q127","original_type":"open-ended","topic":"Redux DevTools","subcategory":"State Management","sample_answers":["Redux DevTools is a browser extension or library that provides a UI to inspect Redux store changes, dispatch actions manually, and travel back in time.","It shows a timeline of actions, lets you cancel past actions, and re-evaluates state when reducer code changes."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f6d437e1-bed8-4e11-982a-c21ed9bd55be',
          'What are the features of Redux DevTools?',
          'Features include state/action inspection, time travel, reducer hot reloading, error tracking, and state persistence.',
          'multiple-choice',
          'beginner',
          6,
          '[{"id":"a","text":"Only shows console logs","isCorrect":false},{"id":"b","text":"State inspection, time travel, hot reloading, error tracking, persistence","isCorrect":true},{"id":"c","text":"Replaces the need for unit tests","isCorrect":false},{"id":"d","text":"Only works in production","isCorrect":false}]',
          NULL,
          'Key features: inspect state/actions, cancel actions (time travel), hot reload reducers, see errors, persist debug sessions.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux-devtools','debugging','features']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q128","original_type":"multiple-choice","topic":"Redux DevTools","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b05cece3-25ff-4ca4-b5e7-f94153442d75',
          'What are Redux selectors and why use them?',
          'Selectors are functions that compute derived data from Redux state. They enable memoization and reduce redundant calculations.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"They directly mutate the Redux state","isCorrect":false},{"id":"b","text":"They compute derived data and memoize results for performance","isCorrect":true},{"id":"c","text":"They replace reducers","isCorrect":false},{"id":"d","text":"They are only for async logic","isCorrect":false}]',
          NULL,
          'Selectors compute derived data (e.g., filtered lists) and memoize results to avoid recomputation unless inputs change.',
          NULL,
          ARRAY[]::text[],
          '["redux","selectors","reselect","memoization"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q129","original_type":"multiple-choice","topic":"Reselect","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e40a3b85-3eac-4f11-a5a9-ed6a9e1286bf',
          'What is Redux Form?',
          'Redux Form is a library that manages form state in Redux, handling values, validation, and submission.',
          'multiple-choice',
          'intermediate',
          6,
          NULL,
          NULL,
          'It stores all form state (values, errors, touched fields) in Redux, enabling complex form logic and persistence.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux-form','forms','validation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q130","original_type":"open-ended","topic":"Redux Form","subcategory":"State Management","sample_answers":["Redux Form integrates with React and Redux to keep all form state (input values, validation errors, submission status) in the Redux store.","It provides higher-order components and action creators to manage form lifecycle and validation."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5d0f40c0-1deb-45dc-a89a-37995fa7f6e4',
          'What are the main features of Redux Form?',
          'Features include field value persistence, sync/async validation, and formatting/parsing of field values.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Only basic input binding","isCorrect":false},{"id":"b","text":"Field persistence, validation, formatting/parsing","isCorrect":true},{"id":"c","text":"Replaces React components","isCorrect":false},{"id":"d","text":"Only works with class components","isCorrect":false}]',
          NULL,
          'It handles form state, validation (sync and async), and data transformation (formatting, parsing, normalization).',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux-form','features','validation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q131","original_type":"multiple-choice","topic":"Redux Form","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '48ca1705-803c-4b73-9099-b339bac862b4',
          'How to add multiple middlewares to Redux?',
          'Use `applyMiddleware()` from Redux, passing all middleware functions as arguments.',
          'multiple-choice',
          'intermediate',
          6,
          NULL,
          NULL,
          '`applyMiddleware(thunk, logger)(createStore)` chains multiple middleware functions.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','middleware','applymiddleware']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q132","original_type":"open-ended","topic":"Redux Middleware","subcategory":"State Management","sample_answers":["Use `applyMiddleware(middleware1, middleware2)(createStore)` to compose multiple middleware functions when creating the store.","Example: `const store = createStore(reducer, applyMiddleware(thunk, logger));`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f16957f3-593d-4f0d-ab53-7c461ef7d851',
          'How to set initial state in Redux?',
          'Pass the initial state as the second argument to `createStore()`.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          '`createStore(reducer, initialState)` sets the starting state of the store.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','initial-state','createstore']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q133","original_type":"open-ended","topic":"Redux Store","subcategory":"State Management","sample_answers":["Call `createStore(rootReducer, initialState)` where `initialState` is a plain object matching your state shape.","This is useful for server-side rendering or preloading data from localStorage."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4c40a094-56c4-48b8-81e4-bf31c35d2dc4',
          'How is Relay different from Redux?',
          'Relay manages only server-originated state via GraphQL; Redux manages all application state.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Relay uses REST APIs","isCorrect":false},{"id":"b","text":"Relay manages only server state via GraphQL; Redux manages all state","isCorrect":true},{"id":"c","text":"Redux requires GraphQL","isCorrect":false},{"id":"d","text":"They are identical","isCorrect":false}]',
          NULL,
          'Relay is GraphQL-specific and handles caching/optimization automatically; Redux is general-purpose.',
          NULL,
          ARRAY[]::text[],
          '["relay","redux","graphql","state-management"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q134","original_type":"multiple-choice","topic":"Relay vs Redux","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '09078e6b-14bc-401e-9a5f-f287907b15d1',
          'What is an action in Redux?',
          'An action is a plain JavaScript object with a `type` property that describes what happened.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"A function that mutates state","isCorrect":false},{"id":"b","text":"A plain object with a `type` property","isCorrect":true},{"id":"c","text":"A class instance","isCorrect":false},{"id":"d","text":"A Promise","isCorrect":false}]',
          NULL,
          'Actions are payloads of information sent to the store. They must have a `type` string.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','actions','flux-standard-action']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q135","original_type":"multiple-choice","topic":"Redux Actions","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b6ba68c3-1661-437d-bfec-73ee3e003249',
          'What is the difference between React Native and React?',
          'React is for web UIs; React Native compiles to native mobile components for iOS/Android.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"React Native uses HTML","isCorrect":false},{"id":"b","text":"React is for web; React Native is for native mobile apps","isCorrect":true},{"id":"c","text":"React Native cannot use JavaScript","isCorrect":false},{"id":"d","text":"They are the same library","isCorrect":false}]',
          NULL,
          'React targets the DOM; React Native targets native mobile APIs using platform-specific components.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','react-native','mobile']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q136","original_type":"multiple-choice","topic":"React Native Basics","subcategory":"Core Concepts","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6820bed3-9197-4c86-895a-0e967d6ae4e5',
          'How to test React Native apps?',
          'Test using iOS/Android simulators or real devices via Expo, which syncs using QR codes over the same network.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'Expo simplifies testing by allowing you to scan a QR code to run the app on a physical device connected to the same Wi-Fi.',
          NULL,
          ARRAY[]::text[],
          '["react-native","expo","testing","simulator"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q137","original_type":"open-ended","topic":"React Native Testing","subcategory":"Testing & Debugging","sample_answers":["Use Expo to run your app on a real device by scanning a QR code, or use iOS/Android simulators from Xcode or Android Studio.","Ensure your computer and mobile device are on the same network when using Expo for live reloading."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6f802533-621d-4cb7-b22e-bc132a5ac82d',
          'How to do logging in React Native?',
          'Use `console.log()`, and view logs with `react-native log-ios` or `react-native log-android`.',
          'multiple-choice',
          'beginner',
          4,
          NULL,
          NULL,
          'Standard `console` methods work, and logs can be viewed via CLI commands or Chrome DevTools.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-native','logging','console']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q138","original_type":"open-ended","topic":"React Native Debugging","subcategory":"Testing & Debugging","sample_answers":["Use `console.log()` in your code, then run `react-native log-ios` or `react-native log-android` to see output in the terminal.","You can also debug in Chrome DevTools by enabling remote debugging in the developer menu."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1edda399-047a-494d-91ab-087be66de4cc',
          'How to debug your React Native?',
          'Use the in-app developer menu (Cmd+D on iOS simulator), then open Chrome DevTools at `http://localhost:8081/debugger-ui`.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Only use Xcode debugger","isCorrect":false},{"id":"b","text":"Use Cmd+D in simulator, then Chrome DevTools at localhost:8081/debugger-ui","isCorrect":true},{"id":"c","text":"Debugging is not supported","isCorrect":false},{"id":"d","text":"Use Firefox only","isCorrect":false}]',
          NULL,
          'The debug workflow involves opening the dev menu, enabling remote JS debugging, and using Chrome DevTools.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-native','debugging','devtools']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q139","original_type":"multiple-choice","topic":"React Native Debugging","subcategory":"Testing & Debugging","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '33c44f5d-a6fd-4d31-847b-f233b3ab07aa',
          'What is Reselect and how it works?',
          'Reselect is a selector library that uses memoization to avoid recomputing derived data unless inputs change.',
          'multiple-choice',
          'intermediate',
          7,
          NULL,
          NULL,
          'It caches the last result and arguments; if inputs are the same, it returns the cached output without recomputing.',
          NULL,
          ARRAY[]::text[],
          '["reselect","selectors","memoization","redux"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q140","original_type":"open-ended","topic":"Reselect","subcategory":"State Management","sample_answers":["Reselect creates memoized selectors that only recompute when their input arguments change, improving performance in Redux apps.","It uses a `createSelector` function that takes input selectors and a result function, caching the output for identical inputs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b59de3f2-f105-4e02-a48b-a25b46496819',
          'What is Flow?',
          'Flow is a static type checker for JavaScript that catches type errors at compile time.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'Flow analyzes code with type annotations to find bugs like null dereferences before runtime.',
          NULL,
          ARRAY[]::text[],
          '["flow","typescript","static-typing","javascript"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q141","original_type":"open-ended","topic":"Static Type Checking","subcategory":"TypeScript Basics","sample_answers":["Flow is a static analysis tool that adds type annotations to JavaScript and checks for type errors during development.","It helps catch common bugs like calling methods on null or passing wrong argument types."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '88d3f5b6-005f-40a7-b9e5-00e9d2f010af',
          'What is the difference between Flow and PropTypes?',
          'Flow is a static type checker (compile-time); PropTypes is a runtime type checker for React component props.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"PropTypes is static; Flow is runtime","isCorrect":false},{"id":"b","text":"Flow is static (compile-time); PropTypes is runtime (only for props)","isCorrect":true},{"id":"c","text":"Both are identical","isCorrect":false},{"id":"d","text":"PropTypes can check entire codebase","isCorrect":false}]',
          NULL,
          'Flow checks all code at build time; PropTypes only checks component props at runtime and is less comprehensive.',
          NULL,
          ARRAY[]::text[],
          '["flow","proptypes","typing","react"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q142","original_type":"multiple-choice","topic":"Static vs Runtime Typing","subcategory":"TypeScript Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '50dcdec8-9c51-4162-8f4e-1a3f88461b22',
          'How to use Font Awesome icons in React?',
          'Install `font-awesome`, import CSS in `index.js`, and use `<i className="fa fa-icon-name" />`.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'Font Awesome provides icon fonts; you include the CSS and use class names in JSX.',
          NULL,
          ARRAY[]::text[],
          '["react","font-awesome","icons","css"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q143","original_type":"open-ended","topic":"Third-Party Libraries","subcategory":"React Basics","sample_answers":["Install `font-awesome` via npm, import the CSS file in your entry point, then use `<i className=\"fa fa-spinner\" />` in components.","Note: Modern apps often use SVG-based icon libraries like `react-icons` instead of font-based ones."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '94c2ee29-d661-4619-b2f0-ce17193c0f76',
          'What is React Dev Tools?',
          'React DevTools is a browser extension or standalone app for inspecting React component hierarchy, props, and state.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"A code formatter","isCorrect":false},{"id":"b","text":"A tool to inspect React components, props, and state","isCorrect":true},{"id":"c","text":"Only works with Angular","isCorrect":false},{"id":"d","text":"A testing framework","isCorrect":false}]',
          NULL,
          'It lets you explore the component tree, view props/state, and profile performance.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-devtools','debugging','chrome-extension']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q144","original_type":"multiple-choice","topic":"React Developer Tools","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd40a7020-2bb8-4381-b8e3-613ddeae5231',
          'Why is DevTools not loading in Chrome for local files?',
          'Because Chrome blocks extensions from accessing `file://` URLs by default. You must enable ''Allow access to file URLs'' in extension settings.',
          'multiple-choice',
          'beginner',
          4,
          NULL,
          NULL,
          'Chrome extensions are sandboxed; you must manually allow file URL access in `chrome://extensions`.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-devtools','chrome','file-urls']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q145","original_type":"open-ended","topic":"React Developer Tools","subcategory":"React Basics","sample_answers":["Open `chrome://extensions`, find React DevTools, and check ''Allow access to file URLs'' to enable it for local HTML files.","Alternatively, serve your app via a local server (e.g., `npx serve`) instead of opening `file://` directly."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7c630f1a-916a-44c8-a5b3-0504f9371937',
          'How to use Polymer in React?',
          'Create a Polymer element, import it in HTML, and use the custom element tag in JSX.',
          'multiple-choice',
          'advanced',
          8,
          NULL,
          NULL,
          'React can render custom elements defined by Polymer by treating them as regular HTML tags.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','polymer','web-components']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q146","original_type":"open-ended","topic":"Web Components","subcategory":"Integration","sample_answers":["Define a Polymer element, import its HTML file in your main `index.html`, then use `<calendar-element />` in your React JSX.","Note: You may need to handle event naming differences (e.g., `onMyEvent` vs `onmyevent`) and property binding carefully."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '464ea4f8-61b3-4567-9a7d-7a58e7228655',
          'What are the advantages of React over Vue.js?',
          'React offers more flexibility in large apps, easier testing, better mobile support (React Native), and a larger ecosystem.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Vue has better mobile support","isCorrect":false},{"id":"b","text":"React offers more flexibility, easier testing, React Native, and larger ecosystem","isCorrect":true},{"id":"c","text":"Vue is harder to learn","isCorrect":false},{"id":"d","text":"React has no advantages","isCorrect":false}]',
          NULL,
          'These are common perceived advantages, though both frameworks are capable.',
          NULL,
          ARRAY[]::text[],
          '["react","vue","comparison","ecosystem"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q147","original_type":"multiple-choice","topic":"React Ecosystem","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f3710bb7-a078-4016-8fb5-81bd8047efe3',
          'What is the difference between React and Angular?',
          'React is a UI library with JSX and unidirectional data flow; Angular is a full framework with templates and two-way binding.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"React is a full framework like Angular","isCorrect":false},{"id":"b","text":"React is a library (View only); Angular is a full framework (MVC)","isCorrect":true},{"id":"c","text":"Angular uses JSX","isCorrect":false},{"id":"d","text":"React has two-way data binding","isCorrect":false}]',
          NULL,
          'React is view-only, uses JavaScript syntax (JSX), and has one-way data flow. Angular is a full MVC framework with HTML templates and two-way binding.',
          NULL,
          ARRAY[]::text[],
          '["react","angular","comparison","frameworks"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q148","original_type":"multiple-choice","topic":"Framework Comparison","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ea2ee1e6-34f6-4a13-85d0-aac00b4d3029',
          'Why React tab is not showing up in DevTools?',
          'Because the page isn’t using React, or React failed to initialize and communicate with DevTools.',
          'multiple-choice',
          'beginner',
          5,
          NULL,
          NULL,
          'DevTools detects React via a global hook set during React initialization. If React isn’t loaded or is in production mode, the tab won’t appear.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react-devtools','debugging','setup']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q149","original_type":"open-ended","topic":"React Developer Tools","subcategory":"React Basics","sample_answers":["The React DevTools tab appears only if React is loaded on the page and not in production mode. Check that you’re using a development build of React.","If using a bundler, ensure React is included and the app is running in development mode."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '37c51890-47f3-4197-a5ab-7cd1fd24427b',
          'What are Styled Components?',
          '`styled-components` is a CSS-in-JS library that lets you write actual CSS in JavaScript to style React components.',
          'multiple-choice',
          'beginner',
          6,
          NULL,
          NULL,
          'It removes the mapping between styles and components by generating unique class names and injecting styles automatically.',
          NULL,
          ARRAY[]::text[],
          '["styled-components","css-in-js","react","styling"]',
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q150","original_type":"open-ended","topic":"Styled Components","subcategory":"CSS-in-JS","sample_answers":["`styled-components` allows you to write CSS inside JavaScript template literals, creating styled React components with automatic scoping and vendor prefixing.","Example: `const Title = styled.h1\\`color: red;\\`;` creates a component that renders an `<h1>` with red text."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );