INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a4537f0b-1cc9-4620-8931-44e740fd8097',
          'HTTP Caching Basics',
          'What is the main purpose of HTTP caching in web applications?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'To store responses locally or on a CDN to reduce server load and speed up subsequent requests.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-1","original_type":"open-ended","topic":"Streaming Rendering","subcategory":"","sample_answers":["To store responses locally or on a CDN to reduce server load and speed up subsequent requests.","It improves performance by serving cached responses without re-fetching from the server."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c033e67c-3ee4-4774-9889-4118f7054502',
          'Cache-Control Headers',
          'Which HTTP header directive ensures a resource is revalidated after expiration?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Cache-Control: must-revalidate","isCorrect":true},{"id":"b","text":"Cache-Control: immutable","isCorrect":false},{"id":"c","text":"ETag: strong","isCorrect":false}]',
          NULL,
          'Cache-Control: must-revalidate',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-2","original_type":"multiple-choice","topic":"Streaming Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ac4f9f0c-7fec-4814-b27d-d2abb157d3a5',
          'ETag Function',
          'What role does an ETag header play in caching?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'ETag is a unique identifier for a resource version that helps browsers validate if content has changed.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-3","original_type":"open-ended","topic":"Streaming Rendering","subcategory":"","sample_answers":["ETag is a unique identifier for a resource version that helps browsers validate if content has changed.","If the ETag matches, the cached version is reused without downloading the full file."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '84eadce9-009b-4e32-8641-5aada8036f2d',
          'CDN Edge Caching',
          'How does CDN edge caching improve rendering performance?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"It stores static assets closer to the user geographically to reduce latency","isCorrect":true},{"id":"b","text":"It only caches dynamic content for faster hydration","isCorrect":false},{"id":"c","text":"It disables browser caching entirely","isCorrect":false}]',
          NULL,
          'It stores static assets closer to the user geographically to reduce latency',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-4","original_type":"multiple-choice","topic":"Streaming Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a9d749f7-1a0b-42b1-b612-92bfd30014f5',
          'Preconnect and Prefetch',
          'What is the difference between preconnect and prefetch in web performance optimization?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Preconnect establishes early network connections (DNS, TCP, TLS) to improve later requests.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-5","original_type":"open-ended","topic":"Streaming Rendering","subcategory":"","sample_answers":["Preconnect establishes early network connections (DNS, TCP, TLS) to improve later requests.","Prefetch fetches resources ahead of time that the user is likely to need soon."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a2a29e08-0a54-40f5-8275-c1a8e40aba6b',
          'Static Asset Versioning',
          'Why is versioning important for static assets in caching?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"It ensures browsers fetch updated assets when changes occur","isCorrect":true},{"id":"b","text":"It prevents caching altogether","isCorrect":false},{"id":"c","text":"It slows down content delivery","isCorrect":false}]',
          NULL,
          'It ensures browsers fetch updated assets when changes occur',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-6","original_type":"multiple-choice","topic":"Streaming Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b4530d97-0702-48f8-969d-5f511ddbf638',
          'Client-Side Cache Invalidation',
          'How can a front-end app force invalidation of a stale cache?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By updating the asset version hash or using service worker cache management APIs.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-7","original_type":"open-ended","topic":"Streaming Rendering","subcategory":"","sample_answers":["By updating the asset version hash or using service worker cache management APIs.","It can also append query parameters to resource URLs to bypass old caches."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '530b8afc-bc9b-421d-9ab8-e5ae94b0769a',
          'Revalidation Techniques',
          'Which caching header combination supports conditional revalidation?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"ETag and If-None-Match","isCorrect":true},{"id":"b","text":"Cache-Control: immutable","isCorrect":false},{"id":"c","text":"Last-Modified and If-Match","isCorrect":false}]',
          NULL,
          'ETag and If-None-Match',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-8","original_type":"multiple-choice","topic":"Streaming Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cc91523d-408e-407c-b744-7fdf3bef34c1',
          'Incremental Static Regeneration (ISR)',
          'How does ISR improve performance in frameworks like Next.js?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'ISR allows static pages to be regenerated in the background at runtime while serving cached versions to users.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-9","original_type":"open-ended","topic":"Streaming Rendering","subcategory":"","sample_answers":["ISR allows static pages to be regenerated in the background at runtime while serving cached versions to users.","This enables near-instant load times with up-to-date content."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9904a25f-831e-4d80-aaf3-80cb7ea90739',
          'Stale-While-Revalidate',
          'What does the stale-while-revalidate caching strategy do?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Serves a stale cache immediately and revalidates it in the background","isCorrect":true},{"id":"b","text":"Deletes old cache entries before fetching new ones","isCorrect":false},{"id":"c","text":"Disables revalidation for dynamic pages","isCorrect":false}]',
          NULL,
          'Serves a stale cache immediately and revalidates it in the background',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','streaming-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering8-10","original_type":"multiple-choice","topic":"Streaming Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9664a32b-a889-4094-a3ec-429b7a63a743',
          'Core Web Vitals Overview',
          'What are Core Web Vitals, and why are they important in rendering performance?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Core Web Vitals are a set of metrics—Largest Contentful Paint (LCP), First Input Delay (FID), and Cumulative Layout Shift (CLS)—that measure real-world user experience.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-1","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["Core Web Vitals are a set of metrics—Largest Contentful Paint (LCP), First Input Delay (FID), and Cumulative Layout Shift (CLS)—that measure real-world user experience.","They help evaluate visual stability, interactivity, and loading performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '548f8339-e981-420f-b151-97feba4f66e8',
          'Largest Contentful Paint (LCP)',
          'What does the Largest Contentful Paint (LCP) metric measure?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Time until the largest visible element (image or text block) renders","isCorrect":true},{"id":"b","text":"Total load time of all resources","isCorrect":false},{"id":"c","text":"Delay before the first user input is processed","isCorrect":false}]',
          NULL,
          'Time until the largest visible element (image or text block) renders',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-2","original_type":"multiple-choice","topic":"Resumability","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '321ac148-3e8c-463c-9c81-c83006c89f2a',
          'First Input Delay (FID)',
          'What does the First Input Delay (FID) metric represent?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'FID measures the delay between a user’s first interaction (e.g., clicking a button) and the browser’s ability to respond to that interaction.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-3","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["FID measures the delay between a user’s first interaction (e.g., clicking a button) and the browser’s ability to respond to that interaction.","It helps quantify responsiveness."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f1a03d65-5e99-4b77-8974-377ce7795534',
          'Cumulative Layout Shift (CLS)',
          'Which user experience issue does Cumulative Layout Shift (CLS) help detect?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Visual instability caused by unexpected layout movements","isCorrect":true},{"id":"b","text":"Slow data fetching","isCorrect":false},{"id":"c","text":"JavaScript bundle size issues","isCorrect":false}]',
          NULL,
          'Visual instability caused by unexpected layout movements',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-4","original_type":"multiple-choice","topic":"Resumability","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0a3778f3-6a41-4697-b2ec-aaa4ba1e6667',
          'First Contentful Paint (FCP)',
          'What is the difference between FCP and LCP?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'FCP measures when the browser first renders any content from the DOM.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-5","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["FCP measures when the browser first renders any content from the DOM.","LCP measures when the largest visible content element has been rendered."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6efa8229-4e27-4ea6-b516-341b547cb0fe',
          'TTFB in Rendering',
          'How does Time To First Byte (TTFB) affect perceived performance in SSR apps?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'TTFB represents the time it takes for the server to start sending a response.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-6","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["TTFB represents the time it takes for the server to start sending a response.","A higher TTFB delays all other metrics, including FCP and LCP, especially in SSR apps."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '73c9062a-fef8-479f-8c4d-be2831b99498',
          'Real User Monitoring (RUM)',
          'What is Real User Monitoring and how does it differ from synthetic testing?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'RUM collects performance data from actual users in the wild, giving real-world insights.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-7","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["RUM collects performance data from actual users in the wild, giving real-world insights.","Synthetic testing simulates performance in controlled environments, not actual usage."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '69eeb951-466e-47be-a2bb-0f491d2a487c',
          'Performance Budgets',
          'How do performance budgets help teams maintain rendering performance?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"They define quantitative limits (like max JS size or LCP time) to prevent regressions","isCorrect":true},{"id":"b","text":"They automatically compress code bundles","isCorrect":false},{"id":"c","text":"They control the rendering order of components","isCorrect":false}]',
          NULL,
          'They define quantitative limits (like max JS size or LCP time) to prevent regressions',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-8","original_type":"multiple-choice","topic":"Resumability","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd9b55756-a24f-4454-b066-80046b401072',
          'Hydration and Performance Monitoring',
          'Which metric is most affected by slow hydration in client-side rendered apps?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"First Input Delay (FID)","isCorrect":true},{"id":"b","text":"Cumulative Layout Shift (CLS)","isCorrect":false},{"id":"c","text":"Time To First Byte (TTFB)","isCorrect":false}]',
          NULL,
          'First Input Delay (FID)',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-9","original_type":"multiple-choice","topic":"Resumability","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fbba2901-23b4-424a-81b6-a750950f575f',
          'Monitoring Rendering in CI/CD',
          'How can rendering performance be monitored in CI/CD pipelines?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Integrate Lighthouse CI or WebPageTest in the pipeline to measure metrics like LCP and CLS on each deployment.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','resumability']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering9-10","original_type":"open-ended","topic":"Resumability","subcategory":"","sample_answers":["Integrate Lighthouse CI or WebPageTest in the pipeline to measure metrics like LCP and CLS on each deployment.","Set performance budgets that fail builds when metrics exceed thresholds."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd4732ee2-a285-4de7-ac51-635e41f04859',
          'Understanding Static Rendering',
          'What is Static Rendering and when is it most suitable?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Static Rendering generates HTML at build time and serves pre-rendered pages from a CDN or edge cache.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-1","original_type":"open-ended","topic":"Static Rendering","subcategory":"","sample_answers":["Static Rendering generates HTML at build time and serves pre-rendered pages from a CDN or edge cache.","It''s best for content that doesn''t change often, like blogs, marketing pages, or documentation."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3cdfe2db-9aad-4fcb-975c-2a0c7a658119',
          'Benefits of Static Rendering',
          'Which of the following is a key advantage of static rendering?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"HTML is pre-generated and can be cached for near-instant TTFB","isCorrect":true},{"id":"b","text":"The server generates HTML for every request","isCorrect":false},{"id":"c","text":"Users must fetch data before rendering","isCorrect":false}]',
          NULL,
          'HTML is pre-generated and can be cached for near-instant TTFB',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-2","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '49963189-ce95-4778-8913-47365bfd35c6',
          'Static Rendering with Client-Side Fetch',
          'What is the drawback of using Client-Side fetch in a static rendered page?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Poor SEO due to server-side rendering","isCorrect":false},{"id":"b","text":"Delayed Largest Contentful Paint (LCP) since main content loads after client fetch","isCorrect":true},{"id":"c","text":"Cannot cache responses on a CDN","isCorrect":false}]',
          NULL,
          'Delayed Largest Contentful Paint (LCP) since main content loads after client fetch',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-3","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3198b3b3-6402-4d87-a322-85a4df5d0050',
          'Static Rendering with getStaticProps',
          'What is the primary purpose of using getStaticProps in Next.js?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It allows fetching data at build time to generate static HTML with data baked in, avoiding client-side API calls.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-4","original_type":"open-ended","topic":"Static Rendering","subcategory":"","sample_answers":["It allows fetching data at build time to generate static HTML with data baked in, avoiding client-side API calls.","It improves performance by reducing runtime data fetching."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2263ec9d-a8e4-472f-9957-b38a692a50d1',
          'Drawback of getStaticProps',
          'What problem can arise when using getStaticProps for large sites with many pages?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Long build times and hitting API request limits","isCorrect":true},{"id":"b","text":"Poor SEO optimization","isCorrect":false},{"id":"c","text":"Increased client-side bundle size","isCorrect":false}]',
          NULL,
          'Long build times and hitting API request limits',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-5","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '833dec4a-2cef-46e2-af5f-fd10fa922bca',
          'Incremental Static Regeneration (ISR)',
          'How does Incremental Static Regeneration improve over plain static rendering?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'ISR allows selective regeneration of pages after deployment without rebuilding the whole site.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-6","original_type":"open-ended","topic":"Static Rendering","subcategory":"","sample_answers":["ISR allows selective regeneration of pages after deployment without rebuilding the whole site.","It reduces build times and enables automatic cache invalidation for dynamic content."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '61a5522f-87ad-43f5-9367-b5a0c699120f',
          'ISR Fallback Behavior',
          'What happens when a user requests a page that hasn’t been generated yet in ISR?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"The server immediately returns a 404 error","isCorrect":false},{"id":"b","text":"The page is generated on-demand and cached for future requests","isCorrect":true},{"id":"c","text":"The user sees a loading spinner until next build","isCorrect":false}]',
          NULL,
          'The page is generated on-demand and cached for future requests',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-7","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7d392551-28f5-452e-a86f-dd35ccfe5c5c',
          'On-Demand Incremental Static Regeneration',
          'How does On-Demand ISR differ from regular ISR?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Instead of regenerating pages at fixed intervals, On-Demand ISR regenerates pages in response to specific events like webhooks or data updates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-8","original_type":"open-ended","topic":"Static Rendering","subcategory":"","sample_answers":["Instead of regenerating pages at fixed intervals, On-Demand ISR regenerates pages in response to specific events like webhooks or data updates.","It reduces unnecessary rebuilds and operational costs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6d2f0911-2b64-4799-9eeb-8fec7867e712',
          'Performance Metric Association',
          'Which Core Web Vital is most improved by Static Rendering?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Largest Contentful Paint (LCP)","isCorrect":true},{"id":"b","text":"Cumulative Layout Shift (CLS)","isCorrect":false},{"id":"c","text":"First Input Delay (FID)","isCorrect":false}]',
          NULL,
          'Largest Contentful Paint (LCP)',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-9","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '77f53d73-7058-4bb1-a5ad-a2cfcc57ed22',
          'Choosing Between Static and Server Rendering',
          'When should you avoid using Static Rendering?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"For highly personalized pages or data that changes per user request","isCorrect":true},{"id":"b","text":"For blogs and documentation","isCorrect":false},{"id":"c","text":"For e-commerce product pages updated daily","isCorrect":false}]',
          NULL,
          'For highly personalized pages or data that changes per user request',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','static-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering-10","original_type":"multiple-choice","topic":"Static Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '318537bb-906b-4617-a916-039fd2fe7ab7',
          'What is an XSS attack?',
          'Cross-Site Scripting (XSS) is when attackers inject malicious scripts into web pages viewed by other users. Explain the potential risks and examples.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec1","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6b7c946b-f8b7-4f70-997b-62a685fd2d9f',
          'Which of the following are types of XSS attacks?',
          'Select all types of XSS attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"DOM-based XSS","isCorrect":true,"explanation":""},{"id":"o2","text":"Reflected XSS","isCorrect":true,"explanation":""},{"id":"o3","text":"Stored XSS","isCorrect":true,"explanation":""},{"id":"o4","text":"SQL Injection","isCorrect":false,"explanation":""}]',
          NULL,
          'DOM-based, Reflected, and Stored are the three main XSS types. SQL Injection is a server-side attack.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec2","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fb0bce1e-000d-4f1a-9376-f9833a9383c0',
          'True or False: CSRF attacks rely on user authentication.',
          'Evaluate whether this statement is true or false.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec3","original_type":"true-false","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bf438755-3576-48b4-81ce-daebca20dc21',
          'What is clickjacking?',
          'Clickjacking is a type of attack where a user is tricked into clicking elements hidden under legitimate UI elements. Explain how it works and prevention strategies.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec4","original_type":"open-ended","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":["Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd6b1778e-7b77-4ef9-8989-397ad45d86c3',
          'Which HTTP header helps prevent clickjacking?',
          'Select the correct header used to prevent clickjacking attacks.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o2","text":"Content-Security-Policy (frame-ancestors)","isCorrect":true,"explanation":""},{"id":"o3","text":"X-Content-Type-Options","isCorrect":false,"explanation":""},{"id":"o4","text":"Strict-Transport-Security","isCorrect":false,"explanation":""}]',
          NULL,
          'X-Frame-Options and CSP frame-ancestors prevent malicious iframe embedding.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec5","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '105dc54b-ec7f-4636-860a-3e9781f24836',
          'True or False: MITM attacks only affect unsecured HTTP connections.',
          'Evaluate whether this statement is true or false.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec6","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'dbd6abff-c8a3-4263-a687-d02d0e61174f',
          'How do HttpOnly and Secure cookies improve security?',
          'Explain how the HttpOnly and Secure flags help prevent attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec7","original_type":"open-ended","topic":"Session Management","subcategory":"Cookies","sample_answers":["HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '793c75b5-bef1-4cba-83d9-de079b527c63',
          'Which of these is a recommended prevention for XSS in React?',
          'Select all correct strategies.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Avoid dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o2","text":"Use DOMPurify or similar sanitizers","isCorrect":true,"explanation":""},{"id":"o3","text":"Use HttpOnly cookies","isCorrect":false,"explanation":""},{"id":"o4","text":"Validate input server-side","isCorrect":true,"explanation":""}]',
          NULL,
          'Avoid unsafe HTML, sanitize inputs, and validate server-side to prevent XSS.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec8","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e381b016-0400-4a64-bcf6-ec39131fc80b',
          'True or False: CSP (Content Security Policy) can help mitigate XSS.',
          'Evaluate whether this statement is true or false.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-01-sec9","original_type":"true-false","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e94146b0-bc4c-47be-a6c0-75a5d7269d91',
          'What is CSRF (Cross-Site Request Forgery)?',
          'Explain what CSRF attacks are and how they work in web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec10","original_type":"open-ended","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":["CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:10:00.000Z',
          '2025-10-11T00:10:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5490eac4-e355-4bc1-a556-8372d21295a1',
          'Which measures can prevent CSRF attacks?',
          'Select all correct prevention techniques.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use anti-CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate the Origin and Referer headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Enable HttpOnly cookies","isCorrect":false,"explanation":""},{"id":"o4","text":"Require user confirmation for critical actions","isCorrect":true,"explanation":""}]',
          NULL,
          'CSRF prevention uses tokens, checks headers, and sometimes asks users for confirmation.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec11","original_type":"multiple-choice","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:11:00.000Z',
          '2025-10-11T00:11:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9519e204-fb83-4099-a815-c8b879244596',
          'True or False: MITM attacks can steal data from HTTPS connections if SSL/TLS is not validated correctly.',
          'Evaluate whether this statement is true or false.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec12","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:12:00.000Z',
          '2025-10-11T00:12:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2fd6e85f-964d-4007-b4e4-70dfb1c65ca1',
          'What is the purpose of a Content Security Policy (CSP)?',
          'Explain how CSP protects web applications and what types of attacks it mitigates.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec13","original_type":"open-ended","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":["CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:13:00.000Z',
          '2025-10-11T00:13:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'af22fa9c-2eca-459e-aaac-bbb34293c382',
          'Which of the following headers help improve web security?',
          'Select all correct HTTP headers.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Strict-Transport-Security","isCorrect":true,"explanation":""},{"id":"o2","text":"X-Content-Type-Options","isCorrect":true,"explanation":""},{"id":"o3","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o4","text":"X-Powered-By","isCorrect":false,"explanation":""}]',
          NULL,
          'HSTS, X-Content-Type-Options, and X-Frame-Options improve security; X-Powered-By reveals server info and is not protective.',
          NULL,
          [],
          ARRAY['security','security-headers','headers','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec14","original_type":"multiple-choice","topic":"Security Headers","subcategory":"Headers","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:14:00.000Z',
          '2025-10-11T00:14:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2cdcf2ff-2c5c-40d6-b50e-daadef36d167',
          'True or False: Using HTTPS alone completely protects against XSS.',
          'Evaluate the statement.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec15","original_type":"true-false","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:15:00.000Z',
          '2025-10-11T00:15:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1b9cecb4-adc6-4ab4-b0de-2d1a0745538c',
          'How can you prevent DOM-based XSS in JavaScript?',
          'Explain best practices for preventing DOM-based XSS attacks in frontend code.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec16","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:16:00.000Z',
          '2025-10-11T00:16:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '63de6820-414e-4972-82f6-8ddd70d6bdab',
          'Which of these are valid ways to secure cookies against XSS and CSRF?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Set HttpOnly flag","isCorrect":true,"explanation":""},{"id":"o2","text":"Set Secure flag","isCorrect":true,"explanation":""},{"id":"o3","text":"Use SameSite=strict","isCorrect":true,"explanation":""},{"id":"o4","text":"Store sensitive info in localStorage","isCorrect":false,"explanation":""}]',
          NULL,
          'HttpOnly prevents JS access, Secure restricts to HTTPS, and SameSite limits cross-site requests. LocalStorage is accessible by JS and vulnerable to XSS.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec17","original_type":"multiple-choice","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:17:00.000Z',
          '2025-10-11T00:17:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2035baa8-c08e-40d2-a213-9f58f65eea09',
          'True or False: Using third-party JavaScript libraries without review is safe if your site uses HTTPS.',
          'Evaluate this statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','third-party','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-02-sec18","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"Third-Party","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:18:00.000Z',
          '2025-10-11T00:18:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd5fce853-463e-46e9-a9e2-c9b0429c3750',
          'What is Clickjacking (UI Redressing)?',
          'Explain what clickjacking is and how attackers can exploit it to trick users.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec19","original_type":"open-ended","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":["Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:19:00.000Z',
          '2025-10-11T00:19:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b6844217-9c1a-4b11-9851-ea6ff3bf5d92',
          'How can you prevent clickjacking?',
          'Select all correct methods to prevent clickjacking attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use X-Frame-Options: DENY or SAMEORIGIN","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable JavaScript entirely","isCorrect":false,"explanation":""},{"id":"o4","text":"Detect and prevent iframes using JS","isCorrect":true,"explanation":""}]',
          NULL,
          'X-Frame-Options and frame-ancestors protect against embedding. JS detection can add extra protection; disabling JS is impractical.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec20","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:20:00.000Z',
          '2025-10-11T00:20:00.000Z'
        );;