INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f13cc229-09b3-49ef-b62b-8b256e525950',
          'How does PRPL enhance offline experience?',
          'Explain how PRPL ensures an app remains functional even without an internet connection.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline.',
          NULL,
          [],
          ARRAY['performance-patterns','prpl-pattern','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-prpl-pp13","original_type":"open-ended","topic":"PRPL Pattern","subcategory":"","sample_answers":["By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-10T00:00:00.000Z',
          '2025-10-10T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8e8efa24-3d54-472f-8074-6c52c349f43c',
          'Which step in PRPL primarily benefits from HTTP/2 server push?',
          'Identify where HTTP/2 server push has the most effect in the PRPL process.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Push","isCorrect":true,"explanation":""},{"id":"o2","text":"Render","isCorrect":false,"explanation":""},{"id":"o3","text":"Pre-cache","isCorrect":false,"explanation":""},{"id":"o4","text":"Lazy-load","isCorrect":false,"explanation":""}]',
          NULL,
          'HTTP/2 server push accelerates the ''Push'' step by sending critical resources before the browser requests them.',
          NULL,
          [],
          ARRAY['performance-patterns','prpl-pattern','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-prpl-pp14","original_type":"multiple-choice","topic":"PRPL Pattern","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-10T00:00:00.000Z',
          '2025-10-10T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'af0dc6d2-f5de-46c4-883f-8843c1c6d04b',
          'True or False: PRPL can only be implemented in Progressive Web Apps (PWAs).',
          'Evaluate the statement about PRPL’s application scope.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['performance-patterns','prpl-pattern','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-prpl-pp15","original_type":"true-false","topic":"PRPL Pattern","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-10T00:00:00.000Z',
          '2025-10-10T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5bfc6099-c482-4cb3-abff-8b48f70dbc15',
          'What are third-party resources on a website?',
          'Define third-party resources and give examples.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements.',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-resources','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp1","original_type":"open-ended","topic":"Third-Party Resources","subcategory":"","sample_answers":["Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd27de4f5-f8de-43ef-93bf-a7dcb2a6af75',
          'Why can third-party scripts slow down your website?',
          'Identify the main ways third-party scripts negatively impact performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Additional round trips to other domains","isCorrect":true,"explanation":""},{"id":"o2","text":"Bulky or unoptimized JavaScript","isCorrect":true,"explanation":""},{"id":"o3","text":"Blocking rendering of critical resources","isCorrect":true,"explanation":""},{"id":"o4","text":"Always reduces DNS lookup times","isCorrect":false,"explanation":""}]',
          NULL,
          'Third-party scripts can block rendering, increase network requests, and execute heavy JS, negatively impacting Core Web Vitals.',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-performance-impact','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp2","original_type":"multiple-choice","topic":"Third-Party Performance Impact","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cee0b7b2-0f6f-4da4-b202-bdf37283aaec',
          'How can you optimize non-critical third-party JavaScript?',
          'Explain async and defer usage for non-critical third-party scripts.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering.',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-loading','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp3","original_type":"open-ended","topic":"Third-Party Loading","subcategory":"","sample_answers":["Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '32786984-747b-41dd-93ef-06100ee67abf',
          'True or False: Preconnect and dns-prefetch can speed up third-party resource loading.',
          'Evaluate whether resource hints improve third-party performance.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-loading','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp4","original_type":"true-false","topic":"Third-Party Loading","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '700714af-00fe-4158-8c08-fb7dc091e1a8',
          'What is the benefit of lazy-loading third-party embeds?',
          'Explain why lazy-loading YouTube, maps, and social media embeds improves page performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering.',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-loading','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp5","original_type":"open-ended","topic":"Third-Party Loading","subcategory":"","sample_answers":["Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7a219998-e295-41a4-ae6a-b07cadc30b9c',
          'Why might self-hosting third-party scripts improve performance?',
          'Describe the advantages and caveats of self-hosting 3P scripts.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current.',
          NULL,
          [],
          ARRAY['performance-patterns','third-party-loading','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp6","original_type":"open-ended","topic":"Third-Party Loading","subcategory":"","sample_answers":["Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '283ce62a-4fe0-4b1d-a229-b480431907c0',
          'Which strategy does Next.js provide to optimize third-party scripts?',
          'Identify the strategies available in the Next.js Script component.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"beforeInteractive","isCorrect":true,"explanation":""},{"id":"o2","text":"afterInteractive","isCorrect":true,"explanation":""},{"id":"o3","text":"lazyOnload","isCorrect":true,"explanation":""},{"id":"o4","text":"documentWrite","isCorrect":false,"explanation":""}]',
          NULL,
          'Next.js Script component allows beforeInteractive for critical scripts, afterInteractive for deferred scripts, and lazyOnload for scripts to load when idle.',
          NULL,
          [],
          ARRAY['performance-patterns','next.js-third-party-scripts','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-third-party-tp7","original_type":"multiple-choice","topic":"Next.js Third-Party Scripts","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '59506cb2-4f50-4fee-9875-d37e5bb11f55',
          'What is tree shaking in JavaScript?',
          'Define tree shaking and its main purpose.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Tree shaking is the process of eliminating unused code from the final JavaScript bundle to reduce size, download, parse, and execution time.',
          NULL,
          [],
          ARRAY['performance-patterns','tree-shaking','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-tree-shaking-ts1","original_type":"open-ended","topic":"Tree Shaking","subcategory":"","sample_answers":["Tree shaking is the process of eliminating unused code from the final JavaScript bundle to reduce size, download, parse, and execution time."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4a20a147-fc46-4e5a-913c-438eea2dd439',
          'True or False: Tree shaking works with CommonJS modules.',
          'Evaluate whether tree shaking can remove dead code from CommonJS modules.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['performance-patterns','tree-shaking-modules','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-tree-shaking-ts2","original_type":"true-false","topic":"Tree Shaking Modules","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3c287f81-926e-477b-9731-38fddb8a807a',
          'Why does tree shaking consider side effects in modules?',
          'Explain what side effects are and why they affect tree shaking.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking.',
          NULL,
          [],
          ARRAY['performance-patterns','tree-shaking-side-effects','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-tree-shaking-ts3","original_type":"open-ended","topic":"Tree Shaking Side Effects","subcategory":"","sample_answers":["A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd96d96a0-1db9-46df-b44d-0f0ed093e5ac',
          'Given the following code, which function will be included in the final bundle?',
          '```javascript
// utilities.js
export function read(props) { return props.book; }
export function nap(props) { return props.winks; }

// index.js
import { read } from ''utilities'';
const eventHandler = (e) => { read({ book: e.target.value }); };
```',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"read()","isCorrect":true,"explanation":""},{"id":"o2","text":"nap()","isCorrect":false,"explanation":""}]',
          NULL,
          'Only read() is used in index.js, so nap() is considered dead code and excluded from the bundle.',
          NULL,
          [],
          ARRAY['performance-patterns','tree-shaking-example','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-tree-shaking-ts4","original_type":"multiple-choice","topic":"Tree Shaking Example","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7122b2e0-2dfa-49af-a2a0-e206bc86d59f',
          'How does tree shaking determine which parts of the code to include?',
          'Explain the traversal process used in tree shaking.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle.',
          NULL,
          [],
          ARRAY['performance-patterns','tree-shaking-mechanism','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-tree-shaking-ts5","original_type":"open-ended","topic":"Tree Shaking Mechanism","subcategory":"","sample_answers":["Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a59794a4-6ce0-42c1-b952-547367aa9a39',
          'What is list virtualization (or windowing)?',
          'Explain the concept of list virtualization and its main benefit.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency.',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv1","original_type":"open-ended","topic":"Virtual Lists","subcategory":"","sample_answers":["List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6403e206-a80c-4ad6-89b8-1085b8981730',
          'Why is react-window preferred over react-virtualized in some cases?',
          'Describe the differences between react-window and react-virtualized and why react-window might be chosen.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly.',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists-libraries','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv2","original_type":"open-ended","topic":"Virtual Lists Libraries","subcategory":"","sample_answers":["React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '61874e03-09d6-4325-aa1b-cc95362e2795',
          'True or False: List virtualization renders all items in the DOM at once.',
          'Evaluate whether virtualization renders all items immediately.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists-rendering','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv3","original_type":"true-false","topic":"Virtual Lists Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b26bd0fe-9247-4426-b2ad-88bb4b39bdf0',
          'What is the role of a ''window'' in list virtualization?',
          'Explain what a ''window'' represents in the context of virtualized lists.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones.',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists-windowing','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv4","original_type":"open-ended","topic":"Virtual Lists Windowing","subcategory":"","sample_answers":["The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '97e548d3-9d34-4108-9796-e0109393cf09',
          'Which components in react-window render virtualized content?',
          'Name and describe the main components in react-window used for list and grid virtualization.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"FixedSizeList and VariableSizeList for lists; FixedSizeGrid and VariableSizeGrid for grids","isCorrect":true,"explanation":""},{"id":"o2","text":"InfiniteScrollList and TableGrid","isCorrect":false,"explanation":""}]',
          NULL,
          'react-window provides FixedSizeList/VariableSizeList for virtualized lists and FixedSizeGrid/VariableSizeGrid for virtualized grids.',
          NULL,
          [],
          ARRAY['performance-patterns','react-window-components','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv5","original_type":"multiple-choice","topic":"React-Window Components","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '71c07c6e-8396-4c0e-9327-95e672412d23',
          'What are some limitations of react-window compared to react-virtualized?',
          'List missing features/components in react-window.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed.',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists-limitations','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv6","original_type":"open-ended","topic":"Virtual Lists Limitations","subcategory":"","sample_answers":["React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '11a87e29-1598-4bab-a330-7055ccc657b7',
          'How does list virtualization improve performance on mid to low-end devices?',
          'Explain the mechanism by which virtualization keeps rendering fast on slower devices.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth.',
          NULL,
          [],
          ARRAY['performance-patterns','virtual-lists-performance','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"performance-patterns-virtualization-lv7","original_type":"open-ended","topic":"Virtual Lists Performance","subcategory":"","sample_answers":["By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Performance"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:00:00.000Z',
          '2025-10-11T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c6fc7f44-e362-4842-a9d6-e140a82a029e',
          'Understanding Islands Architecture',
          'What is the core idea behind the Islands Architecture rendering pattern?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-1","original_type":"open-ended","topic":"Islands Architecture","subcategory":"","sample_answers":["It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML.","Each island is hydrated independently, reducing JavaScript load and improving performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5c551ab6-8f95-46eb-9548-d029d9d8ba40',
          'Islands vs Client-Side Rendering',
          'How does Islands Architecture differ from traditional Client-Side Rendering (CSR)?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"CSR loads all JavaScript at once, while Islands only hydrate interactive components","isCorrect":true},{"id":"b","text":"Islands Architecture doesn’t support user interactions","isCorrect":false},{"id":"c","text":"CSR is faster than Islands because it’s fully client-driven","isCorrect":false}]',
          NULL,
          'CSR loads all JavaScript at once, while Islands only hydrate interactive components',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-2","original_type":"multiple-choice","topic":"Islands Architecture","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '925717fb-8736-4d14-83cb-fff9617971ac',
          'Performance Benefits',
          'Why does Islands Architecture improve performance?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Because it ships less JavaScript and hydrates only necessary interactive components.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-3","original_type":"open-ended","topic":"Islands Architecture","subcategory":"","sample_answers":["Because it ships less JavaScript and hydrates only necessary interactive components.","The static HTML renders instantly while islands load independently without blocking the main thread."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '095ce8e7-63b6-4404-b574-3885dfea410a',
          'Islands in Practice',
          'Which of the following frameworks is primarily designed around the Islands Architecture concept?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Next.js","isCorrect":false},{"id":"b","text":"Astro","isCorrect":true},{"id":"c","text":"Nuxt.js","isCorrect":false},{"id":"d","text":"Remix","isCorrect":false}]',
          NULL,
          'Astro',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-4","original_type":"multiple-choice","topic":"Islands Architecture","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5f31e596-e231-4fb0-81c2-dd02bbeaf896',
          'Hydration Behavior',
          'In Islands Architecture, when are the interactive islands hydrated?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"During the initial HTML parsing","isCorrect":false},{"id":"b","text":"After the static HTML has been rendered and the browser is idle","isCorrect":true},{"id":"c","text":"Only after a user clicks a button","isCorrect":false}]',
          NULL,
          'After the static HTML has been rendered and the browser is idle',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-5","original_type":"multiple-choice","topic":"Islands Architecture","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '26860e74-faed-4012-9a2d-684c08c7df6f',
          'Comparing with Progressive Hydration',
          'What’s a key difference between Islands Architecture and Progressive Hydration?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Progressive Hydration hydrates components in sequence across the page, while Islands Architecture hydrates independent islands in isolation.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-6","original_type":"open-ended","topic":"Islands Architecture","subcategory":"","sample_answers":["Progressive Hydration hydrates components in sequence across the page, while Islands Architecture hydrates independent islands in isolation.","Islands focus on independence and smaller isolated bundles, while Progressive Hydration still considers the page as one app."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6ce8f8e9-5d21-4272-8b45-e520184bc29a',
          'Use Case Fit',
          'Which type of application benefits most from Islands Architecture?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Highly interactive dashboards","isCorrect":false},{"id":"b","text":"Content-heavy websites like blogs or marketing pages","isCorrect":true},{"id":"c","text":"Real-time gaming apps","isCorrect":false}]',
          NULL,
          'Content-heavy websites like blogs or marketing pages',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-7","original_type":"multiple-choice","topic":"Islands Architecture","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fc174df6-d3af-48a3-87eb-dc5da50845b1',
          'Tradeoffs',
          'What’s one major drawback of adopting Islands Architecture today?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Limited framework support outside of Astro and Marko.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-8","original_type":"open-ended","topic":"Islands Architecture","subcategory":"","sample_answers":["Limited framework support outside of Astro and Marko.","Migration from traditional CSR or SSR frameworks can be complex."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1ab144cb-715b-47ea-b436-f505169d76d3',
          'SEO Advantage',
          'Why is Islands Architecture more SEO-friendly compared to Client-Side Rendering?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"It serves fully rendered HTML to crawlers before hydration","isCorrect":true},{"id":"b","text":"It delays rendering until user interaction","isCorrect":false},{"id":"c","text":"It hides interactive components from crawlers","isCorrect":false}]',
          NULL,
          'It serves fully rendered HTML to crawlers before hydration',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-9","original_type":"multiple-choice","topic":"Islands Architecture","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '15fd3c0d-571e-4b1f-b8ce-b26c3da6c69f',
          'Implementation Example',
          'In an Astro project, how could you create a ''Like'' button as an island on a static blog page?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By creating a separate React component for the Like button and importing it using Astro’s client directive like `client:load` or `client:idle`.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','islands-architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-islandarcheticure-10","original_type":"open-ended","topic":"Islands Architecture","subcategory":"","sample_answers":["By creating a separate React component for the Like button and importing it using Astro’s client directive like `client:load` or `client:idle`.","This ensures the rest of the page remains static while only the Like button’s script is loaded and hydrated on demand."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a5c4345f-7690-4943-a345-cfc7f43fe61c',
          'Edge Rendering Basics',
          'What is Edge Rendering and how does it differ from traditional SSR?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Edge Rendering executes server-side logic at CDN edge locations, closer to the user.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-1","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["Edge Rendering executes server-side logic at CDN edge locations, closer to the user.","It differs from traditional SSR because responses are generated with lower latency and faster Time To First Byte (TTFB)."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '98e3e4dc-971b-409c-bb2f-86e667add4ea',
          'Advantages of Edge Rendering',
          'Which of the following is a main advantage of Edge Rendering?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Reduced latency due to geographical proximity to users","isCorrect":true},{"id":"b","text":"It replaces all client-side rendering logic","isCorrect":false},{"id":"c","text":"It always increases server costs","isCorrect":false}]',
          NULL,
          'Reduced latency due to geographical proximity to users',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-2","original_type":"multiple-choice","topic":"Edge Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'be695c17-324d-4e1b-8e56-c262486dba8f',
          'Edge vs CDN Caching',
          'How is Edge Rendering different from traditional CDN caching?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-3","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge.","Edge rendering can personalize responses per user, unlike static CDN cache."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '84fadaf0-5e27-447d-8ef9-ecd1fed9b4c9',
          'Progressive Hydration Concept',
          'What is Progressive Hydration in React or similar frameworks?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"It hydrates parts of the UI gradually as JavaScript loads or user interacts","isCorrect":true},{"id":"b","text":"It waits until all components are fully loaded before rendering anything","isCorrect":false},{"id":"c","text":"It disables interactivity completely","isCorrect":false}]',
          NULL,
          'It hydrates parts of the UI gradually as JavaScript loads or user interacts',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-4","original_type":"multiple-choice","topic":"Edge Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a86ba214-9558-45a7-a681-5bddb7fec27a',
          'Why Progressive Hydration Matters',
          'Why is Progressive Hydration beneficial for large, complex pages?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-5","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates.","Improves perceived performance by prioritizing above-the-fold components."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '09c1b387-e909-4ad4-9740-ab7285c70105',
          'Resumability Explained',
          'What is Resumability in frameworks like Qwik?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Resumability allows the browser to resume application execution without rehydrating all components.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-6","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["Resumability allows the browser to resume application execution without rehydrating all components.","Instead of downloading and re-running the full JS, it resumes from pre-serialized state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3ccaf183-a221-4b0b-96c2-436cfe70d56d',
          'Resumability vs Hydration',
          'How does Resumability differ from traditional hydration?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Resumability skips full rehydration by resuming the app state directly from serialized data","isCorrect":true},{"id":"b","text":"Resumability re-renders everything on the server","isCorrect":false},{"id":"c","text":"They are the same process with different names","isCorrect":false}]',
          NULL,
          'Resumability skips full rehydration by resuming the app state directly from serialized data',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-7","original_type":"multiple-choice","topic":"Edge Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1ca43d88-c1bc-4075-89c1-ea17f05f8751',
          'React Server Components (RSC) Role',
          'How do React Server Components improve rendering performance?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-8","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size.","They send minimal serialized output to the browser and improve render speed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4f020d46-e046-447f-959e-566f161480c0',
          'Streaming + RSC Integration',
          'What benefit do we get when combining React Server Components with streaming rendering?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Users see parts of the UI sooner while server components load progressively","isCorrect":true},{"id":"b","text":"It delays rendering until all components are ready","isCorrect":false},{"id":"c","text":"It removes the need for client components entirely","isCorrect":false}]',
          NULL,
          'Users see parts of the UI sooner while server components load progressively',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-9","original_type":"multiple-choice","topic":"Edge Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '154a656b-6a35-43af-a689-f3d4d81ebd85',
          'Choosing Rendering Strategy',
          'How should a developer decide between SSR, ISR, Edge, and Resumable approaches?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','edge-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render6-10","original_type":"open-ended","topic":"Edge Rendering","subcategory":"","sample_answers":["Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration.","The choice depends on user proximity, data volatility, and performance goals."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '42714303-9b36-4fe1-9b0d-53c751d66f37',
          'Partial Hydration Concept',
          'What is Partial Hydration and when is it beneficial?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Partial Hydration means hydrating only parts of a statically rendered page that require interactivity.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-1","original_type":"open-ended","topic":"Progressive Hydration","subcategory":"","sample_answers":["Partial Hydration means hydrating only parts of a statically rendered page that require interactivity.","It is beneficial for pages with mostly static content and a few interactive widgets."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'efe9d420-73fa-42d7-b510-824dda80debf',
          'Partial vs Progressive Hydration',
          'How is Partial Hydration different from Progressive Hydration?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Partial Hydration only hydrates selected components, Progressive Hydration hydrates sequentially over time","isCorrect":true},{"id":"b","text":"They are identical processes","isCorrect":false},{"id":"c","text":"Partial Hydration works only on client-side rendering","isCorrect":false}]',
          NULL,
          'Partial Hydration only hydrates selected components, Progressive Hydration hydrates sequentially over time',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-2","original_type":"multiple-choice","topic":"Progressive Hydration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8caa837f-d6c1-4b32-a39b-9253a04a0004',
          'Selective Prefetching',
          'What is Selective Prefetching and why is it important?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Selective Prefetching fetches data or resources only for components likely to be used soon, based on user behavior.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-3","original_type":"open-ended","topic":"Progressive Hydration","subcategory":"","sample_answers":["Selective Prefetching fetches data or resources only for components likely to be used soon, based on user behavior.","It prevents bandwidth waste and improves perceived performance on slow networks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '386361d3-b26b-4ced-ac4a-5c690086ab2d',
          'When to Use Selective Prefetching',
          'In what scenario is Selective Prefetching most effective?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"On pages with many navigation routes where user intent can be predicted","isCorrect":true},{"id":"b","text":"On static single-page apps with no dynamic routing","isCorrect":false},{"id":"c","text":"When caching is disabled entirely","isCorrect":false}]',
          NULL,
          'On pages with many navigation routes where user intent can be predicted',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-4","original_type":"multiple-choice","topic":"Progressive Hydration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2f5f2f8c-88db-441f-b792-9fe3f6547c3c',
          'Lazy Streaming Rendering',
          'What is Lazy Streaming Rendering and how does it differ from normal streaming?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Lazy Streaming defers rendering of non-critical content until it’s needed, reducing initial TTFB.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-5","original_type":"open-ended","topic":"Progressive Hydration","subcategory":"","sample_answers":["Lazy Streaming defers rendering of non-critical content until it’s needed, reducing initial TTFB.","Unlike standard streaming, it doesn’t stream everything immediately—it prioritizes essential chunks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '331f12f9-fe09-4a4f-8d11-2a05baecd40b',
          'React Suspense for Data Fetching',
          'What role does React Suspense play in rendering optimization?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"It allows components to wait for data before rendering while showing fallback UI","isCorrect":true},{"id":"b","text":"It blocks all rendering until the entire app loads","isCorrect":false},{"id":"c","text":"It only works for routing, not data fetching","isCorrect":false}]',
          NULL,
          'It allows components to wait for data before rendering while showing fallback UI',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-6","original_type":"multiple-choice","topic":"Progressive Hydration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd4e56a05-29ef-488a-90c1-9a5d6f25ba0a',
          'Concurrent Rendering Advantage',
          'How does React 18''s concurrent rendering improve user experience?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Concurrent Rendering enables React to interrupt non-urgent renders to prioritize important updates, improving responsiveness.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-7","original_type":"open-ended","topic":"Progressive Hydration","subcategory":"","sample_answers":["Concurrent Rendering enables React to interrupt non-urgent renders to prioritize important updates, improving responsiveness.","It helps avoid UI freezes during heavy computation or re-renders."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c29aaf34-951d-42c5-a284-c4cc45033f58',
          'Concurrent vs Synchronous Rendering',
          'What is the difference between concurrent and synchronous rendering in React?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Concurrent rendering can pause and resume renders, synchronous rendering blocks until completion","isCorrect":true},{"id":"b","text":"Concurrent rendering executes faster JavaScript","isCorrect":false},{"id":"c","text":"Synchronous rendering can handle multiple threads","isCorrect":false}]',
          NULL,
          'Concurrent rendering can pause and resume renders, synchronous rendering blocks until completion',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-8","original_type":"multiple-choice","topic":"Progressive Hydration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );;