INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cedf0e15-a1c0-4ab6-a4b3-03967d3444e6',
          'What is Clickjacking (UI Redressing)?',
          'Explain how clickjacking attacks work and why they are dangerous.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec71","original_type":"open-ended","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":["Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:11:00.000Z',
          '2025-10-11T01:11:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '95f7015a-c3ab-45ca-8f5a-f90b90144734',
          'How can you prevent clickjacking attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use X-Frame-Options header","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable JavaScript completely","isCorrect":false,"explanation":""},{"id":"o4","text":"Use secure authentication only","isCorrect":false,"explanation":""}]',
          NULL,
          'X-Frame-Options and CSP frame-ancestors prevent a site from being embedded in iframes, mitigating clickjacking attacks.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec72","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:12:00.000Z',
          '2025-10-11T01:12:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5996fa67-201d-457f-bb92-5a5a69653811',
          'What is Man-in-the-Middle (MITM) attack?',
          'Explain how MITM attacks occur in web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec73","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":["MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:13:00.000Z',
          '2025-10-11T01:13:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f05e8465-89e3-4c81-a59d-69db636d1386',
          'How can you prevent MITM attacks in web applications?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use HTTPS for all communication","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate SSL/TLS certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Implement HSTS headers","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on network-level security","isCorrect":false,"explanation":""}]',
          NULL,
          'HTTPS, certificate validation, and HSTS protect against MITM attacks. Network-level security alone is insufficient.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec74","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:14:00.000Z',
          '2025-10-11T01:14:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ed366063-d2b3-4497-a713-affc91569e09',
          'What is HTTP Strict Transport Security (HSTS)?',
          'Explain how HSTS helps improve web security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','headers','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec75","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Headers","sample_answers":["HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:15:00.000Z',
          '2025-10-11T01:15:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '589d466b-6192-47c6-a8b4-bfe6e2b77899',
          'What is Subresource Integrity (SRI)?',
          'Explain how SRI protects your frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','headers','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec76","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Headers","sample_answers":["SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:16:00.000Z',
          '2025-10-11T01:16:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '81f7b43d-470d-45e5-bc14-f8a38bb3c8ab',
          'How do HTTPS and TLS protect against web attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Encrypts data in transit","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents eavesdropping and tampering","isCorrect":true,"explanation":""},{"id":"o3","text":"Automatically sanitizes user inputs","isCorrect":false,"explanation":""},{"id":"o4","text":"Provides server authentication","isCorrect":true,"explanation":""}]',
          NULL,
          'HTTPS/TLS encrypts data, ensures integrity, and authenticates servers. It does not sanitize inputs.',
          NULL,
          [],
          ARRAY['security','https-&-ssl/tls','tls','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec77","original_type":"multiple-choice","topic":"HTTPS & SSL/TLS","subcategory":"TLS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:17:00.000Z',
          '2025-10-11T01:17:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7ee4ea3c-e255-44cf-84e5-f9905006e306',
          'What are security implications of storing sensitive data in localStorage?',
          'Explain the risks of using localStorage for authentication tokens.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','storage','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec78","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Storage","sample_answers":["localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:18:00.000Z',
          '2025-10-11T01:18:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5c3cf87d-0dd3-49d0-8cc8-17e20a393809',
          'What is a security audit for frontend applications?',
          'Explain the purpose of frontend security audits.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them.',
          NULL,
          [],
          ARRAY['security','security-auditing','audit','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec79","original_type":"open-ended","topic":"Security Auditing","subcategory":"Audit","sample_answers":["A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:19:00.000Z',
          '2025-10-11T01:19:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8e1b9f82-71d8-48fd-8c78-5bb137124872',
          'What is the principle of least privilege in frontend security?',
          'Explain how least privilege applies to frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','least privilege','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-09-sec80","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Least Privilege","sample_answers":["Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:20:00.000Z',
          '2025-10-11T01:20:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4948bb5d-8853-4790-91b9-1087359f171a',
          'How does CSRF (Cross-Site Request Forgery) work?',
          'Explain the mechanism of a CSRF attack and its potential impact.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec81","original_type":"open-ended","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":["CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:20:00.000Z',
          '2025-10-11T01:20:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '75c4452d-f436-4ada-807a-64ba346e1b38',
          'How can you prevent CSRF attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookie attribute","isCorrect":true,"explanation":""},{"id":"o3","text":"Use HTTPS","isCorrect":true,"explanation":""},{"id":"o4","text":"Disable cookies completely","isCorrect":false,"explanation":""}]',
          NULL,
          'CSRF tokens, SameSite cookies, and HTTPS help prevent CSRF attacks. Disabling cookies is not practical for most web apps.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec82","original_type":"multiple-choice","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:21:00.000Z',
          '2025-10-11T01:21:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bc8c302f-6181-4d8e-aeaf-9239e4b5d411',
          'What is the difference between DOM-based XSS and Stored XSS?',
          'Select the correct description.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"DOM-based XSS executes purely on the client side","isCorrect":true,"explanation":""},{"id":"o2","text":"Stored XSS persists in a database or storage and affects multiple users","isCorrect":true,"explanation":""},{"id":"o3","text":"DOM-based XSS stores payloads on the server","isCorrect":false,"explanation":""},{"id":"o4","text":"Stored XSS only affects a single user","isCorrect":false,"explanation":""}]',
          NULL,
          'DOM-based XSS runs in the browser, while Stored XSS is saved in server-side storage and executed when other users access it.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec83","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:22:00.000Z',
          '2025-10-11T01:22:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4a06f440-4ab3-4c3f-90fb-09283ee0b425',
          'Why should you avoid using inline scripts in your frontend code?',
          'Explain the security risk associated with inline JavaScript.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec84","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:23:00.000Z',
          '2025-10-11T01:23:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c04ed3e4-e3da-4925-983e-a54febe1dd52',
          'What is the role of Content Security Policy (CSP) in frontend security?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Restricts sources of scripts and other resources","isCorrect":true,"explanation":""},{"id":"o2","text":"Helps prevent XSS attacks","isCorrect":true,"explanation":""},{"id":"o3","text":"Replaces the need for input validation","isCorrect":false,"explanation":""},{"id":"o4","text":"Can block inline styles and scripts if configured","isCorrect":true,"explanation":""}]',
          NULL,
          'CSP controls resource loading and helps prevent XSS, but does not replace input validation.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','headers','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec85","original_type":"multiple-choice","topic":"Content Security Policy (CSP)","subcategory":"Headers","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:24:00.000Z',
          '2025-10-11T01:24:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3425465b-999c-4194-b22a-a7516198f18c',
          'Why is sanitizing user input important in frontend security?',
          'Explain the consequences of unsanitized inputs.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec86","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:25:00.000Z',
          '2025-10-11T01:25:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '692b6561-3be4-45e2-a9d5-46faa351bb88',
          'How does the SameSite cookie attribute improve security?',
          'Select the correct behavior.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Prevents cookies from being sent with cross-site requests by default","isCorrect":true,"explanation":""},{"id":"o2","text":"Mitigates CSRF attacks","isCorrect":true,"explanation":""},{"id":"o3","text":"Encrypts cookie contents","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents cookies from being accessed via JavaScript","isCorrect":false,"explanation":""}]',
          NULL,
          'SameSite restricts cross-site sending of cookies to reduce CSRF risks. It does not encrypt cookies or make them HttpOnly.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec87","original_type":"multiple-choice","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:26:00.000Z',
          '2025-10-11T01:26:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '52a6df41-45dc-4b77-a331-ae3ec38ec84a',
          'What are best practices for secure cookie usage in frontend applications?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use HttpOnly to prevent JavaScript access","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Secure flag to enforce HTTPS transmission","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid storing sensitive tokens in localStorage","isCorrect":true,"explanation":""},{"id":"o4","text":"Use SameSite attribute to mitigate CSRF","isCorrect":true,"explanation":""}]',
          NULL,
          'HttpOnly, Secure, and SameSite attributes protect cookies from XSS and CSRF attacks. Sensitive tokens should not be stored in localStorage.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec88","original_type":"multiple-choice","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:27:00.000Z',
          '2025-10-11T01:27:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '52e8e711-f9d7-4c9d-8413-7d8011bad39f',
          'What is the risk of using eval() in frontend JavaScript?',
          'Explain why eval() can be dangerous in web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec89","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:28:00.000Z',
          '2025-10-11T01:28:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b8cf69b9-a52e-411b-9b9a-573e8b2208a4',
          'How do you mitigate XSS in React applications?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use JSX curly braces to escape content","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize any user-generated HTML before using dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o3","text":"Use external scripts instead of inline scripts","isCorrect":true,"explanation":""},{"id":"o4","text":"Store session tokens in localStorage without encryption","isCorrect":false,"explanation":""}]',
          NULL,
          'React automatically escapes content in JSX. Any HTML inserted via dangerouslySetInnerHTML must be sanitized. Avoid storing sensitive tokens insecurely.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-10-sec90","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:29:00.000Z',
          '2025-10-11T01:29:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fee54f2c-2248-491e-88a3-3c2c63216335',
          'What is Clickjacking (UI Redressing)?',
          'Explain how clickjacking works and why it''s dangerous.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions.',
          NULL,
          [],
          ARRAY['security','clickjacking','ui redressing','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec91","original_type":"open-ended","topic":"Clickjacking","subcategory":"UI Redressing","sample_answers":["Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:30:00.000Z',
          '2025-10-11T01:30:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1f8abef6-c937-49de-92c1-45f6967f8ec5',
          'How can you prevent Clickjacking attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use X-Frame-Options header to deny framing","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Ensure HTTPS is used","isCorrect":false,"explanation":""},{"id":"o4","text":"Use JavaScript frame-busting techniques","isCorrect":true,"explanation":""}]',
          NULL,
          'X-Frame-Options, CSP frame-ancestors, and frame-busting scripts protect against clickjacking. HTTPS alone does not prevent it.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','ui redressing','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec92","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"UI Redressing","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:31:00.000Z',
          '2025-10-11T01:31:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b01062f9-301c-4f7b-8f22-5ac81e70e1ab',
          'What is a Man-in-the-Middle (MITM) attack?',
          'Explain how MITM attacks can compromise web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','network','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec93","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Network","sample_answers":["MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:32:00.000Z',
          '2025-10-11T01:32:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c2152869-2b3b-477b-9e1a-68214e234074',
          'How can HTTPS prevent MITM attacks?',
          'Select the correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Encrypts data in transit","isCorrect":true,"explanation":""},{"id":"o2","text":"Authenticates the server using certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Prevents phishing attacks","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents unauthorized data tampering","isCorrect":true,"explanation":""}]',
          NULL,
          'HTTPS encrypts traffic and verifies server identity, reducing MITM risks. It does not automatically prevent phishing.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','network','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec94","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"Network","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:33:00.000Z',
          '2025-10-11T01:33:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3e5786de-8be6-4571-b3cc-0f471c9aadfe',
          'What are common signs that a website might be vulnerable to XSS?',
          'Select all applicable options.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"User input is reflected without sanitization","isCorrect":true,"explanation":""},{"id":"o2","text":"Using dangerouslySetInnerHTML without sanitation","isCorrect":true,"explanation":""},{"id":"o3","text":"Input validation for forms","isCorrect":false,"explanation":""},{"id":"o4","text":"Content loaded dynamically from unknown sources","isCorrect":true,"explanation":""}]',
          NULL,
          'Reflected input, unsanitized HTML rendering, and dynamic content from untrusted sources are common XSS vulnerabilities.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec95","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:34:00.000Z',
          '2025-10-11T01:34:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '988b5e7b-57cf-45a0-a8ee-78ef2e098a3d',
          'Why should frontend developers care about security headers?',
          'Explain their role and importance in web security.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior.',
          NULL,
          [],
          ARRAY['security','security-headers','headers','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec96","original_type":"open-ended","topic":"Security Headers","subcategory":"Headers","sample_answers":["Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:35:00.000Z',
          '2025-10-11T01:35:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7d50a8af-8174-4cc6-a5a8-5cdcaf1a569c',
          'What is the purpose of the HttpOnly cookie attribute?',
          'Select the correct option.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Prevents JavaScript from accessing the cookie","isCorrect":true,"explanation":""},{"id":"o2","text":"Encrypts cookie contents","isCorrect":false,"explanation":""},{"id":"o3","text":"Prevents cookies from being sent over HTTP","isCorrect":false,"explanation":""},{"id":"o4","text":"Automatically rotates session cookies","isCorrect":false,"explanation":""}]',
          NULL,
          'HttpOnly restricts access to cookies from JavaScript, reducing XSS risks.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec97","original_type":"multiple-choice","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:36:00.000Z',
          '2025-10-11T01:36:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '886ae8ac-50e8-4a60-8c58-cb59dab62055',
          'What is the main danger of storing JWT tokens in localStorage?',
          'Explain the security risk involved.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','tokens','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec98","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Tokens","sample_answers":["JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:37:00.000Z',
          '2025-10-11T01:37:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a92c32c8-5af1-47f0-9a1d-99169b7b76f3',
          'How can React’s default escaping help prevent XSS?',
          'Select the correct options.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Automatically escapes data in JSX expressions","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents execution of scripts in user content","isCorrect":true,"explanation":""},{"id":"o3","text":"Replaces the need for server-side validation","isCorrect":false,"explanation":""},{"id":"o4","text":"Removes all HTML from user input","isCorrect":false,"explanation":""}]',
          NULL,
          'React escapes data in JSX, preventing scripts from executing. However, server-side validation is still required.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec99","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:38:00.000Z',
          '2025-10-11T01:38:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'de46c550-e627-4689-8416-be23cfdaaee3',
          'What is the role of TLS/SSL certificates in web security?',
          'Explain how TLS/SSL certificates protect users and applications.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','network','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-11-sec100","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"Network","sample_answers":["TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:39:00.000Z',
          '2025-10-11T01:39:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0732dcd9-b668-4192-836f-aaeef3bb9f6e',
          'What are the different approaches for pagination in frontend?',
          'Compare offset-based pagination, cursor-based pagination, and infinite scrolling. Which approach is better for large datasets?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Offset-based pagination","isCorrect":true,"explanation":""},{"id":"o2","text":"Cursor-based pagination","isCorrect":true,"explanation":""},{"id":"o3","text":"Infinite scrolling","isCorrect":true,"explanation":""},{"id":"o4","text":"Randomized pagination","isCorrect":false,"explanation":""}]',
          NULL,
          'Offset pagination is simple but slow at scale. Cursor pagination is efficient and consistent. Infinite scroll provides seamless UX but is harder for bookmarking and SEO.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q1","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '44e39744-2ac7-45d2-b12f-9d83d9e136b6',
          'What is a signed URL for images?',
          'Explain how signed URLs are used for secure and performant image delivery in frontend applications.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'A signed URL is a temporary, cryptographically signed link that allows secure access to a file. It improves performance because the frontend can fetch directly from CDN/storage instead of proxying through the backend.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q2","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["A signed URL is a temporary, cryptographically signed link that allows secure access to a file. It improves performance because the frontend can fetch directly from CDN/storage instead of proxying through the backend."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b89453e1-bcff-4295-aa8d-1b66ca74c0c0',
          'How can you apply critical CSS in frontend performance optimization?',
          'Describe what critical CSS is and how to implement it.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Critical CSS means extracting the styles needed for above-the-fold content and inlining them in the HTML. This reduces render-blocking requests and improves time-to-first-paint.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q3","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Critical CSS means extracting the styles needed for above-the-fold content and inlining them in the HTML. This reduces render-blocking requests and improves time-to-first-paint."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c8951877-5648-48ee-b6dc-941fe756a493',
          'What are the trade-offs between SSR, CSR, and SSG?',
          'Explain the differences between Server-Side Rendering (SSR), Client-Side Rendering (CSR), and Static Site Generation (SSG).',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"SSR improves SEO but requires servers to render each request","isCorrect":true,"explanation":""},{"id":"o2","text":"CSR improves interactivity but may delay first paint","isCorrect":true,"explanation":""},{"id":"o3","text":"SSG pre-renders content, making it very fast for static pages","isCorrect":true,"explanation":""},{"id":"o4","text":"CSR is always better than SSR","isCorrect":false,"explanation":""}]',
          NULL,
          'SSR improves SEO and first load but increases server cost. CSR shifts load to client but may hurt SEO. SSG is fast but static.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q4","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1eeb7cd1-f952-48f7-8031-77dba3594e4d',
          'What is bundle splitting and why is it important?',
          'Explain the concept of bundle splitting in frontend applications.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'Bundle splitting breaks the app into smaller chunks that can be loaded on demand, reducing initial load time.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q5","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5e16c7ba-510e-4d0a-b073-f3613e273b8c',
          'What is the difference between Context API and Redux for state management?',
          'Compare Context API and Redux when designing frontend system state flow.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Context API is simple for small to medium apps with minimal boilerplate, but can cause re-renders. Redux provides structured state management and debugging tools, better for complex apps.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q6","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Context API is simple for small to medium apps with minimal boilerplate, but can cause re-renders. Redux provides structured state management and debugging tools, better for complex apps."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '53436944-47c4-478d-9464-52ae0bd5c536',
          'How do you optimize images for frontend performance?',
          'List and explain techniques to improve image loading performance.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Use WebP or AVIF formats","isCorrect":true,"explanation":""},{"id":"o2","text":"Lazy load images below the fold","isCorrect":true,"explanation":""},{"id":"o3","text":"Serve images via CDN with caching","isCorrect":true,"explanation":""},{"id":"o4","text":"Always use raw PNGs without compression","isCorrect":false,"explanation":""}]',
          NULL,
          'Using optimized formats, lazy loading, and CDNs reduces bandwidth and improves load times.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q7","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '18355747-1b39-4049-a0d2-35f787692ee0',
          'What are ARIA roles and why are they important?',
          'Explain ARIA roles in accessibility design.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'ARIA roles provide semantic meaning for assistive technologies like screen readers.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q8","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '10beeb63-5b7c-4032-9114-80a8f41ce2cc',
          'How do you design a component dependency graph from a Figma design?',
          'Describe how to break down a Figma design into smaller components and map their dependencies.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Start with high-level layout containers, identify reusable UI elements (buttons, cards, forms), then map parent-child relationships. Use a dependency graph to track composition and shared props.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q9","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Start with high-level layout containers, identify reusable UI elements (buttons, cards, forms), then map parent-child relationships. Use a dependency graph to track composition and shared props."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e5b4e532-ccaf-454c-beed-88f3186ec371',
          'What are different approaches for real-time data updates in frontend?',
          'Compare long polling, WebSockets, and Server-Sent Events (SSE).',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"o1","text":"Long polling sends repeated HTTP requests to check for updates","isCorrect":true,"explanation":""},{"id":"o2","text":"WebSockets provide full-duplex communication between client and server","isCorrect":true,"explanation":""},{"id":"o3","text":"SSE is a one-way push from server to client","isCorrect":true,"explanation":""},{"id":"o4","text":"WebSockets are always the best choice","isCorrect":false,"explanation":""}]',
          NULL,
          'Long polling repeatedly requests updates. WebSockets provide bi-directional communication. SSE streams updates one way from server to client.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q10","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4e9937c8-3c67-4f13-850f-209137bb8746',
          'What is the difference between lazy loading and code splitting?',
          'Explain how lazy loading and code splitting optimize performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Lazy loading delays loading of code/resources until needed","isCorrect":true,"explanation":""},{"id":"o2","text":"Code splitting divides the app into smaller chunks","isCorrect":true,"explanation":""},{"id":"o3","text":"They are the same concept with different names","isCorrect":false,"explanation":""}]',
          NULL,
          'Code splitting breaks the app into chunks. Lazy loading ensures chunks load only when needed.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q11","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '137d7de1-1863-4bb9-a30f-7a21b87b37d8',
          'What are Content Delivery Networks (CDNs) and why are they used?',
          'Describe the role of a CDN in frontend performance.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'CDNs reduce latency by caching and serving content closer to the user.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q12","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd6a31171-e789-43dc-b6dd-1738307abd1d',
          'What is tree-shaking in JavaScript bundling?',
          'Explain how tree-shaking improves frontend performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Tree-shaking is the process of removing unused code from bundles during build time. It reduces bundle size and improves performance.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q13","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Tree-shaking is the process of removing unused code from bundles during build time. It reduces bundle size and improves performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '74f0b1ac-4977-45cc-a6c5-d8f86631c066',
          'What are the main principles of accessibility in frontend design?',
          'List core accessibility principles (POUR: Perceivable, Operable, Understandable, Robust).',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Perceivable","isCorrect":true,"explanation":""},{"id":"o2","text":"Operable","isCorrect":true,"explanation":""},{"id":"o3","text":"Understandable","isCorrect":true,"explanation":""},{"id":"o4","text":"Robust","isCorrect":true,"explanation":""},{"id":"o5","text":"Fast","isCorrect":false,"explanation":""}]',
          NULL,
          'Accessibility guidelines are based on POUR principles.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q14","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd167ff06-5faa-44d2-b624-fd2f0d044196',
          'How do you ensure keyboard accessibility in components?',
          'Explain best practices for making UI accessible via keyboard.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Ensure focusable elements use tabindex correctly, use semantic HTML elements, and manage focus state when modals or dialogs open.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q15","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Ensure focusable elements use tabindex correctly, use semantic HTML elements, and manage focus state when modals or dialogs open."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a89e2f68-7305-415a-8fbc-46553057a5de',
          'What are optimistic and pessimistic updates in frontend data flow?',
          'Describe the difference between optimistic and pessimistic updates in state management.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"o1","text":"Optimistic update: update UI before server confirms","isCorrect":true,"explanation":""},{"id":"o2","text":"Pessimistic update: update UI after server confirms","isCorrect":true,"explanation":""},{"id":"o3","text":"Both approaches are identical","isCorrect":false,"explanation":""}]',
          NULL,
          'Optimistic updates update UI immediately before server confirmation. Pessimistic updates wait for server response.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q16","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd1a5d3ee-117b-463c-87fc-249d34557553',
          'What are idempotent APIs and why are they important for frontend?',
          'Explain idempotency in APIs and its impact on frontend state consistency.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Idempotent APIs produce the same result no matter how many times they are called. They prevent duplicate state changes if frontend retries requests due to network issues.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q17","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Idempotent APIs produce the same result no matter how many times they are called. They prevent duplicate state changes if frontend retries requests due to network issues."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e340d880-4645-4d6a-8eda-e093388195c7',
          'What is hydration in React?',
          'Explain how hydration works in React SSR.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'Hydration attaches event listeners to pre-rendered HTML from SSR, making the page interactive.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q18","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3c60428b-abf2-4fe3-9495-cbece2bb4028',
          'What is the difference between virtual DOM and real DOM?',
          'Describe how virtual DOM improves rendering performance in frontend frameworks.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The virtual DOM is an in-memory representation of the UI. Instead of updating the real DOM directly, frameworks update the virtual DOM and compute the minimal changes, which are then applied to the real DOM.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q19","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["The virtual DOM is an in-memory representation of the UI. Instead of updating the real DOM directly, frameworks update the virtual DOM and compute the minimal changes, which are then applied to the real DOM."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '27200e48-2ee2-4846-b6e9-abac6c974865',
          'What are micro-frontends and when would you use them?',
          'Explain the concept of micro-frontends and their trade-offs.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"o1","text":"Micro-frontends allow independent teams to build and deploy parts of the UI","isCorrect":true,"explanation":""},{"id":"o2","text":"Micro-frontends always simplify performance optimization","isCorrect":false,"explanation":""},{"id":"o3","text":"They increase architectural complexity","isCorrect":true,"explanation":""}]',
          NULL,
          'Micro-frontends split the UI into smaller, independently deployable apps. They improve scalability but increase complexity.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q20","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );;