INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8c05eb35-0dbb-4658-bc62-39676125a9c4',
          'Singleton Alternatives in React',
          'What are common alternatives to using Singletons for global state in React applications?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React Context API State management libraries such as Redux, Zustand, or MobX.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-singleton-pattern-85","original_type":"open-ended","topic":"General Design Patterns","subcategory":"","sample_answers":["React Context API","State management libraries such as Redux, Zustand, or MobX."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.208Z',
          '2025-10-15T00:47:17.208Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c14c7b27-4393-401a-912e-7cf0a313f7d1',
          'What is Static Import in JavaScript modules?',
          'Static Import uses the ES2015 `import` keyword to bring in code from another module. These imports are bundled at build time and included in the initial JavaScript bundle, meaning they are executed as soon as the module is loaded.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'No explanation provided.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-57","original_type":"mcq","topic":"General Design Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '662bfd3c-b6a1-419e-a401-5d56a8219b72',
          'How does static import affect bundle size and performance?',
          'All statically imported modules are bundled into the main JavaScript file (e.g., `main.bundle.js` in Webpack). Larger bundles can slow down initial page load, since the browser must download, parse, and execute everything before rendering the UI.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Static imports increase bundle size since everything is loaded upfront. They can hurt performance by delaying time-to-interactive, especially on slow networks or devices. Using too many static imports for rarely used components leads to wasted resources.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-58","original_type":"open-ended","topic":"General Design Patterns","subcategory":"","sample_answers":["Static imports increase bundle size since everything is loaded upfront.","They can hurt performance by delaying time-to-interactive, especially on slow networks or devices.","Using too many static imports for rarely used components leads to wasted resources."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f0b090a7-34d9-45f5-97a8-0d1b2d83dae4',
          'In the chat app example, which components were statically imported?',
          'In the given example, the `App` component statically imports `UserInfo`, `ChatList`, and `ChatInput`. The `ChatInput` component itself statically imports `EmojiPicker`.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'No explanation provided.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-59","original_type":"mcq","topic":"General Design Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5e019e58-f251-4ebe-911b-5f5564876065',
          'What is the main drawback of using only static imports in a React app?',
          'If every component and dependency is statically imported, the initial bundle can become very large. This delays rendering since the browser must download and parse all modules before showing any content.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Slower initial load due to larger bundle size. Worse performance on mobile or slow networks. Even components not immediately needed are still loaded upfront.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-60","original_type":"open-ended","topic":"General Design Patterns","subcategory":"","sample_answers":["Slower initial load due to larger bundle size.","Worse performance on mobile or slow networks.","Even components not immediately needed are still loaded upfront."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'efd687d8-3ead-4547-a331-0ec55f47263d',
          'How does Webpack handle static imports?',
          'Webpack bundles all statically imported modules into the main bundle file. For example, `main.bundle.js` might include every statically imported component from the source code.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'No explanation provided.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-61","original_type":"mcq","topic":"General Design Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3f6d621e-0c07-4e51-98a5-d1a492cca4a0',
          'When should you avoid static imports?',
          'Avoid static imports for components that are not immediately necessary on page load, such as modals, tooltips, or rarely used features. Instead, load them dynamically to improve performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'When the component is behind a user action (e.g., clicking a button). When the component is not critical for the initial render. When optimizing for smaller bundle sizes and faster loads.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-62","original_type":"open-ended","topic":"General Design Patterns","subcategory":"","sample_answers":["When the component is behind a user action (e.g., clicking a button).","When the component is not critical for the initial render.","When optimizing for smaller bundle sizes and faster loads."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9b971376-1151-4774-a200-979638b5b138',
          'Compare Static Import vs Dynamic Import.',
          'Static import loads all modules upfront at build time, increasing initial bundle size. Dynamic import (`import()`) loads modules only when needed (e.g., on user interaction), improving load performance but adding runtime overhead.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Static imports are eager, dynamic imports are lazy. Static imports bundle everything, dynamic imports support code-splitting. Static imports run immediately, dynamic imports return a promise.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-63","original_type":"open-ended","topic":"General Design Patterns","subcategory":"","sample_answers":["Static imports are eager, dynamic imports are lazy.","Static imports bundle everything, dynamic imports support code-splitting.","Static imports run immediately, dynamic imports return a promise."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8e6dc39d-d1be-41d9-a44c-629b999e7405',
          'What performance optimization can replace some static imports in the chat app example?',
          'Instead of statically importing the `EmojiPicker`, we can dynamically import it when the user opens the emoji panel. This reduces initial bundle size and speeds up app load.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'No explanation provided.',
          NULL,
          [],
          ARRAY['design-patterns','general-design-patterns','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"design-patterns-static-import-64","original_type":"mcq","topic":"General Design Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Design Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T00:47:17.209Z',
          '2025-10-15T00:47:17.209Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fc79ec31-b908-4cd7-82dd-4093aa6dca4f',
          'What does HTML stand for?',
          'Explain the full form of HTML and its purpose.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'HTML stands for HyperText Markup Language. It is used to structure content on the web using elements and tags.',
          NULL,
          [],
          ARRAY['html','html-basics','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html1","original_type":"open-ended","topic":"HTML Basics","subcategory":"","sample_answers":["HTML stands for HyperText Markup Language. It is used to structure content on the web using elements and tags."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.814Z',
          '2025-10-15T03:53:54.815Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6c65cd3a-5cb2-42f7-a185-be65036d34c0',
          'What is the purpose of the <!DOCTYPE html> declaration?',
          'Explain why <!DOCTYPE html> is important in an HTML document.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The <!DOCTYPE html> declaration tells the browser to render the page in standards mode using HTML5 syntax.',
          NULL,
          [],
          ARRAY['html','html-structure','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html2","original_type":"open-ended","topic":"HTML Structure","subcategory":"","sample_answers":["The <!DOCTYPE html> declaration tells the browser to render the page in standards mode using HTML5 syntax."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '38f11e5f-c2ae-4f8d-9a8f-6768bd9513a0',
          'True or False: All HTML elements must have a closing tag.',
          'Evaluate whether all HTML elements require closing tags.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['html','html-syntax','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html3","original_type":"true-false","topic":"HTML Syntax","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'da7107d9-d067-4d76-8436-962b260561aa',
          'What is the difference between block-level and inline elements?',
          'Explain how block-level and inline elements behave differently in HTML.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Block-level elements (like <div>, <p>, <h1>) start on a new line and take full width. Inline elements (like <span>, <a>, <strong>) flow within text and do not start on a new line.',
          NULL,
          [],
          ARRAY['html','html-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html4","original_type":"open-ended","topic":"HTML Elements","subcategory":"","sample_answers":["Block-level elements (like <div>, <p>, <h1>) start on a new line and take full width. Inline elements (like <span>, <a>, <strong>) flow within text and do not start on a new line."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5df809b7-353b-48c3-b2db-623f341ccfc9',
          'Which semantic HTML elements are commonly used for page structure?',
          'Name the main semantic elements in HTML5 for structuring content.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"<header>, <main>, <footer>, <section>, <article>, <nav>","isCorrect":true,"explanation":""},{"id":"o2","text":"<div>, <span>, <p>, <b>, <i>","isCorrect":false,"explanation":""}]',
          NULL,
          'HTML5 semantic elements provide meaning and improve accessibility and SEO.',
          NULL,
          [],
          ARRAY['html','html5-semantics','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html5","original_type":"multiple-choice","topic":"HTML5 Semantics","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ad69117a-77a0-488a-9af8-a7e3512776c0',
          'What is the difference between an <id> and a <class> attribute?',
          'Explain when to use id and class in HTML elements.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The id attribute is unique within a page and used to identify a single element. The class attribute can be shared among multiple elements and is used for styling or scripting multiple elements at once.',
          NULL,
          [],
          ARRAY['html','html-attributes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html6","original_type":"open-ended","topic":"HTML Attributes","subcategory":"","sample_answers":["The id attribute is unique within a page and used to identify a single element. The class attribute can be shared among multiple elements and is used for styling or scripting multiple elements at once."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '855adc09-b498-49aa-9600-d141e593cca1',
          'How do you create a hyperlink in HTML?',
          'Provide the syntax to create a link to https://example.com.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<a href="https://example.com">Visit Example</a>',
          NULL,
          [],
          ARRAY['html','html-links','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html7","original_type":"open-ended","topic":"HTML Links","subcategory":"","sample_answers":["<a href=\"https://example.com\">Visit Example</a>"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6c95bcb7-2640-4769-b26d-abef43f6ee18',
          'What is the purpose of the alt attribute on <img> tags?',
          'Explain why the alt attribute is important for images.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The alt attribute provides alternative text for images, which is used by screen readers for accessibility and displayed if the image fails to load.',
          NULL,
          [],
          ARRAY['html','html-accessibility','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html8","original_type":"open-ended","topic":"HTML Accessibility","subcategory":"","sample_answers":["The alt attribute provides alternative text for images, which is used by screen readers for accessibility and displayed if the image fails to load."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1c7b672c-0d00-4607-9ba6-e834118c88a9',
          'Name three HTML form input types and their purpose.',
          'List three different <input> types and when they are used.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<input type="text"> for single-line text input, <input type="email"> for email input with validation, <input type="password"> for password entry masking.',
          NULL,
          [],
          ARRAY['html','html-forms','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html9","original_type":"open-ended","topic":"HTML Forms","subcategory":"","sample_answers":["<input type=\"text\"> for single-line text input, <input type=\"email\"> for email input with validation, <input type=\"password\"> for password entry masking."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e8588fe0-b921-4592-ab12-2af9d7067055',
          'What is the difference between <div> and <span>?',
          'Explain when to use <div> and when to use <span>.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<div> is a block-level element used for grouping content and layout, while <span> is an inline element used to style or wrap a portion of text inside other elements.',
          NULL,
          [],
          ARRAY['html','html-elements','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-01-html10","original_type":"open-ended","topic":"HTML Elements","subcategory":"","sample_answers":["<div> is a block-level element used for grouping content and layout, while <span> is an inline element used to style or wrap a portion of text inside other elements."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '478c3890-bf34-46f2-b1da-bb9d28905222',
          'What are the differences between <ul>, <ol>, and <li>?',
          'Explain the purpose of unordered and ordered lists in HTML.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<ul> is an unordered list with bullets, <ol> is an ordered list with numbers, and <li> represents each list item inside them.',
          NULL,
          [],
          ARRAY['html','html-lists','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html11","original_type":"open-ended","topic":"HTML Lists","subcategory":"","sample_answers":["<ul> is an unordered list with bullets, <ol> is an ordered list with numbers, and <li> represents each list item inside them."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '37eedac5-8dfe-46cd-a927-dea08c46689c',
          'What are semantic tags and why are they important?',
          'Give examples of semantic tags and explain their role.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Semantic tags like <header>, <footer>, <main>, <article>, and <section> give meaning to the content, improving accessibility, SEO, and code readability.',
          NULL,
          [],
          ARRAY['html','semantic-html','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html12","original_type":"open-ended","topic":"Semantic HTML","subcategory":"","sample_answers":["Semantic tags like <header>, <footer>, <main>, <article>, and <section> give meaning to the content, improving accessibility, SEO, and code readability."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1e57c9a2-265c-40f3-af0d-3cc84f7b73b7',
          'How do you embed a video in HTML?',
          'Provide an example of embedding a video with controls.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<video controls>
  <source src="video.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>',
          NULL,
          [],
          ARRAY['html','html-video','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html13","original_type":"open-ended","topic":"HTML Video","subcategory":"","sample_answers":["<video controls>\n  <source src=\"video.mp4\" type=\"video/mp4\">\n  Your browser does not support the video tag.\n</video>"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '974ebd8b-65f8-485c-948f-b6fe3ae69eb6',
          'Explain the use of <canvas> in HTML5.',
          'What is the <canvas> element used for?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<canvas> is used to draw graphics via JavaScript, allowing dynamic rendering of shapes, charts, animations, and games directly in the browser.',
          NULL,
          [],
          ARRAY['html','html5-apis','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html14","original_type":"open-ended","topic":"HTML5 APIs","subcategory":"","sample_answers":["<canvas> is used to draw graphics via JavaScript, allowing dynamic rendering of shapes, charts, animations, and games directly in the browser."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0b4c3ced-92de-4afa-9a1a-c5506386d806',
          'How do you create a table in HTML?',
          'List the main tags used in HTML tables.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<table> defines a table, <tr> defines a table row, <th> defines a table header cell, and <td> defines a table data cell.',
          NULL,
          [],
          ARRAY['html','html-tables','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html15","original_type":"open-ended","topic":"HTML Tables","subcategory":"","sample_answers":["<table> defines a table, <tr> defines a table row, <th> defines a table header cell, and <td> defines a table data cell."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '41ebedf7-0e40-4596-a3a0-abfcb6c1f04e',
          'Explain the use of <iframe> in HTML.',
          'How do you embed external content using <iframe>?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<iframe src="https://example.com" width="600" height="400" title="Example"></iframe> embeds an external webpage or media inside the current page.',
          NULL,
          [],
          ARRAY['html','html-iframes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html16","original_type":"open-ended","topic":"HTML Iframes","subcategory":"","sample_answers":["<iframe src=\"https://example.com\" width=\"600\" height=\"400\" title=\"Example\"></iframe> embeds an external webpage or media inside the current page."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '14a9851d-f93d-4026-a52e-867b75ee4f6b',
          'What are the differences between local and global anchors in HTML?',
          'Explain #id anchors and normal hyperlinks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'A local anchor links to an element on the same page using <a href="#section1">, while a global hyperlink links to a different page or site using <a href="https://example.com">.',
          NULL,
          [],
          ARRAY['html','html-anchors','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html17","original_type":"open-ended","topic":"HTML Anchors","subcategory":"","sample_answers":["A local anchor links to an element on the same page using <a href=\"#section1\">, while a global hyperlink links to a different page or site using <a href=\"https://example.com\">."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8287d5a6-4e70-41ce-b797-27c0aad56018',
          'What is the role of the <meta> tag?',
          'Explain at least two uses of meta tags in HTML.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<meta charset="UTF-8"> sets character encoding, <meta name="description" content="..."> provides page description for SEO, and <meta name="viewport" content="width=device-width, initial-scale=1.0"> helps with responsive design.',
          NULL,
          [],
          ARRAY['html','html-meta-tags','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html18","original_type":"open-ended","topic":"HTML Meta Tags","subcategory":"","sample_answers":["<meta charset=\"UTF-8\"> sets character encoding, <meta name=\"description\" content=\"...\"> provides page description for SEO, and <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> helps with responsive design."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '141fb93f-4692-4c8e-9915-4c2f400244f0',
          'How do you make a form accessible?',
          'Name at least three practices for making forms accessible.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Use <label> for every input, associate inputs with id, provide aria-* attributes when needed, ensure proper tab order, and add clear error messages.',
          NULL,
          [],
          ARRAY['html','accessibility','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html19","original_type":"open-ended","topic":"Accessibility","subcategory":"","sample_answers":["Use <label> for every input, associate inputs with id, provide aria-* attributes when needed, ensure proper tab order, and add clear error messages."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cfe21a95-c0b1-4c90-a153-535ea41a9ff0',
          'What is the difference between <section> and <div>?',
          'Explain when to use semantic <section> vs generic <div>.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<section> is semantic and should represent a standalone section of content with a heading, while <div> is generic and used only for layout or grouping.',
          NULL,
          [],
          ARRAY['html','html5-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html20","original_type":"open-ended","topic":"HTML5 Elements","subcategory":"","sample_answers":["<section> is semantic and should represent a standalone section of content with a heading, while <div> is generic and used only for layout or grouping."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2b6278d0-98d1-4371-baa3-fdabb5e2da6a',
          'Explain the difference between the <b> and <strong> tags.',
          'When should you use <strong> instead of <b>?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<b> applies only visual bold styling, while <strong> adds semantic importance for accessibility and SEO.',
          NULL,
          [],
          ARRAY['html','html-text-styling','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html21","original_type":"open-ended","topic":"HTML Text Styling","subcategory":"","sample_answers":["<b> applies only visual bold styling, while <strong> adds semantic importance for accessibility and SEO."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bda74a64-7934-4e23-ad00-1c96c63ec333',
          'What is the difference between <input type="text"> and <textarea>?',
          'Explain the differences in usage between single-line and multi-line text input.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<input type="text"> is for single-line text, <textarea> allows multi-line text input with resizable area.',
          NULL,
          [],
          ARRAY['html','html-forms','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html22","original_type":"open-ended","topic":"HTML Forms","subcategory":"","sample_answers":["<input type=\"text\"> is for single-line text, <textarea> allows multi-line text input with resizable area."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '92f258f7-9776-47f4-b5fb-3c27b0661b90',
          'What is the difference between <script> in head and body?',
          'Explain how script placement affects loading and rendering.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Scripts in the <head> block rendering unless marked async/defer, while scripts at the end of <body> load after content is parsed, improving perceived performance.',
          NULL,
          [],
          ARRAY['html','html-scripts','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html23","original_type":"open-ended","topic":"HTML Scripts","subcategory":"","sample_answers":["Scripts in the <head> block rendering unless marked async/defer, while scripts at the end of <body> load after content is parsed, improving perceived performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '77be607c-5c28-4675-a03c-254649b33389',
          'Explain the use of the <link> tag.',
          'Provide at least two uses of <link> in HTML.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<link rel="stylesheet" href="styles.css"> links a CSS file, <link rel="icon" href="favicon.ico"> sets the page icon.',
          NULL,
          [],
          ARRAY['html','html-link','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html24","original_type":"open-ended","topic":"HTML Link","subcategory":"","sample_answers":["<link rel=\"stylesheet\" href=\"styles.css\"> links a CSS file, <link rel=\"icon\" href=\"favicon.ico\"> sets the page icon."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.816Z',
          '2025-10-15T03:53:54.816Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '897f5999-5d53-4e45-9bb4-d748fa20dbce',
          'What is the difference between <audio controls> and <audio autoplay>?',
          'Explain how attributes affect audio playback in HTML.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<audio controls> shows playback controls and waits for user interaction, <audio autoplay> starts playing automatically when the page loads.',
          NULL,
          [],
          ARRAY['html','html-audio','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-02-html25","original_type":"open-ended","topic":"HTML Audio","subcategory":"","sample_answers":["<audio controls> shows playback controls and waits for user interaction, <audio autoplay> starts playing automatically when the page loads."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c6c40ea2-9a70-4a19-8795-a84ec1f0e4cf',
          'What is the purpose of the <picture> element?',
          'Explain how <picture> can be used to serve different images for different screen sizes.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<picture> allows multiple <source> elements with media queries or type attributes, letting the browser choose the best image based on device resolution or format.',
          NULL,
          [],
          ARRAY['html','responsive-images','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html26","original_type":"open-ended","topic":"Responsive Images","subcategory":"","sample_answers":["<picture> allows multiple <source> elements with media queries or type attributes, letting the browser choose the best image based on device resolution or format."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a8a2e62c-241d-4e39-9693-bcec70cc19f8',
          'What is the difference between <figure> and <figcaption>?',
          'Explain how <figure> and <figcaption> work together.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<figure> wraps content like images, charts, or diagrams; <figcaption> provides a caption for that content. Together, they semantically describe media.',
          NULL,
          [],
          ARRAY['html','html5-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html27","original_type":"open-ended","topic":"HTML5 Elements","subcategory":"","sample_answers":["<figure> wraps content like images, charts, or diagrams; <figcaption> provides a caption for that content. Together, they semantically describe media."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '220183ca-5042-4270-b35c-b8d72e931899',
          'Explain the difference between <mark> and <em>.',
          'When should you use <mark> instead of <em>?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<mark> highlights text for reference or search relevance, <em> emphasizes text semantically, usually changing voice or importance for accessibility.',
          NULL,
          [],
          ARRAY['html','html-text-styling','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html28","original_type":"open-ended","topic":"HTML Text Styling","subcategory":"","sample_answers":["<mark> highlights text for reference or search relevance, <em> emphasizes text semantically, usually changing voice or importance for accessibility."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1b25bf20-4222-440e-8084-37e0a5b289aa',
          'What are data-* attributes in HTML?',
          'Explain their purpose and how to access them via JavaScript.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'data-* attributes store custom data on elements. Access in JS via element.dataset.key. Example: <div data-user-id=''123''> and JS: element.dataset.userId.',
          NULL,
          [],
          ARRAY['html','html-custom-attributes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html29","original_type":"open-ended","topic":"HTML Custom Attributes","subcategory":"","sample_answers":["data-* attributes store custom data on elements. Access in JS via element.dataset.key. Example: <div data-user-id=''123''> and JS: element.dataset.userId."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f872ff14-22ba-453d-b249-ed93e33ef99f',
          'Explain the difference between <nav> and <header>.',
          'When should each be used in HTML5?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<header> defines introductory content or a site header, <nav> contains navigation links. Header can have nav inside it.',
          NULL,
          [],
          ARRAY['html','html5-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html30","original_type":"open-ended","topic":"HTML5 Elements","subcategory":"","sample_answers":["<header> defines introductory content or a site header, <nav> contains navigation links. Header can have nav inside it."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '65e28827-6002-49ed-b78c-e569c8a49910',
          'How do you use the <details> and <summary> elements?',
          'Explain with an example how users can toggle content visibility.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<details>
  <summary>Click to expand</summary>
  <p>Hidden content</p>
</details> allows toggling visibility of content without JavaScript.',
          NULL,
          [],
          ARRAY['html','html5-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html31","original_type":"open-ended","topic":"HTML5 Elements","subcategory":"","sample_answers":["<details>\n  <summary>Click to expand</summary>\n  <p>Hidden content</p>\n</details> allows toggling visibility of content without JavaScript."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cb406366-ec3f-4e81-aff8-acc438c9c647',
          'Explain the use of the <progress> element.',
          'How is <progress> different from <meter>?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<progress> shows task completion progress, <meter> represents a scalar measurement like disk usage. Both provide semantic feedback to users.',
          NULL,
          [],
          ARRAY['html','html5-forms','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html32","original_type":"open-ended","topic":"HTML5 Forms","subcategory":"","sample_answers":["<progress> shows task completion progress, <meter> represents a scalar measurement like disk usage. Both provide semantic feedback to users."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '57ae2211-03f0-4a22-b19a-fe95ae1590c8',
          'How does the <template> element work?',
          'Explain its use and why it doesn''t render content immediately.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<template> holds HTML that isn''t rendered immediately. JS can clone its content and insert it into the DOM dynamically for efficient rendering.',
          NULL,
          [],
          ARRAY['html','html-templates','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html33","original_type":"open-ended","topic":"HTML Templates","subcategory":"","sample_answers":["<template> holds HTML that isn''t rendered immediately. JS can clone its content and insert it into the DOM dynamically for efficient rendering."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1e62feb0-86cc-44d5-8836-48285916b676',
          'What are ARIA roles in HTML?',
          'How do ARIA attributes improve accessibility?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'ARIA roles like role=''button'' or aria-label provide semantic meaning to assistive technologies, improving accessibility for screen readers.',
          NULL,
          [],
          ARRAY['html','accessibility','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html34","original_type":"open-ended","topic":"Accessibility","subcategory":"","sample_answers":["ARIA roles like role=''button'' or aria-label provide semantic meaning to assistive technologies, improving accessibility for screen readers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd230d6af-a8e6-49e2-9cbb-5434a3695844',
          'What is the difference between <base> and <link> tags?',
          'Explain how <base> affects relative URLs.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<base href=''https://example.com/''> sets a base URL for relative links, affecting <a>, <img>, <script> paths, while <link> attaches resources like CSS or favicon.',
          NULL,
          [],
          ARRAY['html','html-head','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html35","original_type":"open-ended","topic":"HTML Head","subcategory":"","sample_answers":["<base href=''https://example.com/''> sets a base URL for relative links, affecting <a>, <img>, <script> paths, while <link> attaches resources like CSS or favicon."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f90060ed-9571-456c-a5e0-67caaa8c862a',
          'Explain the use of <slot> in Web Components.',
          'How does <slot> enable content projection?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<slot> acts as a placeholder in a Web Component. The parent can inject custom content into it, enabling flexible content composition.',
          NULL,
          [],
          ARRAY['html','web-components','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html36","original_type":"open-ended","topic":"Web Components","subcategory":"","sample_answers":["<slot> acts as a placeholder in a Web Component. The parent can inject custom content into it, enabling flexible content composition."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e3707798-c4c4-44f0-aeb5-4e1a5bb85a94',
          'What is the difference between <bdo> and <dir>?',
          'Explain how <bdo> changes text direction and what <dir> does historically.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<bdo dir=''rtl''> forces text direction, <dir> was used for directories (deprecated). Use <ul> for modern lists instead of <dir>.',
          NULL,
          [],
          ARRAY['html','html-text','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html37","original_type":"open-ended","topic":"HTML Text","subcategory":"","sample_answers":["<bdo dir=''rtl''> forces text direction, <dir> was used for directories (deprecated). Use <ul> for modern lists instead of <dir>."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'efe09906-e3ce-4eeb-99e3-255922b8910f',
          'How can you lazy-load images in HTML5?',
          'Explain the ''loading'' attribute for images.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<img src=''image.jpg'' loading=''lazy'' alt=''Description''> delays loading images until they are about to enter the viewport, improving page performance.',
          NULL,
          [],
          ARRAY['html','html-images','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html38","original_type":"open-ended","topic":"HTML Images","subcategory":"","sample_answers":["<img src=''image.jpg'' loading=''lazy'' alt=''Description''> delays loading images until they are about to enter the viewport, improving page performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '44405b90-2244-4166-8253-59fdff5826d9',
          'Explain the difference between <main> and <article>.',
          'When should each be used in HTML5?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<main> represents the primary content of a page, <article> represents a self-contained piece of content that could be reused independently (e.g., blog post).',
          NULL,
          [],
          ARRAY['html','html5-elements','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html39","original_type":"open-ended","topic":"HTML5 Elements","subcategory":"","sample_answers":["<main> represents the primary content of a page, <article> represents a self-contained piece of content that could be reused independently (e.g., blog post)."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e647f19d-b94f-4648-abbc-13a55a7c967d',
          'What is the difference between <output> and <progress>?',
          'Explain the semantic use cases for <output> vs <progress> in forms.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<output> displays the result of a calculation or user action, <progress> shows task completion progress. Output is for dynamic content, progress is for status indication.',
          NULL,
          [],
          ARRAY['html','html5-forms','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-03-html40","original_type":"open-ended","topic":"HTML5 Forms","subcategory":"","sample_answers":["<output> displays the result of a calculation or user action, <progress> shows task completion progress. Output is for dynamic content, progress is for status indication."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.817Z',
          '2025-10-15T03:53:54.817Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5ccd15a3-09a4-4ab3-8a30-541da7aafbe0',
          'What is the purpose of the <canvas> element?',
          'Explain how <canvas> can be used for rendering graphics on the fly.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '<canvas> provides a drawable region in HTML. Using JS, you can draw shapes, images, or animations dynamically on the client-side.',
          NULL,
          [],
          ARRAY['html','canvas','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"html-04-html41","original_type":"open-ended","topic":"Canvas","subcategory":"","sample_answers":["<canvas> provides a drawable region in HTML. Using JS, you can draw shapes, images, or animations dynamically on the client-side."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"HTML"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-15T03:53:54.818Z',
          '2025-10-15T03:53:54.818Z'
        );;