INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '305c5528-ed2e-4bd1-9c30-18e304ee8446',
          'What is the difference between `next/image` and `next/future/image`?',
          '`next/future/image` was an experimental version in Next.js 12. It’s now stable and available as `next/image` in Next.js 13+.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'As of Next.js 13, `next/image` is the stable, recommended component.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-21-40-nextjs-q37","original_type":"true-false","topic":"Image Optimization","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '69c79e04-d9b3-4764-8b6f-4a3e12ccc83a',
          'How do you deploy a Next.js app?',
          'Deploy to Vercel (official platform), Netlify, AWS, or any Node.js-compatible host. Vercel provides automatic SSR/SSG, edge functions, and preview deployments.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Vercel is optimized for Next.js with zero-config deployments and Git integration.',
          NULL,
          [],
          ARRAY['nextjs','deployment-on-vercel','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-21-40-nextjs-q38","original_type":"open-ended","topic":"Deployment on Vercel","subcategory":"","sample_answers":["Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.","For self-hosting, run `next build` and `next start` on a Node.js server—but you lose edge functions and ISR."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ef8a7910-e025-42eb-bc29-fa57734a76ad',
          'What is EAS in the context of Expo?',
          'EAS (Expo Application Services) is a cloud platform for building, submitting, and updating Expo apps without local Xcode/Android Studio.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'EAS Build compiles apps in the cloud; EAS Submit sends them to app stores; EAS Update pushes JS updates over the air.',
          NULL,
          [],
          ARRAY['nextjs','expo','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-21-40-nextjs-q39","original_type":"open-ended","topic":"Expo","subcategory":"","sample_answers":["EAS replaces `expo build` with cloud-based builds, enabling custom native code without local setup.","It offers services like build automation, app store submission, and OTA updates with rollback."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f808f843-1fd2-417b-80bd-acab9965549a',
          'How does Expo differ from standard React Native?',
          'Expo is a framework and platform built on React Native that provides a managed workflow with prebuilt native modules and cloud services.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Expo: managed workflow, prebuilt modules, cloud services; React Native: bare workflow, full native control","isCorrect":true,"explanation":""},{"id":"b","text":"Expo doesn’t support custom native code","isCorrect":false,"explanation":""},{"id":"c","text":"React Native is only for iOS","isCorrect":false,"explanation":""},{"id":"d","text":"Expo is deprecated","isCorrect":false,"explanation":""}]',
          NULL,
          'Expo simplifies development with a curated set of APIs; EAS enables custom native code when needed.',
          NULL,
          [],
          ARRAY['nextjs','expo','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-21-40-nextjs-q40","original_type":"multiple-choice","topic":"Expo","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '05251cd5-c5d8-4bce-8492-7d2dfa037003',
          'What is the purpose of next/image in Next.js?',
          '`next/image` is an extension of the HTML `<img>` element that provides automatic image optimization, including resizing, format conversion (WebP/AVIF), and lazy loading.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It reduces bandwidth, improves LCP, prevents layout shift, and integrates with CDNs like Vercel or Imgix.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q61","original_type":"open-ended","topic":"Image Optimization","subcategory":"","sample_answers":["`next/image` automatically serves modern formats like WebP, resizes based on device, and lazy-loads offscreen images—no config needed.","It requires a parent with defined width/height or uses `fill` mode for responsive containers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6406341d-ca27-414e-9fd9-c23b53642d77',
          'How do you handle environment variables in Next.js?',
          'Prefix with `NEXT_PUBLIC_` to expose to the browser; others are server-only. Load from `.env.local`.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
          NULL,
          [],
          ARRAY['nextjs','environment-variables','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q62","original_type":"open-ended","topic":"Environment Variables","subcategory":"","sample_answers":["`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","Use `.env.local` for local development; Vercel lets you set env vars in the project dashboard."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '27ef600a-495c-4013-8ede-d5e0a8f234d2',
          'What is the difference between SSG and SSR in Next.js?',
          'SSG (Static Site Generation) renders pages at build time. SSR (Server-Side Rendering) renders on every request.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"SSG: build-time render; SSR: per-request render","isCorrect":true,"explanation":""},{"id":"b","text":"SSR is always faster than SSG","isCorrect":false,"explanation":""},{"id":"c","text":"SSG doesn’t support dynamic data","isCorrect":false,"explanation":""},{"id":"d","text":"They are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'SSG is faster and cacheable; SSR is for dynamic, user-specific content.',
          NULL,
          [],
          ARRAY['nextjs','ssg-vs-ssr','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q63","original_type":"multiple-choice","topic":"SSG vs SSR","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '57273a13-8562-4f53-934b-84fdad59ce1e',
          'What is ISR (Incremental Static Regeneration)?',
          'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'With `revalidate`, Next.js regenerates pages in the background when traffic hits them.',
          NULL,
          [],
          ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q64","original_type":"open-ended","topic":"Incremental Static Regeneration","subcategory":"","sample_answers":["ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","It’s perfect for blogs, e-commerce, or dashboards where content changes periodically but doesn’t need real-time updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '16c07aa8-17f4-46dc-a6bc-29ccc943e567',
          'How do you implement layouts in Next.js?',
          'In App Router, use `layout.js` files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'App Router’s `layout.js` is the modern, built-in way to share UI across routes.',
          NULL,
          [],
          ARRAY['nextjs','layouts','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q65","original_type":"open-ended","topic":"Layouts","subcategory":"","sample_answers":["In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","Pages Router requires manual layout composition via component wrappers or context."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bd7e8994-aef6-4dc6-a2c3-ea2e4661019b',
          'What is the purpose of the ''use client'' directive?',
          '`''use client''` marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By default, all components in App Router are Server Components. Use `''use client''` only when needed for interactivity.',
          NULL,
          [],
          ARRAY['nextjs','client-components','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q66","original_type":"open-ended","topic":"Client Components","subcategory":"","sample_answers":["`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","It should be used sparingly to keep bundles small and leverage Server Components for data fetching."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd786c7f4-7bdd-4937-9b27-ff52978628da',
          'How do you handle loading states in the App Router?',
          'Use the `loading.js` file in a route segment to show a loading UI while data is being fetched. It works with React Suspense.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '`loading.js` provides an instant loading UI without client-side JavaScript, improving perceived performance.',
          NULL,
          [],
          ARRAY['nextjs','loading-states','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q67","original_type":"open-ended","topic":"Loading States","subcategory":"","sample_answers":["Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.","This is built on React Suspense—no need for `useState` or `useEffect` to manage loading states manually."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '14340ee7-2358-48d7-b107-19c656ac41e1',
          'What is the purpose of error.js in the App Router?',
          'The `error.js` file defines an error boundary for a route segment, catching errors in Server and Client Components and displaying a fallback UI.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It uses React error boundaries under the hood and can be reset with the `error.reset()` function.',
          NULL,
          [],
          ARRAY['nextjs','error-handling','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q68","original_type":"open-ended","topic":"Error Handling","subcategory":"","sample_answers":["`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.","Unlike Pages Router, error boundaries are file-based and automatically scoped to the route."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ed9ef9a1-0839-42f2-aa3e-c950ab0537eb',
          'How do you implement nested layouts in Next.js App Router?',
          'Create `layout.js` files in nested folders. Each layout wraps its child routes, enabling persistent UI like headers and sidebars.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance.',
          NULL,
          [],
          ARRAY['nextjs','layouts','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q69","original_type":"open-ended","topic":"Layouts","subcategory":"","sample_answers":["In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.","Layouts can be nested: `app/layout.js` → `app/dashboard/layout.js` → `app/dashboard/settings/page.js`."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bef930e6-60f9-47d6-95ce-17071cd7f146',
          'What is the difference between `generateStaticParams` and `getStaticPaths`?',
          '`generateStaticParams` is used in App Router for dynamic routes with SSG. `getStaticPaths` is the Pages Router equivalent.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"`generateStaticParams`: App Router; `getStaticPaths`: Pages Router","isCorrect":true,"explanation":""},{"id":"b","text":"They are the same function","isCorrect":false,"explanation":""},{"id":"c","text":"`getStaticPaths` works in App Router","isCorrect":false,"explanation":""},{"id":"d","text":"`generateStaticParams` is for SSR","isCorrect":false,"explanation":""}]',
          NULL,
          'Both define which dynamic routes to pre-render at build time.',
          NULL,
          [],
          ARRAY['nextjs','static-site-generation-(ssg)','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q70","original_type":"multiple-choice","topic":"Static Site Generation (SSG)","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4c87ee29-c0b0-41ed-950a-802f589456e4',
          'How do you handle dynamic routes in the App Router?',
          'Use dynamic segments like `app/users/[id]/page.js`. Fetch data using `params.id` in the Server Component.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The `params` object is passed to `page.js`, `layout.js`, and other route handlers automatically.',
          NULL,
          [],
          ARRAY['nextjs','dynamic-routes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q71","original_type":"open-ended","topic":"Dynamic Routes","subcategory":"","sample_answers":["Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`","Use `generateStaticParams` to pre-render dynamic routes at build time for SSG."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e8cdc805-17d4-4db2-b9a0-b8339a67e840',
          'What is the purpose of the `not-found.js` file?',
          '`not-found.js` defines a custom 404 page for a route segment when `notFound()` is thrown or a route doesn’t exist.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It’s the App Router equivalent of `pages/404.js` but scoped to route segments.',
          NULL,
          [],
          ARRAY['nextjs','error-handling','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q72","original_type":"open-ended","topic":"Error Handling","subcategory":"","sample_answers":["Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.","Call `notFound()` from `next/navigation` in a Server Component to trigger it programmatically."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'aba790da-6189-40fd-be5a-ba7da7feec16',
          'How do you redirect in Next.js App Router?',
          'Use `redirect()` from `next/navigation` in Server Components, or `useRouter().push()` in Client Components.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '`redirect()` is for server-side redirects (e.g., auth checks); `useRouter` is for client-side navigation.',
          NULL,
          [],
          ARRAY['nextjs','redirects','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q73","original_type":"open-ended","topic":"Redirects","subcategory":"","sample_answers":["In a Server Component: `import { redirect } from ''next/navigation''; if (!user) redirect(''/login'');`","In a Client Component: `const router = useRouter(); router.push(''/dashboard'');`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b3038051-a798-47ec-ab1e-8470e60c00f6',
          'What is the `useRouter` hook used for?',
          '`useRouter` provides client-side navigation methods like `push`, `replace`, and `refresh` in Client Components.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Client-side navigation in Client Components","isCorrect":true,"explanation":""},{"id":"b","text":"Data fetching in Server Components","isCorrect":false,"explanation":""},{"id":"c","text":"Server-side redirects","isCorrect":false,"explanation":""},{"id":"d","text":"Only works in Pages Router","isCorrect":false,"explanation":""}]',
          NULL,
          'It’s the App Router equivalent of `next/router` but with the same API.',
          NULL,
          [],
          ARRAY['nextjs','client-side-navigation','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q74","original_type":"multiple-choice","topic":"Client-Side Navigation","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8c2ea072-a012-4f1b-bd8a-7ff0d81c66ce',
          'How does Next.js handle caching?',
          'Next.js extends `fetch()` with automatic caching, revalidation, and deduping. Use `cache`, `next.revalidate`, and `next.tags` options.',
          'multiple-choice',
          'advanced',
          9,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Caching is opt-in via `fetch` options, replacing `getStaticProps`/`getServerSideProps`.',
          NULL,
          [],
          ARRAY['nextjs','caching','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q75","original_type":"open-ended","topic":"Caching","subcategory":"","sample_answers":["`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.","Use `tags` for on-demand revalidation: `fetch(url, { next: { tags: [''posts''] } })` then `revalidateTag(''posts'')` in an API route."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '473ac931-cb85-48cf-b210-92c1f204121d',
          'What is on-demand revalidation in Next.js?',
          'On-demand revalidation allows you to purge cached data and regenerate pages after build time using `revalidateTag` or `revalidatePath`.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks.',
          NULL,
          [],
          ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q76","original_type":"open-ended","topic":"Incremental Static Regeneration","subcategory":"","sample_answers":["Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.","Useful for CMS webhooks, e-commerce inventory updates, or admin actions that require immediate content refresh."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1e368716-8f62-4259-aaa3-66989d16ae31',
          'How do you implement middleware in Next.js?',
          'Create a `middleware.js` file in the root or route segment. It runs before requests and can rewrite, redirect, or add headers.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Middleware is ideal for authentication, A/B testing, i18n, and bot protection.',
          NULL,
          [],
          ARRAY['nextjs','middleware','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q77","original_type":"open-ended","topic":"Middleware","subcategory":"","sample_answers":["```js\nexport { default } from ''next-auth/middleware'';\nexport const config = { matcher: [''/dashboard/:path*''] };\n```","Use `NextRequest` to inspect cookies, headers, or URL, then `NextResponse.rewrite()` or `redirect()` as needed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5b01ab11-685b-468c-97cf-2a103a860486',
          'What is the purpose of `next.config.js`?',
          '`next.config.js` customizes Next.js build settings like Webpack, Babel, environment variables, and experimental features.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Customize Webpack, Babel, env vars, and experimental features","isCorrect":true,"explanation":""},{"id":"b","text":"Required for every Next.js app","isCorrect":false,"explanation":""},{"id":"c","text":"Only for CSS configuration","isCorrect":false,"explanation":""},{"id":"d","text":"Replaces package.json","isCorrect":false,"explanation":""}]',
          NULL,
          'It’s optional but powerful for advanced customization without ejecting.',
          NULL,
          [],
          ARRAY['nextjs','next.js-configuration','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q78","original_type":"multiple-choice","topic":"Next.js Configuration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '48776cc2-8368-447b-b0bd-81acc68b63af',
          'How does Next.js optimize images?',
          'Next.js uses the `next/image` component to automatically optimize images (resize, compress, modern formats) and lazy-load them.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It reduces bandwidth, improves LCP, and prevents layout shift with automatic sizing.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q79","original_type":"open-ended","topic":"Image Optimization","subcategory":"","sample_answers":["`next/image` serves optimized WebP/AVIF, resizes based on device, and lazy-loads offscreen images—no config needed.","It integrates with CDNs and local file storage, and supports blur-up placeholders."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '23b52ea2-e61d-4278-8101-ecb438f3b819',
          'What is the difference between `next/image` and `next/future/image`?',
          '`next/future/image` was an experimental version in Next.js 12. It’s now stable and available as `next/image` in Next.js 13+.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'As of Next.js 13, `next/image` is the stable, recommended component.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next-61-80-nextjs-q80","original_type":"true-false","topic":"Image Optimization","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'abd36a65-201c-4466-b3d9-f4376d50e4a8',
          'What is Next.js?',
          'Next.js is a React framework for building full-stack web applications with features like server-side rendering (SSR), static site generation (SSG), file-based routing, and API routes.',
          'multiple-choice',
          'beginner',
          4,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Next.js simplifies React app development by providing built-in solutions for routing, data fetching, optimization, and deployment.',
          NULL,
          [],
          ARRAY['nextjs','next.js-basics','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q1","original_type":"open-ended","topic":"Next.js Basics","subcategory":"","sample_answers":["Next.js is a React framework that enables server-rendered, statically generated, and hybrid applications with zero config.","It provides features like file-based routing, API routes, image optimization, and middleware out of the box."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '93fa781f-620c-40cf-86c3-8f5321b5c2d1',
          'What are the main features of Next.js?',
          'Key features include: file-based routing, server-side rendering (SSR), static site generation (SSG), API routes, image optimization, automatic code splitting, and middleware.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"File-based routing, SSR/SSG, API routes, image optimization, middleware","isCorrect":true,"explanation":""},{"id":"b","text":"Only client-side rendering","isCorrect":false,"explanation":""},{"id":"c","text":"No built-in routing","isCorrect":false,"explanation":""},{"id":"d","text":"Requires manual Webpack configuration","isCorrect":false,"explanation":""}]',
          NULL,
          'These features enable full-stack development with optimized performance and SEO.',
          NULL,
          [],
          ARRAY['nextjs','next.js-basics','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q2","original_type":"multiple-choice","topic":"Next.js Basics","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ed86f930-93e7-41fe-96c1-1ef7ee03058a',
          'What is the difference between Pages Router and App Router in Next.js?',
          'Pages Router uses the `pages/` directory with client-side navigation. App Router uses the `app/` directory with React Server Components, nested layouts, and streaming.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'App Router is the modern architecture with server-first rendering, layouts, and better data fetching.',
          NULL,
          [],
          ARRAY['nextjs','app-router-vs-pages-router','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q3","original_type":"open-ended","topic":"App Router vs Pages Router","subcategory":"","sample_answers":["Pages Router: `pages/` directory, client-side navigation, no layouts. App Router: `app/` directory, React Server Components, nested layouts, and streaming support.","App Router enables partial rendering with Suspense and automatic code splitting by route."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ee506662-031b-4b60-bf9f-f99631f68bd1',
          'What are React Server Components in Next.js?',
          'React Server Components (RSC) run only on the server, can access databases directly, and send only JSON to the client—reducing JavaScript bundle size.',
          'multiple-choice',
          'advanced',
          9,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'RSCs enable zero-bundle-size components and direct backend access without API layers.',
          NULL,
          [],
          ARRAY['nextjs','react-server-components','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q4","original_type":"open-ended","topic":"React Server Components","subcategory":"","sample_answers":["Server Components run on the server, fetch data directly, and send serialized output to the client—no hydration needed.","They’re a core part of Next.js App Router, enabling highly optimized full-stack applications."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a7e37b44-28a5-4834-b23c-a49d5161314c',
          'How does Next.js handle routing?',
          'Next.js uses file-based routing: files in `pages/` or `app/` automatically become routes based on their path.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"File-based routing in pages/ or app/ directories","isCorrect":true,"explanation":""},{"id":"b","text":"Manual route configuration with React Router","isCorrect":false,"explanation":""},{"id":"c","text":"Only hash-based routing","isCorrect":false,"explanation":""},{"id":"d","text":"Routing requires server setup","isCorrect":false,"explanation":""}]',
          NULL,
          'No manual route configuration is needed—just create files in the correct directory structure.',
          NULL,
          [],
          ARRAY['nextjs','next.js-routing','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q5","original_type":"multiple-choice","topic":"Next.js Routing","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b853206e-246f-43f0-a44f-23879da82e30',
          'What is getStaticProps in Next.js?',
          '`getStaticProps` is a Pages Router function that fetches data at build time for static generation (SSG).',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It runs only at build time and returns props to the page component.',
          NULL,
          [],
          ARRAY['nextjs','static-site-generation-(ssg)','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q6","original_type":"open-ended","topic":"Static Site Generation (SSG)","subcategory":"","sample_answers":["`getStaticProps` fetches data during build and generates static HTML. It’s ideal for content that doesn’t change often, like blogs or docs.","It only works in the `pages/` directory and cannot be used in the App Router."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '99014aab-f641-4108-8e96-5d3ba4e2d238',
          'What is getServerSideProps in Next.js?',
          '`getServerSideProps` fetches data on every request for server-side rendering (SSR).',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It runs on the server for every request, making it suitable for frequently changing or user-specific data.',
          NULL,
          [],
          ARRAY['nextjs','server-side-rendering-(ssr)','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q7","original_type":"open-ended","topic":"Server-Side Rendering (SSR)","subcategory":"","sample_answers":["`getServerSideProps` renders pages on the server per request—ideal for dashboards, real-time data, or authenticated views.","Like `getStaticProps`, it’s only available in the Pages Router (`pages/` directory)."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '78075ad6-ade6-4b22-b802-1f98acf69389',
          'How do you fetch data in the App Router?',
          'In App Router, fetch data directly in Server Components using `async` components and the native `fetch()` API with automatic deduping and streaming.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Next.js extends `fetch()` with caching, revalidation, and deduping—no need for `getStaticProps` or `getServerSideProps`.',
          NULL,
          [],
          ARRAY['nextjs','app-router-data-fetching','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q8","original_type":"open-ended","topic":"App Router Data Fetching","subcategory":"","sample_answers":["Write async Server Components that call `fetch()` directly. Next.js handles caching and deduping automatically.","Example: `async function Page() { const res = await fetch(''...''); const data = await res.json(); return <div>{data.title}</div>; }`"],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e3e3bde2-ae27-4c04-8972-73e10c0c68a1',
          'What are API routes in Next.js?',
          'API routes allow you to create serverless API endpoints inside the `pages/api` directory (Pages Router) or `app/api` (App Router).',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Serverless functions in pages/api or app/api that handle HTTP requests","isCorrect":true,"explanation":""},{"id":"b","text":"Only for client-side logic","isCorrect":false,"explanation":""},{"id":"c","text":"Require Express.js","isCorrect":false,"explanation":""},{"id":"d","text":"Not supported in Next.js","isCorrect":false,"explanation":""}]',
          NULL,
          'Each file becomes an API endpoint, enabling full-stack apps without a separate backend.',
          NULL,
          [],
          ARRAY['nextjs','api-routes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q9","original_type":"multiple-choice","topic":"API Routes","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bf2bfae4-581d-4b30-8683-2d74fe9d5a1c',
          'What is ISR (Incremental Static Regeneration)?',
          'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'With `revalidate`, Next.js regenerates pages in the background when traffic hits them.',
          NULL,
          [],
          ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q10","original_type":"open-ended","topic":"Incremental Static Regeneration","subcategory":"","sample_answers":["ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","It’s perfect for blogs, e-commerce, or dashboards where content changes periodically but doesn’t need real-time updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ee9017e4-0142-4a05-b6d8-0a307eb3275a',
          'How do you handle authentication in Next.js?',
          'Use NextAuth.js (Auth.js) for built-in providers, or implement custom auth with cookies, JWT, and middleware in API routes or Server Components.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'NextAuth.js integrates seamlessly with Next.js and supports OAuth, email, and credentials providers.',
          NULL,
          [],
          ARRAY['nextjs','authentication','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q11","original_type":"open-ended","topic":"Authentication","subcategory":"","sample_answers":["Use NextAuth.js for quick setup with providers like Google, GitHub, or custom credentials. Store sessions in cookies for SSR compatibility.","In App Router, protect routes using middleware that checks for valid session cookies before rendering Server Components."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '53660088-728d-4049-b3d0-40828faefcbf',
          'What is middleware in Next.js?',
          'Middleware runs before a request is completed and can modify the request/response, rewrite URLs, or add headers.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Runs before request completion; can rewrite, redirect, or modify headers","isCorrect":true,"explanation":""},{"id":"b","text":"Only for client-side logic","isCorrect":false,"explanation":""},{"id":"c","text":"Replaces API routes","isCorrect":false,"explanation":""},{"id":"d","text":"Not supported in App Router","isCorrect":false,"explanation":""}]',
          NULL,
          'It’s ideal for authentication, A/B testing, i18n, and bot protection.',
          NULL,
          [],
          ARRAY['nextjs','middleware','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q12","original_type":"multiple-choice","topic":"Middleware","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '32098201-f5e1-42af-95e9-cfb1779ce3c7',
          'How does Next.js optimize images?',
          'Next.js uses the `next/image` component to automatically optimize images (resize, compress, modern formats) and lazy-load them.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It reduces bandwidth, improves LCP, and prevents layout shift with automatic sizing.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q13","original_type":"open-ended","topic":"Image Optimization","subcategory":"","sample_answers":["`next/image` serves optimized WebP/AVIF, resizes based on device, and lazy-loads offscreen images—no config needed.","It integrates with CDNs and local file storage, and supports blur-up placeholders."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7a587e72-a031-4fa6-8f94-2934491d4d4c',
          'What is the purpose of next.config.js?',
          '`next.config.js` is used to customize Next.js build settings, like Webpack, Babel, environment variables, and experimental features.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Customize Webpack, Babel, env vars, and experimental features","isCorrect":true,"explanation":""},{"id":"b","text":"Required for every Next.js app","isCorrect":false,"explanation":""},{"id":"c","text":"Only for CSS configuration","isCorrect":false,"explanation":""},{"id":"d","text":"Replaces package.json","isCorrect":false,"explanation":""}]',
          NULL,
          'It’s optional but powerful for advanced customization without ejecting.',
          NULL,
          [],
          ARRAY['nextjs','next.js-configuration','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q14","original_type":"multiple-choice","topic":"Next.js Configuration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ade08313-33ad-4a80-9970-78f6ada9b6e5',
          'How do you deploy a Next.js app?',
          'Deploy to Vercel (official platform), Netlify, AWS, or any Node.js-compatible host. Vercel provides automatic SSR/SSG, edge functions, and preview deployments.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Vercel is optimized for Next.js with zero-config deployments and Git integration.',
          NULL,
          [],
          ARRAY['nextjs','deployment-on-vercel','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q15","original_type":"open-ended","topic":"Deployment on Vercel","subcategory":"","sample_answers":["Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.","For self-hosting, run `next build` and `next start` on a Node.js server—but you lose edge functions and ISR."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '89181a8d-17b7-4772-aba1-e3f79d5e7e65',
          'What are dynamic routes in Next.js?',
          'Dynamic routes use bracket syntax (`[id].js`) to create pages for dynamic data, like `/posts/1` or `/users/john`.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Bracket-based routes like [id].js for dynamic data","isCorrect":true,"explanation":""},{"id":"b","text":"Only static routes are supported","isCorrect":false,"explanation":""},{"id":"c","text":"Require manual React Router setup","isCorrect":false,"explanation":""},{"id":"d","text":"Not compatible with SSR","isCorrect":false,"explanation":""}]',
          NULL,
          'In Pages Router, use `getStaticPaths` for SSG; in App Router, use dynamic segments like `app/posts/[id]/page.js`.',
          NULL,
          [],
          ARRAY['nextjs','dynamic-routes','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q16","original_type":"multiple-choice","topic":"Dynamic Routes","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '44310c66-13ed-487b-a745-2cdbbf09db12',
          'How do you handle environment variables in Next.js?',
          'Prefix with `NEXT_PUBLIC_` to expose to the browser; others are server-only. Load from `.env.local`.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
          NULL,
          [],
          ARRAY['nextjs','environment-variables','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q17","original_type":"open-ended","topic":"Environment Variables","subcategory":"","sample_answers":["`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","Use `.env.local` for local development; Vercel lets you set env vars in the project dashboard."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a51a1d11-d9eb-45bf-b097-b338a29a052b',
          'What is the difference between SSG and SSR in Next.js?',
          'SSG (Static Site Generation) renders pages at build time. SSR (Server-Side Rendering) renders on every request.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"SSG: build-time render; SSR: per-request render","isCorrect":true,"explanation":""},{"id":"b","text":"SSR is always faster than SSG","isCorrect":false,"explanation":""},{"id":"c","text":"SSG doesn’t support dynamic data","isCorrect":false,"explanation":""},{"id":"d","text":"They are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'SSG is faster and cacheable; SSR is for dynamic, user-specific content.',
          NULL,
          [],
          ARRAY['nextjs','ssg-vs-ssr','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q18","original_type":"multiple-choice","topic":"SSG vs SSR","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '80235810-abd5-45fd-a41d-b322c7d267d1',
          'How do you implement layouts in Next.js?',
          'In App Router, use `layout.js` files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'App Router’s `layout.js` is the modern, built-in way to share UI across routes.',
          NULL,
          [],
          ARRAY['nextjs','layouts','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q19","original_type":"open-ended","topic":"Layouts","subcategory":"","sample_answers":["In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","Pages Router requires manual layout composition via component wrappers or context."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '76347328-797c-484e-9d7f-3de2097521ab',
          'What is the purpose of the ''use client'' directive?',
          '`''use client''` marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By default, all components in App Router are Server Components. Use `''use client''` only when needed for interactivity.',
          NULL,
          [],
          ARRAY['nextjs','client-components','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next1-20-nextjs-q20","original_type":"open-ended","topic":"Client Components","subcategory":"","sample_answers":["`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","It should be used sparingly to keep bundles small and leverage Server Components for data fetching."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1f561206-4b29-426b-a035-a8c4b231529d',
          'What is the purpose of next/image in Next.js?',
          '`next/image` is an extension of the HTML `<img>` element that provides automatic image optimization, including resizing, format conversion (WebP/AVIF), and lazy loading.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It reduces bandwidth, improves LCP, prevents layout shift, and integrates with CDNs like Vercel or Imgix.',
          NULL,
          [],
          ARRAY['nextjs','image-optimization','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q41","original_type":"open-ended","topic":"Image Optimization","subcategory":"","sample_answers":["`next/image` automatically serves modern formats like WebP, resizes based on device, and lazy-loads offscreen images—no config needed.","It requires a parent with defined width/height or uses `fill` mode for responsive containers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ea26dfcc-6315-4457-9dd1-28ca5bbe5d9e',
          'How do you handle environment variables in Next.js?',
          'Prefix with `NEXT_PUBLIC_` to expose to the browser; others are server-only. Load from `.env.local`.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
          NULL,
          [],
          ARRAY['nextjs','environment-variables','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q42","original_type":"open-ended","topic":"Environment Variables","subcategory":"","sample_answers":["`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","Use `.env.local` for local development; Vercel lets you set env vars in the project dashboard."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '47d0ead0-1a2c-4ae3-b087-53e8f0662fad',
          'What is the difference between SSG and SSR in Next.js?',
          'SSG (Static Site Generation) renders pages at build time. SSR (Server-Side Rendering) renders on every request.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"SSG: build-time render; SSR: per-request render","isCorrect":true,"explanation":""},{"id":"b","text":"SSR is always faster than SSG","isCorrect":false,"explanation":""},{"id":"c","text":"SSG doesn’t support dynamic data","isCorrect":false,"explanation":""},{"id":"d","text":"They are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'SSG is faster and cacheable; SSR is for dynamic, user-specific content.',
          NULL,
          [],
          ARRAY['nextjs','ssg-vs-ssr','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q43","original_type":"multiple-choice","topic":"SSG vs SSR","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '47d3ef03-5116-4e15-8823-88146d50b782',
          'What is ISR (Incremental Static Regeneration)?',
          'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'With `revalidate`, Next.js regenerates pages in the background when traffic hits them.',
          NULL,
          [],
          ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q44","original_type":"open-ended","topic":"Incremental Static Regeneration","subcategory":"","sample_answers":["ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","It’s perfect for blogs, e-commerce, or dashboards where content changes periodically but doesn’t need real-time updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ffdd709b-0397-4bbd-a354-5071fb728c5b',
          'How do you implement layouts in Next.js?',
          'In App Router, use `layout.js` files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'App Router’s `layout.js` is the modern, built-in way to share UI across routes.',
          NULL,
          [],
          ARRAY['nextjs','layouts','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q45","original_type":"open-ended","topic":"Layouts","subcategory":"","sample_answers":["In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","Pages Router requires manual layout composition via component wrappers or context."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b948fc7d-7c79-44fa-9a96-0849710f41df',
          'What is the purpose of the ''use client'' directive?',
          '`''use client''` marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'By default, all components in App Router are Server Components. Use `''use client''` only when needed for interactivity.',
          NULL,
          [],
          ARRAY['nextjs','client-components','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"next41-60-nextjs-q46","original_type":"open-ended","topic":"Client Components","subcategory":"","sample_answers":["`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","It should be used sparingly to keep bundles small and leverage Server Components for data fetching."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Next.js"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );;