INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'ca293720-7a28-4045-9943-ce45dde176e8',
      'What is the purpose of next/image in Next.js?',
      '`next/image` is an extension of the HTML `<img>` element that provides automatic image optimization, including resizing, format conversion (WebP/AVIF), and lazy loading.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It reduces bandwidth, improves LCP, prevents layout shift, and integrates with CDNs like Vercel or Imgix.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','image-optimization','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q41","original_type":"open-ended","topic":"Image Optimization","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e64368a4-bd14-4b6d-ad80-0e062f62b19d',
      'How do you handle environment variables in Next.js?',
      'Prefix with `NEXT_PUBLIC_` to expose to the browser; others are server-only. Load from `.env.local`.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','environment-variables','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q42","original_type":"open-ended","topic":"Environment Variables","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'daccde38-f66e-45f8-b40f-d9e21b2b0f73',
      'What is the difference between SSG and SSR in Next.js?',
      'SSG (Static Site Generation) renders pages at build time. SSR (Server-Side Rendering) renders on every request.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"SSG: build-time render; SSR: per-request render","isCorrect":true,"explanation":""},{"id":"b","text":"SSR is always faster than SSG","isCorrect":false,"explanation":""},{"id":"c","text":"SSG doesn’t support dynamic data","isCorrect":false,"explanation":""},{"id":"d","text":"They are the same","isCorrect":false,"explanation":""}]',
      'c',
      'SSG is faster and cacheable; SSR is for dynamic, user-specific content.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','ssg-vs-ssr','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q43","original_type":"multiple-choice","topic":"SSG vs SSR","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '238abd8f-d754-4dce-8d05-199457d37624',
      'What is ISR (Incremental Static Regeneration)?',
      'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'With `revalidate`, Next.js regenerates pages in the background when traffic hits them.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q44","original_type":"open-ended","topic":"Incremental Static Regeneration","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'df903dbd-f0e1-4b83-aca2-57449aaa1464',
      'How do you implement layouts in Next.js?',
      'In App Router, use `layout.js` files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'App Router’s `layout.js` is the modern, built-in way to share UI across routes.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','layouts','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q45","original_type":"open-ended","topic":"Layouts","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '7550e2e5-cec7-4507-b024-299b63036803',
      'What is the purpose of the ''use client'' directive?',
      '`''use client''` marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'By default, all components in App Router are Server Components. Use `''use client''` only when needed for interactivity.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','client-components','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q46","original_type":"open-ended","topic":"Client Components","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '5347b5a9-674f-413f-a7f7-57dbf1fa2b45',
      'How do you handle loading states in the App Router?',
      'Use the `loading.js` file in a route segment to show a loading UI while data is being fetched. It works with React Suspense.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      '`loading.js` provides an instant loading UI without client-side JavaScript, improving perceived performance.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','loading-states','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q47","original_type":"open-ended","topic":"Loading States","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e547d090-e9f3-4eda-8e6e-5b57835a4958',
      'What is the purpose of error.js in the App Router?',
      'The `error.js` file defines an error boundary for a route segment, catching errors in Server and Client Components and displaying a fallback UI.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It uses React error boundaries under the hood and can be reset with the `error.reset()` function.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','error-handling','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q48","original_type":"open-ended","topic":"Error Handling","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'c4b8415c-da74-4817-85bf-6a91199cffaf',
      'How do you implement nested layouts in Next.js App Router?',
      'Create `layout.js` files in nested folders. Each layout wraps its child routes, enabling persistent UI like headers and sidebars.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','layouts','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q49","original_type":"open-ended","topic":"Layouts","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '12c293db-a0c2-47a2-8209-e168d5a89e8c',
      'What is the difference between `generateStaticParams` and `getStaticPaths`?',
      '`generateStaticParams` is used in App Router for dynamic routes with SSG. `getStaticPaths` is the Pages Router equivalent.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"`generateStaticParams`: App Router; `getStaticPaths`: Pages Router","isCorrect":true,"explanation":""},{"id":"b","text":"They are the same function","isCorrect":false,"explanation":""},{"id":"c","text":"`getStaticPaths` works in App Router","isCorrect":false,"explanation":""},{"id":"d","text":"`generateStaticParams` is for SSR","isCorrect":false,"explanation":""}]',
      'c',
      'Both define which dynamic routes to pre-render at build time.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','static-site-generation-(ssg)','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q50","original_type":"multiple-choice","topic":"Static Site Generation (SSG)","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'ac4014c5-b5e2-40cb-aaa4-bbe35ecc10ce',
      'How do you handle dynamic routes in the App Router?',
      'Use dynamic segments like `app/users/[id]/page.js`. Fetch data using `params.id` in the Server Component.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'The `params` object is passed to `page.js`, `layout.js`, and other route handlers automatically.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','dynamic-routes','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q51","original_type":"open-ended","topic":"Dynamic Routes","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '92857527-4a02-4c93-bd35-2cbcb0f0785d',
      'What is the purpose of the `not-found.js` file?',
      '`not-found.js` defines a custom 404 page for a route segment when `notFound()` is thrown or a route doesn’t exist.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It’s the App Router equivalent of `pages/404.js` but scoped to route segments.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','error-handling','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q52","original_type":"open-ended","topic":"Error Handling","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '60dcf00e-a348-4b3a-88ae-1aefe9c45a80',
      'How do you redirect in Next.js App Router?',
      'Use `redirect()` from `next/navigation` in Server Components, or `useRouter().push()` in Client Components.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      '`redirect()` is for server-side redirects (e.g., auth checks); `useRouter` is for client-side navigation.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','redirects','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q53","original_type":"open-ended","topic":"Redirects","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '235e8d13-8a46-48f6-b6a3-f821cafcd57a',
      'What is the `useRouter` hook used for?',
      '`useRouter` provides client-side navigation methods like `push`, `replace`, and `refresh` in Client Components.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Client-side navigation in Client Components","isCorrect":true,"explanation":""},{"id":"b","text":"Data fetching in Server Components","isCorrect":false,"explanation":""},{"id":"c","text":"Server-side redirects","isCorrect":false,"explanation":""},{"id":"d","text":"Only works in Pages Router","isCorrect":false,"explanation":""}]',
      'c',
      'It’s the App Router equivalent of `next/router` but with the same API.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','client-side-navigation','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q54","original_type":"multiple-choice","topic":"Client-Side Navigation","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '5a031699-39d4-48f1-881e-bd8c9d282e32',
      'How does Next.js handle caching?',
      'Next.js extends `fetch()` with automatic caching, revalidation, and deduping. Use `cache`, `next.revalidate`, and `next.tags` options.',
      'multiple-choice',
      'advanced',
      9,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Caching is opt-in via `fetch` options, replacing `getStaticProps`/`getServerSideProps`.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','caching','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q55","original_type":"open-ended","topic":"Caching","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '02caad7c-e9aa-41d3-a05d-a2f9ea5b7e43',
      'What is on-demand revalidation in Next.js?',
      'On-demand revalidation allows you to purge cached data and regenerate pages after build time using `revalidateTag` or `revalidatePath`.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','incremental-static-regeneration','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q56","original_type":"open-ended","topic":"Incremental Static Regeneration","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e07d7d10-ead4-40b2-ba92-b49ad0759cd9',
      'How do you implement middleware in Next.js?',
      'Create a `middleware.js` file in the root or route segment. It runs before requests and can rewrite, redirect, or add headers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Middleware is ideal for authentication, A/B testing, i18n, and bot protection.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','middleware','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q57","original_type":"open-ended","topic":"Middleware","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '69b132b1-e173-4df6-90eb-d479c4dae766',
      'What is the purpose of `next.config.js`?',
      '`next.config.js` customizes Next.js build settings like Webpack, Babel, environment variables, and experimental features.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Customize Webpack, Babel, env vars, and experimental features","isCorrect":true,"explanation":""},{"id":"b","text":"Required for every Next.js app","isCorrect":false,"explanation":""},{"id":"c","text":"Only for CSS configuration","isCorrect":false,"explanation":""},{"id":"d","text":"Replaces package.json","isCorrect":false,"explanation":""}]',
      'c',
      'It’s optional but powerful for advanced customization without ejecting.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','next.js-configuration','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q58","original_type":"multiple-choice","topic":"Next.js Configuration","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '804e876c-7b5e-41ac-a642-9b2f34ca6551',
      'How does Next.js optimize images?',
      'Next.js uses the `next/image` component to automatically optimize images (resize, compress, modern formats) and lazy-load them.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It reduces bandwidth, improves LCP, and prevents layout shift with automatic sizing.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','image-optimization','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q59","original_type":"open-ended","topic":"Image Optimization","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '387bdd5a-6f8b-4f48-badc-e32fc669c585',
      'What is the difference between `next/image` and `next/future/image`?',
      '`next/future/image` was an experimental version in Next.js 12. It’s now stable and available as `next/image` in Next.js 13+.',
      'true-false',
      'intermediate',
      5,
      '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
      'false',
      'As of Next.js 13, `next/image` is the stable, recommended component.',
      ARRAY[]::jsonb[],
      ARRAY[]::text[],
      ARRAY['nextjs','image-optimization','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"next41-60-nextjs-q60","original_type":"true-false","topic":"Image Optimization","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"Next.js"}',
      '9686f91c-d21e-4b1b-a5b9-9f702a58631e',
      true,
      '2025-10-21T22:25:43.210Z',
      '2025-10-21T22:25:43.210Z'
    );;
