INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What are API routes in Next.js?',
      'API routes allow you to create serverless API endpoints inside the <code>pages/api</code> directory (Pages Router) or <code>app/api</code> (App Router).',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Serverless functions in pages/api or app/api that handle HTTP requests","isCorrect":true,"explanation":""},{"id":"b","text":"Only for client-side logic","isCorrect":false,"explanation":""},{"id":"c","text":"Require Express.js","isCorrect":false,"explanation":""},{"id":"d","text":"Not supported in Next.js","isCorrect":false,"explanation":""}]',
      'Serverless functions in pages/api or app/api that handle HTTP requests',
      'Each file becomes an API endpoint, enabling full-stack apps without a separate backend.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'api-routes', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you fetch data in the App Router?',
      'In App Router, fetch data directly in Server Components using <code>async</code> components and the native <code>fetch()</code> API with automatic deduping and streaming.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Write async Server Components that call `fetch()` directly. Next.js handles caching and deduping automatically.","isCorrect":true,"explanation":"Next.js extends <code>fetch()</code> with caching, revalidation, and deduping—no need for <code>getStaticProps</code> or <code>getServerSideProps</code>."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Write async Server Components that call `fetch()` directly. Next.js handles caching and deduping automatically.',
      'Next.js extends <code>fetch()</code> with caching, revalidation, and deduping—no need for <code>getStaticProps</code> or <code>getServerSideProps</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'app-router-data-fetching', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between `resolving` and `fetching` in Next.js?',
      'Resolving is determining which route to render. Fetching is retrieving data for that route.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Resolving matches the URL to a file in `app/`. Fetching runs the Server Component to get data and render HTML.","isCorrect":true,"explanation":"Next.js first resolves the route (e.g., <code>/blog/[slug]</code>), then fetches data for it using Server Components."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Resolving matches the URL to a file in `app/`. Fetching runs the Server Component to get data and render HTML.',
      'Next.js first resolves the route (e.g., <code>/blog/[slug]</code>), then fetches data for it using Server Components.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'app-router-internals', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle authentication in Next.js?',
      'Use NextAuth.js (Auth.js) for built-in providers, or implement custom auth with cookies, JWT, and middleware in API routes or Server Components.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Use NextAuth.js for quick setup with providers like Google, GitHub, or custom credentials. Store sessions in cookies for SSR compatibility.","isCorrect":true,"explanation":"NextAuth.js integrates seamlessly with Next.js and supports OAuth, email, and credentials providers."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Use NextAuth.js for quick setup with providers like Google, GitHub, or custom credentials. Store sessions in cookies for SSR compatibility.',
      'NextAuth.js integrates seamlessly with Next.js and supports OAuth, email, and credentials providers.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'authentication', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is Next.js?',
      'Next.js is a React framework for building full-stack web applications with features like server-side rendering (SSR), static site generation (SSG), file-based routing, and API routes.',
      'multiple-choice',
      'intermediate',
      4,
      '[{"id":"o1","text":"Next.js is a React framework that enables server-rendered, statically generated, and hybrid applications with zero config.","isCorrect":true,"explanation":"Next.js simplifies React app development by providing built-in solutions for routing, data fetching, optimization, and deployment."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Next.js is a React framework that enables server-rendered, statically generated, and hybrid applications with zero config.',
      'Next.js simplifies React app development by providing built-in solutions for routing, data fetching, optimization, and deployment.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'next.js-basics', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What are the main features of Next.js?',
      'Key features include: file-based routing, server-side rendering (SSR), static site generation (SSG), API routes, image optimization, automatic code splitting, and middleware.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"File-based routing, SSR/SSG, API routes, image optimization, middleware","isCorrect":true,"explanation":""},{"id":"b","text":"Only client-side rendering","isCorrect":false,"explanation":""},{"id":"c","text":"No built-in routing","isCorrect":false,"explanation":""},{"id":"d","text":"Requires manual Webpack configuration","isCorrect":false,"explanation":""}]',
      'File-based routing, SSR/SSG, API routes, image optimization, middleware',
      'These features enable full-stack development with optimized performance and SEO.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'next.js-basics', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How does Next.js handle caching?',
      'Next.js extends <code>fetch()</code> with automatic caching, revalidation, and deduping. Use <code>cache</code>, <code>next.revalidate</code>, and <code>next.tags</code> options.',
      'multiple-choice',
      'advanced',
      9,
      '[{"id":"o1","text":"`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.","isCorrect":true,"explanation":"Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.',
      'Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'caching', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How does Next.js handle caching?',
      'Next.js extends <code>fetch()</code> with automatic caching, revalidation, and deduping. Use <code>cache</code>, <code>next.revalidate</code>, and <code>next.tags</code> options.',
      'multiple-choice',
      'advanced',
      9,
      '[{"id":"o1","text":"`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.","isCorrect":true,"explanation":"Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.',
      'Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'caching', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How does Next.js handle caching?',
      'Next.js extends <code>fetch()</code> with automatic caching, revalidation, and deduping. Use <code>cache</code>, <code>next.revalidate</code>, and <code>next.tags</code> options.',
      'multiple-choice',
      'advanced',
      9,
      '[{"id":"o1","text":"`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.","isCorrect":true,"explanation":"Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`fetch(url, { next: { revalidate: 60 } })` caches for 60 seconds. `fetch(url, { cache: ''no-store'' })` disables caching for SSR.',
      'Caching is opt-in via <code>fetch</code> options, replacing <code>getStaticProps</code>/<code>getServerSideProps</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'caching', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the `useRouter` hook used for?',
      '<code>useRouter</code> provides client-side navigation methods like <code>push</code>, <code>replace</code>, and <code>refresh</code> in Client Components.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Client-side navigation in Client Components","isCorrect":true,"explanation":""},{"id":"b","text":"Data fetching in Server Components","isCorrect":false,"explanation":""},{"id":"c","text":"Server-side redirects","isCorrect":false,"explanation":""},{"id":"d","text":"Only works in Pages Router","isCorrect":false,"explanation":""}]',
      'Client-side navigation in Client Components',
      'It’s the App Router equivalent of <code>next/router</code> but with the same API.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-side-navigation', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the `useRouter` hook used for?',
      '<code>useRouter</code> provides client-side navigation methods like <code>push</code>, <code>replace</code>, and <code>refresh</code> in Client Components.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Client-side navigation in Client Components","isCorrect":true,"explanation":""},{"id":"b","text":"Data fetching in Server Components","isCorrect":false,"explanation":""},{"id":"c","text":"Server-side redirects","isCorrect":false,"explanation":""},{"id":"d","text":"Only works in Pages Router","isCorrect":false,"explanation":""}]',
      'Client-side navigation in Client Components',
      'It’s the App Router equivalent of <code>next/router</code> but with the same API.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-side-navigation', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the `useRouter` hook used for?',
      '<code>useRouter</code> provides client-side navigation methods like <code>push</code>, <code>replace</code>, and <code>refresh</code> in Client Components.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Client-side navigation in Client Components","isCorrect":true,"explanation":""},{"id":"b","text":"Data fetching in Server Components","isCorrect":false,"explanation":""},{"id":"c","text":"Server-side redirects","isCorrect":false,"explanation":""},{"id":"d","text":"Only works in Pages Router","isCorrect":false,"explanation":""}]',
      'Client-side navigation in Client Components',
      'It’s the App Router equivalent of <code>next/router</code> but with the same API.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-side-navigation', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the ''use client'' directive?',
      '<code>''use client''</code> marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","isCorrect":true,"explanation":"By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.',
      'By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-components', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the ''use client'' directive?',
      '<code>''use client''</code> marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","isCorrect":true,"explanation":"By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.',
      'By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-components', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the ''use client'' directive?',
      '<code>''use client''</code> marks a file as a Client Component, enabling interactivity, hooks, and event handlers in the App Router.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.","isCorrect":true,"explanation":"By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`''use client''` at the top of a file enables useState, useEffect, and event handlers—turning it into a Client Component.',
      'By default, all components in App Router are Server Components. Use <code>''use client''</code> only when needed for interactivity.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'client-components', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle loading states in the App Router?',
      'Use the <code>loading.js</code> file in a route segment to show a loading UI while data is being fetched. It works with React Suspense.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.","isCorrect":true,"explanation":"<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.',
      '<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'loading-states', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle loading states in the App Router?',
      'Use the <code>loading.js</code> file in a route segment to show a loading UI while data is being fetched. It works with React Suspense.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.","isCorrect":true,"explanation":"<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.',
      '<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'loading-states', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle loading states in the App Router?',
      'Use the <code>loading.js</code> file in a route segment to show a loading UI while data is being fetched. It works with React Suspense.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.","isCorrect":true,"explanation":"<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/dashboard/loading.js` that exports a component. Next.js shows it immediately while the `page.js` data loads.',
      '<code>loading.js</code> provides an instant loading UI without client-side JavaScript, improving perceived performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'loading-states', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you deploy a Next.js app?',
      'Deploy to Vercel (official platform), Netlify, AWS, or any Node.js-compatible host. Vercel provides automatic SSR/SSG, edge functions, and preview deployments.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.","isCorrect":true,"explanation":"Vercel is optimized for Next.js with zero-config deployments and Git integration."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.',
      'Vercel is optimized for Next.js with zero-config deployments and Git integration.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'deployment-on-vercel', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you deploy a Next.js app?',
      'Deploy to Vercel (official platform), Netlify, AWS, or any Node.js-compatible host. Vercel provides automatic SSR/SSG, edge functions, and preview deployments.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.","isCorrect":true,"explanation":"Vercel is optimized for Next.js with zero-config deployments and Git integration."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Push to GitHub and deploy on Vercel for automatic builds, preview URLs, and edge network caching.',
      'Vercel is optimized for Next.js with zero-config deployments and Git integration.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'deployment-on-vercel', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle dynamic routes in the App Router?',
      'Use dynamic segments like <code>app/users/[id]/page.js</code>. Fetch data using <code>params.id</code> in the Server Component.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`","isCorrect":true,"explanation":"The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`',
      'The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'dynamic-routes', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle dynamic routes in the App Router?',
      'Use dynamic segments like <code>app/users/[id]/page.js</code>. Fetch data using <code>params.id</code> in the Server Component.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`","isCorrect":true,"explanation":"The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`',
      'The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'dynamic-routes', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What are dynamic routes in Next.js?',
      'Dynamic routes use bracket syntax (<code>[id].js</code>) to create pages for dynamic data, like <code>/posts/1</code> or <code>/users/john</code>.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Bracket-based routes like [id].js for dynamic data","isCorrect":true,"explanation":""},{"id":"b","text":"Only static routes are supported","isCorrect":false,"explanation":""},{"id":"c","text":"Require manual React Router setup","isCorrect":false,"explanation":""},{"id":"d","text":"Not compatible with SSR","isCorrect":false,"explanation":""}]',
      'Bracket-based routes like [id].js for dynamic data',
      'In Pages Router, use <code>getStaticPaths</code> for SSG; in App Router, use dynamic segments like <code>app/posts/[id]/page.js</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'dynamic-routes', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle dynamic routes in the App Router?',
      'Use dynamic segments like <code>app/users/[id]/page.js</code>. Fetch data using <code>params.id</code> in the Server Component.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`","isCorrect":true,"explanation":"The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/blog/[slug]/page.js`. The `slug` is available via `params.slug` in the component: `export default async function Page({ params }) { ... }`',
      'The <code>params</code> object is passed to <code>page.js</code>, <code>layout.js</code>, and other route handlers automatically.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'dynamic-routes', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle environment variables in Next.js?',
      'Prefix with <code>NEXT_PUBLIC_</code> to expose to the browser; others are server-only. Load from <code>.env.local</code>.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","isCorrect":true,"explanation":"Non-prefixed variables are only available in Server Components and API routes—never exposed to client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.',
      'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'environment-variables', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle environment variables in Next.js?',
      'Prefix with <code>NEXT_PUBLIC_</code> to expose to the browser; others are server-only. Load from <code>.env.local</code>.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","isCorrect":true,"explanation":"Non-prefixed variables are only available in Server Components and API routes—never exposed to client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.',
      'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'environment-variables', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle environment variables in Next.js?',
      'Prefix with <code>NEXT_PUBLIC_</code> to expose to the browser; others are server-only. Load from <code>.env.local</code>.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","isCorrect":true,"explanation":"Non-prefixed variables are only available in Server Components and API routes—never exposed to client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.',
      'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'environment-variables', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle environment variables in Next.js?',
      'Prefix with <code>NEXT_PUBLIC_</code> to expose to the browser; others are server-only. Load from <code>.env.local</code>.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.","isCorrect":true,"explanation":"Non-prefixed variables are only available in Server Components and API routes—never exposed to client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`NEXT_PUBLIC_API_URL` is available in the browser; `DATABASE_URL` is only in server code—keeping secrets safe.',
      'Non-prefixed variables are only available in Server Components and API routes—never exposed to client.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'environment-variables', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of error.js in the App Router?',
      'The <code>error.js</code> file defines an error boundary for a route segment, catching errors in Server and Client Components and displaying a fallback UI.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.","isCorrect":true,"explanation":"It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.',
      'It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the `not-found.js` file?',
      '<code>not-found.js</code> defines a custom 404 page for a route segment when <code>notFound()</code> is thrown or a route doesn’t exist.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.","isCorrect":true,"explanation":"It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.',
      'It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of error.js in the App Router?',
      'The <code>error.js</code> file defines an error boundary for a route segment, catching errors in Server and Client Components and displaying a fallback UI.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.","isCorrect":true,"explanation":"It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.',
      'It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the `not-found.js` file?',
      '<code>not-found.js</code> defines a custom 404 page for a route segment when <code>notFound()</code> is thrown or a route doesn’t exist.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.","isCorrect":true,"explanation":"It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.',
      'It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of error.js in the App Router?',
      'The <code>error.js</code> file defines an error boundary for a route segment, catching errors in Server and Client Components and displaying a fallback UI.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.","isCorrect":true,"explanation":"It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '`error.js` exports a Client Component that receives `error` and `reset` props. It catches errors in the route segment and lets users retry.',
      'It uses React error boundaries under the hood and can be reset with the <code>error.reset()</code> function.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the `not-found.js` file?',
      '<code>not-found.js</code> defines a custom 404 page for a route segment when <code>notFound()</code> is thrown or a route doesn’t exist.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"o1","text":"Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.","isCorrect":true,"explanation":"It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Create `app/not-found.js` for a global 404, or `app/blog/not-found.js` for blog-specific 404s.',
      'It’s the App Router equivalent of <code>pages/404.js</code> but scoped to route segments.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'error-handling', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is EAS in the context of Expo?',
      'EAS (Expo Application Services) is a cloud platform for building, submitting, and updating Expo apps without local Xcode/Android Studio.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"EAS replaces `expo build` with cloud-based builds, enabling custom native code without local setup.","isCorrect":true,"explanation":"EAS Build compiles apps in the cloud; EAS Submit sends them to app stores; EAS Update pushes JS updates over the air."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'EAS replaces `expo build` with cloud-based builds, enabling custom native code without local setup.',
      'EAS Build compiles apps in the cloud; EAS Submit sends them to app stores; EAS Update pushes JS updates over the air.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'expo', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How does Expo differ from standard React Native?',
      'Expo is a framework and platform built on React Native that provides a managed workflow with prebuilt native modules and cloud services.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Expo: managed workflow, prebuilt modules, cloud services; React Native: bare workflow, full native control","isCorrect":true,"explanation":""},{"id":"b","text":"Expo doesn’t support custom native code","isCorrect":false,"explanation":""},{"id":"c","text":"React Native is only for iOS","isCorrect":false,"explanation":""},{"id":"d","text":"Expo is deprecated","isCorrect":false,"explanation":""}]',
      'Expo: managed workflow, prebuilt modules, cloud services; React Native: bare workflow, full native control',
      'Expo simplifies development with a curated set of APIs; EAS enables custom native code when needed.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'expo', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is on-demand revalidation in Next.js?',
      'On-demand revalidation allows you to purge cached data and regenerate pages after build time using <code>revalidateTag</code> or <code>revalidatePath</code>.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.","isCorrect":true,"explanation":"It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.',
      'It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is ISR (Incremental Static Regeneration)?',
      'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","isCorrect":true,"explanation":"With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.',
      'With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is on-demand revalidation in Next.js?',
      'On-demand revalidation allows you to purge cached data and regenerate pages after build time using <code>revalidateTag</code> or <code>revalidatePath</code>.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.","isCorrect":true,"explanation":"It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.',
      'It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is ISR (Incremental Static Regeneration)?',
      'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","isCorrect":true,"explanation":"With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.',
      'With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is ISR (Incremental Static Regeneration)?',
      'ISR allows you to update static content after build time by revalidating pages at a specified interval.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.","isCorrect":true,"explanation":"With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'ISR combines the speed of SSG with the freshness of SSR. Use `revalidate: 60` in `getStaticProps` to update every 60 seconds.',
      'With <code>revalidate</code>, Next.js regenerates pages in the background when traffic hits them.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'What is on-demand revalidation in Next.js?',
      'On-demand revalidation allows you to purge cached data and regenerate pages after build time using <code>revalidateTag</code> or <code>revalidatePath</code>.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"o1","text":"Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.","isCorrect":true,"explanation":"It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'Tag a `fetch` with `next: { tags: [''product-123''] }`. Later, call `revalidateTag(''product-123'')` in an API route to update the page.',
      'It’s the App Router equivalent of ISR but triggered manually via API routes or webhooks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'incremental-static-regeneration', 'advanced'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement nested layouts in Next.js App Router?',
      'Create <code>layout.js</code> files in nested folders. Each layout wraps its child routes, enabling persistent UI like headers and sidebars.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.","isCorrect":true,"explanation":"Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.',
      'Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement layouts in Next.js?',
      'In App Router, use <code>layout.js</code> files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","isCorrect":true,"explanation":"App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.',
      'App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement nested layouts in Next.js App Router?',
      'Create <code>layout.js</code> files in nested folders. Each layout wraps its child routes, enabling persistent UI like headers and sidebars.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.","isCorrect":true,"explanation":"Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.',
      'Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement layouts in Next.js?',
      'In App Router, use <code>layout.js</code> files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","isCorrect":true,"explanation":"App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.',
      'App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement layouts in Next.js?',
      'In App Router, use <code>layout.js</code> files for nested, persistent layouts. In Pages Router, use higher-order components or custom wrappers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.","isCorrect":true,"explanation":"App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In App Router, create `app/layout.js` to wrap all pages with a shared header/footer. Nested layouts are possible with folder structure.',
      'App Router’s <code>layout.js</code> is the modern, built-in way to share UI across routes.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement nested layouts in Next.js App Router?',
      'Create <code>layout.js</code> files in nested folders. Each layout wraps its child routes, enabling persistent UI like headers and sidebars.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.","isCorrect":true,"explanation":"Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      'In `app/dashboard/layout.js`, return a layout with a sidebar. All pages in `app/dashboard/` will be wrapped by it.',
      'Layouts are Server Components by default and can fetch data. They persist across route changes, improving performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'layouts', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement middleware in Next.js?',
      'Create a <code>middleware.js</code> file in the root or route segment. It runs before requests and can rewrite, redirect, or add headers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"```js\\nexport { default } from ''next-auth/middleware'';\\nexport const config = { matcher: [''/dashboard/:path*''] };\\n```","isCorrect":true,"explanation":"Middleware is ideal for authentication, A/B testing, i18n, and bot protection."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '```js
export { default } from ''next-auth/middleware'';
export const config = { matcher: [''/dashboard/:path*''] };
```',
      'Middleware is ideal for authentication, A/B testing, i18n, and bot protection.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'middleware', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    ),
    (
      gen_random_uuid(),
      'How do you implement middleware in Next.js?',
      'Create a <code>middleware.js</code> file in the root or route segment. It runs before requests and can rewrite, redirect, or add headers.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"o1","text":"```js\\nexport { default } from ''next-auth/middleware'';\\nexport const config = { matcher: [''/dashboard/:path*''] };\\n```","isCorrect":true,"explanation":"Middleware is ideal for authentication, A/B testing, i18n, and bot protection."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review Next.js documentation and concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider Next.js best practices and architecture.","isCorrect":false,"explanation":""}]',
      '```js
export { default } from ''next-auth/middleware'';
export const config = { matcher: [''/dashboard/:path*''] };
```',
      'Middleware is ideal for authentication, A/B testing, i18n, and bot protection.',
      NULL,
      ARRAY[]::text[],
      ARRAY['nextjs', 'middleware', 'intermediate'],
      '{}',
      NULL,
      'b6018602-d9ad-445d-ae97-8d1351b5ed10',
      NULL,
      true,
      '2025-11-18T18:46:59.295Z',
      '2025-11-18T18:46:59.295Z',
      'b39959a9-02c4-461f-9589-583894f1a652',
      300
    );