INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is the purpose of HttpOnly cookies?',
      'Explain how HttpOnly cookies improve security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks.","isCorrect":true,"explanation":"HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks.',
      'HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are the best practices for session management in frontend apps?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use short-lived tokens and refresh them securely","isCorrect":true,"explanation":""},{"id":"o2","text":"Store tokens in memory or HttpOnly cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely solely on localStorage for tokens","isCorrect":false,"explanation":""},{"id":"o4","text":"Invalidate sessions on logout and after inactivity","isCorrect":true,"explanation":""}]',
      'Use short-lived tokens and refresh them securely',
      'Use secure storage, short-lived tokens, refresh tokens carefully, and invalidate sessions properly. Avoid storing sensitive tokens in localStorage due to XSS risk.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'session management', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does the SameSite cookie attribute improve security?',
      'Select the correct behavior.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Prevents cookies from being sent with cross-site requests by default","isCorrect":true,"explanation":""},{"id":"o2","text":"Mitigates CSRF attacks","isCorrect":true,"explanation":""},{"id":"o3","text":"Encrypts cookie contents","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents cookies from being accessed via JavaScript","isCorrect":false,"explanation":""}]',
      'Prevents cookies from being sent with cross-site requests by default',
      'SameSite restricts cross-site sending of cookies to reduce CSRF risks. It does not encrypt cookies or make them HttpOnly.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are best practices for secure cookie usage in frontend applications?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use HttpOnly to prevent JavaScript access","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Secure flag to enforce HTTPS transmission","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid storing sensitive tokens in localStorage","isCorrect":true,"explanation":""},{"id":"o4","text":"Use SameSite attribute to mitigate CSRF","isCorrect":true,"explanation":""}]',
      'Use HttpOnly to prevent JavaScript access',
      'HttpOnly, Secure, and SameSite attributes protect cookies from XSS and CSRF attacks. Sensitive tokens should not be stored in localStorage.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the HttpOnly cookie attribute?',
      'Select the correct option.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Prevents JavaScript from accessing the cookie","isCorrect":true,"explanation":""},{"id":"o2","text":"Encrypts cookie contents","isCorrect":false,"explanation":""},{"id":"o3","text":"Prevents cookies from being sent over HTTP","isCorrect":false,"explanation":""},{"id":"o4","text":"Automatically rotates session cookies","isCorrect":false,"explanation":""}]',
      'Prevents JavaScript from accessing the cookie',
      'HttpOnly restricts access to cookies from JavaScript, reducing XSS risks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: MITM attacks only affect unsecured HTTP connections.',
      'Evaluate whether this statement is true or false.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"MITM can also target HTTPS via certificate spoofing or rogue networks."},{"id":"o2","text":"False","isCorrect":false,"explanation":"MITM can also target HTTPS via certificate spoofing or rogue networks."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: MITM attacks can steal data from HTTPS connections if SSL/TLS is not validated correctly.',
      'Evaluate whether this statement is true or false.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"Improper certificate validation or self-signed certs allow MITM attacks even over HTTPS."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Using third-party JavaScript libraries without review is safe if your site uses HTTPS.',
      'Evaluate this statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"Even over HTTPS, malicious or vulnerable third-party JS can introduce XSS or malware."},{"id":"o2","text":"False","isCorrect":false,"explanation":"Even over HTTPS, malicious or vulnerable third-party JS can introduce XSS or malware."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'third-party', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a Man-in-the-Middle (MITM) attack?',
      'Explain what MITM attacks are and how they affect web communication.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing.","isCorrect":true,"explanation":"A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing.',
      'A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Using HTTPS prevents all types of MITM attacks.',
      'Evaluate this statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"HTTPS protects against MITM attacks in transit, but misconfigured certificates or weak crypto can still be exploited."},{"id":"o2","text":"False","isCorrect":false,"explanation":"HTTPS protects against MITM attacks in transit, but misconfigured certificates or weak crypto can still be exploited."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following improve web app security against MITM attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Enforce HTTPS and HSTS","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate SSL/TLS certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Use strong encryption algorithms","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on client-side validation","isCorrect":false,"explanation":""}]',
      'Enforce HTTPS and HSTS',
      'Proper HTTPS, certificate validation, and strong crypto protect against MITM; client-side validation alone is not sufficient.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: XSS attacks can be used to bypass CSRF protections.',
      'Evaluate the statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"An XSS vulnerability can allow an attacker to execute scripts that perform CSRF-like actions using the victim’s credentials."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'xss & csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the Same-Origin Policy (SOP) and why is it important?',
      'Explain SOP and its significance in web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access.","isCorrect":true,"explanation":"SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access.',
      'SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'sop', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is MITM (Man-in-the-Middle) attack?',
      'Describe MITM attacks and their impact on frontend web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies.","isCorrect":true,"explanation":"MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies.',
      'MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can HTTPS prevent MITM attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Encrypts traffic between client and server","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents tampering of data in transit","isCorrect":true,"explanation":""},{"id":"o3","text":"Automatically detects phishing websites","isCorrect":false,"explanation":""},{"id":"o4","text":"Ensures integrity via TLS certificates","isCorrect":true,"explanation":""}]',
      'Encrypts traffic between client and server',
      'HTTPS (TLS) encrypts data, ensures integrity, and authenticates the server. It does not automatically detect phishing sites.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a Man-in-the-Middle (MITM) attack?',
      'Explain how MITM attacks work and their potential impact on web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge.","isCorrect":true,"explanation":"In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge.',
      'In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can HTTPS prevent MITM attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Encrypts data between client and server","isCorrect":true,"explanation":""},{"id":"o2","text":"Validates server identity using certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Blocks phishing emails automatically","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents cookie theft if Secure flag is set","isCorrect":true,"explanation":""}]',
      'Encrypts data between client and server',
      'HTTPS encrypts communication, validates the server''s certificate, and combined with Secure cookies, helps prevent MITM attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: All third-party libraries are safe by default.',
      'Evaluate the statement in terms of frontend security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"Third-party libraries can have vulnerabilities, outdated dependencies, or malicious code; always review and update them."},{"id":"o2","text":"False","isCorrect":false,"explanation":"Third-party libraries can have vulnerabilities, outdated dependencies, or malicious code; always review and update them."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'third-party security', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Man-in-the-Middle (MITM) attack?',
      'Explain how MITM attacks occur in web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit.","isCorrect":true,"explanation":"MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit.',
      'MITM attacks occur when an attacker intercepts communication between a client and server to eavesdrop, steal credentials, or manipulate data in transit.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent MITM attacks in web applications?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use HTTPS for all communication","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate SSL/TLS certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Implement HSTS headers","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on network-level security","isCorrect":false,"explanation":""}]',
      'Use HTTPS for all communication',
      'HTTPS, certificate validation, and HSTS protect against MITM attacks. Network-level security alone is insufficient.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'mitm', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is HTTP Strict Transport Security (HSTS)?',
      'Explain how HSTS helps improve web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks.","isCorrect":true,"explanation":"HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks.',
      'HSTS tells browsers to only communicate over HTTPS, preventing protocol downgrade attacks and reducing the risk of MITM attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'headers', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Subresource Integrity (SRI)?',
      'Explain how SRI protects your frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks.","isCorrect":true,"explanation":"SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks.',
      'SRI allows you to provide a hash for external scripts or stylesheets. The browser verifies the file has not been tampered with, protecting against CDN compromises or MITM attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'headers', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are security implications of storing sensitive data in localStorage?',
      'Explain the risks of using localStorage for authentication tokens.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts.","isCorrect":true,"explanation":"localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts.',
      'localStorage is accessible via JavaScript, making it vulnerable to XSS attacks. Sensitive tokens can be stolen if an attacker injects malicious scripts.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'storage', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the principle of least privilege in frontend security?',
      'Explain how least privilege applies to frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions.","isCorrect":true,"explanation":"Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions.',
      'Least privilege restricts access to only what is necessary for a user or application to perform its tasks, reducing the risk of data breaches and unauthorized actions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'least privilege', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent Clickjacking attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use X-Frame-Options header to deny framing","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Ensure HTTPS is used","isCorrect":false,"explanation":""},{"id":"o4","text":"Use JavaScript frame-busting techniques","isCorrect":true,"explanation":""}]',
      'Use X-Frame-Options header to deny framing',
      'X-Frame-Options, CSP frame-ancestors, and frame-busting scripts protect against clickjacking. HTTPS alone does not prevent it.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'ui redressing', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a Man-in-the-Middle (MITM) attack?',
      'Explain how MITM attacks can compromise web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing.","isCorrect":true,"explanation":"MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing.',
      'MITM occurs when an attacker intercepts communication between a user and a server, allowing them to read, modify, or inject malicious data without either party knowing.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'network', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can HTTPS prevent MITM attacks?',
      'Select the correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Encrypts data in transit","isCorrect":true,"explanation":""},{"id":"o2","text":"Authenticates the server using certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Prevents phishing attacks","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents unauthorized data tampering","isCorrect":true,"explanation":""}]',
      'Encrypts data in transit',
      'HTTPS encrypts traffic and verifies server identity, reducing MITM risks. It does not automatically prevent phishing.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'network', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the main danger of storing JWT tokens in localStorage?',
      'Explain the security risk involved.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users.","isCorrect":true,"explanation":"JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users.',
      'JWT tokens in localStorage are accessible via JavaScript, making them vulnerable to XSS attacks. If stolen, attackers can impersonate users.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'tokens', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of TLS/SSL certificates in web security?',
      'Explain how TLS/SSL certificates protect users and applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks.","isCorrect":true,"explanation":"TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks.',
      'TLS/SSL certificates encrypt traffic between the browser and server, ensuring data confidentiality, integrity, and authentication, which prevents eavesdropping and MITM attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'web-security-fundamentals', 'network', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is an XSS attack?',
      'Cross-Site Scripting (XSS) is when attackers inject malicious scripts into web pages viewed by other users. Explain the potential risks and examples.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters.","isCorrect":true,"explanation":"XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters.',
      'XSS is when an attacker injects scripts into a page to steal cookies, hijack sessions, or manipulate the DOM. Examples: stored XSS in comments, reflected XSS in search forms, DOM-based XSS via URL parameters.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following are types of XSS attacks?',
      'Select all types of XSS attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"DOM-based XSS","isCorrect":true,"explanation":""},{"id":"o2","text":"Reflected XSS","isCorrect":true,"explanation":""},{"id":"o3","text":"Stored XSS","isCorrect":true,"explanation":""},{"id":"o4","text":"SQL Injection","isCorrect":false,"explanation":""}]',
      'DOM-based XSS',
      'DOM-based, Reflected, and Stored are the three main XSS types. SQL Injection is a server-side attack.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of these is a recommended prevention for XSS in React?',
      'Select all correct strategies.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Avoid dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o2","text":"Use DOMPurify or similar sanitizers","isCorrect":true,"explanation":""},{"id":"o3","text":"Use HttpOnly cookies","isCorrect":false,"explanation":""},{"id":"o4","text":"Validate input server-side","isCorrect":true,"explanation":""}]',
      'Avoid dangerouslySetInnerHTML',
      'Avoid unsafe HTML, sanitize inputs, and validate server-side to prevent XSS.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Using HTTPS alone completely protects against XSS.',
      'Evaluate the statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"HTTPS protects data in transit but does not prevent script injection on the client side."},{"id":"o2","text":"False","isCorrect":false,"explanation":"HTTPS protects data in transit but does not prevent script injection on the client side."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent DOM-based XSS in JavaScript?',
      'Explain best practices for preventing DOM-based XSS attacks in frontend code.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers.","isCorrect":true,"explanation":"Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers.',
      'Avoid setting innerHTML with untrusted input, sanitize inputs with libraries like DOMPurify, use textContent instead of innerHTML, and avoid inline event handlers.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'advanced'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: DOM-based XSS only occurs on the server side.',
      'Evaluate whether this statement is true or false.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"DOM-based XSS occurs entirely on the client-side, manipulating the DOM with JavaScript."},{"id":"o2","text":"False","isCorrect":false,"explanation":"DOM-based XSS occurs entirely on the client-side, manipulating the DOM with JavaScript."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which practices reduce the risk of XSS in frontend frameworks like React?',
      'Select all that apply.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use React’s JSX variable escaping","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize any HTML before using dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid inline event handlers","isCorrect":true,"explanation":""},{"id":"o4","text":"Store all sensitive data in localStorage","isCorrect":false,"explanation":""}]',
      'Use React’s JSX variable escaping',
      'React escapes content by default. Using DOMPurify for dangerouslySetInnerHTML and avoiding inline JS reduces XSS risk. LocalStorage is vulnerable to XSS.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between stored and reflected XSS?',
      'Explain the differences between stored (persistent) and reflected (non-persistent) XSS attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters.","isCorrect":true,"explanation":"Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters.',
      'Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between Reflected, Stored, and DOM-based XSS?',
      'Explain the three main types of XSS attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side.","isCorrect":true,"explanation":"Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side.',
      'Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following is the most dangerous type of XSS?',
      'Select the correct answer.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"DOM-based XSS","isCorrect":false,"explanation":""},{"id":"o2","text":"Reflected XSS","isCorrect":false,"explanation":""},{"id":"o3","text":"Stored XSS","isCorrect":true,"explanation":""},{"id":"o4","text":"All are equally dangerous","isCorrect":false,"explanation":""}]',
      'Stored XSS',
      'Stored XSS is persistent and can affect all users who visit the page, making it the most dangerous.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are common mitigation strategies against XSS?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Input validation and sanitization","isCorrect":true,"explanation":""},{"id":"o2","text":"Using HttpOnly cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid inline scripts and use external scripts","isCorrect":true,"explanation":""},{"id":"o4","text":"Use eval() to encode input","isCorrect":false,"explanation":""}]',
      'Input validation and sanitization',
      'Validating/sanitizing inputs, HttpOnly cookies, and avoiding inline scripts help prevent XSS. Using eval() is unsafe.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Using HTTPS alone fully protects against XSS attacks.',
      'Evaluate this statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"HTTPS protects data in transit but does not prevent injection of malicious scripts in the browser."},{"id":"o2","text":"False","isCorrect":false,"explanation":"HTTPS protects data in transit but does not prevent injection of malicious scripts in the browser."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent XSS when displaying user-generated content?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Escape HTML before rendering","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize input using libraries like DOMPurify","isCorrect":true,"explanation":""},{"id":"o3","text":"Use dangerouslySetInnerHTML without sanitization","isCorrect":false,"explanation":""},{"id":"o4","text":"Implement Content Security Policy (CSP)","isCorrect":true,"explanation":""}]',
      'Escape HTML before rendering',
      'Escape and sanitize user content, and enforce CSP. Avoid unsanitized dangerouslySetInnerHTML as it introduces XSS vulnerabilities.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between stored and reflected XSS?',
      'Select the correct statements.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Stored XSS persists in the database and affects multiple users","isCorrect":true,"explanation":""},{"id":"o2","text":"Reflected XSS occurs immediately and is non-persistent","isCorrect":true,"explanation":""},{"id":"o3","text":"Reflected XSS stores payload in server database","isCorrect":false,"explanation":""},{"id":"o4","text":"Stored XSS is less dangerous than reflected XSS","isCorrect":false,"explanation":""}]',
      'Stored XSS persists in the database and affects multiple users',
      'Stored XSS is persistent and affects all users viewing the content; reflected XSS is immediate, targeting a single user through crafted requests.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between DOM-based XSS and Stored XSS?',
      'Select the correct description.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"DOM-based XSS executes purely on the client side","isCorrect":true,"explanation":""},{"id":"o2","text":"Stored XSS persists in a database or storage and affects multiple users","isCorrect":true,"explanation":""},{"id":"o3","text":"DOM-based XSS stores payloads on the server","isCorrect":false,"explanation":""},{"id":"o4","text":"Stored XSS only affects a single user","isCorrect":false,"explanation":""}]',
      'DOM-based XSS executes purely on the client side',
      'DOM-based XSS runs in the browser, while Stored XSS is saved in server-side storage and executed when other users access it.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why should you avoid using inline scripts in your frontend code?',
      'Explain the security risk associated with inline JavaScript.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code.","isCorrect":true,"explanation":"Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code.',
      'Inline scripts can easily be exploited by attackers in XSS attacks. Using external scripts and event bindings reduces the risk of executing malicious code.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why is sanitizing user input important in frontend security?',
      'Explain the consequences of unsanitized inputs.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking.","isCorrect":true,"explanation":"Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking.',
      'Unsanitized input can contain scripts or HTML that execute in the user''s browser, leading to XSS attacks, data theft, or session hijacking.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the risk of using eval() in frontend JavaScript?',
      'Explain why eval() can be dangerous in web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks.","isCorrect":true,"explanation":"eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks.',
      'eval() executes arbitrary strings as code, which can lead to remote code execution if user input is passed, making applications vulnerable to XSS and other attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you mitigate XSS in React applications?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use JSX curly braces to escape content","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize any user-generated HTML before using dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o3","text":"Use external scripts instead of inline scripts","isCorrect":true,"explanation":""},{"id":"o4","text":"Store session tokens in localStorage without encryption","isCorrect":false,"explanation":""}]',
      'Use JSX curly braces to escape content',
      'React automatically escapes content in JSX. Any HTML inserted via dangerouslySetInnerHTML must be sanitized. Avoid storing sensitive tokens insecurely.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are common signs that a website might be vulnerable to XSS?',
      'Select all applicable options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"User input is reflected without sanitization","isCorrect":true,"explanation":""},{"id":"o2","text":"Using dangerouslySetInnerHTML without sanitation","isCorrect":true,"explanation":""},{"id":"o3","text":"Input validation for forms","isCorrect":false,"explanation":""},{"id":"o4","text":"Content loaded dynamically from unknown sources","isCorrect":true,"explanation":""}]',
      'User input is reflected without sanitization',
      'Reflected input, unsanitized HTML rendering, and dynamic content from untrusted sources are common XSS vulnerabilities.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can React’s default escaping help prevent XSS?',
      'Select the correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Automatically escapes data in JSX expressions","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents execution of scripts in user content","isCorrect":true,"explanation":""},{"id":"o3","text":"Replaces the need for server-side validation","isCorrect":false,"explanation":""},{"id":"o4","text":"Removes all HTML from user input","isCorrect":false,"explanation":""}]',
      'Automatically escapes data in JSX expressions',
      'React escapes data in JSX, preventing scripts from executing. However, server-side validation is still required.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-scripting-xss', 'xss', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.321Z',
      '2025-11-18T18:46:59.321Z',
      NULL,
      300
    );