INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is the purpose of the View Transitions API?',
      'It provides a simple way to animate visual DOM changes between two states, enabling smooth transitions between UI views or pages.',
      'multiple-choice',
      'intermediate',
      10,
      '["To animate data fetching operations","To transition visual changes between DOM states smoothly","To handle form validation errors visually","To optimize network requests"]',
      '',
      'It provides a simple way to animate visual DOM changes between two states, enabling smooth transitions between UI views or pages.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which method is central to the View Transitions API?',
      'The document.startViewTransition(callback) method initiates a view transition and calls the provided callback to update the DOM.',
      'multiple-choice',
      'intermediate',
      10,
      '["document.animateTransition()","window.beginViewChange()","document.startViewTransition()","window.transitionTo()"]',
      '',
      'The document.startViewTransition(callback) method initiates a view transition and calls the provided callback to update the DOM.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What does document.startViewTransition(callback) do before executing the callback?',
      'It takes a screenshot of the current DOM state before applying the callback changes.',
      'multiple-choice',
      'intermediate',
      10,
      '["Preloads all CSS animations","Takes a screenshot of the current DOM","Stores a snapshot of localStorage","Pauses all event listeners"]',
      '',
      'It takes a screenshot of the current DOM state before applying the callback changes.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS pseudo-elements allow developers to style the before and after states of a transition?',
      'Developers can use ::view-transition-old(root) and ::view-transition-new(root) to style the old and new DOM states during a transition.',
      'multiple-choice',
      'intermediate',
      10,
      '["::before and ::after","::view-transition-old(root) and ::view-transition-new(root)","::transition-old and ::transition-new","::prev-state and ::next-state"]',
      '',
      'Developers can use ::view-transition-old(root) and ::view-transition-new(root) to style the old and new DOM states during a transition.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of view-transition-name in the View Transitions API?',
      'It assigns a unique name to elements so that matching elements across states can be smoothly animated together.',
      'multiple-choice',
      'intermediate',
      10,
      '["It defines a CSS keyframe","It assigns an animation ID for transitions","It uniquely identifies elements for smooth state transitions","It determines animation duration"]',
      '',
      'It assigns a unique name to elements so that matching elements across states can be smoothly animated together.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What happens to the DOM during a view transition callback?',
      'The DOM becomes non-interactive (frozen) until the callback and transition animation complete.',
      'multiple-choice',
      'advanced',
      10,
      '["The DOM remains interactive","The DOM becomes non-interactive until the callback resolves","Only CSS changes are blocked","Event listeners are temporarily removed"]',
      '',
      'The DOM becomes non-interactive (frozen) until the callback and transition animation complete.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'When should document.startViewTransition ideally be called during page navigation?',
      'After the data request completes to minimize the time the DOM is frozen and improve user experience.',
      'multiple-choice',
      'intermediate',
      10,
      '["Before sending the data request","Immediately on link click","After the data request completes","After component unmount"]',
      '',
      'After the data request completes to minimize the time the DOM is frozen and improve user experience.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can developers delay the completion of a transition?',
      'By returning a Promise from the callback, which must resolve before the animation completes.',
      'multiple-choice',
      'advanced',
      10,
      '["By using setTimeout inside the callback","By returning a Promise that resolves when the DOM update is complete","By pausing the animation manually","By re-rendering the DOM asynchronously"]',
      '',
      'By returning a Promise from the callback, which must resolve before the animation completes.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which React lifecycle method is used in the example to prevent premature rendering during a transition?',
      'shouldComponentUpdate() is overridden to return false, delaying rendering until the view transition begins.',
      'multiple-choice',
      'advanced',
      10,
      '["componentDidMount()","componentWillUnmount()","shouldComponentUpdate()","getSnapshotBeforeUpdate()"]',
      '',
      'shouldComponentUpdate() is overridden to return false, delaying rendering until the view transition begins.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What does the componentDidUpdate() method do in the React example?',
      'It resolves the promise returned during the DOM update, notifying the View Transition API that the DOM has been updated.',
      'multiple-choice',
      'advanced',
      10,
      '["Starts a new transition","Forces a DOM re-render","Resolves the update promise for the transition","Triggers a fade-out animation"]',
      '',
      'It resolves the promise returned during the DOM update, notifying the View Transition API that the DOM has been updated.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why is React’s strict mode disabled in the Next.js example?',
      'Because React’s strict mode causes double rendering in development, interfering with the transition flow.',
      'multiple-choice',
      'intermediate',
      10,
      '["It breaks routing","It prevents componentDidUpdate from firing","It causes components to render twice and disrupts transitions","It disables animation hooks"]',
      '',
      'Because React’s strict mode causes double rendering in development, interfering with the transition flow.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the main limitation of using the View Transitions API for page transitions?',
      'It requires the new page HTML to be available before animating, potentially delaying feedback for users.',
      'multiple-choice',
      'advanced',
      10,
      '["It only supports inline styles","It can’t animate DOM elements","It needs new page HTML before animating","It blocks network requests"]',
      '',
      'It requires the new page HTML to be available before animating, potentially delaying feedback for users.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the advantage of performing exit animations immediately after a link click?',
      'It provides instant feedback while waiting for the new content to load, improving perceived performance.',
      'multiple-choice',
      'intermediate',
      10,
      '["It improves SEO performance","It reduces memory usage","It offers immediate visual feedback to the user","It prevents animation jank"]',
      '',
      'It provides instant feedback while waiting for the new content to load, improving perceived performance.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which library enhances server-side rendered MPAs with SPA-like speeds by replacing the <body> with new HTML from the response?',
      'Turbo, part of the Hotwire suite, enhances MPAs by replacing the page body dynamically using JavaScript.',
      'multiple-choice',
      'intermediate',
      10,
      '["Turn","Turbo","Astro","Remix"]',
      '',
      'Turbo, part of the Hotwire suite, enhances MPAs by replacing the page body dynamically using JavaScript.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Turn used for in combination with Turbo?',
      'Turn handles animating page navigations by adding classes like turn-exit and turn-enter to trigger CSS transitions.',
      'multiple-choice',
      'intermediate',
      10,
      '["It performs server rendering","It adds routing capabilities","It animates page navigations via CSS classes","It caches HTML responses"]',
      '',
      'Turn handles animating page navigations by adding classes like turn-exit and turn-enter to trigger CSS transitions.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which events does Turn hook into to manage the flow of page animations?',
      'Turn listens to Turbo events such as turbo:visit, turbo:before-render, and turbo:render to control animations.',
      'multiple-choice',
      'advanced',
      10,
      '["turbo:start and turbo:end","turbo:visit, turbo:before-render, turbo:render","turbo:click and turbo:load","animationstart and animationend"]',
      '',
      'Turn listens to Turbo events such as turbo:visit, turbo:before-render, and turbo:render to control animations.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What does setting Turn.config.experimental.viewTransitions = true enable?',
      'It activates experimental support for the View Transitions API, falling back to CSS animations when unsupported.',
      'multiple-choice',
      'advanced',
      10,
      '["It disables animations completely","It enables experimental view transitions with fallback","It triggers full page reloads","It forces server-side rendering"]',
      '',
      'It activates experimental support for the View Transitions API, falling back to CSS animations when unsupported.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the main design trade-off between the View Transitions API and traditional exit animations?',
      'The View Transitions API can animate shared elements across pages but requires waiting for new content, while exit animations give instant feedback but can’t transition shared elements.',
      'multiple-choice',
      'advanced',
      10,
      '["View transitions are faster in all cases","Exit animations support cross-page element morphing","View transitions handle shared elements but may delay feedback","Exit animations require the new HTML before starting"]',
      '',
      'The View Transitions API can animate shared elements across pages but requires waiting for new content, while exit animations give instant feedback but can’t transition shared elements.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'advanced-patterns', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Client-Side Rendering (CSR) Fundamentals',
      'What happens during the Client-Side Rendering (CSR) process in a React application?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"In CSR, the browser loads a minimal HTML shell and JavaScript bundles.","isCorrect":true,"explanation":"In CSR, the browser loads a minimal HTML shell and JavaScript bundles."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'In CSR, the browser loads a minimal HTML shell and JavaScript bundles.',
      'In CSR, the browser loads a minimal HTML shell and JavaScript bundles.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'CSR and SEO Challenges',
      'Why can Client-Side Rendering negatively affect SEO?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Search engines struggle to index JavaScript-rendered pages","isCorrect":true},{"id":"b","text":"CSR prevents the use of meta tags","isCorrect":false},{"id":"c","text":"CSR makes sites slower for all users","isCorrect":false}]',
      'Search engines struggle to index JavaScript-rendered pages',
      'Search engines struggle to index JavaScript-rendered pages',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Improving CSR Performance',
      'What is a common technique to improve perceived performance in Client-Side Rendering?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use code-splitting and lazy loading to reduce the initial bundle size.","isCorrect":true,"explanation":"Use code-splitting and lazy loading to reduce the initial bundle size."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Use code-splitting and lazy loading to reduce the initial bundle size.',
      'Use code-splitting and lazy loading to reduce the initial bundle size.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'CSR vs SSR Trade-offs',
      'Which of the following best describes the difference between CSR and SSR?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"CSR renders pages on the client, SSR renders them on the server before sending HTML","isCorrect":true},{"id":"b","text":"SSR requires no JavaScript on the client","isCorrect":false},{"id":"c","text":"CSR is faster than SSR in all cases","isCorrect":false}]',
      'CSR renders pages on the client, SSR renders them on the server before sending HTML',
      'CSR renders pages on the client, SSR renders them on the server before sending HTML',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Islands Architecture Concept',
      'What is the core principle of the Islands Architecture pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client.","isCorrect":true,"explanation":"Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client.',
      'Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Dynamic Islands Example',
      'Which of these is an example of a dynamic island on a static page?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"A social media share widget inside a static blog post","isCorrect":true},{"id":"b","text":"Static article text with no JavaScript","isCorrect":false},{"id":"c","text":"Server-rendered navigation bar","isCorrect":false}]',
      'A social media share widget inside a static blog post',
      'A social media share widget inside a static blog post',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Partial Hydration',
      'How does Partial Hydration improve performance in the Islands Architecture?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"It allows each component to hydrate independently rather than rehydrating the entire page.","isCorrect":true,"explanation":"It allows each component to hydrate independently rather than rehydrating the entire page."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'It allows each component to hydrate independently rather than rehydrating the entire page.',
      'It allows each component to hydrate independently rather than rehydrating the entire page.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Frameworks Supporting Islands',
      'Which frameworks natively support Islands Architecture?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Astro and Marko","isCorrect":true},{"id":"b","text":"Next.js only","isCorrect":false},{"id":"c","text":"Create React App","isCorrect":false}]',
      'Astro and Marko',
      'Astro and Marko',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Advantages of Islands Architecture',
      'What are some benefits of adopting the Islands Architecture?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Reduces the amount of JavaScript shipped to the client.","isCorrect":true,"explanation":"Reduces the amount of JavaScript shipped to the client."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Reduces the amount of JavaScript shipped to the client.',
      'Reduces the amount of JavaScript shipped to the client.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Limitations of Islands Architecture',
      'What is a limitation of the Islands Architecture approach?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"It’s difficult to scale for highly interactive apps like social media feeds","isCorrect":true},{"id":"b","text":"It cannot be used with React","isCorrect":false},{"id":"c","text":"It requires a full backend rewrite","isCorrect":false}]',
      'It’s difficult to scale for highly interactive apps like social media feeds',
      'It’s difficult to scale for highly interactive apps like social media feeds',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'client-side-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Edge Rendering Basics',
      'What is Edge Rendering and how does it differ from traditional SSR?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Edge Rendering executes server-side logic at CDN edge locations, closer to the user.","isCorrect":true,"explanation":"Edge Rendering executes server-side logic at CDN edge locations, closer to the user."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Edge Rendering executes server-side logic at CDN edge locations, closer to the user.',
      'Edge Rendering executes server-side logic at CDN edge locations, closer to the user.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Advantages of Edge Rendering',
      'Which of the following is a main advantage of Edge Rendering?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Reduced latency due to geographical proximity to users","isCorrect":true},{"id":"b","text":"It replaces all client-side rendering logic","isCorrect":false},{"id":"c","text":"It always increases server costs","isCorrect":false}]',
      'Reduced latency due to geographical proximity to users',
      'Reduced latency due to geographical proximity to users',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Edge vs CDN Caching',
      'How is Edge Rendering different from traditional CDN caching?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge.","isCorrect":true,"explanation":"CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge.',
      'CDN caching serves static assets, while Edge Rendering runs dynamic server code at the edge.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Progressive Hydration Concept',
      'What is Progressive Hydration in React or similar frameworks?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"It hydrates parts of the UI gradually as JavaScript loads or user interacts","isCorrect":true},{"id":"b","text":"It waits until all components are fully loaded before rendering anything","isCorrect":false},{"id":"c","text":"It disables interactivity completely","isCorrect":false}]',
      'It hydrates parts of the UI gradually as JavaScript loads or user interacts',
      'It hydrates parts of the UI gradually as JavaScript loads or user interacts',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why Progressive Hydration Matters',
      'Why is Progressive Hydration beneficial for large, complex pages?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates.","isCorrect":true,"explanation":"It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates.',
      'It reduces the blocking time by enabling interaction in critical parts of the page before the entire app hydrates.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Resumability Explained',
      'What is Resumability in frameworks like Qwik?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Resumability allows the browser to resume application execution without rehydrating all components.","isCorrect":true,"explanation":"Resumability allows the browser to resume application execution without rehydrating all components."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Resumability allows the browser to resume application execution without rehydrating all components.',
      'Resumability allows the browser to resume application execution without rehydrating all components.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Resumability vs Hydration',
      'How does Resumability differ from traditional hydration?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"Resumability skips full rehydration by resuming the app state directly from serialized data","isCorrect":true},{"id":"b","text":"Resumability re-renders everything on the server","isCorrect":false},{"id":"c","text":"They are the same process with different names","isCorrect":false}]',
      'Resumability skips full rehydration by resuming the app state directly from serialized data',
      'Resumability skips full rehydration by resuming the app state directly from serialized data',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'React Server Components (RSC) Role',
      'How do React Server Components improve rendering performance?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size.","isCorrect":true,"explanation":"RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size.',
      'RSCs allow heavy computation and data fetching to happen on the server, reducing client bundle size.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Streaming + RSC Integration',
      'What benefit do we get when combining React Server Components with streaming rendering?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"Users see parts of the UI sooner while server components load progressively","isCorrect":true},{"id":"b","text":"It delays rendering until all components are ready","isCorrect":false},{"id":"c","text":"It removes the need for client components entirely","isCorrect":false}]',
      'Users see parts of the UI sooner while server components load progressively',
      'Users see parts of the UI sooner while server components load progressively',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Choosing Rendering Strategy',
      'How should a developer decide between SSR, ISR, Edge, and Resumable approaches?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration.","isCorrect":true,"explanation":"Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration.',
      'Use SSR for dynamic personalized content, ISR for semi-static content, Edge Rendering for global low-latency responses, and Resumability for ultra-fast interactivity without full hydration.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'edge-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Incremental Static Regeneration (ISR) Basics',
      'What problem does Incremental Static Regeneration (ISR) solve compared to standard static generation?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"ISR allows pages to be updated after the initial build without rebuilding the entire site.","isCorrect":true,"explanation":"ISR allows pages to be updated after the initial build without rebuilding the entire site."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'ISR allows pages to be updated after the initial build without rebuilding the entire site.',
      'ISR allows pages to be updated after the initial build without rebuilding the entire site.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'ISR Workflow',
      'How does ISR update static pages over time?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"It regenerates pages on-demand when a user visits an outdated page","isCorrect":true},{"id":"b","text":"It rebuilds the entire website daily","isCorrect":false},{"id":"c","text":"It updates pages manually via admin dashboard","isCorrect":false}]',
      'It regenerates pages on-demand when a user visits an outdated page',
      'It regenerates pages on-demand when a user visits an outdated page',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Revalidation in ISR',
      'What does the ''revalidate'' field do in Next.js Incremental Static Regeneration?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It defines how often a static page should be regenerated in the background.","isCorrect":true,"explanation":"It defines how often a static page should be regenerated in the background."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'It defines how often a static page should be regenerated in the background.',
      'It defines how often a static page should be regenerated in the background.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'ISR and Performance',
      'Why does ISR improve performance compared to SSR for frequently accessed pages?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"ISR caches pre-rendered pages at the edge and avoids regenerating on every request","isCorrect":true},{"id":"b","text":"ISR avoids hydration completely","isCorrect":false},{"id":"c","text":"ISR runs entirely on the client","isCorrect":false}]',
      'ISR caches pre-rendered pages at the edge and avoids regenerating on every request',
      'ISR caches pre-rendered pages at the edge and avoids regenerating on every request',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'On-Demand ISR',
      'How is On-Demand ISR different from regular ISR?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals.","isCorrect":true,"explanation":"On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals.',
      'On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Use Case for On-Demand ISR',
      'When should you prefer On-Demand ISR over time-based ISR?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"When content changes are event-driven, such as CMS updates","isCorrect":true},{"id":"b","text":"When your website never changes","isCorrect":false},{"id":"c","text":"When you have no API data","isCorrect":false}]',
      'When content changes are event-driven, such as CMS updates',
      'When content changes are event-driven, such as CMS updates',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Streaming Server-Side Rendering',
      'What is the main benefit of streaming SSR compared to traditional SSR?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint.","isCorrect":true,"explanation":"Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint.',
      'Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'React Server Components (RSC)',
      'What role do React Server Components play in modern rendering strategies?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"They allow parts of React components to render on the server without sending unnecessary JavaScript to the client","isCorrect":true},{"id":"b","text":"They replace all client-side interactivity","isCorrect":false},{"id":"c","text":"They only work in static generation","isCorrect":false}]',
      'They allow parts of React components to render on the server without sending unnecessary JavaScript to the client',
      'They allow parts of React components to render on the server without sending unnecessary JavaScript to the client',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Edge SSR and Cold Boots',
      'Why is Edge SSR often faster than traditional serverless SSR?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Edge SSR runs closer to users, reducing latency and cold boot times.","isCorrect":true,"explanation":"Edge SSR runs closer to users, reducing latency and cold boot times."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'Edge SSR runs closer to users, reducing latency and cold boot times.',
      'Edge SSR runs closer to users, reducing latency and cold boot times.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Choosing Between Patterns',
      'When should you choose SSR over ISR or Static Generation?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"When your page depends on highly personalized data that changes per user request","isCorrect":true},{"id":"b","text":"When the content is static and rarely changes","isCorrect":false},{"id":"c","text":"When build times are slow","isCorrect":false}]',
      'When your page depends on highly personalized data that changes per user request',
      'When your page depends on highly personalized data that changes per user request',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'hybrid-rendering', 'advanced'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Understanding Islands Architecture',
      'What is the core idea behind the Islands Architecture rendering pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML.","isCorrect":true,"explanation":"It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review rendering pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider rendering strategy best practices.","isCorrect":false,"explanation":""}]',
      'It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML.',
      'It divides a web page into small independent interactive sections called islands, while keeping the rest of the page static HTML.',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'islands-architecture', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Islands vs Client-Side Rendering',
      'How does Islands Architecture differ from traditional Client-Side Rendering (CSR)?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"CSR loads all JavaScript at once, while Islands only hydrate interactive components","isCorrect":true},{"id":"b","text":"Islands Architecture doesn’t support user interactions","isCorrect":false},{"id":"c","text":"CSR is faster than Islands because it’s fully client-driven","isCorrect":false}]',
      'CSR loads all JavaScript at once, while Islands only hydrate interactive components',
      'CSR loads all JavaScript at once, while Islands only hydrate interactive components',
      NULL,
      ARRAY['Review rendering pattern documentation', 'Consider server vs client rendering trade-offs', 'Think about performance and SEO implications'],
      ARRAY['rendering-patterns', 'islands-architecture', 'intermediate'],
      '{}',
      NULL,
      'e66965de-3197-4e60-b774-25958009d094',
      NULL,
      true,
      '2025-11-18T18:46:59.316Z',
      '2025-11-18T18:46:59.316Z',
      NULL,
      300
    );