INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is Static Import in JavaScript modules?',
      'Static Import uses the ES2015 <code>import</code> keyword to bring in code from another module. These imports are bundled at build time and included in the initial JavaScript bundle, meaning they are executed as soon as the module is loaded.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"A","1":" ","2":"w","3":"a","4":"y","5":" ","6":"t","7":"o","8":" ","9":"i","10":"m","11":"p","12":"o","13":"r","14":"t","15":" ","16":"m","17":"o","18":"d","19":"u","20":"l","21":"e","22":"s","23":" ","24":"d","25":"y","26":"n","27":"a","28":"m","29":"i","30":"c","31":"a","32":"l","33":"l","34":"y","35":" ","36":"a","37":"t","38":" ","39":"r","40":"u","41":"n","42":"t","43":"i","44":"m","45":"e","explanation":""},{"0":"A","1":" ","2":"w","3":"a","4":"y","5":" ","6":"t","7":"o","8":" ","9":"i","10":"m","11":"p","12":"o","13":"r","14":"t","15":" ","16":"m","17":"o","18":"d","19":"u","20":"l","21":"e","22":"s","23":" ","24":"a","25":"t","26":" ","27":"b","28":"u","29":"i","30":"l","31":"d","32":" ","33":"t","34":"i","35":"m","36":"e","37":",","38":" ","39":"i","40":"n","41":"c","42":"l","43":"u","44":"d","45":"e","46":"d","47":" ","48":"i","49":"n","50":" ","51":"t","52":"h","53":"e","54":" ","55":"i","56":"n","57":"i","58":"t","59":"i","60":"a","61":"l","62":" ","63":"b","64":"u","65":"n","66":"d","67":"l","68":"e","explanation":""},{"0":"A","1":" ","2":"f","3":"e","4":"a","5":"t","6":"u","7":"r","8":"e","9":" ","10":"o","11":"n","12":"l","13":"y","14":" ","15":"a","16":"v","17":"a","18":"i","19":"l","20":"a","21":"b","22":"l","23":"e","24":" ","25":"i","26":"n","27":" ","28":"N","29":"o","30":"d","31":"e","32":".","33":"j","34":"s","explanation":""},{"0":"A","1":" ","2":"m","3":"e","4":"t","5":"h","6":"o","7":"d","8":" ","9":"t","10":"o","11":" ","12":"l","13":"a","14":"z","15":"y","16":" ","17":"l","18":"o","19":"a","20":"d","21":" ","22":"m","23":"o","24":"d","25":"u","26":"l","27":"e","28":"s","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does static import affect bundle size and performance?',
      'All statically imported modules are bundled into the main JavaScript file (e.g., <code>main.bundle.js</code> in Webpack). Larger bundles can slow down initial page load, since the browser must download, parse, and execute everything before rendering the UI.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Static imports increase bundle size since everything is loaded upfront.","isCorrect":true,"explanation":"Static imports increase bundle size since everything is loaded upfront. They can hurt performance by delaying time-to-interactive, especially on slow networks or devices. Using too many static imports for rarely used components leads to wasted resources."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Static imports increase bundle size since everything is loaded upfront.',
      'Static imports increase bundle size since everything is loaded upfront. They can hurt performance by delaying time-to-interactive, especially on slow networks or devices. Using too many static imports for rarely used components leads to wasted resources.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'In the chat app example, which components were statically imported?',
      'In the given example, the <code>App</code> component statically imports <code>UserInfo</code>, <code>ChatList</code>, and <code>ChatInput</code>. The <code>ChatInput</code> component itself statically imports <code>EmojiPicker</code>.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"O","1":"n","2":"l","3":"y","4":" ","5":"U","6":"s","7":"e","8":"r","9":"I","10":"n","11":"f","12":"o","13":" ","14":"a","15":"n","16":"d","17":" ","18":"C","19":"h","20":"a","21":"t","22":"L","23":"i","24":"s","25":"t","explanation":""},{"0":"U","1":"s","2":"e","3":"r","4":"I","5":"n","6":"f","7":"o","8":",","9":" ","10":"C","11":"h","12":"a","13":"t","14":"L","15":"i","16":"s","17":"t","18":",","19":" ","20":"a","21":"n","22":"d","23":" ","24":"C","25":"h","26":"a","27":"t","28":"I","29":"n","30":"p","31":"u","32":"t","33":" ","34":"(","35":"w","36":"h","37":"i","38":"c","39":"h","40":" ","41":"i","42":"n","43":"c","44":"l","45":"u","46":"d","47":"e","48":"s","49":" ","50":"E","51":"m","52":"o","53":"j","54":"i","55":"P","56":"i","57":"c","58":"k","59":"e","60":"r","61":")","explanation":""},{"0":"O","1":"n","2":"l","3":"y","4":" ","5":"E","6":"m","7":"o","8":"j","9":"i","10":"P","11":"i","12":"c","13":"k","14":"e","15":"r","explanation":""},{"0":"N","1":"o","2":"n","3":"e","4":" ","5":"o","6":"f","7":" ","8":"t","9":"h","10":"e","11":" ","12":"a","13":"b","14":"o","15":"v","16":"e","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the main drawback of using only static imports in a React app?',
      'If every component and dependency is statically imported, the initial bundle can become very large. This delays rendering since the browser must download and parse all modules before showing any content.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Slower initial load due to larger bundle size.","isCorrect":true,"explanation":"Slower initial load due to larger bundle size. Worse performance on mobile or slow networks. Even components not immediately needed are still loaded upfront."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Slower initial load due to larger bundle size.',
      'Slower initial load due to larger bundle size. Worse performance on mobile or slow networks. Even components not immediately needed are still loaded upfront.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does Webpack handle static imports?',
      'Webpack bundles all statically imported modules into the main bundle file. For example, <code>main.bundle.js</code> might include every statically imported component from the source code.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"I","1":"t","2":" ","3":"b","4":"u","5":"n","6":"d","7":"l","8":"e","9":"s","10":" ","11":"t","12":"h","13":"e","14":"m","15":" ","16":"o","17":"n","18":"l","19":"y","20":" ","21":"w","22":"h","23":"e","24":"n","25":" ","26":"u","27":"s","28":"e","29":"d","30":" ","31":"a","32":"t","33":" ","34":"r","35":"u","36":"n","37":"t","38":"i","39":"m","40":"e","explanation":""},{"0":"I","1":"t","2":" ","3":"s","4":"p","5":"l","6":"i","7":"t","8":"s","9":" ","10":"t","11":"h","12":"e","13":"m","14":" ","15":"i","16":"n","17":"t","18":"o","19":" ","20":"s","21":"e","22":"p","23":"a","24":"r","25":"a","26":"t","27":"e","28":" ","29":"f","30":"i","31":"l","32":"e","33":"s","34":" ","35":"a","36":"u","37":"t","38":"o","39":"m","40":"a","41":"t","42":"i","43":"c","44":"a","45":"l","46":"l","47":"y","explanation":""},{"0":"I","1":"t","2":" ","3":"i","4":"n","5":"c","6":"l","7":"u","8":"d","9":"e","10":"s","11":" ","12":"a","13":"l","14":"l","15":" ","16":"s","17":"t","18":"a","19":"t","20":"i","21":"c","22":"a","23":"l","24":"l","25":"y","26":" ","27":"i","28":"m","29":"p","30":"o","31":"r","32":"t","33":"e","34":"d","35":" ","36":"m","37":"o","38":"d","39":"u","40":"l","41":"e","42":"s","43":" ","44":"i","45":"n","46":"t","47":"o","48":" ","49":"t","50":"h","51":"e","52":" ","53":"m","54":"a","55":"i","56":"n","57":" ","58":"b","59":"u","60":"n","61":"d","62":"l","63":"e","explanation":""},{"0":"I","1":"t","2":" ","3":"i","4":"g","5":"n","6":"o","7":"r","8":"e","9":"s","10":" ","11":"t","12":"h","13":"e","14":"m","15":" ","16":"u","17":"n","18":"l","19":"e","20":"s","21":"s","22":" ","23":"e","24":"x","25":"p","26":"l","27":"i","28":"c","29":"i","30":"t","31":"l","32":"y","33":" ","34":"c","35":"o","36":"n","37":"f","38":"i","39":"g","40":"u","41":"r","42":"e","43":"d","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'When should you avoid static imports?',
      'Avoid static imports for components that are not immediately necessary on page load, such as modals, tooltips, or rarely used features. Instead, load them dynamically to improve performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"When the component is behind a user action (e.g., clicking a button).","isCorrect":true,"explanation":"When the component is behind a user action (e.g., clicking a button). When the component is not critical for the initial render. When optimizing for smaller bundle sizes and faster loads."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'When the component is behind a user action (e.g., clicking a button).',
      'When the component is behind a user action (e.g., clicking a button). When the component is not critical for the initial render. When optimizing for smaller bundle sizes and faster loads.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Compare Static Import vs Dynamic Import.',
      'Static import loads all modules upfront at build time, increasing initial bundle size. Dynamic import (<code>import()</code>) loads modules only when needed (e.g., on user interaction), improving load performance but adding runtime overhead.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Static imports are eager, dynamic imports are lazy.","isCorrect":true,"explanation":"Static imports are eager, dynamic imports are lazy. Static imports bundle everything, dynamic imports support code-splitting. Static imports run immediately, dynamic imports return a promise."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Static imports are eager, dynamic imports are lazy.',
      'Static imports are eager, dynamic imports are lazy. Static imports bundle everything, dynamic imports support code-splitting. Static imports run immediately, dynamic imports return a promise.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What performance optimization can replace some static imports in the chat app example?',
      'Instead of statically importing the <code>EmojiPicker</code>, we can dynamically import it when the user opens the emoji panel. This reduces initial bundle size and speeds up app load.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"S","1":"t","2":"a","3":"t","4":"i","5":"c","6":" ","7":"e","8":"x","9":"p","10":"o","11":"r","12":"t","explanation":""},{"0":"D","1":"y","2":"n","3":"a","4":"m","5":"i","6":"c","7":" ","8":"i","9":"m","10":"p","11":"o","12":"r","13":"t","14":" ","15":"(","16":"`","17":"i","18":"m","19":"p","20":"o","21":"r","22":"t","23":"(","24":")","25":"`","26":")","explanation":""},{"0":"T","1":"r","2":"e","3":"e","4":" ","5":"s","6":"h","7":"a","8":"k","9":"i","10":"n","11":"g","explanation":""},{"0":"C","1":"o","2":"d","3":"e","4":" ","5":"m","6":"i","7":"n","8":"i","9":"f","10":"i","11":"c","12":"a","13":"t","14":"i","15":"o","16":"n","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Provider Pattern Basics',
      'What problem does the Provider Pattern primarily solve in React applications?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It solves the issue of prop drilling by allowing components to access shared state directly through context.","isCorrect":true,"explanation":"It solves the issue of prop drilling by allowing components to access shared state directly through context. It provides a way to make global state or values accessible to deeply nested components without passing props manually."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'It solves the issue of prop drilling by allowing components to access shared state directly through context.',
      'It solves the issue of prop drilling by allowing components to access shared state directly through context. It provides a way to make global state or values accessible to deeply nested components without passing props manually.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Prop Drilling',
      'Which of the following best describes ''prop drilling''?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Passing props through multiple components that don’t use them","isCorrect":true,"explanation":""},{"id":"b","text":"Drilling into the DOM with refs","isCorrect":false,"explanation":""},{"id":"c","text":"Creating deeply nested providers","isCorrect":false,"explanation":""}]',
      'Passing props through multiple components that don’t use them',
      'The correct answer is: Passing props through multiple components that don’t use them',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'useContext Hook',
      'In React, how does a component consume values from a Provider?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"By using the useContext hook with the context object created via React.createContext().","isCorrect":true,"explanation":"By using the useContext hook with the context object created via React.createContext(). The component calls useContext(SomeContext) to directly access the value provided by the Provider."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'By using the useContext hook with the context object created via React.createContext().',
      'By using the useContext hook with the context object created via React.createContext(). The component calls useContext(SomeContext) to directly access the value provided by the Provider.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Provider Pattern Code',
      'What will be rendered by the Header component in this example?

<pre><code>const DataContext = React.createContext();

function App() {
  const data = { title: ''Hello Provider'' };
  return (
    &lt;DataContext.Provider value={data}&gt;
      &lt;Header /&gt;
    &lt;/DataContext.Provider&gt;
  );
}

function Header() {
  const data = React.useContext(DataContext);
  return &lt;h1&gt;{data.title}&lt;/h1&gt;;
}</code></pre>',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Nothing, React throws an error","isCorrect":false,"explanation":""},{"id":"b","text":"h1 with text ''Hello Provider''","isCorrect":true,"explanation":""},{"id":"c","text":"h1 with text ''undefined''","isCorrect":false,"explanation":""}]',
      'h1 with text ''Hello Provider''',
      'The correct answer is: h1 with text ''Hello Provider''',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Performance Concern',
      'What is a potential downside of overusing the Provider Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"All components consuming the context re-render whenever the value changes, which can hurt performance in large apps.","isCorrect":true,"explanation":"All components consuming the context re-render whenever the value changes, which can hurt performance in large apps. It can cause unnecessary re-renders if too much state is stored in a single provider."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'All components consuming the context re-render whenever the value changes, which can hurt performance in large apps.',
      'All components consuming the context re-render whenever the value changes, which can hurt performance in large apps. It can cause unnecessary re-renders if too much state is stored in a single provider.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Theme Provider Use Case',
      'Why is the Provider Pattern a good fit for managing application themes (dark/light mode)?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Because many components need access to the theme, and the Provider allows sharing it globally without prop drilling.","isCorrect":true,"explanation":"Because many components need access to the theme, and the Provider allows sharing it globally without prop drilling. It centralizes theme state and makes it easy to toggle or update across the entire app."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Because many components need access to the theme, and the Provider allows sharing it globally without prop drilling.',
      'Because many components need access to the theme, and the Provider allows sharing it globally without prop drilling. It centralizes theme state and makes it easy to toggle or update across the entire app.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Multiple Providers',
      'How can you avoid unnecessary re-renders when using Providers for frequently changing values?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"By splitting contexts into multiple smaller providers so that components only re-render when the specific value they consume changes.","isCorrect":true,"explanation":"By splitting contexts into multiple smaller providers so that components only re-render when the specific value they consume changes. Using memoization or selective context providers to isolate updates."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'By splitting contexts into multiple smaller providers so that components only re-render when the specific value they consume changes.',
      'By splitting contexts into multiple smaller providers so that components only re-render when the specific value they consume changes. Using memoization or selective context providers to isolate updates.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Custom Hook for Context',
      'What is the benefit of creating a custom hook like <code>useThemeContext()</code> instead of calling <code>useContext(ThemeContext)</code> directly in every component?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"It enforces correct usage and can throw errors if used outside the provider","isCorrect":true,"explanation":""},{"id":"b","text":"It avoids the need to import useContext at all","isCorrect":false,"explanation":""},{"id":"c","text":"It improves runtime performance automatically","isCorrect":false,"explanation":""}]',
      'It enforces correct usage and can throw errors if used outside the provider',
      'The correct answer is: It enforces correct usage and can throw errors if used outside the provider',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Provider vs Redux',
      'How does the Provider Pattern differ from using Redux for global state management?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Provider Pattern with context is simpler and built into React, but doesn’t offer advanced features like middleware, devtools, or predictable reducers.","isCorrect":true,"explanation":"Provider Pattern with context is simpler and built into React, but doesn’t offer advanced features like middleware, devtools, or predictable reducers. Redux adds structure and tooling, while Context Providers are best for simpler shared state."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Provider Pattern with context is simpler and built into React, but doesn’t offer advanced features like middleware, devtools, or predictable reducers.',
      'Provider Pattern with context is simpler and built into React, but doesn’t offer advanced features like middleware, devtools, or predictable reducers. Redux adds structure and tooling, while Context Providers are best for simpler shared state.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Styled-Components Provider',
      'What role does the ThemeProvider from styled-components play?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It provides a theme object via context so that styled components can access theme values without passing them as props.","isCorrect":true,"explanation":"It provides a theme object via context so that styled components can access theme values without passing them as props. It applies consistent design tokens (colors, spacing, etc.) across the entire component tree."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'It provides a theme object via context so that styled components can access theme values without passing them as props.',
      'It provides a theme object via context so that styled components can access theme values without passing them as props. It applies consistent design tokens (colors, spacing, etc.) across the entire component tree.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Definition of Flyweight Pattern',
      'What is the Flyweight Pattern, and why is it useful?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It’s a structural design pattern that minimizes memory usage by sharing common object data instead of creating duplicates.","isCorrect":true,"explanation":"It’s a structural design pattern that minimizes memory usage by sharing common object data instead of creating duplicates. It’s useful when creating a large number of similar objects, e.g., books with the same ISBN."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'It’s a structural design pattern that minimizes memory usage by sharing common object data instead of creating duplicates.',
      'It’s a structural design pattern that minimizes memory usage by sharing common object data instead of creating duplicates. It’s useful when creating a large number of similar objects, e.g., books with the same ISBN.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'flyweight-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Flyweight Example Output',
      'What will this code log?

<pre><code>console.log("Total amount of copies: ", bookList.length);
console.log("Total amount of books: ", isbnNumbers.size);</code></pre>
After adding 5 copies of 3 different books, what is the output?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Total amount of copies: 5, Total amount of books: 5","isCorrect":false,"explanation":""},{"id":"b","text":"Total amount of copies: 3, Total amount of books: 5","isCorrect":false,"explanation":""},{"id":"c","text":"Total amount of copies: 5, Total amount of books: 3","isCorrect":true,"explanation":""}]',
      'Total amount of copies: 5, Total amount of books: 3',
      'The correct answer is: Total amount of copies: 5, Total amount of books: 3',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Advantages of Flyweight Pattern',
      'Which of the following are advantages of the Flyweight Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Reduced memory usage by reusing objects","isCorrect":true,"explanation":""},{"id":"b","text":"Improved performance for large-scale applications","isCorrect":true,"explanation":""},{"id":"c","text":"Simplifies debugging","isCorrect":false,"explanation":""},{"id":"d","text":"Reduces network latency","isCorrect":false,"explanation":""}]',
      'Reduced memory usage by reusing objects',
      'The correct answer is: Reduced memory usage by reusing objects',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Validation with Proxies',
      'How can the Proxy pattern help with data validation? Give an example.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"No explanation provided","isCorrect":true,"explanation":"No explanation provided."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'No explanation provided',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Logging Changes',
      'Write a proxy that prevents setting <code>age</code> to a non-numeric value and logs attempts with an error message.',
      'code',
      'advanced',
      10,
      NULL,
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Proxy and Non-Existent Properties',
      'When trying to access a property that does not exist, how can a Proxy handler respond?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"0":"T","1":"h","2":"r","3":"o","4":"w","5":" ","6":"a","7":"n","8":" ","9":"e","10":"r","11":"r","12":"o","13":"r","explanation":""},{"0":"R","1":"e","2":"t","3":"u","4":"r","5":"n","6":" ","7":"u","8":"n","9":"d","10":"e","11":"f","12":"i","13":"n","14":"e","15":"d","explanation":""},{"0":"L","1":"o","2":"g","3":" ","4":"a","5":" ","6":"c","7":"u","8":"s","9":"t","10":"o","11":"m","12":" ","13":"m","14":"e","15":"s","16":"s","17":"a","18":"g","19":"e","explanation":""},{"0":"A","1":"n","2":"y","3":" ","4":"o","5":"f","6":" ","7":"t","8":"h","9":"e","10":" ","11":"a","12":"b","13":"o","14":"v","15":"e","16":",","17":" ","18":"d","19":"e","20":"p","21":"e","22":"n","23":"d","24":"i","25":"n","26":"g","27":" ","28":"o","29":"n","30":" ","31":"t","32":"h","33":"e","34":" ","35":"h","36":"a","37":"n","38":"d","39":"l","40":"e","41":"r","42":" ","43":"l","44":"o","45":"g","46":"i","47":"c","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Reflect with Proxies',
      'What is the role of the <code>Reflect</code> object when working with Proxies, and why is it preferred over direct property access?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"No explanation provided","isCorrect":true,"explanation":"No explanation provided."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'No explanation provided',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Refactoring Proxy with Reflect',
      'Rewrite this Proxy handler to use <code>Reflect.get</code> and <code>Reflect.set</code> instead of direct object manipulation.',
      'code',
      'advanced',
      10,
      NULL,
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Proxy Use Cases',
      'Which of the following are valid use cases for the Proxy pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"0":"V","1":"a","2":"l","3":"i","4":"d","5":"a","6":"t","7":"i","8":"o","9":"n","10":" ","11":"o","12":"f","13":" ","14":"o","15":"b","16":"j","17":"e","18":"c","19":"t","20":" ","21":"p","22":"r","23":"o","24":"p","25":"e","26":"r","27":"t","28":"i","29":"e","30":"s","explanation":""},{"0":"D","1":"e","2":"b","3":"u","4":"g","5":"g","6":"i","7":"n","8":"g","9":" ","10":"a","11":"n","12":"d","13":" ","14":"l","15":"o","16":"g","17":"g","18":"i","19":"n","20":"g","explanation":""},{"0":"F","1":"o","2":"r","3":"m","4":"a","5":"t","6":"t","7":"i","8":"n","9":"g","10":" ","11":"d","12":"a","13":"t","14":"a","15":" ","16":"b","17":"e","18":"f","19":"o","20":"r","21":"e","22":" ","23":"r","24":"e","25":"t","26":"u","27":"r","28":"n","explanation":""},{"0":"P","1":"e","2":"r","3":"f","4":"o","5":"r","6":"m","7":"a","8":"n","9":"c","10":"e","11":" ","12":"o","13":"p","14":"t","15":"i","16":"m","17":"i","18":"z","19":"a","20":"t","21":"i","22":"o","23":"n","24":" ","25":"i","26":"n","27":" ","28":"c","29":"r","30":"i","31":"t","32":"i","33":"c","34":"a","35":"l","36":" ","37":"c","38":"o","39":"d","40":"e","explanation":""}]',
      '',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Tradeoffs of Proxy',
      'What are the performance tradeoffs of using Proxy objects in large applications?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"No explanation provided","isCorrect":true,"explanation":"No explanation provided."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'No explanation provided',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Disadvantages of Flyweight Pattern',
      'What is a drawback of using the Flyweight Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It can increase code complexity by adding an extra layer of object management.","isCorrect":true,"explanation":"It can increase code complexity by adding an extra layer of object management. Modern hardware often has enough memory, so the benefit may be negligible in many applications."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'It can increase code complexity by adding an extra layer of object management.',
      'It can increase code complexity by adding an extra layer of object management. Modern hardware often has enough memory, so the benefit may be negligible in many applications.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Flyweight vs Factory Pattern',
      'How does the Flyweight Pattern differ from the Factory Pattern?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Factory Pattern abstracts object creation, while Flyweight Pattern focuses on sharing existing objects to save memory.","isCorrect":true,"explanation":"Factory Pattern abstracts object creation, while Flyweight Pattern focuses on sharing existing objects to save memory. Factory decides *how* to create, Flyweight decides *whether to reuse*."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Factory Pattern abstracts object creation, while Flyweight Pattern focuses on sharing existing objects to save memory.',
      'Factory Pattern abstracts object creation, while Flyweight Pattern focuses on sharing existing objects to save memory. Factory decides *how* to create, Flyweight decides *whether to reuse*.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Fix the Bug',
      'What’s wrong with this implementation?

<pre><code>const isbnNumbers = new Set();

const createBook = (title, author, isbn) =&gt; {
  const book = isbnNumbers.has(isbn);
  if (book) {
    return book;
  } else {
    const book = new Book(title, author, isbn);
    isbnNumbers.add(isbn);
    return book;
  }
};</code></pre>',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"The code incorrectly treats `isbnNumbers.has(isbn)` as the book object, but it returns a boolean.","isCorrect":true,"explanation":"The code incorrectly treats <code>isbnNumbers.has(isbn)</code> as the book object, but it returns a boolean. A <code>Map</code> or dictionary should be used to store ISBN → Book mappings, not just a <code>Set</code>."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'The code incorrectly treats `isbnNumbers.has(isbn)` as the book object, but it returns a boolean.',
      'The code incorrectly treats <code>isbnNumbers.has(isbn)</code> as the book object, but it returns a boolean. A <code>Map</code> or dictionary should be used to store ISBN → Book mappings, not just a <code>Set</code>.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'When to Use Flyweight',
      'In which situation would the Flyweight Pattern be the best choice?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"When creating thousands of objects that share common properties","isCorrect":true,"explanation":""},{"id":"b","text":"When creating a single instance of a service","isCorrect":false,"explanation":""},{"id":"c","text":"When caching API responses","isCorrect":false,"explanation":""},{"id":"d","text":"When setting up event delegation in DOM","isCorrect":false,"explanation":""}]',
      'When creating thousands of objects that share common properties',
      'The correct answer is: When creating thousands of objects that share common properties',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Flyweight Pattern in Modern JS',
      'Why is the Flyweight Pattern considered less critical in modern JavaScript applications compared to older times?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Because modern devices have large amounts of memory (RAM), so optimizing object count is less often necessary.","isCorrect":true,"explanation":"Because modern devices have large amounts of memory (RAM), so optimizing object count is less often necessary. JavaScript engines also optimize memory allocation internally."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Because modern devices have large amounts of memory (RAM), so optimizing object count is less often necessary.',
      'Because modern devices have large amounts of memory (RAM), so optimizing object count is less often necessary. JavaScript engines also optimize memory allocation internally.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Definition of Mixin Pattern',
      'What is the Mixin Pattern and why is it used?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A mixin is an object containing reusable functionality that can be added to another object or class without inheritance.","isCorrect":true,"explanation":"A mixin is an object containing reusable functionality that can be added to another object or class without inheritance. It allows sharing behavior across classes without forming rigid inheritance hierarchies."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'A mixin is an object containing reusable functionality that can be added to another object or class without inheritance.',
      'A mixin is an object containing reusable functionality that can be added to another object or class without inheritance. It allows sharing behavior across classes without forming rigid inheritance hierarchies.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'mixin-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Dog Example with Mixins',
      'Given the following code:

<pre><code>class Dog {
  constructor(name) {
    this.name = name;
  }
}

const dogFunctionality = {
  bark: () =&gt; console.log("Woof!"),
  wagTail: () =&gt; console.log("Wagging my tail!"),
};

Object.assign(Dog.prototype, dogFunctionality);

const pet1 = new Dog("Daisy");
pet1.bark();</code></pre>
What will be logged when <code>pet1.bark()</code> is executed?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"undefined","isCorrect":false,"explanation":""},{"id":"b","text":"Woof!","isCorrect":true,"explanation":""},{"id":"c","text":"Error: bark is not a function","isCorrect":false,"explanation":""}]',
      'Woof!',
      'The correct answer is: Woof!',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Mixins vs Inheritance',
      'How does the Mixin Pattern differ from classical inheritance?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Inheritance creates a parent-child relationship between classes, while mixins simply copy functionality into another class.","isCorrect":true,"explanation":"Inheritance creates a parent-child relationship between classes, while mixins simply copy functionality into another class. Mixins allow horizontal code reuse across unrelated classes, inheritance enforces vertical hierarchy."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Inheritance creates a parent-child relationship between classes, while mixins simply copy functionality into another class.',
      'Inheritance creates a parent-child relationship between classes, while mixins simply copy functionality into another class. Mixins allow horizontal code reuse across unrelated classes, inheritance enforces vertical hierarchy.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Chaining Mixins',
      'In the example with <code>animalFunctionality</code> and <code>dogFunctionality</code>, why does Dog end up with both <code>bark()</code> and <code>walk()</code> methods?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Because `Object.assign(dogFunctionality, animalFunctionality)` merged animal methods into dogFunctionality, then `Object.assign(Dog.prototype, dogFunctionality)` added all methods to Dog’s prototype.","isCorrect":true,"explanation":"Because <code>Object.assign(dogFunctionality, animalFunctionality)</code> merged animal methods into dogFunctionality, then <code>Object.assign(Dog.prototype, dogFunctionality)</code> added all methods to Dog’s prototype. This effectively chained multiple mixins together."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Because `Object.assign(dogFunctionality, animalFunctionality)` merged animal methods into dogFunctionality, then `Object.assign(Dog.prototype, dogFunctionality)` added all methods to Dog’s prototype.',
      'Because <code>Object.assign(dogFunctionality, animalFunctionality)</code> merged animal methods into dogFunctionality, then <code>Object.assign(Dog.prototype, dogFunctionality)</code> added all methods to Dog’s prototype. This effectively chained multiple mixins together.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Real World Browser Example',
      'Which of the following are examples of mixins in the browser Window object?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"setTimeout and setInterval (from WindowOrWorkerGlobalScope)","isCorrect":true,"explanation":""},{"id":"b","text":"onbeforeunload (from WindowEventHandlers)","isCorrect":true,"explanation":""},{"id":"c","text":"document.querySelector","isCorrect":false,"explanation":""},{"id":"d","text":"console.log","isCorrect":false,"explanation":""}]',
      'setTimeout and setInterval (from WindowOrWorkerGlobalScope)',
      'The correct answer is: setTimeout and setInterval (from WindowOrWorkerGlobalScope)',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.275Z',
      '2025-11-18T18:46:59.275Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Disadvantages of Mixins',
      'What are potential disadvantages of using Mixins?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"They can cause prototype pollution, making it unclear where a function originated.","isCorrect":true,"explanation":"They can cause prototype pollution, making it unclear where a function originated. They can introduce naming conflicts if two mixins define the same property. In React, they added complexity, leading the team to recommend HOCs and Hooks instead."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'They can cause prototype pollution, making it unclear where a function originated.',
      'They can cause prototype pollution, making it unclear where a function originated. They can introduce naming conflicts if two mixins define the same property. In React, they added complexity, leading the team to recommend HOCs and Hooks instead.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Mixin vs Higher Order Components',
      'Why did React discourage mixins in favor of Higher Order Components (HOCs) and later Hooks?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Mixins often lead to implicit dependencies and complexity, while HOCs and Hooks are more explicit, composable, and predictable.","isCorrect":true,"explanation":"Mixins often lead to implicit dependencies and complexity, while HOCs and Hooks are more explicit, composable, and predictable. Hooks allow better reusability and cleaner separation of concerns than mixins."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Mixins often lead to implicit dependencies and complexity, while HOCs and Hooks are more explicit, composable, and predictable.',
      'Mixins often lead to implicit dependencies and complexity, while HOCs and Hooks are more explicit, composable, and predictable. Hooks allow better reusability and cleaner separation of concerns than mixins.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Debugging Mixins',
      'If you accidentally overwrite a method from another mixin when using <code>Object.assign</code>, what will happen?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"Both methods are preserved","isCorrect":false,"explanation":""},{"id":"b","text":"The last assigned method overwrites the previous one","isCorrect":true,"explanation":""},{"id":"c","text":"JavaScript throws an error","isCorrect":false,"explanation":""}]',
      'The last assigned method overwrites the previous one',
      'The correct answer is: The last assigned method overwrites the previous one',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Definition of Module Pattern',
      'What is the Module Pattern in JavaScript and why is it used?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"The Module Pattern is a design pattern that uses closures to create private and public encapsulation.","isCorrect":true,"explanation":"The Module Pattern is a design pattern that uses closures to create private and public encapsulation. It is used to avoid polluting the global scope and to create reusable, maintainable code structures."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'The Module Pattern is a design pattern that uses closures to create private and public encapsulation.',
      'The Module Pattern is a design pattern that uses closures to create private and public encapsulation. It is used to avoid polluting the global scope and to create reusable, maintainable code structures.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Basic Module Syntax',
      'Which of the following correctly implements a simple Module Pattern in JavaScript?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"function Module() { var x = 10; return x; }","isCorrect":false,"explanation":""},{"id":"b","text":"var Module = (function(){ var privateVar = 10; return { get: function(){ return privateVar; } }; })();","isCorrect":true,"explanation":""},{"id":"c","text":"let Module = class { constructor(){ this.x = 10; } }","isCorrect":false,"explanation":""}]',
      'var Module = (function(){ var privateVar = 10; return { get: function(){ return privateVar; } }; })();',
      'The correct answer is: var Module = (function(){ var privateVar = 10; return { get: function(){ return privateVar; } }; })();',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Encapsulation in Module Pattern',
      'How does the Module Pattern achieve encapsulation?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"By using an Immediately Invoked Function Expression (IIFE) to create a private scope.","isCorrect":true,"explanation":"By using an Immediately Invoked Function Expression (IIFE) to create a private scope. Only the returned object exposes public members, while variables/functions inside the closure remain private."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'By using an Immediately Invoked Function Expression (IIFE) to create a private scope.',
      'By using an Immediately Invoked Function Expression (IIFE) to create a private scope. Only the returned object exposes public members, while variables/functions inside the closure remain private.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Drawback of Module Pattern',
      'Which of the following is a drawback of the Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"It makes code modular and organized","isCorrect":false,"explanation":""},{"id":"b","text":"Private members cannot be accessed or modified without changing the original module","isCorrect":true,"explanation":""},{"id":"c","text":"It always requires classes","isCorrect":false,"explanation":""}]',
      'Private members cannot be accessed or modified without changing the original module',
      'The correct answer is: Private members cannot be accessed or modified without changing the original module',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Revealing Module Pattern',
      'What is the difference between the classic Module Pattern and the Revealing Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"The Revealing Module Pattern maps private functions/variables to a returned object explicitly, improving readability.","isCorrect":true,"explanation":"The Revealing Module Pattern maps private functions/variables to a returned object explicitly, improving readability. It makes it clear which functions are public and which remain private."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'The Revealing Module Pattern maps private functions/variables to a returned object explicitly, improving readability.',
      'The Revealing Module Pattern maps private functions/variables to a returned object explicitly, improving readability. It makes it clear which functions are public and which remain private.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Debugging Modules',
      'If you forget to return a method in your Module Pattern, what will happen?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"The method is still accessible globally","isCorrect":false,"explanation":""},{"id":"b","text":"The method remains private and cannot be accessed outside","isCorrect":true,"explanation":""},{"id":"c","text":"JavaScript throws a syntax error","isCorrect":false,"explanation":""}]',
      'The method remains private and cannot be accessed outside',
      'The correct answer is: The method remains private and cannot be accessed outside',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Module Pattern vs ES6 Modules',
      'How does the Module Pattern differ from ES6 Modules?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Module Pattern relies on closures and IIFEs for encapsulation, while ES6 Modules are built-in language features with `import` and `export`.","isCorrect":true,"explanation":"Module Pattern relies on closures and IIFEs for encapsulation, while ES6 Modules are built-in language features with <code>import</code> and <code>export</code>. ES6 Modules are statically analyzed at compile time, while Module Pattern modules are runtime constructs."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'Module Pattern relies on closures and IIFEs for encapsulation, while ES6 Modules are built-in language features with `import` and `export`.',
      'Module Pattern relies on closures and IIFEs for encapsulation, while ES6 Modules are built-in language features with <code>import</code> and <code>export</code>. ES6 Modules are statically analyzed at compile time, while Module Pattern modules are runtime constructs.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'advanced', 'advanced'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Use Case of Module Pattern',
      'Which scenario is best suited for the Module Pattern?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"a","text":"When you want to encapsulate private state in legacy JavaScript without ES6 support","isCorrect":true,"explanation":""},{"id":"b","text":"When you need dynamic imports and tree-shaking","isCorrect":false,"explanation":""},{"id":"c","text":"When you only work with classes","isCorrect":false,"explanation":""}]',
      'When you want to encapsulate private state in legacy JavaScript without ES6 support',
      'The correct answer is: When you want to encapsulate private state in legacy JavaScript without ES6 support',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Introduction to Proxy Pattern',
      'What is the Proxy Pattern in JavaScript and how does it differ from directly interacting with an object?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"No explanation provided","isCorrect":true,"explanation":"No explanation provided."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review the design pattern concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""}]',
      'No explanation provided',
      'No explanation provided.',
      NULL,
      ARRAY[]::text[],
      ARRAY['design-patterns', 'general-design-patterns', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '7384b45b-c779-49c3-b9e9-ef335a7cccfa',
      NULL,
      true,
      '2025-11-18T18:46:59.276Z',
      '2025-11-18T18:46:59.276Z',
      NULL,
      300
    );