INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is the main advantage of SASS/SCSS over plain CSS? (Select all that apply)',
      'CSS preprocessors add features. Identify the main advantages SASS provides over vanilla CSS.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Variables (reusable values)","isCorrect":true,"explanation":"Correct. Variables enable DRY code."},{"id":"o2","text":"Nesting (hierarchical structure)","isCorrect":true,"explanation":"Correct. Nesting improves organization."},{"id":"o3","text":"Mixins (reusable code blocks)","isCorrect":true,"explanation":"Correct. Mixins enable code reuse."},{"id":"o4","text":"Native browser support (no compilation needed)","isCorrect":false,"explanation":"Incorrect. SASS requires compilation to CSS."}]',
      'Variables (reusable values)',
      'SASS advantages: variables, nesting, mixins, functions, partials/modularity, inheritance (<code>@extend</code>), operators. Enables DRY code, better organization, maintainability. Compiles to CSS.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'sass', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain the difference between SASS and SCSS syntax. When should each be used?',
      'SASS has two syntaxes. Explain the differences and use cases for each.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"SCSS: CSS-like with braces; SASS: indented syntax, more concise","isCorrect":true,"explanation":"Correct. SCSS is more popular and familiar."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They have different syntaxes."},{"id":"o3","text":"SASS is deprecated","isCorrect":false,"explanation":"Incorrect. Both syntaxes are valid."},{"id":"o4","text":"SCSS only works with JavaScript","isCorrect":false,"explanation":"Incorrect. SCSS is a CSS preprocessor."}]',
      'SCSS: CSS-like with braces; SASS: indented syntax, more concise',
      'SCSS: CSS-like syntax, uses braces and semicolons, easier migration from CSS. SASS: indented syntax, no braces/semicolons, more concise. SCSS is more popular, easier for teams. SASS is more concise but less familiar.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'sass', 'scss', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of PostCSS? How does it differ from SASS/LESS?',
      'PostCSS is a different type of CSS tool. Explain its purpose and how it compares to preprocessors.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"PostCSS: CSS transformer with plugins; SASS/LESS: preprocessors that compile to CSS","isCorrect":true,"explanation":"Correct. PostCSS is more flexible and plugin-based."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. PostCSS is a transformer, not a preprocessor."},{"id":"o3","text":"PostCSS replaces all preprocessors","isCorrect":false,"explanation":"Incorrect. They can work together."},{"id":"o4","text":"PostCSS only works with React","isCorrect":false,"explanation":"Incorrect. PostCSS is framework-agnostic."}]',
      'PostCSS: CSS transformer with plugins; SASS/LESS: preprocessors that compile to CSS',
      'PostCSS: CSS transformer (not preprocessor), plugin-based, processes CSS with JavaScript. SASS/LESS: preprocessors, compile to CSS. PostCSS can add features (autoprefixer, nesting), optimize, lint. More flexible, modern approach. Often used with preprocessors.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'postcss', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which SASS features help with code organization? (Select all that apply)',
      'SASS provides organizational features. Identify features that improve CSS code structure.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Partials (<code>@import, @use) for modular files</code>","isCorrect":true,"explanation":"Correct. Partials enable modular organization."},{"id":"o2","text":"Nesting for hierarchical structure","isCorrect":true,"explanation":"Correct. Nesting improves organization."},{"id":"o3","text":"Mixins for reusable code","isCorrect":true,"explanation":"Correct. Mixins enable code reuse."},{"id":"o4","text":"Inline styles (not a SASS feature)","isCorrect":false,"explanation":"Incorrect. This is not a SASS organizational feature."}]',
      'Partials (<code>@import, @use) for modular files</code>',
      'Partials (<code>@import</code>/_file<code>.scss</code>): modular files. <code>@use</code>/<code>@forward</code>: modern module system. Nesting: hierarchical structure. Mixins: reusable blocks. Functions: reusable logic. All help organize and maintain CSS.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'sass', 'organization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain SASS ''<code>@extend</code>'' vs ''<code>@mixin</code>''. When should each be used?',
      'SASS provides two code reuse mechanisms. Explain extend vs mixin and their trade-offs.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>@extend</code>: shares selector; <code>@mixin</code>: duplicates code with parameters (more flexible)","isCorrect":true,"explanation":"Correct. Mixins are generally more flexible."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They work differently."},{"id":"o3","text":"<code>@extend</code> is always better","isCorrect":false,"explanation":"Incorrect. Mixins are often preferred for flexibility."},{"id":"o4","text":"<code>@mixin</code> is deprecated","isCorrect":false,"explanation":"Incorrect. Both are valid and useful."}]',
      '<code>@extend</code>: shares selector; <code>@mixin</code>: duplicates code with parameters (more flexible)',
      '<code>@extend</code>: shares selector (groups selectors), less CSS output, but can create specificity issues, less flexible. <code>@mixin</code>: duplicates code (more output), more flexible with parameters, clearer intent. Prefer <code>@mixin</code> for flexibility, <code>@extend</code> for simple sharing.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'sass', 'extend', 'mixin', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of ''autoprefixer'' in PostCSS? How does it help with browser compatibility?',
      'Browser prefixes are tedious. Explain autoprefixer and how it automates vendor prefixing.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Automatically adds vendor prefixes based on browser support data","isCorrect":true,"explanation":"Correct. autoprefixer automates prefixing."},{"id":"o2","text":"Removes all prefixes","isCorrect":false,"explanation":"Incorrect. It adds prefixes, not removes them."},{"id":"o3","text":"Only works with SASS","isCorrect":false,"explanation":"Incorrect. autoprefixer works with any CSS."},{"id":"o4","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. autoprefixer is widely used."}]',
      'Automatically adds vendor prefixes based on browser support data',
      'autoprefixer: PostCSS plugin that automatically adds vendor prefixes (-webkit-, -moz-, -ms-) based on browser support data. Write modern CSS, autoprefixer adds needed prefixes. Keeps CSS clean, ensures compatibility, uses Can I Use data.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'postcss', 'autoprefixer', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which LESS features are similar to SASS? (Select all that apply)',
      'LESS is another CSS preprocessor. Identify features it shares with SASS.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Variables","isCorrect":true,"explanation":"Correct. Both support variables."},{"id":"o2","text":"Nesting","isCorrect":true,"explanation":"Correct. Both support nesting."},{"id":"o3","text":"Mixins","isCorrect":true,"explanation":"Correct. Both support mixins."},{"id":"o4","text":"Native browser support without compilation","isCorrect":false,"explanation":"Incorrect. Both require compilation (though LESS can run client-side)."}]',
      'Variables',
      'Both LESS and SASS provide: variables, nesting, mixins, functions, imports. SASS has more features (extend, advanced functions). LESS can run in browser (JavaScript), SASS requires compilation. Both compile to CSS.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'less', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS custom properties (CSS variables). How do they differ from SASS variables?',
      'CSS now has native variables. Explain CSS custom properties vs SASS variables and when to use each.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"CSS variables: runtime, dynamic, cascade; SASS: compile-time, static","isCorrect":true,"explanation":"Correct. CSS variables are more powerful for dynamic theming."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. CSS variables are runtime, SASS is compile-time."},{"id":"o3","text":"SASS variables are always better","isCorrect":false,"explanation":"Incorrect. CSS variables enable dynamic theming."},{"id":"o4","text":"CSS variables require a preprocessor","isCorrect":false,"explanation":"Incorrect. CSS variables are native CSS."}]',
      'CSS variables: runtime, dynamic, cascade; SASS: compile-time, static',
      'CSS custom properties: native CSS, runtime values (can change with JS), cascade, scoped. SASS variables: compile-time, static, no runtime access. Use CSS variables for theming, dynamic values. Use SASS for compile-time constants, calculations.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'css-variables', 'custom-properties', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of ''cssnano'' in PostCSS? How does it optimize CSS?',
      'CSS optimization tools reduce file size. Explain cssnano and its optimization techniques.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Minifies CSS: removes whitespace, comments, optimizes values for smaller file size","isCorrect":true,"explanation":"Correct. cssnano optimizes CSS for production."},{"id":"o2","text":"Adds vendor prefixes","isCorrect":false,"explanation":"Incorrect. That''s autoprefixer."},{"id":"o3","text":"Compiles SASS to CSS","isCorrect":false,"explanation":"Incorrect. cssnano minifies already-compiled CSS."},{"id":"o4","text":"Only works with LESS","isCorrect":false,"explanation":"Incorrect. cssnano works with any CSS."}]',
      'Minifies CSS: removes whitespace, comments, optimizes values for smaller file size',
      'cssnano: PostCSS plugin that minifies CSS. Removes whitespace, comments, unused rules, optimizes values, merges rules. Reduces file size significantly. Essential for production builds. Part of modern build pipelines.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'postcss', 'cssnano', 'optimization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which SASS functions are useful for color manipulation? (Select all that apply)',
      'SASS provides color functions. Identify functions that help manipulate colors programmatically.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"lighten() / darken() (adjust lightness)","isCorrect":true,"explanation":"Correct. These adjust color brightness."},{"id":"o2","text":"saturate() / desaturate() (adjust saturation)","isCorrect":true,"explanation":"Correct. These adjust color intensity."},{"id":"o3","text":"mix() (blend colors)","isCorrect":true,"explanation":"Correct. mix() blends two colors."},{"id":"o4","text":"compile() (not a color function)","isCorrect":false,"explanation":"Incorrect. This is not a color manipulation function."}]',
      'lighten() / darken() (adjust lightness)',
      'SASS color functions: lighten(), darken(), saturate(), desaturate(), fade-in(), fade-out(), mix(), adjust-color(), scale-color(). Enable programmatic color manipulation, theming, variations. Very useful for design systems.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'preprocessors', 'sass', 'colors', 'functions', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is Critical CSS? How does it improve page load performance?',
      'Performance optimization requires understanding Critical CSS. Explain its purpose and implementation.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Above-the-fold styles inlined in head; improves First Contentful Paint","isCorrect":true,"explanation":"Correct. Critical CSS reduces render-blocking."},{"id":"o2","text":"All CSS in one file","isCorrect":false,"explanation":"Incorrect. Critical CSS is only above-the-fold styles."},{"id":"o3","text":"CSS loaded after page render","isCorrect":false,"explanation":"Incorrect. Critical CSS loads first, inline."},{"id":"o4","text":"Only needed for mobile","isCorrect":false,"explanation":"Incorrect. Critical CSS helps on all devices."}]',
      'Above-the-fold styles inlined in head; improves First Contentful Paint',
      'Critical CSS: above-the-fold styles needed for initial render. Inline in <head> to avoid render-blocking. Remaining CSS loads asynchronously. Improves First Contentful Paint (FCP), reduces render-blocking. Essential for performance.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'critical-css', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which techniques reduce CSS file size? (Select all that apply)',
      'Smaller CSS files load faster. Identify techniques that reduce CSS file size.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Minification (remove whitespace, comments)","isCorrect":true,"explanation":"Correct. Minification reduces file size."},{"id":"o2","text":"Unused CSS removal (PurgeCSS)","isCorrect":true,"explanation":"Correct. Removing unused CSS reduces size."},{"id":"o3","text":"Compression (gzip, brotli)","isCorrect":true,"explanation":"Correct. Compression reduces transfer size."},{"id":"o4","text":"Adding more comments","isCorrect":false,"explanation":"Incorrect. Comments increase file size."}]',
      'Minification (remove whitespace, comments)',
      'Minification (remove whitespace, comments), unused CSS removal (PurgeCSS), compression (gzip/brotli), code splitting, removing duplicate rules, using shorthand properties, avoiding !important overuse.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'optimization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS loading strategies. What is the difference between render-blocking and non-blocking CSS?',
      'CSS loading affects page performance. Explain render-blocking vs non-blocking CSS and optimization strategies.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Render-blocking: blocks parsing (default); Non-blocking: async loading for non-critical CSS","isCorrect":true,"explanation":"Correct. Non-blocking improves performance."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They affect performance differently."},{"id":"o3","text":"All CSS should be render-blocking","isCorrect":false,"explanation":"Incorrect. Non-critical CSS should load async."},{"id":"o4","text":"Non-blocking CSS doesn''t work","isCorrect":false,"explanation":"Incorrect. Non-blocking CSS is a valid optimization."}]',
      'Render-blocking: blocks parsing (default); Non-blocking: async loading for non-critical CSS',
      'Render-blocking: CSS in <head> blocks HTML parsing until loaded (default). Non-blocking: load asynchronously (media=''print'' then switch, or load via JS). Critical CSS inline, non-critical async. Improves Time to First Byte, FCP.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'loading', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of ''content-visibility'' property? How does it improve rendering performance?',
      'Modern CSS provides rendering optimizations. Explain content-visibility and its performance benefits.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Skips rendering off-screen content until needed; improves initial render performance","isCorrect":true,"explanation":"Correct. content-visibility optimizes rendering."},{"id":"o2","text":"Hides content permanently","isCorrect":false,"explanation":"Incorrect. It defers rendering, doesn''t hide."},{"id":"o3","text":"Only works with JavaScript","isCorrect":false,"explanation":"Incorrect. content-visibility is pure CSS."},{"id":"o4","text":"Increases rendering time","isCorrect":false,"explanation":"Incorrect. It reduces rendering time."}]',
      'Skips rendering off-screen content until needed; improves initial render performance',
      '<code>content-visibility:</code> auto skips rendering off-screen content until needed. Significantly improves initial render for long pages. Similar to lazy loading but for rendering. Use on sections that are initially off-screen. Limited browser support.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'content-visibility', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS properties trigger expensive layout recalculations? (Select all that apply)',
      'Layout performance matters. Identify properties that trigger layout (reflow) and should be avoided in animations.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"width / height (triggers layout)","isCorrect":true,"explanation":"Correct. These trigger expensive layout."},{"id":"o2","text":"margin / padding (triggers layout)","isCorrect":true,"explanation":"Correct. These trigger layout recalculation."},{"id":"o3","text":"transform (GPU-accelerated, no layout)","isCorrect":false,"explanation":"Incorrect. transform doesn''t trigger layout."},{"id":"o4","text":"opacity (GPU-accelerated, no layout)","isCorrect":false,"explanation":"Incorrect. opacity doesn''t trigger layout."}]',
      'width / height (triggers layout)',
      'Layout-triggering properties: width, height, margin, padding, border, display, position (static/relative), top/left/right/bottom, font-size, line-height. These cause reflow (expensive). Use transform/opacity for animations instead.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'layout', 'reflow', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS containment. How does ''contain'' property optimize rendering?',
      'CSS containment is a performance feature. Explain the contain property and its optimization benefits.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Isolates element rendering; prevents changes from affecting outside; optimizes layout/paint","isCorrect":true,"explanation":"Correct. Containment optimizes rendering scope."},{"id":"o2","text":"Hides the element","isCorrect":false,"explanation":"Incorrect. contain optimizes, doesn''t hide."},{"id":"o3","text":"Only works with Flexbox","isCorrect":false,"explanation":"Incorrect. contain works with any layout."},{"id":"o4","text":"Increases rendering cost","isCorrect":false,"explanation":"Incorrect. contain reduces rendering cost."}]',
      'Isolates element rendering; prevents changes from affecting outside; optimizes layout/paint',
      '<code>contain:</code> isolates element''s rendering (layout, style, paint, size). Prevents changes from affecting outside. Optimizes: layout (<code>contain:</code> layout), paint (<code>contain:</code> paint), style recalculation. Use on isolated components. Improves performance for complex pages.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'containment', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between ''will-change'' and ''contain'' for performance optimization?',
      'Both properties optimize performance. Explain when to use will-change vs contain and their different purposes.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"<code>will-change:</code> animation optimization; <code>contain:</code> rendering isolation for components","isCorrect":true,"explanation":"Correct. They optimize different aspects."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They serve different optimization purposes."},{"id":"o3","text":"contain is deprecated","isCorrect":false,"explanation":"Incorrect. Both are modern features."},{"id":"o4","text":"will-change isolates rendering","isCorrect":false,"explanation":"Incorrect. That''s contain''s purpose."}]',
      '<code>will-change:</code> animation optimization; <code>contain:</code> rendering isolation for components',
      '<code>will-change:</code> hints about upcoming changes, promotes to GPU layer, use for animations about to start. <code>contain:</code> isolates rendering scope, prevents cascade effects, use for isolated components. Different purposes: will-change for animations, contain for isolation.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'will-change', 'contain', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which strategies improve CSS delivery performance? (Select all that apply)',
      'CSS delivery affects page load. Identify strategies that improve CSS loading and rendering performance.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Critical CSS inline in <head>","isCorrect":true,"explanation":"Correct. Inline critical CSS reduces render-blocking."},{"id":"o2","text":"Preload for critical CSS files","isCorrect":true,"explanation":"Correct. Preload prioritizes critical resources."},{"id":"o3","text":"Code splitting (separate CSS per route)","isCorrect":true,"explanation":"Correct. Code splitting reduces initial payload."},{"id":"o4","text":"Load all CSS synchronously","isCorrect":false,"explanation":"Incorrect. Async loading is better for non-critical CSS."}]',
      'Critical CSS inline in <head>',
      'Critical CSS inline, non-critical async, HTTP/2 server push, preload for critical CSS, code splitting, CDN delivery, compression (gzip/brotli), remove unused CSS, minification.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'delivery', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain ''font-display'' property. How does it affect font loading performance?',
      'Web fonts can block rendering. Explain font-display and its impact on performance and user experience.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Controls font rendering strategy; swap shows fallback immediately (best for performance)","isCorrect":true,"explanation":"Correct. swap prevents invisible text."},{"id":"o2","text":"Controls font file size","isCorrect":false,"explanation":"Incorrect. font-display controls rendering, not file size."},{"id":"o3","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. font-display is a modern, important feature."},{"id":"o4","text":"Only works with system fonts","isCorrect":false,"explanation":"Incorrect. font-display works with web fonts."}]',
      'Controls font rendering strategy; swap shows fallback immediately (best for performance)',
      'font-display controls font rendering: block (invisible until loaded, FOIT), swap (show fallback immediately, FOUT), fallback (short block then swap), optional (only if cached). swap is best for performance, prevents invisible text.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'fonts', 'font-display', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of CSS ''<code>contain:</code> layout''? How does it optimize layout calculations?',
      'Layout containment is a performance feature. Explain <code>contain:</code> layout and its optimization benefits.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Isolates layout calculations; changes inside don''t affect outside; optimizes performance","isCorrect":true,"explanation":"Correct. Layout containment optimizes calculations."},{"id":"o2","text":"Prevents layout from working","isCorrect":false,"explanation":"Incorrect. It optimizes layout, doesn''t prevent it."},{"id":"o3","text":"Only works with Grid","isCorrect":false,"explanation":"Incorrect. contain works with any layout method."},{"id":"o4","text":"Increases layout calculations","isCorrect":false,"explanation":"Incorrect. It reduces layout calculations."}]',
      'Isolates layout calculations; changes inside don''t affect outside; optimizes performance',
      '<code>contain:</code> layout isolates element''s layout calculations. Changes inside don''t affect outside layout. Browser can skip layout calculations for outside elements. Use on isolated components. Improves performance for complex layouts.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'performance', 'containment', 'layout', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain BEM methodology. What do Block, Element, and Modifier mean?',
      'CSS architecture requires methodologies. Explain BEM naming convention and its structure.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Block__Element<code>--Modifier</code>: component, part, variation; clear naming structure","isCorrect":true,"explanation":"Correct. BEM provides clear, maintainable naming."},{"id":"o2","text":"Only works with SASS","isCorrect":false,"explanation":"Incorrect. BEM works with any CSS."},{"id":"o3","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. BEM is widely used."},{"id":"o4","text":"Requires JavaScript","isCorrect":false,"explanation":"Incorrect. BEM is a CSS naming convention."}]',
      'Block__Element<code>--Modifier</code>: component, part, variation; clear naming structure',
      'BEM: Block__Element<code>--Modifier</code>. Block: standalone component (button). Element: part of block (button__icon). Modifier: variation (button<code>--primary</code>). Naming: <code>.block__element--modifier</code>. Benefits: clear structure, avoids specificity issues, self-documenting.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'bem', 'methodology', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS architecture methodologies exist? (Select all that apply)',
      'CSS organization requires methodologies. Identify popular CSS architecture approaches.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"BEM (Block Element Modifier)","isCorrect":true,"explanation":"Correct. BEM is a popular methodology."},{"id":"o2","text":"OOCSS (Object-Oriented CSS)","isCorrect":true,"explanation":"Correct. OOCSS is a methodology."},{"id":"o3","text":"SMACSS (Scalable and Modular)","isCorrect":true,"explanation":"Correct. SMACSS is a methodology."},{"id":"o4","text":"Inline styles (not a methodology)","isCorrect":false,"explanation":"Incorrect. This is not a CSS architecture methodology."}]',
      'BEM (Block Element Modifier)',
      'BEM (Block Element Modifier), OOCSS (Object-Oriented), SMACSS (Scalable and Modular), ITCSS (Inverted Triangle), Atomic CSS, Utility-first (Tailwind approach). Each has different organization principles.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'methodologies', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of ITCSS? How does it organize CSS layers?',
      'ITCSS provides a layered CSS architecture. Explain its inverted triangle structure and layer organization.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Organizes CSS in layers from generic to specific; prevents specificity conflicts","isCorrect":true,"explanation":"Correct. ITCSS provides layered architecture."},{"id":"o2","text":"Only works with PostCSS","isCorrect":false,"explanation":"Incorrect. ITCSS is a methodology, not a tool."},{"id":"o3","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. ITCSS is a valid methodology."},{"id":"o4","text":"Requires JavaScript","isCorrect":false,"explanation":"Incorrect. ITCSS is a CSS organization method."}]',
      'Organizes CSS in layers from generic to specific; prevents specificity conflicts',
      'ITCSS: Inverted Triangle CSS. Layers (bottom to top): Settings (variables), Tools (mixins), Generic (resets), Elements (base styles), Objects (layout), Components (UI), Utilities (helpers). Specificity increases upward. Prevents specificity conflicts.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'itcss', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain OOCSS principles. What is separation of structure from skin?',
      'Object-Oriented CSS provides principles. Explain OOCSS and its core concepts.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Separates structure (layout) from skin (visual); enables reusable objects","isCorrect":true,"explanation":"Correct. OOCSS promotes reusability."},{"id":"o2","text":"Only works with classes","isCorrect":false,"explanation":"Incorrect. OOCSS is a principle, works with any selectors."},{"id":"o3","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. OOCSS principles are still valid."},{"id":"o4","text":"Requires SASS","isCorrect":false,"explanation":"Incorrect. OOCSS works with plain CSS."}]',
      'Separates structure (layout) from skin (visual); enables reusable objects',
      'OOCSS: Object-Oriented CSS. Principles: 1) Separate structure (layout) from skin (visual), 2) Separate container from content. Reusable objects, avoid location-dependent styles. Enables code reuse, maintainability. Example: <code>.button</code> (structure) + <code>.button-primary</code> (skin).',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'oocss', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which strategies help organize large CSS codebases? (Select all that apply)',
      'Large projects need organization. Identify strategies for managing complex CSS codebases.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Modular files (partials, components)","isCorrect":true,"explanation":"Correct. Modularity improves organization."},{"id":"o2","text":"Naming conventions (BEM, etc.)","isCorrect":true,"explanation":"Correct. Consistent naming helps maintainability."},{"id":"o3","text":"Component-based organization","isCorrect":true,"explanation":"Correct. Component organization scales well."},{"id":"o4","text":"One large CSS file (anti-pattern)","isCorrect":false,"explanation":"Incorrect. Large files are hard to maintain."}]',
      'Modular files (partials, components)',
      'Modular files (partials), naming conventions (BEM), component-based organization, utility classes, CSS-in-JS (for component frameworks), design tokens, style guides, documentation. All help maintain large codebases.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'organization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between utility-first CSS (Tailwind) and component-based CSS?',
      'CSS approaches differ. Explain utility-first vs component-based CSS and their trade-offs.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Utility-first: compose in HTML; Component-based: semantic classes in CSS","isCorrect":true,"explanation":"Correct. Different approaches with different trade-offs."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They have fundamentally different approaches."},{"id":"o3","text":"Utility-first is deprecated","isCorrect":false,"explanation":"Incorrect. Utility-first is popular (Tailwind)."},{"id":"o4","text":"Component-based only works with React","isCorrect":false,"explanation":"Incorrect. Component-based CSS works with any framework."}]',
      'Utility-first: compose in HTML; Component-based: semantic classes in CSS',
      'Utility-first: small utility classes (flex, p-4, text-center), compose in HTML, less custom CSS, faster development, larger HTML. Component-based: semantic classes, styles in CSS, more maintainable CSS, cleaner HTML. Tailwind is utility-first, BEM is component-based.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'utility-first', 'tailwind', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS custom properties for theming. How do they enable dynamic themes?',
      'Theming requires flexible CSS. Explain how CSS custom properties enable dynamic theming systems.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Runtime variables enable dynamic theming; change with JS; supports dark mode, user preferences","isCorrect":true,"explanation":"Correct. CSS variables enable dynamic theming."},{"id":"o2","text":"Only works at compile time","isCorrect":false,"explanation":"Incorrect. CSS variables work at runtime."},{"id":"o3","text":"Requires SASS","isCorrect":false,"explanation":"Incorrect. CSS custom properties are native CSS."},{"id":"o4","text":"Cannot be changed dynamically","isCorrect":false,"explanation":"Incorrect. CSS variables can be changed with JavaScript."}]',
      'Runtime variables enable dynamic theming; change with JS; supports dark mode, user preferences',
      'CSS custom properties (<code>--variable</code>) enable runtime theming. Define theme variables at <code>:root</code>, override in themes. Change with JavaScript (setProperty). Enables dark mode, user preferences, dynamic themes. More flexible than SASS variables (compile-time).',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'theming', 'css-variables', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which file organization strategies work well for CSS? (Select all that apply)',
      'File structure affects maintainability. Identify effective CSS file organization strategies.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"Component-based (one file per component)","isCorrect":true,"explanation":"Correct. Component organization scales well."},{"id":"o2","text":"Feature-based (grouped by feature)","isCorrect":true,"explanation":"Correct. Feature organization works for large apps."},{"id":"o3","text":"Layer-based (ITCSS approach)","isCorrect":true,"explanation":"Correct. Layer organization prevents conflicts."},{"id":"o4","text":"One massive file (anti-pattern)","isCorrect":false,"explanation":"Incorrect. Large files are hard to maintain."}]',
      'Component-based (one file per component)',
      'Component-based (one file per component), feature-based (grouped by feature), layer-based (ITCSS), utility files (separate utilities), vendor files (third-party), main file (imports all). Choose based on project size and team preference.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'organization', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of CSS design tokens? How do they improve consistency?',
      'Design systems use tokens. Explain CSS design tokens and their role in maintaining design consistency.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Named values (colors, spacing) as CSS variables; single source of truth for consistency","isCorrect":true,"explanation":"Correct. Design tokens ensure consistency."},{"id":"o2","text":"Only work with SASS","isCorrect":false,"explanation":"Incorrect. Design tokens work with CSS variables."},{"id":"o3","text":"Are deprecated","isCorrect":false,"explanation":"Incorrect. Design tokens are modern best practice."},{"id":"o4","text":"Require JavaScript","isCorrect":false,"explanation":"Incorrect. Design tokens are CSS variables."}]',
      'Named values (colors, spacing) as CSS variables; single source of truth for consistency',
      'Design tokens: named values (colors, spacing, typography) stored as CSS variables. Single source of truth, ensures consistency, easy theming, maintainable. Example: <code>--color-primary</code>: #007bff. Used throughout codebase, changed in one place.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'design-tokens', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS specificity conflicts in large codebases. How do methodologies help prevent them?',
      'Specificity wars are a problem. Explain how CSS methodologies prevent specificity conflicts.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Methodologies provide flat specificity (BEM), layered structure (ITCSS) to prevent conflicts","isCorrect":true,"explanation":"Correct. Methodologies prevent specificity issues."},{"id":"o2","text":"Methodologies increase specificity conflicts","isCorrect":false,"explanation":"Incorrect. They help prevent conflicts."},{"id":"o3","text":"Specificity conflicts are unavoidable","isCorrect":false,"explanation":"Incorrect. Methodologies help prevent them."},{"id":"o4","text":"Only !important solves conflicts","isCorrect":false,"explanation":"Incorrect. !important is an anti-pattern."}]',
      'Methodologies provide flat specificity (BEM), layered structure (ITCSS) to prevent conflicts',
      'Large codebases: specificity conflicts, !important overuse, hard to override. Methodologies help: BEM (flat specificity), ITCSS (layered specificity), OOCSS (avoid nesting). Consistent naming, flat selectors, avoid deep nesting. Prevents specificity wars.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'architecture', 'specificity', 'methodologies', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain advanced CSS selectors. What is the difference between ''<code>:nth-child</code>()'' and ''<code>:nth-of-type</code>()''?',
      'Advanced selectors enable precise targeting. Explain nth-child vs nth-of-type and when to use each.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>:nth-child</code>: position-based (any type); <code>:nth-of-type</code>: type-based selection","isCorrect":true,"explanation":"Correct. They select based on different criteria."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They work differently."},{"id":"o3","text":"<code>:nth-child</code> only works with classes","isCorrect":false,"explanation":"Incorrect. nth-child works with any element."},{"id":"o4","text":"<code>:nth-of-type</code> is deprecated","isCorrect":false,"explanation":"Incorrect. Both are standard CSS selectors."}]',
      '<code>:nth-child</code>: position-based (any type); <code>:nth-of-type</code>: type-based selection',
      '<code>:nth-child</code>(n) selects nth child element regardless of type. <code>:nth-of-type</code>(n) selects nth element of specific type. <code>:nth-child</code>(2) = 2nd child (any type). <code>:nth-of-type</code>(2) = 2nd <p> if selector is p<code>:nth-of-type</code>(2). Use nth-child for position-based, nth-of-type for type-based selection.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'selectors', 'nth-child', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which pseudo-elements can be used with the ''<code>::before</code>'' and ''<code>::after</code>'' syntax? (Select all that apply)',
      'Pseudo-elements create virtual elements. Identify valid pseudo-elements in CSS.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>::before</code> (creates element before)","isCorrect":true,"explanation":"Correct. <code>::before</code> is a valid pseudo-element."},{"id":"o2","text":"<code>::after</code> (creates element after)","isCorrect":true,"explanation":"Correct. <code>::after</code> is a valid pseudo-element."},{"id":"o3","text":"<code>::first-letter</code> (styles first letter)","isCorrect":true,"explanation":"Correct. <code>::first-letter</code> is a valid pseudo-element."},{"id":"o4","text":"<code>::hover</code> (not a pseudo-element, it''s a pseudo-class)","isCorrect":false,"explanation":"Incorrect. <code>::hover</code> is a pseudo-class, not pseudo-element."}]',
      '<code>::before</code> (creates element before)',
      'Valid pseudo-elements: <code>::before</code>, <code>::after</code>, <code>::first-line</code>, <code>::first-letter</code>, <code>::selection</code>, <code>::placeholder</code>, <code>::backdrop</code>. Double colon (::) is modern syntax, single colon (:) works for backward compatibility. <code>::before</code> and <code>::after</code> require content property.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'pseudo-elements', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the CSS cascade order when multiple rules have the same specificity?',
      'Understanding cascade order is crucial. Explain how source order affects which styles are applied.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Later rules win when specificity is equal (source order determines winner)","isCorrect":true,"explanation":"Correct. Source order breaks ties when specificity is equal."},{"id":"o2","text":"Earlier rules always win","isCorrect":false,"explanation":"Incorrect. Later rules win when specificity is equal."},{"id":"o3","text":"Random selection","isCorrect":false,"explanation":"Incorrect. Source order determines the winner."},{"id":"o4","text":"Specificity doesn''t matter","isCorrect":false,"explanation":"Incorrect. Specificity matters first, then source order."}]',
      'Later rules win when specificity is equal (source order determines winner)',
      'When specificity is equal, later rules win (source order). Stylesheet order matters: earlier < later. Inline styles (highest specificity) > embedded < external. Within same specificity, last declared wins. This is why order matters in CSS.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'cascade', 'specificity', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS attribute selectors. What is the difference between ''<code>[attr]</code>'', ''<code>[attr=value]</code>'', and ''<code>[attr~=value]</code>''?',
      'Attribute selectors provide powerful targeting. Explain different attribute selector syntaxes and their meanings.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>[attr]</code>: has attribute; <code>[attr=value]: exact match; [attr~=value]</code>: in space-separated list","isCorrect":true,"explanation":"Correct. Different operators match differently."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They match differently."},{"id":"o3","text":"<code>[attr~=value]</code> means exact match","isCorrect":false,"explanation":"Incorrect. ~= means in space-separated list."},{"id":"o4","text":"Attribute selectors don''t work","isCorrect":false,"explanation":"Incorrect. Attribute selectors are powerful and widely supported."}]',
      '<code>[attr]</code>: has attribute; <code>[attr=value]: exact match; [attr~=value]</code>: in space-separated list',
      '<code>[attr]</code>: element has attribute. <code>[attr=value]: exact match. [attr~=value]: value in space-separated list. [attr|=value]: value or value- prefix. [attr^=value]: starts with. [attr$=value]: ends with. [attr*=value]</code>: contains substring.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'selectors', 'attributes', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS units are relative to the viewport? (Select all that apply)',
      'Viewport units enable responsive sizing. Identify CSS units that are relative to viewport dimensions.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"vw (viewport width)","isCorrect":true,"explanation":"Correct. vw is relative to viewport width."},{"id":"o2","text":"vh (viewport height)","isCorrect":true,"explanation":"Correct. vh is relative to viewport height."},{"id":"o3","text":"vmin (smaller of vw/vh)","isCorrect":true,"explanation":"Correct. vmin is relative to smaller viewport dimension."},{"id":"o4","text":"em (relative to parent)","isCorrect":false,"explanation":"Incorrect. em is relative to parent, not viewport."}]',
      'vw (viewport width)',
      'Viewport units: vw (viewport width 1%), vh (viewport height 1%), vmin (smaller of vw/vh), vmax (larger of vw/vh). These are relative to viewport size, not parent elements. Useful for full-screen layouts, hero sections.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'units', 'viewport', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the ''<code>:is</code>()'' and ''<code>:where</code>()'' pseudo-class functions? How do they differ?',
      'Modern CSS provides selector grouping functions. Explain <code>:is</code>() and <code>:where</code>() and their specificity differences.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"<code>:is</code>() maintains specificity; <code>:where</code>() has zero specificity (always)","isCorrect":true,"explanation":"Correct. This is the key difference."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They handle specificity differently."},{"id":"o3","text":"<code>:where</code>() has higher specificity","isCorrect":false,"explanation":"Incorrect. <code>:where</code>() has zero specificity."},{"id":"o4","text":"Both are deprecated","isCorrect":false,"explanation":"Incorrect. Both are modern, useful features."}]',
      '<code>:is</code>() maintains specificity; <code>:where</code>() has zero specificity (always)',
      '<code>:is</code>(selector1, selector2) groups selectors, specificity = most specific in group. <code>:where</code>(selector1, selector2) groups selectors, specificity = 0 (always). <code>:is</code>() maintains specificity, <code>:where</code>() resets it. Use <code>:where</code>() to avoid specificity conflicts, <code>:is</code>() when you need specificity.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'selectors', 'is', 'where', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS custom properties (variables) scoping. How does inheritance work with CSS variables?',
      'CSS variables have scoping rules. Explain how custom properties inherit and can be overridden.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Variables inherit down the DOM tree; can be overridden in any selector for local scope","isCorrect":true,"explanation":"Correct. CSS variables cascade and can be scoped."},{"id":"o2","text":"Variables don''t inherit","isCorrect":false,"explanation":"Incorrect. CSS variables do inherit."},{"id":"o3","text":"Only work at <code>:root</code> level","isCorrect":false,"explanation":"Incorrect. Variables can be defined at any level."},{"id":"o4","text":"Require JavaScript to work","isCorrect":false,"explanation":"Incorrect. CSS variables are pure CSS."}]',
      'Variables inherit down the DOM tree; can be overridden in any selector for local scope',
      'CSS variables inherit (cascade down). Define at <code>:root</code> for global scope. Override in any selector for local scope. Child elements inherit parent''s variable values. Use <code>var(--name, fallback)</code> for fallback values. Scoped to selector and descendants.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'css-variables', 'custom-properties', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS properties are not inherited by default? (Select all that apply)',
      'Understanding inheritance helps write efficient CSS. Identify properties that are not inherited.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"margin (not inherited)","isCorrect":true,"explanation":"Correct. margin is not inherited."},{"id":"o2","text":"padding (not inherited)","isCorrect":true,"explanation":"Correct. padding is not inherited."},{"id":"o3","text":"width / height (not inherited)","isCorrect":true,"explanation":"Correct. width and height are not inherited."},{"id":"o4","text":"color (inherited)","isCorrect":false,"explanation":"Incorrect. color is inherited."}]',
      'margin (not inherited)',
      'Non-inherited: margin, padding, border, width, height, display, position, float, clear, background, z-index, overflow, text-decoration (some values), vertical-align. These must be set on each element or use ''inherit'' keyword.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'inheritance', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between ''<code>::first-line</code>'' and ''<code>::first-letter</code>'' pseudo-elements?',
      'Text pseudo-elements style specific parts. Explain first-line vs first-letter and their use cases.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>::first-line</code>: entire first line; <code>::first-letter</code>: single first character","isCorrect":true,"explanation":"Correct. They target different scopes."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They target different parts of text."},{"id":"o3","text":"<code>::first-letter</code> styles the whole line","isCorrect":false,"explanation":"Incorrect. <code>::first-letter</code> only styles the first character."},{"id":"o4","text":"Only work on inline elements","isCorrect":false,"explanation":"Incorrect. They work on block-level elements."}]',
      '<code>::first-line</code>: entire first line; <code>::first-letter</code>: single first character',
      '<code>::first-line</code> styles first line of block element (wraps based on width). <code>::first-letter</code> styles first letter (drop caps, styling). <code>::first-line</code> can style multiple words, <code>::first-letter</code> is single character. Both only work on block-level elements.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'pseudo-elements', 'typography', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain the ''<code>:has</code>()'' pseudo-class. What problem does it solve and what are its limitations?',
      '<code>:has</code>() is a powerful modern selector. Explain its purpose, use cases, and browser support considerations.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Parent selector - selects element based on descendants; limited browser support","isCorrect":true,"explanation":"Correct. <code>:has</code>() enables parent selection."},{"id":"o2","text":"Only selects children","isCorrect":false,"explanation":"Incorrect. <code>:has</code>() selects the parent based on children."},{"id":"o3","text":"Works in all browsers","isCorrect":false,"explanation":"Incorrect. Browser support is limited."},{"id":"o4","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. <code>:has</code>() is a modern, powerful feature."}]',
      'Parent selector - selects element based on descendants; limited browser support',
      '<code>:has</code>() is parent selector - selects parent based on child. Example: div<code>:has</code>(> img) selects divs containing img. Solves ''parent selector problem''. Limited browser support (Safari 15<code>.4</code>+, Chrome 105+). Enables conditional styling based on content.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'basics', 'selectors', 'has', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS Grid ''subgrid'' feature. What problem does it solve and what are its limitations?',
      'Subgrid is an advanced Grid feature. Explain its purpose, use cases, and browser support.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Inherits parent grid tracks for alignment; limited browser support (Firefox, Safari)","isCorrect":true,"explanation":"Correct. subgrid solves nested grid alignment."},{"id":"o2","text":"Creates independent nested grid","isCorrect":false,"explanation":"Incorrect. That''s regular nested grid, not subgrid."},{"id":"o3","text":"Works in all browsers","isCorrect":false,"explanation":"Incorrect. Browser support is limited."},{"id":"o4","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. subgrid is a modern feature."}]',
      'Inherits parent grid tracks for alignment; limited browser support (Firefox, Safari)',
      'subgrid allows nested grid to inherit parent''s grid tracks. Solves alignment in nested grids. Without subgrid, nested grids are independent. With subgrid, child aligns with parent. Limited support: Firefox 71+, Safari 16+. Use for card layouts, complex nested structures.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'grid', 'subgrid', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which Flexbox properties control item alignment on the cross axis? (Select all that apply)',
      'Flexbox cross-axis alignment requires specific properties. Identify properties that control cross-axis alignment.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"align-items (all items on cross axis)","isCorrect":true,"explanation":"Correct. align-items controls cross-axis alignment."},{"id":"o2","text":"align-self (individual item on cross axis)","isCorrect":true,"explanation":"Correct. align-self overrides align-items."},{"id":"o3","text":"align-content (wrapped lines on cross axis)","isCorrect":true,"explanation":"Correct. align-content aligns wrapped content."},{"id":"o4","text":"justify-content (main axis, not cross axis)","isCorrect":false,"explanation":"Incorrect. justify-content works on main axis."}]',
      'align-items (all items on cross axis)',
      'Cross-axis alignment: align-items (all items), align-self (individual item), align-content (wrapped lines). These work on cross axis (perpendicular to main axis). justify-content works on main axis.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'flexbox', 'alignment', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between ''grid-auto-rows'' and ''grid-template-rows'' in CSS Grid?',
      'Grid row definition has multiple approaches. Explain grid-template-rows vs grid-auto-rows and when to use each.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"grid-template-rows: explicit rows; grid-auto-rows: implicit/auto-created rows","isCorrect":true,"explanation":"Correct. Template is for explicit, auto is for implicit rows."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They define different row types."},{"id":"o3","text":"grid-auto-rows is deprecated","isCorrect":false,"explanation":"Incorrect. Both are valid and useful."},{"id":"o4","text":"Only grid-template-rows works","isCorrect":false,"explanation":"Incorrect. Both serve different purposes."}]',
      'grid-template-rows: explicit rows; grid-auto-rows: implicit/auto-created rows',
      'grid-template-rows: defines explicit rows (named or sized). grid-auto-rows: defines size for implicit rows (created automatically when items exceed explicit rows). Use template for known structure, auto for dynamic content. Can combine both.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'grid', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain ''<code>position:</code> sticky'' behavior. What are the requirements for sticky positioning to work?',
      'Sticky positioning has specific requirements. Explain what''s needed for sticky to function correctly.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"Requires top/left/right/bottom value; parent must allow scrolling; can break with overflow: hidden","isCorrect":true,"explanation":"Correct. Sticky has specific requirements."},{"id":"o2","text":"Works without any properties","isCorrect":false,"explanation":"Incorrect. Requires positioning values."},{"id":"o3","text":"Always works regardless of parent","isCorrect":false,"explanation":"Incorrect. Parent properties affect it."},{"id":"o4","text":"Only works with JavaScript","isCorrect":false,"explanation":"Incorrect. Sticky is pure CSS."}]',
      'Requires top/left/right/bottom value; parent must allow scrolling; can break with overflow: hidden',
      'Requirements: top/left/right/bottom must be set (defines stick point). Parent container must have space (can''t overflow). Works within containing block. If parent has overflow: hidden/scroll, sticky may not work. Needs scrollable ancestor.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'positioning', 'sticky', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which CSS Grid properties enable responsive grid layouts without media queries? (Select all that apply)',
      'Grid provides responsive capabilities. Identify Grid features that enable responsive layouts without media queries.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"auto-fit / auto-fill with minmax() (responsive columns)","isCorrect":true,"explanation":"Correct. auto-fit/auto-fill enable responsive grids."},{"id":"o2","text":"fr units (flexible distribution)","isCorrect":true,"explanation":"Correct. fr units are flexible."},{"id":"o3","text":"min-content / max-content (content-based sizing)","isCorrect":true,"explanation":"Correct. These adapt to content."},{"id":"o4","text":"Fixed pixel values (not responsive)","isCorrect":false,"explanation":"Incorrect. Fixed pixels are not responsive."}]',
      'auto-fit / auto-fill with minmax() (responsive columns)',
      'auto-fit/auto-fill with minmax() create responsive columns. fr units distribute space flexibly. min-content, max-content adapt to content. repeat(auto-fit, minmax(<code>200px</code>, <code>1fr</code>)) creates responsive grid. No media queries needed.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'grid', 'responsive', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of ''gap'' property in Flexbox and Grid? How does it differ from margins?',
      'Gap property simplifies spacing. Explain gap vs margins and when to use each.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>gap:</code> spacing between items in Flexbox/Grid; simpler than margins, no edge cases","isCorrect":true,"explanation":"Correct. gap is cleaner for Flexbox/Grid spacing."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. gap only works in Flexbox/Grid."},{"id":"o3","text":"gap works on all elements","isCorrect":false,"explanation":"Incorrect. gap only works in Flexbox/Grid contexts."},{"id":"o4","text":"margins are always better","isCorrect":false,"explanation":"Incorrect. gap is often simpler for Flexbox/Grid."}]',
      '<code>gap:</code> spacing between items in Flexbox/Grid; simpler than margins, no edge cases',
      '<code>gap:</code> spacing between flex/grid items (row-gap, column-gap). Only works in Flexbox/Grid. Margins: spacing around any element, works everywhere. gap is simpler (no negative margins, no first/last child exceptions), margins more flexible but more complex.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'flexbox', 'grid', 'gap', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS Grid ''masonry'' layout. What is it and what''s the current browser support?',
      'Masonry is a proposed Grid feature. Explain masonry layout and its implementation status.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Pinterest-style layout; experimental, not standardized; limited browser support","isCorrect":true,"explanation":"Correct. Masonry is experimental."},{"id":"o2","text":"Standard CSS Grid feature","isCorrect":false,"explanation":"Incorrect. Masonry is not yet standardized."},{"id":"o3","text":"Works in all browsers","isCorrect":false,"explanation":"Incorrect. Support is very limited."},{"id":"o4","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. It''s a proposed feature, not deprecated."}]',
      'Pinterest-style layout; experimental, not standardized; limited browser support',
      'Masonry: Pinterest-style layout where items flow into shortest column. Proposed for CSS Grid but not yet standardized. Firefox has experimental support behind flag. Workaround: use JavaScript libraries or column-based approaches. Not production-ready yet.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'grid', 'masonry', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Which Flexbox properties control item sizing when there''s extra space? (Select all that apply)',
      'Flexbox sizing controls how items grow and shrink. Identify properties that control item sizing.',
      'multiple-select',
      'intermediate',
      15,
      '[{"id":"o1","text":"flex-grow (growth factor)","isCorrect":true,"explanation":"Correct. flex-grow controls growth."},{"id":"o2","text":"flex-shrink (shrink factor)","isCorrect":true,"explanation":"Correct. flex-shrink controls shrinking."},{"id":"o3","text":"flex-basis (initial size)","isCorrect":true,"explanation":"Correct. flex-basis sets initial size."},{"id":"o4","text":"justify-content (alignment, not sizing)","isCorrect":false,"explanation":"Incorrect. justify-content controls alignment, not sizing."}]',
      'flex-grow (growth factor)',
      '<code>flex-grow:</code> growth factor (how much item grows). <code>flex-shrink:</code> shrink factor (how much item shrinks). <code>flex-basis:</code> initial size. <code>flex:</code> shorthand (grow shrink basis). min-width/max-width also affect sizing. These control how items use available space.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'flexbox', 'sizing', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between ''align-items'' and ''align-content'' in Flexbox?',
      'Flexbox has two alignment properties for cross axis. Explain the difference between align-items and align-content.',
      'multiple-choice',
      'intermediate',
      15,
      '[{"id":"o1","text":"<code>align-items:</code> items within lines; <code>align-content:</code> spacing between wrapped lines","isCorrect":true,"explanation":"Correct. They control different aspects of alignment."},{"id":"o2","text":"They are identical","isCorrect":false,"explanation":"Incorrect. They work on different levels."},{"id":"o3","text":"align-content is deprecated","isCorrect":false,"explanation":"Incorrect. Both are valid and useful."},{"id":"o4","text":"align-items only works with single line","isCorrect":false,"explanation":"Incorrect. align-items works with wrapped content too."}]',
      '<code>align-items:</code> items within lines; <code>align-content:</code> spacing between wrapped lines',
      '<code>align-items:</code> aligns items within each line (single-line or multi-line). <code>align-content:</code> aligns lines when content wraps (only works with flex-wrap: wrap). <code>align-items:</code> per-line alignment. <code>align-content:</code> between-lines spacing. Use align-items for item alignment, align-content for line spacing.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'flexbox', 'alignment', 'intermediate'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    ),
    (
      gen_random_uuid(),
      'Explain CSS Grid ''auto-placement'' algorithm. How does it determine where items are placed?',
      'Grid automatically places items. Explain the auto-placement algorithm and how items flow into the grid.',
      'multiple-choice',
      'advanced',
      20,
      '[{"id":"o1","text":"Items flow row by row (default); grid-auto-flow controls direction and gap-filling","isCorrect":true,"explanation":"Correct. Auto-placement follows grid-auto-flow rules."},{"id":"o2","text":"Random placement","isCorrect":false,"explanation":"Incorrect. Placement follows specific algorithm."},{"id":"o3","text":"Only works with explicit placement","isCorrect":false,"explanation":"Incorrect. Auto-placement works when no explicit placement."},{"id":"o4","text":"Is deprecated","isCorrect":false,"explanation":"Incorrect. Auto-placement is a core Grid feature."}]',
      'Items flow row by row (default); grid-auto-flow controls direction and gap-filling',
      'Auto-placement: items flow row by row, left to right. grid-auto-flow controls direction: row (default, left-right), column (top-bottom), dense (fills gaps). Items without explicit placement use auto-placement. Can specify grid-auto-flow: dense to fill gaps.',
      NULL,
      ARRAY['Consider browser compatibility and modern CSS features', 'Think about performance implications and best practices', 'Remember that CSS affects both visual design and user experience'],
      ARRAY['css', 'layout', 'grid', 'auto-placement', 'difficult'],
      '{}',
      NULL,
      'c66e9e94-32e0-4dea-8594-4931251fa59d',
      NULL,
      true,
      '2025-11-18T18:46:59.272Z',
      '2025-11-18T18:46:59.272Z',
      '18dd4733-a53b-4962-8884-402d4a92b5aa',
      300
    );