INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is rate limiting and why is it important?',
      'Explain how rate limiting protects web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks.","isCorrect":true,"explanation":"Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks.',
      'Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'api-security', 'rate limiting', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you secure API endpoints in a frontend application?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use authentication tokens like JWT","isCorrect":true,"explanation":""},{"id":"o2","text":"Enforce HTTPS for all API requests","isCorrect":true,"explanation":""},{"id":"o3","text":"Validate all user inputs on the server","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on client-side checks","isCorrect":false,"explanation":""}]',
      'Use authentication tokens like JWT',
      'Server-side validation, HTTPS, and token-based authentication are essential. Client-side checks alone cannot ensure security.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'api-security', 'api security', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is JWT and how does it help with security?',
      'Explain JWT (JSON Web Token) and its use in authentication.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication.","isCorrect":true,"explanation":"JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication.',
      'JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'authentication-&-authorization', 'authentication', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is token expiration and why is it important?',
      'Explain token expiration in authentication and session management.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period.","isCorrect":true,"explanation":"Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period.',
      'Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'authentication-&-authorization', 'authentication', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is OAuth 2.0?',
      'Explain OAuth 2.0 and its use in web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration.","isCorrect":true,"explanation":"OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration.',
      'OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'authentication-&-authorization', 'authentication', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is clickjacking?',
      'Clickjacking is a type of attack where a user is tricked into clicking elements hidden under legitimate UI elements. Explain how it works and prevention strategies.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays.","isCorrect":true,"explanation":"Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays.',
      'Clickjacking tricks users into clicking hidden elements using overlays or iframes. Prevention: X-Frame-Options header, CSP frame-ancestors, avoid transparent overlays.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which HTTP header helps prevent clickjacking?',
      'Select the correct header used to prevent clickjacking attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o2","text":"Content-Security-Policy (frame-ancestors)","isCorrect":true,"explanation":""},{"id":"o3","text":"X-Content-Type-Options","isCorrect":false,"explanation":""},{"id":"o4","text":"Strict-Transport-Security","isCorrect":false,"explanation":""}]',
      'X-Frame-Options',
      'X-Frame-Options and CSP frame-ancestors prevent malicious iframe embedding.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Clickjacking (UI Redressing)?',
      'Explain what clickjacking is and how attackers can exploit it to trick users.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms.","isCorrect":true,"explanation":"Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms.',
      'Clickjacking tricks a user into clicking on a hidden element or iframe, causing them to perform actions they didn’t intend, such as changing settings, liking a page, or submitting forms.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent clickjacking?',
      'Select all correct methods to prevent clickjacking attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use X-Frame-Options: DENY or SAMEORIGIN","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable JavaScript entirely","isCorrect":false,"explanation":""},{"id":"o4","text":"Detect and prevent iframes using JS","isCorrect":true,"explanation":""}]',
      'Use X-Frame-Options: DENY or SAMEORIGIN',
      'X-Frame-Options and frame-ancestors protect against embedding. JS detection can add extra protection; disabling JS is impractical.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Clickjacking (UI Redressing)?',
      'Explain how clickjacking works and its impact on users.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions.","isCorrect":true,"explanation":"Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions.',
      'Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent Clickjacking attacks?',
      'Select all correct mitigation strategies.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use X-Frame-Options header","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Obfuscate your buttons with CSS","isCorrect":false,"explanation":""},{"id":"o4","text":"Require user confirmation for critical actions","isCorrect":true,"explanation":""}]',
      'Use X-Frame-Options header',
      'X-Frame-Options and CSP frame-ancestors prevent your site from being framed; additional user confirmation mitigates risk. CSS obfuscation is not a reliable defense.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which HTTP header helps prevent Clickjacking?',
      'Select the correct answer.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o2","text":"Content-Security-Policy","isCorrect":false,"explanation":""},{"id":"o3","text":"Strict-Transport-Security","isCorrect":false,"explanation":""},{"id":"o4","text":"X-Content-Type-Options","isCorrect":false,"explanation":""}]',
      'X-Frame-Options',
      'The X-Frame-Options header prevents your site from being embedded in iframes, mitigating clickjacking.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is UI Redressing (Clickjacking)?',
      'Explain how clickjacking attacks manipulate user interface elements.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings.","isCorrect":true,"explanation":"Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings.',
      'Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you prevent clickjacking attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use X-Frame-Options header to deny framing","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely only on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Implement UI overlays as security measure","isCorrect":false,"explanation":""}]',
      'Use X-Frame-Options header to deny framing',
      'X-Frame-Options and CSP frame-ancestors prevent your site from being embedded in iframes, mitigating clickjacking attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Clickjacking (UI Redressing)?',
      'Explain how clickjacking attacks work and why they are dangerous.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments.","isCorrect":true,"explanation":"Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments.',
      'Clickjacking tricks a user into clicking on invisible or disguised elements on a page, performing actions without their knowledge, such as changing settings or authorizing payments.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent clickjacking attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use X-Frame-Options header","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable JavaScript completely","isCorrect":false,"explanation":""},{"id":"o4","text":"Use secure authentication only","isCorrect":false,"explanation":""}]',
      'Use X-Frame-Options header',
      'X-Frame-Options and CSP frame-ancestors prevent a site from being embedded in iframes, mitigating clickjacking attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'clickjacking', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Clickjacking (UI Redressing)?',
      'Explain how clickjacking works and why it''s dangerous.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions.","isCorrect":true,"explanation":"Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions.',
      'Clickjacking tricks users into clicking invisible or disguised elements, causing unintended actions like approving transactions, changing settings, or enabling permissions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'clickjacking', 'ui redressing', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: CSP (Content Security Policy) can help mitigate XSS.',
      'Evaluate whether this statement is true or false.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"CSP restricts allowed script sources, mitigating XSS."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of a Content Security Policy (CSP)?',
      'Explain how CSP protects web applications and what types of attacks it mitigates.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks.","isCorrect":true,"explanation":"CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks.',
      'CSP restricts which sources are allowed for scripts, styles, and media. It reduces XSS, clickjacking, and data injection risks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of Content Security Policy (CSP) in web security?',
      'Explain how CSP helps protect frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed.","isCorrect":true,"explanation":"CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed.',
      'CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Select the correct ways to implement CSP.',
      'Choose all that apply.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use meta tag in HTML","isCorrect":true,"explanation":""},{"id":"o2","text":"Set HTTP response headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely solely on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Whitelist only trusted sources","isCorrect":true,"explanation":""}]',
      'Use meta tag in HTML',
      'CSP works via meta tags or headers, and whitelisting trusted sources restricts malicious content.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the Content Security Policy (CSP) header?',
      'Explain how CSP helps prevent XSS and other attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks.","isCorrect":true,"explanation":"CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks.',
      'CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does a Content Security Policy (CSP) improve security?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Restrict sources of scripts, styles, and media","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevent inline script execution","isCorrect":true,"explanation":""},{"id":"o3","text":"Encrypt cookies automatically","isCorrect":false,"explanation":""},{"id":"o4","text":"Mitigate XSS attacks","isCorrect":true,"explanation":""}]',
      'Restrict sources of scripts, styles, and media',
      'CSP controls which sources are allowed for scripts and styles, blocks inline scripts, and helps mitigate XSS attacks. It does not encrypt cookies.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'csp', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of Content Security Policy (CSP) in frontend security?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Restricts sources of scripts and other resources","isCorrect":true,"explanation":""},{"id":"o2","text":"Helps prevent XSS attacks","isCorrect":true,"explanation":""},{"id":"o3","text":"Replaces the need for input validation","isCorrect":false,"explanation":""},{"id":"o4","text":"Can block inline styles and scripts if configured","isCorrect":true,"explanation":""}]',
      'Restricts sources of scripts and other resources',
      'CSP controls resource loading and helps prevent XSS, but does not replace input validation.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'content-security-policy-csp', 'headers', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Cross-Origin Resource Sharing (CORS) overrides the Same-Origin Policy.',
      'Evaluate this statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"CORS allows controlled access to resources from different origins, effectively relaxing SOP for approved domains."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-origin-resource-sharing-cors', 'cors', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CORS (Cross-Origin Resource Sharing)?',
      'Explain CORS and its role in web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access.","isCorrect":true,"explanation":"CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access.',
      'CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-origin-resource-sharing-cors', 'cors', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you safely allow cross-origin requests?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Set Access-Control-Allow-Origin to a specific trusted domain","isCorrect":true,"explanation":""},{"id":"o2","text":"Use credentials (cookies) only when necessary","isCorrect":true,"explanation":""},{"id":"o3","text":"Set Access-Control-Allow-Origin to ''*''","isCorrect":false,"explanation":""},{"id":"o4","text":"Use server-side proxy to handle requests","isCorrect":true,"explanation":""}]',
      'Set Access-Control-Allow-Origin to a specific trusted domain',
      'Allow only trusted domains, use credentials carefully, and proxy requests server-side to control access. Using ''*'' allows any domain and is unsafe for sensitive data.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-origin-resource-sharing-cors', 'cors', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: CSRF attacks rely on user authentication.',
      'Evaluate whether this statement is true or false.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"CSRF exploits the fact that the user is already authenticated."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CSRF (Cross-Site Request Forgery)?',
      'Explain what CSRF attacks are and how they work in web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials.","isCorrect":true,"explanation":"CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials.',
      'CSRF tricks a logged-in user into performing unwanted actions on a web application by submitting requests without their consent, using their authentication credentials.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which measures can prevent CSRF attacks?',
      'Select all correct prevention techniques.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use anti-CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate the Origin and Referer headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Enable HttpOnly cookies","isCorrect":false,"explanation":""},{"id":"o4","text":"Require user confirmation for critical actions","isCorrect":true,"explanation":""}]',
      'Use anti-CSRF tokens in forms',
      'CSRF prevention uses tokens, checks headers, and sometimes asks users for confirmation.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CSRF (Cross-Site Request Forgery)?',
      'Explain what CSRF attacks are and how they affect web applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions.","isCorrect":true,"explanation":"CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions.',
      'CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent CSRF attacks?',
      'Select all correct methods to prevent CSRF.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use anti-CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookie attributes","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Validate origin and referer headers","isCorrect":true,"explanation":""}]',
      'Use anti-CSRF tokens in forms',
      'Anti-CSRF tokens, SameSite cookies, and validating headers are standard defenses; disabling HTTPS weakens security.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CSRF (Cross-Site Request Forgery)?',
      'Explain how CSRF attacks work and why they are dangerous.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent.","isCorrect":true,"explanation":"CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent.',
      'CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent CSRF attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use CSRF tokens in forms and API requests","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Validate the origin or referer header","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on HTTPS","isCorrect":false,"explanation":""}]',
      'Use CSRF tokens in forms and API requests',
      'CSRF tokens, SameSite cookies, and header validation prevent CSRF. HTTPS alone does not protect against CSRF.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CSRF (Cross-Site Request Forgery)?',
      'Explain how CSRF attacks work and why they are dangerous.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content.","isCorrect":true,"explanation":"CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content.',
      'CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent CSRF attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use CSRF tokens for forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate Origin and Referer headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely only on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Use SameSite attribute on cookies","isCorrect":true,"explanation":""}]',
      'Use CSRF tokens for forms',
      'CSRF tokens, checking Origin/Referer, and setting cookies as SameSite help prevent CSRF attacks. HTTPS alone does not prevent CSRF.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does CSRF (Cross-Site Request Forgery) work?',
      'Explain the mechanism of a CSRF attack and its potential impact.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site.","isCorrect":true,"explanation":"CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site.',
      'CSRF tricks an authenticated user into unknowingly performing actions on a web application, like changing account details or transferring funds, by submitting malicious requests from another site.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you prevent CSRF attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookie attribute","isCorrect":true,"explanation":""},{"id":"o3","text":"Use HTTPS","isCorrect":true,"explanation":""},{"id":"o4","text":"Disable cookies completely","isCorrect":false,"explanation":""}]',
      'Use CSRF tokens in forms',
      'CSRF tokens, SameSite cookies, and HTTPS help prevent CSRF attacks. Disabling cookies is not practical for most web apps.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'cross-site-request-forgery-csrf', 'csrf', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which is safer for sensitive data transmission: HTTP or HTTPS?',
      'Select the correct answer.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HTTP","isCorrect":false,"explanation":""},{"id":"o2","text":"HTTPS","isCorrect":true,"explanation":""},{"id":"o3","text":"Both are equally safe","isCorrect":false,"explanation":""},{"id":"o4","text":"Depends on browser","isCorrect":false,"explanation":""}]',
      'HTTPS',
      'HTTPS encrypts data in transit, ensuring confidentiality, integrity, and protection against MITM attacks, unlike HTTP.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'https-&-ssl/tls', 'transport security', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do HTTPS and TLS protect against web attacks?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Encrypts data in transit","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents eavesdropping and tampering","isCorrect":true,"explanation":""},{"id":"o3","text":"Automatically sanitizes user inputs","isCorrect":false,"explanation":""},{"id":"o4","text":"Provides server authentication","isCorrect":true,"explanation":""}]',
      'Encrypts data in transit',
      'HTTPS/TLS encrypts data, ensures integrity, and authenticates servers. It does not sanitize inputs.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'https-&-ssl/tls', 'tls', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is input validation and why is it important for security?',
      'Explain the role of input validation in preventing attacks like XSS and SQL Injection.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks.","isCorrect":true,"explanation":"Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks.',
      'Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'input-validation-&-sanitization', 'input validation', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a security audit for frontend applications?',
      'Explain the purpose of frontend security audits.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them.","isCorrect":true,"explanation":"A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them.',
      'A security audit identifies vulnerabilities in frontend code, including XSS, CSRF, insecure storage, misconfigured headers, and third-party libraries, and provides recommendations to fix them.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'security-auditing', 'audit', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following headers help improve web security?',
      'Select all correct HTTP headers.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Strict-Transport-Security","isCorrect":true,"explanation":""},{"id":"o2","text":"X-Content-Type-Options","isCorrect":true,"explanation":""},{"id":"o3","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o4","text":"X-Powered-By","isCorrect":false,"explanation":""}]',
      'Strict-Transport-Security',
      'HSTS, X-Content-Type-Options, and X-Frame-Options improve security; X-Powered-By reveals server info and is not protective.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'security-headers', 'headers', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are security headers and why are they important?',
      'Explain common security headers and their role in protecting frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security.","isCorrect":true,"explanation":"Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security.',
      'Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'security-headers', 'headers', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why should frontend developers care about security headers?',
      'Explain their role and importance in web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior.","isCorrect":true,"explanation":"Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior.',
      'Security headers like CSP, X-Frame-Options, and Strict-Transport-Security help protect against XSS, clickjacking, and MITM attacks by instructing the browser on safe behavior.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'security-headers', 'headers', 'beginner', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do HttpOnly and Secure cookies improve security?',
      'Explain how the HttpOnly and Secure flags help prevent attacks.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS.","isCorrect":true,"explanation":"HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS.',
      'HttpOnly prevents JavaScript from reading cookies (protects against XSS). Secure ensures cookies are only sent over HTTPS.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of these are valid ways to secure cookies against XSS and CSRF?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Set HttpOnly flag","isCorrect":true,"explanation":""},{"id":"o2","text":"Set Secure flag","isCorrect":true,"explanation":""},{"id":"o3","text":"Use SameSite=strict","isCorrect":true,"explanation":""},{"id":"o4","text":"Store sensitive info in localStorage","isCorrect":false,"explanation":""}]',
      'Set HttpOnly flag',
      'HttpOnly prevents JS access, Secure restricts to HTTPS, and SameSite limits cross-site requests. LocalStorage is accessible by JS and vulnerable to XSS.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which practices improve frontend security regarding cookies?',
      'Select all correct options.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Set HttpOnly flag","isCorrect":true,"explanation":""},{"id":"o2","text":"Set Secure flag for HTTPS","isCorrect":true,"explanation":""},{"id":"o3","text":"Use SameSite attribute","isCorrect":true,"explanation":""},{"id":"o4","text":"Store passwords directly in cookies","isCorrect":false,"explanation":""}]',
      'Set HttpOnly flag',
      'HttpOnly, Secure, and SameSite protect cookies from XSS, MITM, and CSRF. Storing passwords in cookies is insecure.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Using HttpOnly and Secure flags on cookies protects against XSS and MITM attacks.',
      'Evaluate the statement.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"HttpOnly prevents JavaScript access to cookies, mitigating XSS; Secure ensures cookies are only sent over HTTPS, mitigating MITM attacks."},{"id":"o2","text":"False","isCorrect":false,"explanation":""},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the SameSite cookie attribute?',
      'Explain how SameSite helps with web security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks.","isCorrect":true,"explanation":"The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review web security concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider security best practices.","isCorrect":false,"explanation":""}]',
      'The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks.',
      'The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['security', 'session-management', 'cookies', 'intermediate'],
      '{}',
      NULL,
      'e41ed4a2-738e-487f-8d1e-4e7df90ec478',
      NULL,
      true,
      '2025-11-18T18:46:59.320Z',
      '2025-11-18T18:46:59.320Z',
      NULL,
      300
    );