INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is the difference between REST and GraphQL when designing frontend APIs?',
      'Explain how each API style affects data fetching, over-fetching, and frontend flexibility.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"REST endpoints return fixed data structures","isCorrect":true,"explanation":""},{"id":"o2","text":"GraphQL allows querying only required fields","isCorrect":true,"explanation":""},{"id":"o3","text":"GraphQL eliminates the need for pagination","isCorrect":false,"explanation":""}]',
      'REST endpoints return fixed data structures',
      'The correct answer is: REST endpoints return fixed data structures',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you design a frontend data store for posts and comments?',
      'Explain the structure and normalization strategies for storing related entities in frontend state.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates.","isCorrect":true,"explanation":"Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates."},{"id":"o2","text":"Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates.',
      'Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle data caching in frontend applications?',
      'Explain strategies for caching API responses and syncing with the server.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions.","isCorrect":true,"explanation":"Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions."},{"id":"o2","text":"Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions.',
      'Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between localStorage, sessionStorage, and IndexedDB?',
      'Explain when to use each browser storage type for frontend data persistence.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"localStorage persists data indefinitely across sessions","isCorrect":true,"explanation":""},{"id":"o2","text":"sessionStorage persists data only for the session","isCorrect":true,"explanation":""},{"id":"o3","text":"IndexedDB is useful for storing large structured data","isCorrect":true,"explanation":""},{"id":"o4","text":"localStorage automatically syncs with the server","isCorrect":false,"explanation":""}]',
      'localStorage persists data indefinitely across sessions',
      'The correct answer is: localStorage persists data indefinitely across sessions',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you measure frontend network performance?',
      'Explain tools and metrics used to analyze network requests in frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets.","isCorrect":true,"explanation":"Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets."},{"id":"o2","text":"Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets.',
      'Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a frontend performance budget and why is it important?',
      'Describe the concept of a performance budget and how it helps maintain good UX.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times.","isCorrect":true,"explanation":"A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times."},{"id":"o2","text":"A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times.',
      'A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you profile and optimize JavaScript performance?',
      'Explain techniques for identifying and fixing slow JS execution.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations.","isCorrect":true,"explanation":"Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations."},{"id":"o2","text":"Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations.',
      'Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you profile rendering performance in a React app?',
      'Discuss tools and techniques for identifying re-render bottlenecks.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization.","isCorrect":true,"explanation":"Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization."},{"id":"o2","text":"Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization.',
      'Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are Lighthouse audits and how do they help in frontend system design?',
      'Explain the purpose of Lighthouse and its reports for performance and accessibility.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps.","isCorrect":true,"explanation":"Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps."},{"id":"o2","text":"Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps.',
      'Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you monitor accessibility issues in a frontend application?',
      'Describe tools and methods to detect and fix a11y problems.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems.","isCorrect":true,"explanation":"Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems."},{"id":"o2","text":"Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems.',
      'Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Time to Interactive (TTI) and why is it important?',
      'Explain the TTI metric and its significance for user experience.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX.","isCorrect":true,"explanation":"TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX."},{"id":"o2","text":"TTI measures the time until the page becomes fully interactive for users","isCorrect":false,"explanation":""},{"id":"o3","text":" Lower TTI improves perceived performance and UX","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX.',
      'TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Largest Contentful Paint (LCP) and how can you improve it?',
      'Explain LCP and strategies to reduce its value.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN.","isCorrect":true,"explanation":"LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN."},{"id":"o2","text":"LCP measures time for the largest visible element to load","isCorrect":false,"explanation":""},{"id":"o3","text":" Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN.',
      'LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you detect memory leaks in frontend applications?',
      'Describe methods to identify and fix memory leaks in JavaScript apps.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks.","isCorrect":true,"explanation":"Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks."},{"id":"o2","text":"Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks.',
      'Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are some strategies to monitor frontend errors in production?',
      'Explain how to track and report frontend runtime errors effectively.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging.","isCorrect":true,"explanation":"Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging."},{"id":"o2","text":"Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions","isCorrect":false,"explanation":""},{"id":"o3","text":" Include context and stack traces for debugging","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging.',
      'Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a signed URL and why is it important for security?',
      'Explain the purpose of signed URLs for accessing private resources.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security.","isCorrect":true,"explanation":"Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security."},{"id":"o2","text":"Signed URLs provide temporary, time-limited access to private resources on a server or CDN","isCorrect":false,"explanation":""},{"id":"o3","text":" They prevent unauthorized access and allow caching while maintaining security","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security.',
      'Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you prevent CSRF attacks in frontend applications?',
      'Describe techniques to protect against Cross-Site Request Forgery.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests.","isCorrect":true,"explanation":"Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests."},{"id":"o2","text":"Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests.',
      'Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you prevent XSS attacks in frontend applications?',
      'Explain strategies to mitigate Cross-Site Scripting vulnerabilities.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend.","isCorrect":true,"explanation":"Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend."},{"id":"o2","text":"Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend.',
      'Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid <code>innerHTML</code>, and validate input on both frontend and backend.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are HTTP-only cookies and why are they important?',
      'Explain the role of HTTP-only cookies in frontend security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data.","isCorrect":true,"explanation":"HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data."},{"id":"o2","text":"HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data.',
      'HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle authentication in frontend applications?',
      'Discuss strategies for managing user authentication and session state.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests.","isCorrect":true,"explanation":"Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests."},{"id":"o2","text":"Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests.',
      'Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between JWT and opaque tokens?',
      'Compare JWT and opaque tokens for frontend authentication.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"JWT is self-contained, includes claims, can be verified without server","isCorrect":true,"explanation":""},{"id":"o2","text":"Opaque tokens are random identifiers, require server to validate","isCorrect":true,"explanation":""},{"id":"o3","text":"JWT cannot be used in SPAs","isCorrect":false,"explanation":""}]',
      'JWT is self-contained, includes claims, can be verified without server',
      'The correct answer is: JWT is self-contained, includes claims, can be verified without server',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is CORS and why is it important in frontend apps?',
      'Explain Cross-Origin Resource Sharing and its relevance for security.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests.","isCorrect":true,"explanation":"CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests."},{"id":"o2","text":"CORS is a browser security mechanism that controls which origins can access resources","isCorrect":false,"explanation":""},{"id":"o3","text":" It prevents unauthorized cross-origin requests","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests.',
      'CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you securely handle API tokens in frontend applications?',
      'Discuss best practices for storing and using API tokens in the browser.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header.","isCorrect":true,"explanation":"Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header."},{"id":"o2","text":"Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header.',
      'Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between authentication and authorization?',
      'Explain the difference between verifying identity and granting access.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Authentication verifies user identity","isCorrect":true,"explanation":""},{"id":"o2","text":"Authorization determines access level or permissions","isCorrect":true,"explanation":""},{"id":"o3","text":"They are the same","isCorrect":false,"explanation":""}]',
      'Authentication verifies user identity',
      'The correct answer is: Authentication verifies user identity',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do signed URLs impact performance in frontend applications?',
      'Explain how using signed URLs can improve frontend loading and caching.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets.","isCorrect":true,"explanation":"Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets."},{"id":"o2","text":"Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets.',
      'Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is web accessibility (a11y) and why is it important?',
      'Explain the concept of web accessibility and its significance in frontend design.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity.","isCorrect":true,"explanation":"Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity."},{"id":"o2","text":"Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality","isCorrect":false,"explanation":""},{"id":"o3","text":" It improves usability and inclusivity","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity.',
      'Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are ARIA roles and how do you use them?',
      'Explain ARIA roles and attributes to improve accessibility.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"ARIA roles and attributes provide semantic information for assistive technologies. Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning.","isCorrect":true,"explanation":"ARIA roles and attributes provide semantic information for assistive technologies. Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning."},{"id":"o2","text":"ARIA roles and attributes provide semantic information for assistive technologies","isCorrect":false,"explanation":""},{"id":"o3","text":" Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'ARIA roles and attributes provide semantic information for assistive technologies. Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning.',
      'ARIA roles and attributes provide semantic information for assistive technologies. Use roles like <code>button</code>, <code>dialog</code>, and states like <code>aria-expanded</code> to convey meaning.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you test accessibility in frontend applications?',
      'Describe tools and methods to verify a11y compliance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance.","isCorrect":true,"explanation":"Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance."},{"id":"o2","text":"Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance.',
      'Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are common accessibility mistakes in frontend apps?',
      'Identify frequent a11y issues and how to avoid them.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Missing alt text on images","isCorrect":true,"explanation":""},{"id":"o2","text":"Poor color contrast","isCorrect":true,"explanation":""},{"id":"o3","text":"Non-focusable interactive elements","isCorrect":true,"explanation":""},{"id":"o4","text":"Using semantic HTML","isCorrect":false,"explanation":""}]',
      'Missing alt text on images',
      'The correct answer is: Missing alt text on images',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is internationalization (i18n) in frontend applications?',
      'Explain the purpose of i18n and how it impacts frontend design.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code.","isCorrect":true,"explanation":"Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code."},{"id":"o2","text":"Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code.',
      'Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between i18n and l10n?',
      'Compare internationalization and localization in frontend development.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"i18n is the process of designing for multiple languages","isCorrect":true,"explanation":""},{"id":"o2","text":"l10n is the process of adapting content for a specific locale","isCorrect":true,"explanation":""},{"id":"o3","text":"i18n and l10n are the same","isCorrect":false,"explanation":""}]',
      'i18n is the process of designing for multiple languages',
      'The correct answer is: i18n is the process of designing for multiple languages',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle right-to-left (RTL) languages in frontend apps?',
      'Explain strategies for supporting RTL layouts and text.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment.","isCorrect":true,"explanation":"Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment."},{"id":"o2","text":"Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment.',
      'Use CSS logical properties (<code>margin-inline-start</code>), direction attributes (<code>dir=''rtl''</code>), mirrored layout components, and test with RTL content to ensure proper alignment.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What UX considerations should be taken for performance-sensitive pages?',
      'Discuss UX strategies to improve perceived performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content.","isCorrect":true,"explanation":"Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content."},{"id":"o2","text":"Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content.',
      'Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between progressive enhancement and graceful degradation?',
      'Explain these two strategies in frontend development.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Progressive enhancement starts with basic functionality and adds features for modern browsers","isCorrect":true,"explanation":""},{"id":"o2","text":"Graceful degradation starts with full features and reduces functionality for older browsers","isCorrect":true,"explanation":""},{"id":"o3","text":"They are exactly the same","isCorrect":false,"explanation":""}]',
      'Progressive enhancement starts with basic functionality and adds features for modern browsers',
      'The correct answer is: Progressive enhancement starts with basic functionality and adds features for modern browsers',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you ensure a frontend app is usable for all users, including those with disabilities?',
      'Describe strategies for inclusive frontend design.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts.","isCorrect":true,"explanation":"Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts."},{"id":"o2","text":"Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts.',
      'Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is WebSocket and when should you use it?',
      'Explain WebSocket protocol and its use cases in frontend applications.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds.","isCorrect":true,"explanation":"WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds."},{"id":"o2","text":"WebSocket is a full-duplex, persistent connection between client and server for real-time communication","isCorrect":false,"explanation":""},{"id":"o3","text":" Use it for chat apps, notifications, and live feeds","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds.',
      'WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is Server-Sent Events (SSE) and how does it differ from WebSocket?',
      'Compare SSE and WebSocket in terms of use cases and protocol features.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data.","isCorrect":true,"explanation":"SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data."},{"id":"o2","text":"SSE is a unidirectional protocol where server pushes updates to the client over HTTP","isCorrect":false,"explanation":""},{"id":"o3","text":" Use SSE for live feeds or notifications where the client doesn''t need to send frequent data","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data.',
      'SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is long polling and when is it used?',
      'Explain long polling technique for real-time updates.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible.","isCorrect":true,"explanation":"Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible."},{"id":"o2","text":"Long polling is a technique where the client sends a request and the server holds it until data is available","isCorrect":false,"explanation":""},{"id":"o3","text":" Use it when WebSocket or SSE is not possible","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible.',
      'Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are the pros and cons of WebSocket vs SSE vs long polling?',
      'Compare these real-time strategies in terms of latency, scalability, and complexity.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"WebSocket: low latency, bidirectional, more complex, heavier on server.\\nSSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.\\nLong Polling: compatible with HTTP, higher...","isCorrect":true,"explanation":"WebSocket: low latency, bidirectional, more complex, heavier on server.\\nSSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.\\nLong Polling: compatible with HTTP, higher latency, server holds connections, less efficient."},{"id":"o2","text":"WebSocket: low latency, bidirectional, more complex, heavier on server","isCorrect":false,"explanation":""},{"id":"o3","text":"\\nSSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'WebSocket: low latency, bidirectional, more complex, heavier on server.
SSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.
Long Polling: compatible with HTTP, higher...',
      'WebSocket: low latency, bidirectional, more complex, heavier on server.
SSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.
Long Polling: compatible with HTTP, higher latency, server holds connections, less efficient.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle reconnection logic in real-time frontend apps?',
      'Describe strategies to maintain real-time connectivity.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect.","isCorrect":true,"explanation":"Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect."},{"id":"o2","text":"Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect.',
      'Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are the best practices for handling high-frequency real-time data in the frontend?',
      'Explain strategies to manage performance when receiving frequent updates.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates.","isCorrect":true,"explanation":"Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates."},{"id":"o2","text":"Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates.',
      'Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you secure WebSocket connections in frontend apps?',
      'Discuss authentication and encryption for WebSocket connections.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection.","isCorrect":true,"explanation":"Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection."},{"id":"o2","text":"Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection.',
      'Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you manage subscriptions to multiple real-time channels efficiently?',
      'Explain strategies for handling multiple feeds in frontend apps.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels.","isCorrect":true,"explanation":"Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels."},{"id":"o2","text":"Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels.',
      'Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'advanced'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How do you handle fallback mechanisms if WebSocket or SSE fails?',
      'Describe strategies to maintain real-time updates when primary methods fail.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores.","isCorrect":true,"explanation":"Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores."},{"id":"o2","text":"Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores.',
      'Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'When would you choose SSE over WebSocket in a frontend system?',
      'Explain scenarios where Server-Sent Events are more suitable than WebSocket.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication.","isCorrect":true,"explanation":"Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication."},{"id":"o2","text":"Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication","isCorrect":false,"explanation":""},{"id":"o3","text":"This method prioritizes user experience and maintainability.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication.',
      'Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between browser cache and CDN cache?',
      'Explain how browser caching and CDN caching work and their differences.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads.","isCorrect":true,"explanation":"Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads."},{"id":"o2","text":"Browser cache stores assets locally on the client device","isCorrect":false,"explanation":""},{"id":"o3","text":" CDN cache stores assets on edge servers closer to the user","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads.',
      'Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are cache-control headers and why are they important?',
      'Explain cache-control strategies for frontend assets.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Cache-control headers define how long and where a resource can be cached. Examples: `max-age`, `no-store`, `must-revalidate`. They help control freshness and prevent stale content.","isCorrect":true,"explanation":"Cache-control headers define how long and where a resource can be cached. Examples: `max-age`, `no-store`, `must-revalidate`. They help control freshness and prevent stale content."},{"id":"o2","text":"Cache-control headers define how long and where a resource can be cached","isCorrect":false,"explanation":""},{"id":"o3","text":" Examples: `max-age`, `no-store`, `must-revalidate`","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Cache-control headers define how long and where a resource can be cached. Examples: `max-age`, `no-store`, `must-revalidate`. They help control freshness and prevent stale content.',
      'Cache-control headers define how long and where a resource can be cached. Examples: <code>max-age</code>, <code>no-store</code>, <code>must-revalidate</code>. They help control freshness and prevent stale content.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a service worker and what role does it play in caching?',
      'Explain service workers and how they enable offline-first frontend apps.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs.","isCorrect":true,"explanation":"A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs."},{"id":"o2","text":"A service worker is a script running in the background that intercepts network requests","isCorrect":false,"explanation":""},{"id":"o3","text":" It can cache assets, serve offline content, and enable push notifications for PWAs","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs.',
      'A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the difference between AppCache and Service Worker?',
      'Compare the deprecated AppCache and modern Service Worker approach.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"AppCache was limited and inflexible","isCorrect":true,"explanation":""},{"id":"o2","text":"Service Worker provides programmable caching and background sync","isCorrect":true,"explanation":""},{"id":"o3","text":"Both are actively supported","isCorrect":false,"explanation":""}]',
      'AppCache was limited and inflexible',
      'The correct answer is: AppCache was limited and inflexible',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'beginner'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is stale-while-revalidate caching strategy?',
      'Explain how stale-while-revalidate improves perceived performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date.","isCorrect":true,"explanation":"Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date."},{"id":"o2","text":"Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background","isCorrect":false,"explanation":""},{"id":"o3","text":" The user sees fast responses while data stays up-to-date","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date.',
      'Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does IndexedDB help with offline frontend applications?',
      'Explain the role of IndexedDB for client-side storage.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions.","isCorrect":true,"explanation":"IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions."},{"id":"o2","text":"IndexedDB is a low-level NoSQL database in the browser","isCorrect":false,"explanation":""},{"id":"o3","text":" It stores structured data, useful for offline applications where data must persist across sessions","isCorrect":false,"explanation":""},{"id":"o4","text":"This is incorrect. Please refer to system design best practices.","isCorrect":false,"explanation":""}]',
      'IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions.',
      'IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions.',
      NULL,
      ARRAY[]::text[],
      ARRAY['system-design', 'frontend-system-design', 'intermediate'],
      '{}',
      NULL,
      '40599335-648e-452f-91c6-36c1bcfd390c',
      NULL,
      true,
      '2025-11-18T18:46:59.323Z',
      '2025-11-18T18:46:59.323Z',
      NULL,
      300
    );