INSERT INTO questions (
    id, title, content, type, difficulty, points, options, correct_answer, 
    explanation, test_cases, hints, tags, metadata, stats, category_id, 
    learning_card_id, is_active, created_at, updated_at, topic_id, time_limit
  ) VALUES (
      gen_random_uuid(),
      'What is the PRPL Pattern?',
      '### PRPL Pattern
The **PRPL Pattern** is a web performance optimization strategy that focuses on making applications load and run efficiently, even on low-end devices or slow networks.

**PRPL** stands for:
- **P**: Push critical resources for the initial route.
- **R**: Render the initial route as soon as possible.
- **P**: Pre-cache assets for future routes.
- **L**: Lazy-load remaining routes and assets.

This approach improves load times, offline experience, and caching efficiency.

**Example:** Progressive Web Apps (PWAs) that use an app shell, service workers, and code-splitting to load only what’s needed.

**Pros:**
- Faster first render.
- Improved caching and offline usability.
- Reduced bandwidth usage.

**Cons:**
- Requires careful bundling and caching strategy.
- Over-pushing or preloading can waste bandwidth.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A web performance pattern that optimizes loading by pushing critical resources, rendering fast, pre-caching assets, and lazy-loading the rest.","isCorrect":true,"explanation":"A web performance pattern that optimizes loading by pushing critical resources, rendering fast, pre-caching assets, and lazy-loading the rest."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'A web performance pattern that optimizes loading by pushing critical resources, rendering fast, pre-caching assets, and lazy-loading the rest.',
      'A web performance pattern that optimizes loading by pushing critical resources, rendering fast, pre-caching assets, and lazy-loading the rest.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What does each letter in the PRPL acronym stand for?',
      'Choose the correct expansion of PRPL.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Push, Render, Pre-cache, Lazy-load","isCorrect":true,"explanation":""},{"id":"o2","text":"Preload, Render, Pre-fetch, Load","isCorrect":false,"explanation":""},{"id":"o3","text":"Push, Render, Preload, Link","isCorrect":false,"explanation":""},{"id":"o4","text":"Prepare, Run, Pre-cache, Load","isCorrect":false,"explanation":""}]',
      'Push, Render, Pre-cache, Lazy-load',
      'PRPL stands for Push critical resources, Render initial route, Pre-cache assets, and Lazy-load remaining routes.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: The PRPL pattern focuses on optimizing the first route before loading any other resources.',
      'Evaluate the statement about PRPL’s optimization focus.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"PRPL prioritizes loading and rendering the initial route first, then caching and lazy-loading the rest."},{"id":"o2","text":"False","isCorrect":false,"explanation":"Other resources load only after the initial route completes."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following technologies does the PRPL pattern often rely on?',
      'Select all the technologies that typically support PRPL pattern implementation.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"HTTP/2 Server Push","isCorrect":true,"explanation":""},{"id":"o2","text":"Service Workers","isCorrect":true,"explanation":""},{"id":"o3","text":"App Shell Architecture","isCorrect":true,"explanation":""},{"id":"o4","text":"jQuery AJAX for resource loading","isCorrect":false,"explanation":""}]',
      'HTTP/2 Server Push',
      'PRPL commonly uses HTTP/2 server push, service workers for caching, and an app shell for faster rendering.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why is code-splitting important in the PRPL pattern?',
      '### Code-Splitting in PRPL
Code-splitting divides the application into smaller, cachable chunks. This helps browsers load only what''s necessary for the current route, improving performance and reducing cache bloat.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"It ensures only the necessary parts of the app are loaded, improving performance and caching efficiency.","isCorrect":true,"explanation":"It ensures only the necessary parts of the app are loaded, improving performance and caching efficiency."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'It ensures only the necessary parts of the app are loaded, improving performance and caching efficiency.',
      'It ensures only the necessary parts of the app are loaded, improving performance and caching efficiency.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which step in PRPL involves caching frequently visited routes?',
      'Identify which phase of the PRPL process focuses on pre-caching routes for better offline performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Push","isCorrect":false,"explanation":""},{"id":"o2","text":"Render","isCorrect":false,"explanation":""},{"id":"o3","text":"Pre-cache","isCorrect":true,"explanation":""},{"id":"o4","text":"Lazy-load","isCorrect":false,"explanation":""}]',
      'Pre-cache',
      'Pre-caching ensures frequently visited routes and assets are stored for quick access and offline use.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a potential drawback of pushing too many resources in PRPL?',
      'Select the correct consequence of over-pushing or over-preloading resources.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Improved caching performance","isCorrect":false,"explanation":""},{"id":"o2","text":"Wasted bandwidth and filled browser cache","isCorrect":true,"explanation":""},{"id":"o3","text":"Better offline support","isCorrect":false,"explanation":""},{"id":"o4","text":"Reduced initial load time","isCorrect":false,"explanation":""}]',
      'Wasted bandwidth and filled browser cache',
      'Pushing unnecessary files wastes bandwidth and fills the browser cache, reducing overall performance.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does HTTP/2 improve performance for the PRPL pattern?',
      '### HTTP/2 and PRPL
HTTP/2 enables multiplexing — allowing multiple request/response streams over a single TCP connection. This reduces ''head-of-line'' blocking and speeds up resource delivery, which complements PRPL’s ''Push'' and ''Render'' steps.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"HTTP/2 allows multiple requests in one TCP connection, reducing latency and supporting PRPL’s goal of faster initial route rendering.","isCorrect":true,"explanation":"HTTP/2 allows multiple requests in one TCP connection, reducing latency and supporting PRPL’s goal of faster initial route rendering."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'HTTP/2 allows multiple requests in one TCP connection, reducing latency and supporting PRPL’s goal of faster initial route rendering.',
      'HTTP/2 allows multiple requests in one TCP connection, reducing latency and supporting PRPL’s goal of faster initial route rendering.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What role does the App Shell play in the PRPL pattern?',
      'Identify how the App Shell architecture supports the PRPL pattern.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Provides a minimal structure that loads instantly and handles routing","isCorrect":true,"explanation":""},{"id":"o2","text":"Delays rendering until all assets are fetched","isCorrect":false,"explanation":""},{"id":"o3","text":"Caches server responses in memory only","isCorrect":false,"explanation":""},{"id":"o4","text":"Forces the app to reload on each navigation","isCorrect":false,"explanation":""}]',
      'Provides a minimal structure that loads instantly and handles routing',
      'The App Shell delivers the minimal UI structure immediately, allowing PRPL to render the first route quickly and cache other assets later.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Service Workers are essential to implement the ''Pre-cache'' and ''Lazy-load'' steps of PRPL.',
      'Assess whether Service Workers are necessary for caching and lazy loading in PRPL.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"Service Workers enable background caching and lazy-loading of routes and assets in PRPL."},{"id":"o2","text":"False","isCorrect":false,"explanation":"PRPL relies heavily on Service Workers for offline caching and background resource fetching."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What happens if we preload too many resources in the PRPL pattern?',
      '### Over-Preloading
Preloading too many assets increases competition for bandwidth, delaying critical resources like CSS or hero images and worsening Core Web Vitals such as Largest Contentful Paint (LCP).',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"It can delay critical rendering assets like CSS and images, worsening user-perceived performance metrics.","isCorrect":true,"explanation":"It can delay critical rendering assets like CSS and images, worsening user-perceived performance metrics."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'It can delay critical rendering assets like CSS and images, worsening user-perceived performance metrics.',
      'It can delay critical rendering assets like CSS and images, worsening user-perceived performance metrics.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which PRPL step directly improves the Time to Interactive (TTI) metric?',
      'Select which part of the PRPL process helps achieve a faster TTI.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Render initial route quickly","isCorrect":true,"explanation":""},{"id":"o2","text":"Pre-cache assets in background","isCorrect":false,"explanation":""},{"id":"o3","text":"Lazy-load unused modules","isCorrect":false,"explanation":""},{"id":"o4","text":"Push critical resources after render","isCorrect":false,"explanation":""}]',
      'Render initial route quickly',
      'Rendering the initial route early reduces the time before a user can interact, improving TTI.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does PRPL enhance offline experience?',
      'Explain how PRPL ensures an app remains functional even without an internet connection.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline.","isCorrect":true,"explanation":"By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline.',
      'By using Service Workers to pre-cache frequently visited routes and assets, so they can load from cache when offline.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which step in PRPL primarily benefits from HTTP/2 server push?',
      'Identify where HTTP/2 server push has the most effect in the PRPL process.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Push","isCorrect":true,"explanation":""},{"id":"o2","text":"Render","isCorrect":false,"explanation":""},{"id":"o3","text":"Pre-cache","isCorrect":false,"explanation":""},{"id":"o4","text":"Lazy-load","isCorrect":false,"explanation":""}]',
      'Push',
      'HTTP/2 server push accelerates the ''Push'' step by sending critical resources before the browser requests them.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: PRPL can only be implemented in Progressive Web Apps (PWAs).',
      'Evaluate the statement about PRPL’s application scope.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"While PWAs benefit most, PRPL can be used in any web app with modular architecture and caching."},{"id":"o2","text":"False","isCorrect":false,"explanation":"While PWAs benefit most, PRPL can be used in any web app with modular architecture and caching."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'prpl-pattern', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which React function is used to dynamically import components?',
      'React.lazy is used to dynamically import components at runtime.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"u","7":"s","8":"e","9":"M","10":"e","11":"m","12":"o","explanation":""},{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"l","7":"a","8":"z","9":"y","explanation":""},{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"l","7":"o","8":"a","9":"d","explanation":""},{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"d","7":"e","8":"f","9":"e","10":"r","explanation":""}]',
      '',
      '<code>React.lazy(() =&gt; import(''./Component''))</code> loads a component only when it is rendered for the first time.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-lazy-loading', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does React support Import On Interaction?',
      'React supports lazy-loading components using React.lazy and Suspense, or by dynamically importing a component on user interaction.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"B","1":"y","2":" ","3":"c","4":"o","5":"m","6":"p","7":"i","8":"l","9":"i","10":"n","11":"g","12":" ","13":"c","14":"o","15":"m","16":"p","17":"o","18":"n","19":"e","20":"n","21":"t","22":"s","23":" ","24":"o","25":"n","26":" ","27":"t","28":"h","29":"e","30":" ","31":"s","32":"e","33":"r","34":"v","35":"e","36":"r","explanation":""},{"0":"U","1":"s","2":"i","3":"n","4":"g","5":" ","6":"R","7":"e","8":"a","9":"c","10":"t","11":".","12":"l","13":"a","14":"z","15":"y","16":" ","17":"a","18":"n","19":"d","20":" ","21":"S","22":"u","23":"s","24":"p","25":"e","26":"n","27":"s","28":"e","29":" ","30":"o","31":"r","32":" ","33":"d","34":"y","35":"n","36":"a","37":"m","38":"i","39":"c","40":" ","41":"i","42":"m","43":"p","44":"o","45":"r","46":"t","47":" ","48":"o","49":"n","50":" ","51":"c","52":"l","53":"i","54":"c","55":"k","explanation":""},{"0":"B","1":"y","2":" ","3":"u","4":"s","5":"i","6":"n","7":"g","8":" ","9":"R","10":"e","11":"a","12":"c","13":"t","14":".","15":"u","16":"s","17":"e","18":"M","19":"e","20":"m","21":"o","22":" ","23":"f","24":"o","25":"r","26":" ","27":"c","28":"a","29":"c","30":"h","31":"i","32":"n","33":"g","explanation":""},{"0":"T","1":"h","2":"r","3":"o","4":"u","5":"g","6":"h","7":" ","8":"h","9":"y","10":"d","11":"r","12":"a","13":"t","14":"i","15":"o","16":"n","17":" ","18":"d","19":"e","20":"l","21":"a","22":"y","23":" ","24":"A","25":"P","26":"I","27":"s","explanation":""}]',
      '',
      'React’s <code>lazy()</code> and <code>Suspense</code> make it easy to defer loading non-critical components until interaction occurs.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-lazy-loading', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does React Suspense help in dynamic importing?',
      'React Suspense allows components to wait for a dynamically imported module to load, showing a fallback while loading.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"I","1":"t","2":" ","3":"p","4":"r","5":"e","6":"l","7":"o","8":"a","9":"d","10":"s","11":" ","12":"a","13":"l","14":"l","15":" ","16":"c","17":"o","18":"m","19":"p","20":"o","21":"n","22":"e","23":"n","24":"t","25":"s","26":" ","27":"b","28":"e","29":"f","30":"o","31":"r","32":"e","33":" ","34":"r","35":"e","36":"n","37":"d","38":"e","39":"r","40":"i","41":"n","42":"g","explanation":""},{"0":"I","1":"t","2":" ","3":"b","4":"l","5":"o","6":"c","7":"k","8":"s","9":" ","10":"r","11":"e","12":"n","13":"d","14":"e","15":"r","16":"i","17":"n","18":"g","19":" ","20":"u","21":"n","22":"t","23":"i","24":"l","25":" ","26":"a","27":"l","28":"l","29":" ","30":"r","31":"e","32":"s","33":"o","34":"u","35":"r","36":"c","37":"e","38":"s","39":" ","40":"a","41":"r","42":"e","43":" ","44":"l","45":"o","46":"a","47":"d","48":"e","49":"d","explanation":""},{"0":"I","1":"t","2":" ","3":"r","4":"e","5":"n","6":"d","7":"e","8":"r","9":"s","10":" ","11":"a","12":" ","13":"f","14":"a","15":"l","16":"l","17":"b","18":"a","19":"c","20":"k","21":" ","22":"w","23":"h","24":"i","25":"l","26":"e","27":" ","28":"a","29":" ","30":"l","31":"a","32":"z","33":"y","34":" ","35":"c","36":"o","37":"m","38":"p","39":"o","40":"n","41":"e","42":"n","43":"t","44":" ","45":"l","46":"o","47":"a","48":"d","49":"s","explanation":""},{"0":"I","1":"t","2":" ","3":"d","4":"i","5":"s","6":"a","7":"b","8":"l","9":"e","10":"s","11":" ","12":"l","13":"a","14":"z","15":"y","16":" ","17":"l","18":"o","19":"a","20":"d","21":"i","22":"n","23":"g","explanation":""}]',
      '',
      'Suspense provides a fallback UI while waiting for the dynamically imported component to be fetched and rendered.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-suspense', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the purpose of the fallback prop in Suspense?',
      'The fallback prop defines what should be rendered while a component is being dynamically loaded.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"D","1":"e","2":"f","3":"i","4":"n","5":"e","6":"s","7":" ","8":"a","9":" ","10":"b","11":"a","12":"c","13":"k","14":"u","15":"p","16":" ","17":"c","18":"o","19":"m","20":"p","21":"o","22":"n","23":"e","24":"n","25":"t","26":" ","27":"t","28":"o","29":" ","30":"u","31":"s","32":"e","33":" ","34":"i","35":"f","36":" ","37":"l","38":"o","39":"a","40":"d","41":"i","42":"n","43":"g","44":" ","45":"f","46":"a","47":"i","48":"l","49":"s","explanation":""},{"0":"D","1":"i","2":"s","3":"p","4":"l","5":"a","6":"y","7":"s","8":" ","9":"c","10":"o","11":"n","12":"t","13":"e","14":"n","15":"t","16":" ","17":"w","18":"h","19":"i","20":"l","21":"e","22":" ","23":"w","24":"a","25":"i","26":"t","27":"i","28":"n","29":"g","30":" ","31":"f","32":"o","33":"r","34":" ","35":"l","36":"a","37":"z","38":"y","39":" ","40":"c","41":"o","42":"m","43":"p","44":"o","45":"n","46":"e","47":"n","48":"t","explanation":""},{"0":"T","1":"r","2":"i","3":"g","4":"g","5":"e","6":"r","7":"s","8":" ","9":"a","10":" ","11":"r","12":"e","13":"-","14":"r","15":"e","16":"n","17":"d","18":"e","19":"r","20":" ","21":"o","22":"n","23":" ","24":"e","25":"r","26":"r","27":"o","28":"r","explanation":""},{"0":"C","1":"a","2":"c","3":"h","4":"e","5":"s","6":" ","7":"t","8":"h","9":"e","10":" ","11":"l","12":"a","13":"z","14":"y","15":" ","16":"c","17":"o","18":"m","19":"p","20":"o","21":"n","22":"e","23":"n","24":"t","explanation":""}]',
      '',
      'Suspense uses the fallback UI (like a loader or placeholder) until the lazy component finishes loading.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-suspense-fallback', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does “react-loadable-visibility” enhance lazy loading in React?',
      'It combines dynamic imports with visibility detection, ensuring components are only loaded when they are about to appear on screen.',
      'concept',
      'intermediate',
      10,
      '[]',
      '',
      'Instead of pre-loading all lazy components, it waits until the user scrolls to them, saving bandwidth and improving UX.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-loadable-visibility', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which components in react-window render virtualized content?',
      'Name and describe the main components in react-window used for list and grid virtualization.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"FixedSizeList and VariableSizeList for lists; FixedSizeGrid and VariableSizeGrid for grids","isCorrect":true,"explanation":""},{"id":"o2","text":"InfiniteScrollList and TableGrid","isCorrect":false,"explanation":""}]',
      'FixedSizeList and VariableSizeList for lists; FixedSizeGrid and VariableSizeGrid for grids',
      'react-window provides FixedSizeList/VariableSizeList for virtualized lists and FixedSizeGrid/VariableSizeGrid for virtualized grids.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'react-window-components', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is an example of Import On Interaction in Google Docs?',
      'Google Docs loads the 500KB share feature script only when the user clicks the Share button.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"I","1":"t","2":" ","3":"p","4":"r","5":"e","6":"l","7":"o","8":"a","9":"d","10":"s","11":" ","12":"a","13":"l","14":"l","15":" ","16":"s","17":"c","18":"r","19":"i","20":"p","21":"t","22":"s","23":" ","24":"o","25":"n","26":" ","27":"s","28":"t","29":"a","30":"r","31":"t","32":"u","33":"p","explanation":""},{"0":"I","1":"t","2":" ","3":"l","4":"o","5":"a","6":"d","7":"s","8":" ","9":"t","10":"h","11":"e","12":" ","13":"s","14":"h","15":"a","16":"r","17":"e","18":" ","19":"f","20":"e","21":"a","22":"t","23":"u","24":"r","25":"e","26":" ","27":"d","28":"y","29":"n","30":"a","31":"m","32":"i","33":"c","34":"a","35":"l","36":"l","37":"y","38":" ","39":"o","40":"n","41":" ","42":"c","43":"l","44":"i","45":"c","46":"k","explanation":""},{"0":"I","1":"t","2":" ","3":"b","4":"l","5":"o","6":"c","7":"k","8":"s","9":" ","10":"t","11":"h","12":"e","13":" ","14":"m","15":"a","16":"i","17":"n","18":" ","19":"t","20":"h","21":"r","22":"e","23":"a","24":"d","25":" ","26":"f","27":"o","28":"r","29":" ","30":"p","31":"e","32":"r","33":"f","34":"o","35":"r","36":"m","37":"a","38":"n","39":"c","40":"e","explanation":""},{"0":"I","1":"t","2":" ","3":"d","4":"i","5":"s","6":"a","7":"b","8":"l","9":"e","10":"s","11":" ","12":"u","13":"s","14":"e","15":"r","16":" ","17":"i","18":"n","19":"t","20":"e","21":"r","22":"a","23":"c","24":"t","25":"i","26":"o","27":"n","28":"s","29":" ","30":"d","31":"u","32":"r","33":"i","34":"n","35":"g","36":" ","37":"l","38":"o","39":"a","40":"d","explanation":""}]',
      '',
      'Google Docs defers loading large non-critical scripts until the user actually interacts with the Share feature.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'real-world-example', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Next.js ScriptLoader Usage',
      'Which Next.js ScriptLoader priority should be used for scripts that run after hydration, such as analytics?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"0":"B","1":"e","2":"f","3":"o","4":"r","5":"e","6":"-","7":"I","8":"n","9":"t","10":"e","11":"r","12":"a","13":"c","14":"t","15":"i","16":"v","17":"e","explanation":""},{"0":"A","1":"f","2":"t","3":"e","4":"r","5":"-","6":"I","7":"n","8":"t","9":"e","10":"r","11":"a","12":"c","13":"t","14":"i","15":"v","16":"e","explanation":""},{"0":"L","1":"a","2":"z","3":"y","4":"-","5":"O","6":"n","7":"l","8":"o","9":"a","10":"d","explanation":""},{"0":"A","1":"s","2":"y","3":"n","4":"c","5":"-","6":"P","7":"r","8":"e","9":"l","10":"o","11":"a","12":"d","explanation":""}]',
      '',
      'Scripts like analytics should use ''After-Interactive'' so they load after hydration without blocking critical rendering.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'script-loading', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Preload + Async Hack',
      'What is the goal of combining <code>&lt;link rel=''preload''&gt;</code> with <code>&lt;script async&gt;</code>?',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"a","text":"To load a script early without blocking the HTML parser","isCorrect":true,"explanation":""},{"id":"b","text":"To execute the script synchronously","isCorrect":false,"explanation":""},{"id":"c","text":"To delay the script until the user interacts","isCorrect":false,"explanation":""}]',
      'To load a script early without blocking the HTML parser',
      'This technique downloads the script as a high-priority resource but doesn’t block parsing while it loads.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'script-optimization', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What benefits does import-on-visibility offer for large single-page applications?',
      'It helps reduce main bundle size, optimizes network requests, and improves time-to-interactive (TTI) by loading only visible components.',
      'concept',
      'intermediate',
      10,
      '[]',
      '',
      'Users experience faster initial render and smoother scrolling as code loads progressively.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'spa-optimization', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Preload in Single-Page Applications',
      'In SPAs, when is preloading most useful?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"When a component or font must be available instantly on the first render.","isCorrect":true,"explanation":"Preloading helps ensure components needed immediately after page load are ready without waiting for network fetches."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'When a component or font must be available instantly on the first render.',
      'Preloading helps ensure components needed immediately after page load are ready without waiting for network fetches.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'spa-optimization', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What library is recommended for dynamic imports in SSR applications?',
      'The loadable-components library is recommended for SSR applications since React Suspense does not yet support SSR.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"l","7":"a","8":"z","9":"y","explanation":""},{"0":"R","1":"e","2":"a","3":"c","4":"t","5":".","6":"S","7":"u","8":"s","9":"p","10":"e","11":"n","12":"s","13":"e","explanation":""},{"0":"@","1":"l","2":"o","3":"a","4":"d","5":"a","6":"b","7":"l","8":"e","9":"/","10":"c","11":"o","12":"m","13":"p","14":"o","15":"n","16":"e","17":"n","18":"t","explanation":""},{"0":"N","1":"e","2":"x","3":"t","4":"D","5":"y","6":"n","7":"a","8":"m","9":"i","10":"c","explanation":""}]',
      '',
      'The <code>@loadable/component</code> library provides a Suspense-like API compatible with both SSR and CSR environments.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'ssr-alternatives', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why is React Suspense not ideal for server-side rendering (SSR)?',
      'React Suspense currently lacks SSR support, meaning lazy-loaded components can’t be pre-rendered on the server.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"B","1":"e","2":"c","3":"a","4":"u","5":"s","6":"e","7":" ","8":"S","9":"S","10":"R","11":" ","12":"c","13":"a","14":"n","15":"’","16":"t","17":" ","18":"h","19":"a","20":"n","21":"d","22":"l","23":"e","24":" ","25":"a","26":"s","27":"y","28":"n","29":"c","30":" ","31":"o","32":"p","33":"e","34":"r","35":"a","36":"t","37":"i","38":"o","39":"n","40":"s","explanation":""},{"0":"B","1":"e","2":"c","3":"a","4":"u","5":"s","6":"e","7":" ","8":"S","9":"u","10":"s","11":"p","12":"e","13":"n","14":"s","15":"e","16":" ","17":"c","18":"a","19":"n","20":"’","21":"t","22":" ","23":"y","24":"e","25":"t","26":" ","27":"s","28":"t","29":"r","30":"e","31":"a","32":"m","33":" ","34":"s","35":"e","36":"r","37":"v","38":"e","39":"r","40":"-","41":"r","42":"e","43":"n","44":"d","45":"e","46":"r","47":"e","48":"d","49":" ","50":"l","51":"a","52":"z","53":"y","54":" ","55":"c","56":"o","57":"m","58":"p","59":"o","60":"n","61":"e","62":"n","63":"t","64":"s","explanation":""},{"0":"B","1":"e","2":"c","3":"a","4":"u","5":"s","6":"e","7":" ","8":"i","9":"t","10":" ","11":"i","12":"n","13":"c","14":"r","15":"e","16":"a","17":"s","18":"e","19":"s","20":" ","21":"b","22":"u","23":"n","24":"d","25":"l","26":"e","27":" ","28":"s","29":"i","30":"z","31":"e","explanation":""},{"0":"B","1":"e","2":"c","3":"a","4":"u","5":"s","6":"e","7":" ","8":"S","9":"u","10":"s","11":"p","12":"e","13":"n","14":"s","15":"e","16":" ","17":"o","18":"n","19":"l","20":"y","21":" ","22":"w","23":"o","24":"r","25":"k","26":"s","27":" ","28":"i","29":"n","30":" ","31":"N","32":"e","33":"x","34":"t","35":".","36":"j","37":"s","explanation":""}]',
      '',
      'Suspense currently only supports client-side rendering; SSR requires libraries like <code>@loadable/component</code> to manage lazy imports.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'ssr-limitation', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How can you optimize non-critical third-party JavaScript?',
      'Explain async and defer usage for non-critical third-party scripts.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering.","isCorrect":true,"explanation":"Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering.',
      'Use defer to fetch scripts in parallel and execute after DOM parsing, or async to execute as soon as available without blocking the parser, for scripts that are not critical to initial rendering.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-loading', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: Preconnect and dns-prefetch can speed up third-party resource loading.',
      'Evaluate whether resource hints improve third-party performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":true,"explanation":"Resource hints like dns-prefetch and preconnect reduce latency by initiating DNS lookups and TCP/TLS connections early."},{"id":"o2","text":"False","isCorrect":false,"explanation":"Resource hints are effective and recommended for critical third-party resources."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      'True',
      'The correct answer is: True',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-loading', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the benefit of lazy-loading third-party embeds?',
      'Explain why lazy-loading YouTube, maps, and social media embeds improves page performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering.","isCorrect":true,"explanation":"Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering.',
      'Embeds not visible on page load are delayed until needed, reducing initial load times and blocking of critical rendering.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-loading', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why might self-hosting third-party scripts improve performance?',
      'Describe the advantages and caveats of self-hosting 3P scripts.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current.","isCorrect":true,"explanation":"Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current.',
      'Reduces DNS lookups, allows better caching control, and can use HTTP/2 push, but scripts must be updated regularly to stay current.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-loading', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is a common use case for Import On Interaction with third-party widgets?',
      'Loading chat widgets, video players, or authentication SDKs only after user interaction to save initial load time.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"P","1":"r","2":"e","3":"l","4":"o","5":"a","6":"d","7":"i","8":"n","9":"g","10":" ","11":"a","12":"l","13":"l","14":" ","15":"e","16":"x","17":"t","18":"e","19":"r","20":"n","21":"a","22":"l","23":" ","24":"S","25":"D","26":"K","27":"s","explanation":""},{"0":"L","1":"a","2":"z","3":"y","4":"-","5":"l","6":"o","7":"a","8":"d","9":"i","10":"n","11":"g","12":" ","13":"n","14":"o","15":"n","16":"-","17":"c","18":"r","19":"i","20":"t","21":"i","22":"c","23":"a","24":"l","25":" ","26":"t","27":"h","28":"i","29":"r","30":"d","31":"-","32":"p","33":"a","34":"r","35":"t","36":"y","37":" ","38":"w","39":"i","40":"d","41":"g","42":"e","43":"t","44":"s","explanation":""},{"0":"L","1":"o","2":"a","3":"d","4":"i","5":"n","6":"g","7":" ","8":"a","9":"l","10":"l","11":" ","12":"w","13":"i","14":"d","15":"g","16":"e","17":"t","18":"s","19":" ","20":"s","21":"y","22":"n","23":"c","24":"h","25":"r","26":"o","27":"n","28":"o","29":"u","30":"s","31":"l","32":"y","explanation":""},{"0":"D","1":"i","2":"s","3":"a","4":"b","5":"l","6":"i","7":"n","8":"g","9":" ","10":"w","11":"i","12":"d","13":"g","14":"e","15":"t","16":"s","17":" ","18":"f","19":"o","20":"r","21":" ","22":"p","23":"e","24":"r","25":"f","26":"o","27":"r","28":"m","29":"a","30":"n","31":"c","32":"e","explanation":""}]',
      '',
      'Deferring third-party widget code until interaction avoids blocking critical rendering and reduces main-thread congestion.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-optimization', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Third-Party Scripts Impact',
      'How do third-party scripts usually affect page load performance?',
      'multiple-choice',
      'intermediate',
      10,
      '[{"0":"T","1":"h","2":"e","3":"y","4":" ","5":"o","6":"p","7":"t","8":"i","9":"m","10":"i","11":"z","12":"e","13":" ","14":"t","15":"h","16":"e","17":" ","18":"s","19":"e","20":"q","21":"u","22":"e","23":"n","24":"c","25":"e","26":" ","27":"a","28":"u","29":"t","30":"o","31":"m","32":"a","33":"t","34":"i","35":"c","36":"a","37":"l","38":"l","39":"y","explanation":""},{"0":"T","1":"h","2":"e","3":"y","4":" ","5":"o","6":"f","7":"t","8":"e","9":"n","10":" ","11":"b","12":"l","13":"o","14":"c","15":"k","16":" ","17":"r","18":"e","19":"n","20":"d","21":"e","22":"r","23":"i","24":"n","25":"g","26":" ","27":"a","28":"n","29":"d","30":" ","31":"d","32":"e","33":"l","34":"a","35":"y","36":" ","37":"c","38":"r","39":"i","40":"t","41":"i","42":"c","43":"a","44":"l","45":" ","46":"r","47":"e","48":"s","49":"o","50":"u","51":"r","52":"c","53":"e","54":" ","55":"l","56":"o","57":"a","58":"d","59":"i","60":"n","61":"g","explanation":""},{"0":"T","1":"h","2":"e","3":"y","4":" ","5":"i","6":"m","7":"p","8":"r","9":"o","10":"v","11":"e","12":" ","13":"C","14":"P","15":"U","16":" ","17":"u","18":"t","19":"i","20":"l","21":"i","22":"z","23":"a","24":"t","25":"i","26":"o","27":"n","explanation":""},{"0":"T","1":"h","2":"e","3":"y","4":" ","5":"l","6":"o","7":"a","8":"d","9":" ","10":"a","11":"f","12":"t","13":"e","14":"r","15":" ","16":"a","17":"l","18":"l","19":" ","20":"f","21":"i","22":"r","23":"s","24":"t","25":"-","26":"p","27":"a","28":"r","29":"t","30":"y","31":" ","32":"s","33":"c","34":"r","35":"i","36":"p","37":"t","38":"s","39":" ","40":"b","41":"y","42":" ","43":"d","44":"e","45":"f","46":"a","47":"u","48":"l","49":"t","explanation":""}]',
      '',
      'Third-party scripts like ads or analytics often block rendering or delay other resources, harming metrics like FID and LCP.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-performance', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why can third-party scripts slow down your website?',
      'Identify the main ways third-party scripts negatively impact performance.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Additional round trips to other domains","isCorrect":true,"explanation":""},{"id":"o2","text":"Bulky or unoptimized JavaScript","isCorrect":true,"explanation":""},{"id":"o3","text":"Blocking rendering of critical resources","isCorrect":true,"explanation":""},{"id":"o4","text":"Always reduces DNS lookup times","isCorrect":false,"explanation":""}]',
      'Additional round trips to other domains',
      'Third-party scripts can block rendering, increase network requests, and execute heavy JS, negatively impacting Core Web Vitals.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-performance-impact', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are third-party resources on a website?',
      'Define third-party resources and give examples.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements.","isCorrect":true,"explanation":"Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements.',
      'Resources hosted on another domain and used by your site, e.g., YouTube embeds, Google Analytics, social media widgets, maps, advertisements.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-resources', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What problem does Import On Interaction solve with third-party scripts?',
      'Third-party scripts can block rendering or hydration. Import On Interaction delays their load until user interaction.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"I","1":"t","2":" ","3":"b","4":"l","5":"o","6":"c","7":"k","8":"s","9":" ","10":"t","11":"h","12":"i","13":"r","14":"d","15":"-","16":"p","17":"a","18":"r","19":"t","20":"y","21":" ","22":"s","23":"c","24":"r","25":"i","26":"p","27":"t","28":"s","29":" ","30":"c","31":"o","32":"m","33":"p","34":"l","35":"e","36":"t","37":"e","38":"l","39":"y","explanation":""},{"0":"I","1":"t","2":" ","3":"e","4":"n","5":"s","6":"u","7":"r","8":"e","9":"s","10":" ","11":"t","12":"h","13":"i","14":"r","15":"d","16":"-","17":"p","18":"a","19":"r","20":"t","21":"y","22":" ","23":"s","24":"c","25":"r","26":"i","27":"p","28":"t","29":"s","30":" ","31":"l","32":"o","33":"a","34":"d","35":" ","36":"b","37":"e","38":"f","39":"o","40":"r","41":"e","42":" ","43":"f","44":"i","45":"r","46":"s","47":"t","48":" ","49":"p","50":"a","51":"i","52":"n","53":"t","explanation":""},{"0":"I","1":"t","2":" ","3":"d","4":"e","5":"f","6":"e","7":"r","8":"s","9":" ","10":"n","11":"o","12":"n","13":"-","14":"c","15":"r","16":"i","17":"t","18":"i","19":"c","20":"a","21":"l","22":" ","23":"t","24":"h","25":"i","26":"r","27":"d","28":"-","29":"p","30":"a","31":"r","32":"t","33":"y","34":" ","35":"s","36":"c","37":"r","38":"i","39":"p","40":"t","41":"s","42":" ","43":"u","44":"n","45":"t","46":"i","47":"l","48":" ","49":"n","50":"e","51":"e","52":"d","53":"e","54":"d","explanation":""},{"0":"I","1":"t","2":" ","3":"p","4":"r","5":"e","6":"l","7":"o","8":"a","9":"d","10":"s","11":" ","12":"a","13":"l","14":"l","15":" ","16":"e","17":"x","18":"t","19":"e","20":"r","21":"n","22":"a","23":"l","24":" ","25":"s","26":"c","27":"r","28":"i","29":"p","30":"t","31":"s","explanation":""}]',
      '',
      'By loading third-party scripts only when needed, the main thread remains available for critical tasks like rendering and user input.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'third-party-script-optimization', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which of the following statements best describes Time To Interactive (TTI)?',
      'Select the correct definition for TTI in the context of performance patterns.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"c1","text":"The time it takes for all content to be painted and interactive after the bundle loads","isCorrect":true,"explanation":""},{"id":"c2","text":"The time between a user''s first input and a response","isCorrect":false,"explanation":""},{"id":"c3","text":"The time it takes to fetch the HTML document from the server","isCorrect":false,"explanation":""},{"id":"c4","text":"The total JavaScript execution time","isCorrect":false,"explanation":""}]',
      'The time it takes for all content to be painted and interactive after the bundle loads',
      'TTI measures how long it takes for the page to become fully interactive, which bundle splitting helps improve by reducing load and execution time.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'time-to-interactive', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Given the following code, which function will be included in the final bundle?',
      '<pre><code>// utilities.js
export function read(props) { return props.book; }
export function nap(props) { return props.winks; }

// index.js
import { read } from ''utilities'';
const eventHandler = (e) =&gt; { read({ book: e.target.value }); };</code></pre>',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"read()","isCorrect":true,"explanation":""},{"id":"o2","text":"nap()","isCorrect":false,"explanation":""}]',
      'read()',
      'Only read() is used in index.js, so nap() is considered dead code and excluded from the bundle.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'tree-shaking-example', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does tree shaking determine which parts of the code to include?',
      'Explain the traversal process used in tree shaking.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle.","isCorrect":true,"explanation":"Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle.',
      'Tree shaking starts at the entry point and traverses the dependency graph, marking only the code paths that are used. Unused paths are excluded from the final bundle.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'tree-shaking-mechanism', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why does tree shaking consider side effects in modules?',
      'Explain what side effects are and why they affect tree shaking.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking.","isCorrect":true,"explanation":"A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking.',
      'A module has side effects if importing it changes the global scope or performs actions even if its exports are not used. Such modules cannot be safely removed by tree shaking.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'tree-shaking-side-effects', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What happens while a lazy-loaded module is still being fetched?',
      'The fallback component (e.g., a loading message) is rendered until the lazy-loaded component is ready.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"T","1":"h","2":"e","3":" ","4":"a","5":"p","6":"p","7":" ","8":"f","9":"r","10":"e","11":"e","12":"z","13":"e","14":"s","explanation":""},{"0":"T","1":"h","2":"e","3":" ","4":"p","5":"a","6":"g","7":"e","8":" ","9":"r","10":"e","11":"l","12":"o","13":"a","14":"d","15":"s","explanation":""},{"0":"T","1":"h","2":"e","3":" ","4":"f","5":"a","6":"l","7":"l","8":"b","9":"a","10":"c","11":"k","12":" ","13":"c","14":"o","15":"m","16":"p","17":"o","18":"n","19":"e","20":"n","21":"t","22":" ","23":"d","24":"i","25":"s","26":"p","27":"l","28":"a","29":"y","30":"s","31":" ","32":"t","33":"e","34":"m","35":"p","36":"o","37":"r","38":"a","39":"r","40":"i","41":"l","42":"y","explanation":""},{"0":"N","1":"o","2":"t","3":"h","4":"i","5":"n","6":"g","7":" ","8":"h","9":"a","10":"p","11":"p","12":"e","13":"n","14":"s","15":" ","16":"u","17":"n","18":"t","19":"i","20":"l","21":" ","22":"i","23":"t","24":" ","25":"l","26":"o","27":"a","28":"d","29":"s","explanation":""}]',
      '',
      'A fallback placeholder keeps the UI responsive and visually communicates that the module is still loading.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'user-experience', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Which user actions typically trigger Import On Interaction?',
      'The pattern can be triggered when a user clicks, scrolls into view, or when the browser is idle.',
      'mcq',
      'intermediate',
      10,
      '[{"0":"O","1":"n","2":"l","3":"y","4":" ","5":"w","6":"h","7":"e","8":"n","9":" ","10":"a","11":" ","12":"u","13":"s","14":"e","15":"r","16":" ","17":"r","18":"e","19":"f","20":"r","21":"e","22":"s","23":"h","24":"e","25":"s","26":" ","27":"t","28":"h","29":"e","30":" ","31":"p","32":"a","33":"g","34":"e","explanation":""},{"0":"O","1":"n","2":" ","3":"u","4":"s","5":"e","6":"r","7":" ","8":"c","9":"l","10":"i","11":"c","12":"k","13":",","14":" ","15":"s","16":"c","17":"r","18":"o","19":"l","20":"l","21":",","22":" ","23":"o","24":"r","25":" ","26":"i","27":"d","28":"l","29":"e","30":" ","31":"t","32":"i","33":"m","34":"e","explanation":""},{"0":"W","1":"h","2":"e","3":"n","4":" ","5":"d","6":"a","7":"t","8":"a","9":" ","10":"f","11":"e","12":"t","13":"c","14":"h","15":"i","16":"n","17":"g","18":" ","19":"c","20":"o","21":"m","22":"p","23":"l","24":"e","25":"t","26":"e","27":"s","explanation":""},{"0":"D","1":"u","2":"r","3":"i","4":"n","5":"g","6":" ","7":"s","8":"e","9":"r","10":"v","11":"e","12":"r","13":"-","14":"s","15":"i","16":"d","17":"e","18":" ","19":"r","20":"e","21":"n","22":"d","23":"e","24":"r","25":"i","26":"n","27":"g","explanation":""}]',
      '',
      'The pattern optimizes performance by waiting for direct user interactions or idle time before loading heavy resources.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'user-interaction-events', 'null', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of the fallback component in import-on-visibility?',
      'The fallback UI is displayed while the requested module is being fetched, parsed, and executed, giving users feedback instead of a blank screen.',
      'concept',
      'intermediate',
      10,
      '[]',
      '',
      'The fallback reassures users that loading is in progress, preventing perceived freezes.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'ux-during-lazy-load', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is list virtualization (or windowing)?',
      'Explain the concept of list virtualization and its main benefit.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency.","isCorrect":true,"explanation":"List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency.',
      'List virtualization is a technique where only the visible rows of a list are rendered at a time, rather than the entire list. This improves rendering performance and scroll efficiency.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'Why is react-window preferred over react-virtualized in some cases?',
      'Describe the differences between react-window and react-virtualized and why react-window might be chosen.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly.","isCorrect":true,"explanation":"React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly.',
      'React-window is smaller, faster, and more tree-shakeable than react-virtualized. It provides simpler APIs for most virtualization use cases and reduces bundle size significantly.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists-libraries', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What are some limitations of react-window compared to react-virtualized?',
      'List missing features/components in react-window.',
      'multiple-choice',
      'advanced',
      10,
      '[{"id":"o1","text":"React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed.","isCorrect":true,"explanation":"React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed.',
      'React-window does not include WindowScroller, AutoSizer, or CellMeasurer by default. These need to be implemented separately if needed.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists-limitations', 'advanced'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'How does list virtualization improve performance on mid to low-end devices?',
      'Explain the mechanism by which virtualization keeps rendering fast on slower devices.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth.","isCorrect":true,"explanation":"By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth.',
      'By rendering only the visible items and not the entire list, virtualization reduces DOM nodes, lowering layout, paint, and reflow costs, which keeps frame rates smooth.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists-performance', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'True or False: List virtualization renders all items in the DOM at once.',
      'Evaluate whether virtualization renders all items immediately.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"True","isCorrect":false,"explanation":"Virtualization renders only the visible items, not the entire list, to improve performance."},{"id":"o2","text":"False","isCorrect":false,"explanation":"Virtualization renders only the visible items, not the entire list, to improve performance."},{"id":"o3","text":"Partially true - depends on the context","isCorrect":false,"explanation":""},{"id":"o4","text":"Not applicable","isCorrect":false,"explanation":""}]',
      '',
      'The correct answer is: False',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists-rendering', 'beginner', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    ),
    (
      gen_random_uuid(),
      'What is the role of a ''window'' in list virtualization?',
      'Explain what a ''window'' represents in the context of virtualized lists.',
      'multiple-choice',
      'intermediate',
      10,
      '[{"id":"o1","text":"The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones.","isCorrect":true,"explanation":"The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones."},{"id":"o2","text":"This is not correct. Please refer to the explanation.","isCorrect":false,"explanation":""},{"id":"o3","text":"Incorrect. Review performance optimization concepts.","isCorrect":false,"explanation":""},{"id":"o4","text":"This is a common misconception. The correct answer is different.","isCorrect":false,"explanation":""},{"id":"o5","text":"Not quite. Consider web performance best practices.","isCorrect":false,"explanation":""}]',
      'The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones.',
      'The ''window'' refers to the subset of list items that are currently visible and rendered in the DOM. As the user scrolls, the window moves along the list, rendering new items and removing old ones.',
      NULL,
      ARRAY[]::text[],
      ARRAY['performance-patterns', 'virtual-lists-windowing', 'intermediate'],
      '{}',
      NULL,
      '85e21817-b2b0-4cd8-8623-8264bdd228d2',
      NULL,
      true,
      '2025-11-18T18:46:59.301Z',
      '2025-11-18T18:46:59.301Z',
      NULL,
      300
    );