INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '328823eb-349e-4264-acb9-49cddcbdc46a',
          'Idle Time Rendering',
          'What is Idle Time Rendering and how does it optimize performance?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Idle Time Rendering defers rendering of non-critical UI parts until the main thread is idle.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-9","original_type":"open-ended","topic":"Progressive Hydration","subcategory":"","sample_answers":["Idle Time Rendering defers rendering of non-critical UI parts until the main thread is idle.","It uses browser APIs like requestIdleCallback to improve smoothness."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a78f6496-a353-4954-8667-5a3608dfa08a',
          'Pre-rendering Optimization Tradeoffs',
          'What trade-offs do pre-rendering optimizations (like ISR or static generation) have?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"They improve initial load but can serve outdated content until revalidated","isCorrect":true},{"id":"b","text":"They slow down page loads by increasing bundle size","isCorrect":false},{"id":"c","text":"They disable interactivity on the client","isCorrect":false}]',
          NULL,
          'They improve initial load but can serve outdated content until revalidated',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','progressive-hydration']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-render7-10","original_type":"multiple-choice","topic":"Progressive Hydration","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a728b1dd-8ca4-48fa-a5fe-65afa44c74fa',
          'What is the purpose of the View Transitions API?',
          'It provides a simple way to animate visual DOM changes between two states, enabling smooth transitions between UI views or pages.',
          'multiple-choice',
          'intermediate',
          10,
          '["To animate data fetching operations","To transition visual changes between DOM states smoothly","To handle form validation errors visually","To optimize network requests"]',
          NULL,
          'It provides a simple way to animate visual DOM changes between two states, enabling smooth transitions between UI views or pages.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-1","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '001cf23d-023f-4fe4-87f7-0c10fb49a183',
          'Which method is central to the View Transitions API?',
          'The document.startViewTransition(callback) method initiates a view transition and calls the provided callback to update the DOM.',
          'multiple-choice',
          'intermediate',
          10,
          '["document.animateTransition()","window.beginViewChange()","document.startViewTransition()","window.transitionTo()"]',
          NULL,
          'The document.startViewTransition(callback) method initiates a view transition and calls the provided callback to update the DOM.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-2","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '623087d5-776b-4d05-9e4a-2ced21fa70aa',
          'What does document.startViewTransition(callback) do before executing the callback?',
          'It takes a screenshot of the current DOM state before applying the callback changes.',
          'multiple-choice',
          'intermediate',
          10,
          '["Preloads all CSS animations","Takes a screenshot of the current DOM","Stores a snapshot of localStorage","Pauses all event listeners"]',
          NULL,
          'It takes a screenshot of the current DOM state before applying the callback changes.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-3","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'dc7b3f02-cd85-47d7-9515-98f4aecef3a4',
          'Which CSS pseudo-elements allow developers to style the before and after states of a transition?',
          'Developers can use ::view-transition-old(root) and ::view-transition-new(root) to style the old and new DOM states during a transition.',
          'multiple-choice',
          'intermediate',
          10,
          '["::before and ::after","::view-transition-old(root) and ::view-transition-new(root)","::transition-old and ::transition-new","::prev-state and ::next-state"]',
          NULL,
          'Developers can use ::view-transition-old(root) and ::view-transition-new(root) to style the old and new DOM states during a transition.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-4","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bc382478-c93c-49a2-b3c4-3d8423cb341e',
          'What is the role of view-transition-name in the View Transitions API?',
          'It assigns a unique name to elements so that matching elements across states can be smoothly animated together.',
          'multiple-choice',
          'intermediate',
          10,
          '["It defines a CSS keyframe","It assigns an animation ID for transitions","It uniquely identifies elements for smooth state transitions","It determines animation duration"]',
          NULL,
          'It assigns a unique name to elements so that matching elements across states can be smoothly animated together.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-5","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5f090566-6c44-4d6c-9bcb-1dec0e74a458',
          'What happens to the DOM during a view transition callback?',
          'The DOM becomes non-interactive (frozen) until the callback and transition animation complete.',
          'multiple-choice',
          'advanced',
          10,
          '["The DOM remains interactive","The DOM becomes non-interactive until the callback resolves","Only CSS changes are blocked","Event listeners are temporarily removed"]',
          NULL,
          'The DOM becomes non-interactive (frozen) until the callback and transition animation complete.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-6","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '25d55b42-0ef1-4712-bfe9-929a1b55a394',
          'When should document.startViewTransition ideally be called during page navigation?',
          'After the data request completes to minimize the time the DOM is frozen and improve user experience.',
          'multiple-choice',
          'intermediate',
          10,
          '["Before sending the data request","Immediately on link click","After the data request completes","After component unmount"]',
          NULL,
          'After the data request completes to minimize the time the DOM is frozen and improve user experience.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-7","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd551aaa5-8155-43fe-b67d-1f008f2bab59',
          'How can developers delay the completion of a transition?',
          'By returning a Promise from the callback, which must resolve before the animation completes.',
          'multiple-choice',
          'advanced',
          10,
          '["By using setTimeout inside the callback","By returning a Promise that resolves when the DOM update is complete","By pausing the animation manually","By re-rendering the DOM asynchronously"]',
          NULL,
          'By returning a Promise from the callback, which must resolve before the animation completes.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-8","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3d31b09d-6b86-42ec-ba08-f0dd2bbebbce',
          'Which React lifecycle method is used in the example to prevent premature rendering during a transition?',
          'shouldComponentUpdate() is overridden to return false, delaying rendering until the view transition begins.',
          'multiple-choice',
          'advanced',
          10,
          '["componentDidMount()","componentWillUnmount()","shouldComponentUpdate()","getSnapshotBeforeUpdate()"]',
          NULL,
          'shouldComponentUpdate() is overridden to return false, delaying rendering until the view transition begins.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-9","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bee3024a-c073-4352-aaaf-820142139500',
          'What does the componentDidUpdate() method do in the React example?',
          'It resolves the promise returned during the DOM update, notifying the View Transition API that the DOM has been updated.',
          'multiple-choice',
          'advanced',
          10,
          '["Starts a new transition","Forces a DOM re-render","Resolves the update promise for the transition","Triggers a fade-out animation"]',
          NULL,
          'It resolves the promise returned during the DOM update, notifying the View Transition API that the DOM has been updated.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-10","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '685731e9-1214-478e-9a9a-682ed4c7f0f9',
          'Why is React’s strict mode disabled in the Next.js example?',
          'Because React’s strict mode causes double rendering in development, interfering with the transition flow.',
          'multiple-choice',
          'intermediate',
          10,
          '["It breaks routing","It prevents componentDidUpdate from firing","It causes components to render twice and disrupts transitions","It disables animation hooks"]',
          NULL,
          'Because React’s strict mode causes double rendering in development, interfering with the transition flow.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-11","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7e1f90ad-59ec-4448-a428-4cef2a4b38b3',
          'What is the main limitation of using the View Transitions API for page transitions?',
          'It requires the new page HTML to be available before animating, potentially delaying feedback for users.',
          'multiple-choice',
          'advanced',
          10,
          '["It only supports inline styles","It can’t animate DOM elements","It needs new page HTML before animating","It blocks network requests"]',
          NULL,
          'It requires the new page HTML to be available before animating, potentially delaying feedback for users.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-12","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cf4804e3-55a7-4806-bd9a-fe955bec2636',
          'What is the advantage of performing exit animations immediately after a link click?',
          'It provides instant feedback while waiting for the new content to load, improving perceived performance.',
          'multiple-choice',
          'intermediate',
          10,
          '["It improves SEO performance","It reduces memory usage","It offers immediate visual feedback to the user","It prevents animation jank"]',
          NULL,
          'It provides instant feedback while waiting for the new content to load, improving perceived performance.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-13","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '56867170-7ac5-473b-b6f6-5374280be8c4',
          'Which library enhances server-side rendered MPAs with SPA-like speeds by replacing the <body> with new HTML from the response?',
          'Turbo, part of the Hotwire suite, enhances MPAs by replacing the page body dynamically using JavaScript.',
          'multiple-choice',
          'intermediate',
          10,
          '["Turn","Turbo","Astro","Remix"]',
          NULL,
          'Turbo, part of the Hotwire suite, enhances MPAs by replacing the page body dynamically using JavaScript.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-14","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ea85eef1-10ae-4312-9622-043a131edb1d',
          'What is Turn used for in combination with Turbo?',
          'Turn handles animating page navigations by adding classes like turn-exit and turn-enter to trigger CSS transitions.',
          'multiple-choice',
          'intermediate',
          10,
          '["It performs server rendering","It adds routing capabilities","It animates page navigations via CSS classes","It caches HTML responses"]',
          NULL,
          'Turn handles animating page navigations by adding classes like turn-exit and turn-enter to trigger CSS transitions.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-15","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '622a8164-71e3-4993-ac69-869b606220d0',
          'Which events does Turn hook into to manage the flow of page animations?',
          'Turn listens to Turbo events such as turbo:visit, turbo:before-render, and turbo:render to control animations.',
          'multiple-choice',
          'advanced',
          10,
          '["turbo:start and turbo:end","turbo:visit, turbo:before-render, turbo:render","turbo:click and turbo:load","animationstart and animationend"]',
          NULL,
          'Turn listens to Turbo events such as turbo:visit, turbo:before-render, and turbo:render to control animations.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-16","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5853edbb-4a19-46e4-abbb-cc58761dc10c',
          'What does setting Turn.config.experimental.viewTransitions = true enable?',
          'It activates experimental support for the View Transitions API, falling back to CSS animations when unsupported.',
          'multiple-choice',
          'advanced',
          10,
          '["It disables animations completely","It enables experimental view transitions with fallback","It triggers full page reloads","It forces server-side rendering"]',
          NULL,
          'It activates experimental support for the View Transitions API, falling back to CSS animations when unsupported.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-17","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a0546f60-d2d4-4ecf-9cdf-a7320a172150',
          'What is the main design trade-off between the View Transitions API and traditional exit animations?',
          'The View Transitions API can animate shared elements across pages but requires waiting for new content, while exit animations give instant feedback but can’t transition shared elements.',
          'multiple-choice',
          'advanced',
          10,
          '["View transitions are faster in all cases","Exit animations support cross-page element morphing","View transitions handle shared elements but may delay feedback","Exit animations require the new HTML before starting"]',
          NULL,
          'The View Transitions API can animate shared elements across pages but requires waiting for new content, while exit animations give instant feedback but can’t transition shared elements.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','advanced-patterns']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering10-18","original_type":"multiple-choice","topic":"Advanced Patterns","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e8c2bf8a-d16c-48c3-a293-5cf8398dfe76',
          'Understanding Server-Side Rendering (SSR)',
          'What happens during the Server-Side Rendering (SSR) process in frameworks like Next.js?',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'The server executes React components to generate HTML on each request and sends it to the client.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-1","original_type":"open-ended","topic":"Server-Side Rendering","subcategory":"","sample_answers":["The server executes React components to generate HTML on each request and sends it to the client.","The client then hydrates the HTML to make it interactive."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '99ee940e-5bb5-4692-8d7e-a4ded3cc7eb5',
          'SSR Performance Trade-off',
          'What is the main trade-off when using Server-Side Rendering?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Faster Time to First Byte (TTFB)","isCorrect":false},{"id":"b","text":"Higher server load and slower TTFB compared to static rendering","isCorrect":true},{"id":"c","text":"Improved client-side bundle size","isCorrect":false}]',
          NULL,
          'Higher server load and slower TTFB compared to static rendering',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-2","original_type":"multiple-choice","topic":"Server-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c9433cb9-5f41-4984-a045-04598bd68255',
          'SSR Use Case',
          'Which scenario best benefits from Server-Side Rendering?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"A marketing blog updated monthly","isCorrect":false},{"id":"b","text":"A dashboard showing real-time user data","isCorrect":true},{"id":"c","text":"A static documentation website","isCorrect":false}]',
          NULL,
          'A dashboard showing real-time user data',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-3","original_type":"multiple-choice","topic":"Server-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0db595f2-d8a3-4d27-b5a5-1320c5e2da56',
          'Hydration in SSR',
          'What does ''hydration'' mean in the context of SSR?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Hydration is the process where React attaches event listeners and reuses server-rendered HTML to make the page interactive.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-4","original_type":"open-ended","topic":"Server-Side Rendering","subcategory":"","sample_answers":["Hydration is the process where React attaches event listeners and reuses server-rendered HTML to make the page interactive.","It bridges the server-rendered static HTML with client-side React logic."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '68e0c819-e72f-4dd4-879b-98d14444bc3c',
          'Streaming SSR',
          'How does Streaming SSR differ from traditional SSR?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Streaming SSR sends HTML to the browser in chunks as components are rendered, instead of waiting for the full page to be ready.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-5","original_type":"open-ended","topic":"Server-Side Rendering","subcategory":"","sample_answers":["Streaming SSR sends HTML to the browser in chunks as components are rendered, instead of waiting for the full page to be ready.","It improves TTFB and makes perceived performance faster."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ff056547-c228-4c8c-ad0b-4f396f8da580',
          'React 18 and Streaming SSR',
          'Which React feature introduced in React 18 enhances Streaming SSR?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"React Suspense for data fetching","isCorrect":true},{"id":"b","text":"React Context API","isCorrect":false},{"id":"c","text":"React.memo","isCorrect":false}]',
          NULL,
          'React Suspense for data fetching',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-6","original_type":"multiple-choice","topic":"Server-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9f4ee952-a881-4904-8827-1013fc94767e',
          'Edge Rendering',
          'What is Edge Rendering and why is it becoming popular?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Edge Rendering runs SSR logic on edge servers close to the user, reducing latency and improving global performance.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-7","original_type":"open-ended","topic":"Server-Side Rendering","subcategory":"","sample_answers":["Edge Rendering runs SSR logic on edge servers close to the user, reducing latency and improving global performance.","It’s ideal for personalization with low latency."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '746fcf1a-95f8-4675-81d3-2398a9021983',
          'Edge vs Server Rendering',
          'How does Edge Rendering differ from traditional SSR?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Edge Rendering happens on globally distributed edge nodes rather than a central server","isCorrect":true},{"id":"b","text":"Edge Rendering always requires a CDN","isCorrect":false},{"id":"c","text":"Edge Rendering only works for static pages","isCorrect":false}]',
          NULL,
          'Edge Rendering happens on globally distributed edge nodes rather than a central server',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-8","original_type":"multiple-choice","topic":"Server-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c17fde2c-a29b-4109-bf6f-3c4cbd296e91',
          'React Server Components (RSC)',
          'How do React Server Components (RSC) improve rendering performance?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'RSC allow parts of the React tree to render on the server without sending extra JavaScript to the client.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-9","original_type":"open-ended","topic":"Server-Side Rendering","subcategory":"","sample_answers":["RSC allow parts of the React tree to render on the server without sending extra JavaScript to the client.","They reduce hydration cost and client bundle size."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a3b6ccd7-a79b-47f1-a109-0057c2a7d9da',
          'Combining Rendering Strategies',
          'Which rendering approach combines static and dynamic techniques for optimal performance?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Hybrid Rendering — mixing SSG, SSR, and ISR depending on route needs","isCorrect":true},{"id":"b","text":"Full Client-Side Rendering only","isCorrect":false},{"id":"c","text":"Single Static HTML rendering","isCorrect":false}]',
          NULL,
          'Hybrid Rendering — mixing SSG, SSR, and ISR depending on route needs',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','server-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering2-10","original_type":"multiple-choice","topic":"Server-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '09e6c9f6-001d-441d-8a89-64383a6c4c74',
          'Client-Side Rendering (CSR) Fundamentals',
          'What happens during the Client-Side Rendering (CSR) process in a React application?',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'In CSR, the browser loads a minimal HTML shell and JavaScript bundles.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-1","original_type":"open-ended","topic":"Client-Side Rendering","subcategory":"","sample_answers":["In CSR, the browser loads a minimal HTML shell and JavaScript bundles.","React builds and renders the entire UI in the client’s browser."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0b19c5a9-8b73-4b7a-be9e-335fd5e4b48b',
          'CSR and SEO Challenges',
          'Why can Client-Side Rendering negatively affect SEO?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Search engines struggle to index JavaScript-rendered pages","isCorrect":true},{"id":"b","text":"CSR prevents the use of meta tags","isCorrect":false},{"id":"c","text":"CSR makes sites slower for all users","isCorrect":false}]',
          NULL,
          'Search engines struggle to index JavaScript-rendered pages',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-2","original_type":"multiple-choice","topic":"Client-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '443b425e-e761-4e37-8b9f-562808988e52',
          'Improving CSR Performance',
          'What is a common technique to improve perceived performance in Client-Side Rendering?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use code-splitting and lazy loading to reduce the initial bundle size.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-3","original_type":"open-ended","topic":"Client-Side Rendering","subcategory":"","sample_answers":["Use code-splitting and lazy loading to reduce the initial bundle size.","Show loading skeletons while data is being fetched."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '095edac4-583a-420a-bce2-304ab3766cca',
          'CSR vs SSR Trade-offs',
          'Which of the following best describes the difference between CSR and SSR?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"CSR renders pages on the client, SSR renders them on the server before sending HTML","isCorrect":true},{"id":"b","text":"SSR requires no JavaScript on the client","isCorrect":false},{"id":"c","text":"CSR is faster than SSR in all cases","isCorrect":false}]',
          NULL,
          'CSR renders pages on the client, SSR renders them on the server before sending HTML',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-4","original_type":"multiple-choice","topic":"Client-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'df9e9c9e-d951-43eb-ace2-3e52cf667fdf',
          'Islands Architecture Concept',
          'What is the core principle of the Islands Architecture pattern?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-5","original_type":"open-ended","topic":"Client-Side Rendering","subcategory":"","sample_answers":["Islands Architecture renders mostly static HTML on the server and hydrates only small interactive ''islands'' on the client.","It helps reduce the amount of JavaScript shipped to the user."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ae93d534-9345-4c5c-afca-30ce97f27d81',
          'Dynamic Islands Example',
          'Which of these is an example of a dynamic island on a static page?',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"A social media share widget inside a static blog post","isCorrect":true},{"id":"b","text":"Static article text with no JavaScript","isCorrect":false},{"id":"c","text":"Server-rendered navigation bar","isCorrect":false}]',
          NULL,
          'A social media share widget inside a static blog post',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-6","original_type":"multiple-choice","topic":"Client-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e62b514e-5dca-4c0f-a9ae-82ec51f83f5d',
          'Partial Hydration',
          'How does Partial Hydration improve performance in the Islands Architecture?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'It allows each component to hydrate independently rather than rehydrating the entire page.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-7","original_type":"open-ended","topic":"Client-Side Rendering","subcategory":"","sample_answers":["It allows each component to hydrate independently rather than rehydrating the entire page.","This reduces JavaScript execution time and memory usage."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '39be5c6f-6b35-4bed-bbd7-d7193ee2e270',
          'Frameworks Supporting Islands',
          'Which frameworks natively support Islands Architecture?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Astro and Marko","isCorrect":true},{"id":"b","text":"Next.js only","isCorrect":false},{"id":"c","text":"Create React App","isCorrect":false}]',
          NULL,
          'Astro and Marko',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-8","original_type":"multiple-choice","topic":"Client-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ede354ca-26b8-4330-ab6e-40d0e6d523d8',
          'Advantages of Islands Architecture',
          'What are some benefits of adopting the Islands Architecture?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Reduces the amount of JavaScript shipped to the client.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-9","original_type":"open-ended","topic":"Client-Side Rendering","subcategory":"","sample_answers":["Reduces the amount of JavaScript shipped to the client.","Improves SEO and accessibility due to static HTML.","Allows independent hydration of interactive components."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a5bdb465-f716-4ac9-a30a-567f632a1b04',
          'Limitations of Islands Architecture',
          'What is a limitation of the Islands Architecture approach?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"It’s difficult to scale for highly interactive apps like social media feeds","isCorrect":true},{"id":"b","text":"It cannot be used with React","isCorrect":false},{"id":"c","text":"It requires a full backend rewrite","isCorrect":false}]',
          NULL,
          'It’s difficult to scale for highly interactive apps like social media feeds',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','client-side-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering4-10","original_type":"multiple-choice","topic":"Client-Side Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '164f885f-9546-45c9-a646-239b84d886f4',
          'Incremental Static Regeneration (ISR) Basics',
          'What problem does Incremental Static Regeneration (ISR) solve compared to standard static generation?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'ISR allows pages to be updated after the initial build without rebuilding the entire site.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-1","original_type":"open-ended","topic":"Hybrid Rendering","subcategory":"","sample_answers":["ISR allows pages to be updated after the initial build without rebuilding the entire site.","It helps maintain dynamic content with fast load times."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd7cdd917-ae03-49d1-a6c8-c072f37ae3bb',
          'ISR Workflow',
          'How does ISR update static pages over time?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"It regenerates pages on-demand when a user visits an outdated page","isCorrect":true},{"id":"b","text":"It rebuilds the entire website daily","isCorrect":false},{"id":"c","text":"It updates pages manually via admin dashboard","isCorrect":false}]',
          NULL,
          'It regenerates pages on-demand when a user visits an outdated page',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-2","original_type":"multiple-choice","topic":"Hybrid Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '39c7e06b-b2e3-4b63-9256-f9f1b27a45c7',
          'Revalidation in ISR',
          'What does the ''revalidate'' field do in Next.js Incremental Static Regeneration?',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'It defines how often a static page should be regenerated in the background.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-3","original_type":"open-ended","topic":"Hybrid Rendering","subcategory":"","sample_answers":["It defines how often a static page should be regenerated in the background.","Once the revalidation interval passes, the next request triggers page regeneration."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5a612d17-76be-47f1-96e1-c61de6d3db54',
          'ISR and Performance',
          'Why does ISR improve performance compared to SSR for frequently accessed pages?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"ISR caches pre-rendered pages at the edge and avoids regenerating on every request","isCorrect":true},{"id":"b","text":"ISR avoids hydration completely","isCorrect":false},{"id":"c","text":"ISR runs entirely on the client","isCorrect":false}]',
          NULL,
          'ISR caches pre-rendered pages at the edge and avoids regenerating on every request',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-4","original_type":"multiple-choice","topic":"Hybrid Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bda2048a-6600-4f14-bacc-29415f91a9eb',
          'On-Demand ISR',
          'How is On-Demand ISR different from regular ISR?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-5","original_type":"open-ended","topic":"Hybrid Rendering","subcategory":"","sample_answers":["On-Demand ISR regenerates pages when triggered by specific events like webhook updates instead of fixed time intervals.","It avoids unnecessary revalidations and reduces serverless costs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '656990fa-8b91-4c10-9b26-bc8e4dcb153f',
          'Use Case for On-Demand ISR',
          'When should you prefer On-Demand ISR over time-based ISR?',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"When content changes are event-driven, such as CMS updates","isCorrect":true},{"id":"b","text":"When your website never changes","isCorrect":false},{"id":"c","text":"When you have no API data","isCorrect":false}]',
          NULL,
          'When content changes are event-driven, such as CMS updates',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-6","original_type":"multiple-choice","topic":"Hybrid Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7ea72d9e-aed7-4ad7-94ac-0ca90b7e0d08',
          'Streaming Server-Side Rendering',
          'What is the main benefit of streaming SSR compared to traditional SSR?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-7","original_type":"open-ended","topic":"Hybrid Rendering","subcategory":"","sample_answers":["Streaming SSR allows sending parts of the page to the browser as they are generated, reducing time to first paint.","Users see content progressively instead of waiting for the full page to render."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'edf60968-0313-401a-bacd-ac3c73580a96',
          'React Server Components (RSC)',
          'What role do React Server Components play in modern rendering strategies?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"They allow parts of React components to render on the server without sending unnecessary JavaScript to the client","isCorrect":true},{"id":"b","text":"They replace all client-side interactivity","isCorrect":false},{"id":"c","text":"They only work in static generation","isCorrect":false}]',
          NULL,
          'They allow parts of React components to render on the server without sending unnecessary JavaScript to the client',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-8","original_type":"multiple-choice","topic":"Hybrid Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e3592723-9652-4ccb-a17b-8260747eaa42',
          'Edge SSR and Cold Boots',
          'Why is Edge SSR often faster than traditional serverless SSR?',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Edge SSR runs closer to users, reducing latency and cold boot times.',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-9","original_type":"open-ended","topic":"Hybrid Rendering","subcategory":"","sample_answers":["Edge SSR runs closer to users, reducing latency and cold boot times.","It also enables HTTP streaming for faster content delivery."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5e8fa8bc-c663-4c3d-bc54-1b3857e0ace6',
          'Choosing Between Patterns',
          'When should you choose SSR over ISR or Static Generation?',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"When your page depends on highly personalized data that changes per user request","isCorrect":true},{"id":"b","text":"When the content is static and rarely changes","isCorrect":false},{"id":"c","text":"When build times are slow","isCorrect":false}]',
          NULL,
          'When your page depends on highly personalized data that changes per user request',
          NULL,
          ARRAY[]::text[],
          ARRAY['rendering-patterns','hybrid-rendering']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"rendering-patterns-rendering5-10","original_type":"multiple-choice","topic":"Hybrid Rendering","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Rendering Patterns"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );