INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a149fc54-4b2e-4bde-8857-499a33c2605d',
          'What is the difference between Client-Side Rendering (CSR), Server-Side Rendering (SSR), and Static Site Generation (SSG)?',
          'Compare CSR, SSR, and SSG in terms of performance, SEO, and user experience.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"1","text":"CSR loads JavaScript first and renders in the browser; SSR renders HTML on the server per request; SSG pre-renders HTML at build time.","isCorrect":true,"explanation":"CSR delays first render but enables rich interactivity; SSR improves SEO and first load but adds server cost; SSG is best for static content with CDN delivery."},{"id":"2","text":"CSR is faster than SSR in all cases.","isCorrect":false,"explanation":""},{"id":"3","text":"SSG cannot be cached on CDN.","isCorrect":false,"explanation":""}]',
          NULL,
          'CSR is good for highly interactive apps, SSR helps SEO-driven apps like e-commerce, and SSG is ideal for blogs, docs, and marketing sites.',
          NULL,
          [],
          ARRAY['system-design','rendering-strategies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q21","original_type":"multiple-choice","topic":"Rendering Strategies","subcategory":"","sample_answers":["CSR = client-side execution, SSR = server renders per request, SSG = build-time pre-rendering."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T00:00:00Z',
          '2025-10-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '712fb3c2-6cc5-422b-bccb-80a594286696',
          'What are frontend caching strategies?',
          'Discuss strategies like browser cache, CDN cache, service workers, and caching APIs.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Caching reduces redundant network requests and speeds up page loads. Browser caching handles static assets, CDN caching distributes content closer to users, and service workers enable offline support.',
          NULL,
          ["Think of caching at multiple layers: browser, CDN, service worker."],
          ARRAY['system-design','caching','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q22","original_type":"open-ended","topic":"Caching","subcategory":"","sample_answers":["Use browser caching with Cache-Control headers, CDN caching for static assets, and service workers for offline support."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T00:00:00Z',
          '2025-10-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a9ad6553-3c6c-4361-8a6f-aa402ad521f3',
          'What is a Content Delivery Network (CDN) and how does it improve frontend performance?',
          'Explain the role of CDNs in reducing latency and improving availability.',
          'true-false',
          'beginner',
          10,
          '[{"id":"1","text":"A CDN reduces latency by serving content from edge servers close to the user.","isCorrect":true,"explanation":"CDNs cache static files at edge locations globally to reduce round-trip times."},{"id":"2","text":"A CDN always replaces the need for backend servers.","isCorrect":false,"explanation":""}]',
          NULL,
          'CDNs accelerate delivery of static files (CSS, JS, images, videos) and improve fault tolerance.',
          NULL,
          [],
          ARRAY['system-design','content-delivery','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q23","original_type":"true-false","topic":"Content Delivery","subcategory":"","sample_answers":["A CDN caches and serves assets from geographically closer servers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T00:00:00Z',
          '2025-10-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5563dae1-64ac-4572-9825-a4be0f123abd',
          'What is lazy loading and how does it improve frontend performance?',
          'Explain lazy loading for images, components, and modules in a web app.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"1","text":"Lazy loading defers the loading of non-critical resources until they are needed.","isCorrect":true,"explanation":"Helps reduce initial load time and improves perceived performance."},{"id":"2","text":"Lazy loading means loading all resources as early as possible.","isCorrect":false,"explanation":""},{"id":"3","text":"Lazy loading only applies to JavaScript modules, not images.","isCorrect":false,"explanation":""}]',
          NULL,
          'Lazy loading is especially useful for images, videos, and code-splitting in large applications.',
          NULL,
          [],
          ARRAY['system-design','lazy-loading','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q24","original_type":"multiple-choice","topic":"Lazy Loading","subcategory":"","sample_answers":["Lazy loading delays loading of resources until needed, improving first paint performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T00:00:00Z',
          '2025-10-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '94667859-05a7-4cd1-90d6-313b700f0f44',
          'What is tree-shaking in frontend build optimization?',
          'Explain how tree-shaking helps in reducing bundle size and when it is most effective.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Removes unused CSS from the DOM","isCorrect":false,"explanation":""},{"id":"o2","text":"Removes unused JavaScript exports from bundles","isCorrect":true,"explanation":""},{"id":"o3","text":"Shakes DOM nodes to re-render faster","isCorrect":false,"explanation":""},{"id":"o4","text":"Optimizes images automatically","isCorrect":false,"explanation":""}]',
          NULL,
          'Tree-shaking removes unused code from bundles. It works best with ES6 module imports.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q25","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '09a4a827-bd90-459a-a41f-d013051db55a',
          'What are Web Workers and when should you use them?',
          'Discuss how Web Workers improve performance in web applications and provide an example use case.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Web Workers run scripts in background threads separate from the main UI thread. They are useful for CPU-intensive tasks like parsing large JSON, image processing, or data transformations without blocking the UI.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q26","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Web Workers run scripts in background threads separate from the main UI thread. They are useful for CPU-intensive tasks like parsing large JSON, image processing, or data transformations without blocking the UI."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3ca0b4bc-6cf7-4c49-8bb9-87a467f8c5a5',
          'What is code splitting and how is it different from tree-shaking?',
          'Explain the concept of code splitting and compare it with tree-shaking.',
          'true-false',
          'beginner',
          10,
          '[{"id":"o1","text":"Code splitting reduces bundle size by removing unused code","isCorrect":false,"explanation":""},{"id":"o2","text":"Code splitting loads code in chunks only when needed","isCorrect":true,"explanation":""}]',
          NULL,
          'Code splitting splits bundles into smaller chunks loaded on demand, while tree-shaking removes unused code.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q27","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f07bf379-27fb-4db1-937a-12a63d8fc2be',
          'What is prefetching vs preloading in frontend performance?',
          'Explain how prefetch and preload directives differ in terms of resource loading strategy.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"o1","text":"Prefetch is for resources needed immediately","isCorrect":false,"explanation":""},{"id":"o2","text":"Preload is for resources needed immediately","isCorrect":true,"explanation":""},{"id":"o3","text":"Prefetch is for resources likely needed in future","isCorrect":true,"explanation":""},{"id":"o4","text":"Preload defers resources until user interaction","isCorrect":false,"explanation":""}]',
          NULL,
          'Prefetch loads resources for future navigation, while preload ensures critical resources are fetched earlier for the current page.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q28","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '183542dd-f46b-44c2-ba18-b9457cda1897',
          'What is the purpose of ARIA roles in frontend design?',
          'Explain how ARIA roles help assistive technologies interpret UI components.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'ARIA roles provide semantic information about elements to assistive technologies, improving accessibility for screen readers and keyboard navigation.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q29","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["ARIA roles provide semantic information about elements to assistive technologies, improving accessibility for screen readers and keyboard navigation."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a0986352-a2e5-4bb4-909a-455179a65d20',
          'What are semantic HTML elements and why are they important for accessibility?',
          'Discuss how semantic HTML improves usability and accessibility.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Semantic HTML improves SEO","isCorrect":true,"explanation":""},{"id":"o2","text":"Semantic HTML is ignored by screen readers","isCorrect":false,"explanation":""},{"id":"o3","text":"Semantic HTML improves accessibility for keyboard and screen reader users","isCorrect":true,"explanation":""},{"id":"o4","text":"Semantic HTML automatically optimizes bundle size","isCorrect":false,"explanation":""}]',
          NULL,
          'Semantic elements like `<header>`, `<nav>`, `<main>` provide meaning, improving navigation for assistive technologies.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q30","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3ecc89bd-044b-490d-bb3e-264bc092b085',
          'What is color contrast and how does it affect accessibility?',
          'Explain the importance of sufficient color contrast in frontend UI design.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Color contrast ensures that text and UI elements are distinguishable for users with visual impairments. WCAG recommends a minimum contrast ratio of 4.5:1 for normal text.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q31","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Color contrast ensures that text and UI elements are distinguishable for users with visual impairments. WCAG recommends a minimum contrast ratio of 4.5:1 for normal text."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9e6df008-1aba-4f20-849c-f5e85ab6a316',
          'How can you ensure keyboard navigability for custom components?',
          'Describe best practices to make interactive components accessible via keyboard.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Ensure focusable elements have `tabindex`, use `aria` attributes correctly, manage focus order for dialogs/modals, and provide keyboard shortcuts where necessary.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q32","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Ensure focusable elements have `tabindex`, use `aria` attributes correctly, manage focus order for dialogs/modals, and provide keyboard shortcuts where necessary."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b47fc0aa-ea6a-4afd-9515-2ddc941a73d4',
          'What is an optimistic update in frontend state management?',
          'Explain optimistic updates and when they are used.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Optimistic updates immediately update the UI assuming the server request will succeed. If the request fails, the UI is reverted. It improves perceived responsiveness.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q33","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Optimistic updates immediately update the UI assuming the server request will succeed. If the request fails, the UI is reverted. It improves perceived responsiveness."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '92790915-9fd6-4162-8316-cded7c5b5399',
          'What is a pessimistic update in frontend state management?',
          'Explain pessimistic updates and how they differ from optimistic updates.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Pessimistic updates wait for server confirmation before updating the UI. This ensures consistency but may feel slower to the user.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q34","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Pessimistic updates wait for server confirmation before updating the UI. This ensures consistency but may feel slower to the user."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bd8a5fa2-0d38-41b3-a811-4437c70f8710',
          'What is long-polling and when would you use it?',
          'Explain how long-polling works for real-time updates.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Client repeatedly sends requests at a fixed interval","isCorrect":false,"explanation":""},{"id":"o2","text":"Client sends a request, server responds only when new data is available, then client repeats","isCorrect":true,"explanation":""},{"id":"o3","text":"Client uses WebSocket connection for continuous streaming","isCorrect":false,"explanation":""}]',
          NULL,
          'Long-polling keeps an HTTP request open until the server has data, then immediately sends a new request for the next update.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q35","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '76ffbf2b-f339-492f-a03b-9acbe1f0920c',
          'What is WebSocket and why is it used in frontend apps?',
          'Explain the WebSocket protocol and its benefits for real-time communication.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'WebSocket establishes a persistent bidirectional connection between client and server, allowing real-time updates with lower overhead compared to HTTP polling.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q36","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["WebSocket establishes a persistent bidirectional connection between client and server, allowing real-time updates with lower overhead compared to HTTP polling."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9bc4338c-c3c6-40bc-865a-9b047d27a4eb',
          'What are Server-Sent Events (SSE) and when should they be used?',
          'Explain SSE and how it differs from WebSocket.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"SSE is unidirectional (server -> client)","isCorrect":true,"explanation":""},{"id":"o2","text":"WebSocket is bidirectional (client <-> server)","isCorrect":true,"explanation":""},{"id":"o3","text":"SSE requires a persistent TCP connection like WebSocket","isCorrect":false,"explanation":""}]',
          NULL,
          'SSE provides a unidirectional stream of updates from server to client over HTTP.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q37","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '104d8af4-e7ec-4c20-9e80-c139b46c8763',
          'How do you design a frontend entity for a Post with Comments and Media?',
          'Describe the structure of a frontend entity object for a Post.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q38","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'be09ef4d-c262-41b2-87e9-493118dc0be3',
          'What is the difference between REST and GraphQL APIs for frontend consumption?',
          'Compare REST and GraphQL in terms of data fetching and flexibility.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"REST returns fixed data structures per endpoint","isCorrect":true,"explanation":""},{"id":"o2","text":"GraphQL allows client to request exactly the fields needed","isCorrect":true,"explanation":""},{"id":"o3","text":"GraphQL cannot support real-time updates","isCorrect":false,"explanation":""},{"id":"o4","text":"REST APIs can never be cached","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: REST returns fixed data structures per endpoint',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q39","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '33e1d4be-9730-44b1-b0c8-bff3bf5774b3',
          'How do you handle real-time updates for a feed of posts?',
          'Discuss strategies for updating the UI when new posts or comments arrive.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use WebSockets or SSE to push updates, update frontend state optimistically, maintain a local cache, and optionally batch updates to reduce re-renders.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q40","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use WebSockets or SSE to push updates, update frontend state optimistically, maintain a local cache, and optionally batch updates to reduce re-renders."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '350f6cca-ba70-4930-a110-891c1d3c5b49',
          'What is critical CSS and how do you apply it?',
          'Explain the concept of critical CSS and how it improves page load performance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Critical CSS is the CSS required to render above-the-fold content. Load it inline in the HTML to reduce render-blocking, while deferring non-critical CSS.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q41","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Critical CSS is the CSS required to render above-the-fold content. Load it inline in the HTML to reduce render-blocking, while deferring non-critical CSS."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b4094a73-3069-4037-8fb4-24e47fae7986',
          'What are signed URLs for images and why are they used?',
          'Explain the purpose of signed URLs and their impact on security and performance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Signed URLs provide temporary, time-limited access to private resources (like images) on CDNs. They ensure secure access while allowing caching and CDN optimization.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q42","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Signed URLs provide temporary, time-limited access to private resources (like images) on CDNs. They ensure secure access while allowing caching and CDN optimization."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '498facf7-9bb6-4b53-8553-000653c8f205',
          'What are different approaches for pagination and which is better?',
          'Compare offset-based, cursor-based, and infinite scroll pagination in frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Offset-based: simple, can have duplicates","isCorrect":true,"explanation":""},{"id":"o2","text":"Cursor-based: more reliable for dynamic data","isCorrect":true,"explanation":""},{"id":"o3","text":"Infinite scroll: UX-friendly but can be tricky to manage state","isCorrect":true,"explanation":""},{"id":"o4","text":"All approaches are identical in performance","isCorrect":false,"explanation":""}]',
          NULL,
          'Offset-based pagination is simple but can have duplicates on fast-changing data. Cursor-based is more reliable for real-time feeds. Infinite scroll is UX dependent.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q43","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0a6bc2cf-fd3e-4295-bfb5-f0699705e423',
          'How do you optimize image loading in frontend apps?',
          'Explain techniques like WebP format, responsive images, lazy loading, and CDN caching.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use modern formats like WebP, serve different resolutions with `srcset`, lazy load offscreen images, compress images, and cache via CDN.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q44","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use modern formats like WebP, serve different resolutions with `srcset`, lazy load offscreen images, compress images, and cache via CDN."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9f38c409-0f36-4daf-a1f4-f442f946e1b7',
          'How do you improve rendering performance for large lists?',
          'Discuss techniques like windowing, virtualization, and memoization for list rendering.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use libraries like react-window or react-virtualized to render only visible items, memoize list items to avoid unnecessary re-renders, and paginate data if possible.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q45","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use libraries like react-window or react-virtualized to render only visible items, memoize list items to avoid unnecessary re-renders, and paginate data if possible."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e8738172-8ff3-4570-8b96-af043b4b385f',
          'What is the difference between reflow and repaint in the browser?',
          'Explain how reflow and repaint affect rendering performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Reflow recalculates layout and can trigger repaint","isCorrect":true,"explanation":""},{"id":"o2","text":"Repaint only redraws pixels without layout calculation","isCorrect":true,"explanation":""},{"id":"o3","text":"Reflow and repaint are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Reflow recalculates layout and can trigger repaint',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q46","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '69042d5d-30dd-4411-8459-c852fa5fc6a8',
          'How can HTTPS help with frontend performance?',
          'Explain performance benefits of HTTPS beyond security.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'HTTPS enables HTTP/2 or HTTP/3 which supports multiplexing, header compression, and better caching, improving load performance.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q47","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["HTTPS enables HTTP/2 or HTTP/3 which supports multiplexing, header compression, and better caching, improving load performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '65f1010b-83f4-42b2-8b82-5defb42df85d',
          'What is bundle splitting and why is it important?',
          'Explain how splitting JavaScript bundles improves performance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Bundle splitting breaks the app into smaller chunks, allowing the browser to load only necessary code on demand, reducing initial load time.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q48","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Bundle splitting breaks the app into smaller chunks, allowing the browser to load only necessary code on demand, reducing initial load time."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'eaf0a046-548e-422f-9abd-9ce3ca3d8a1c',
          'What is memoization in React and when should you use it?',
          'Explain how memoization improves rendering performance in React.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Memoization (using React.memo, useMemo, or useCallback) avoids unnecessary re-rendering of components or expensive calculations when props/state haven’t changed.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q49","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Memoization (using React.memo, useMemo, or useCallback) avoids unnecessary re-rendering of components or expensive calculations when props/state haven’t changed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6609ccf3-dea0-4c9c-a4f6-987ca6b94ddd',
          'What is infinite scroll and what are its pros and cons?',
          'Explain how infinite scroll works and its impact on UX and performance.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Infinite scroll automatically loads more content as user scrolls","isCorrect":true,"explanation":""},{"id":"o2","text":"Pros: improves UX for browsing feeds, keeps engagement high","isCorrect":true,"explanation":""},{"id":"o3","text":"Cons: harder to track scroll position and can impact memory","isCorrect":true,"explanation":""},{"id":"o4","text":"Infinite scroll replaces the need for backend pagination","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Infinite scroll automatically loads more content as user scrolls',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q50","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ca049a09-0cbf-49fa-a73e-88822bb1aee6',
          'How do you decide when to break a UI into smaller components?',
          'Explain criteria for dividing a large component into smaller reusable components.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Break components when parts are reusable, have independent state, or to improve readability and maintainability. Follow Single Responsibility Principle and avoid deep prop drilling.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q51","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Break components when parts are reusable, have independent state, or to improve readability and maintainability. Follow Single Responsibility Principle and avoid deep prop drilling."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '50201b36-c27b-4cf1-80d5-569c45b0ad05',
          'What is the difference between controlled and uncontrolled components in React?',
          'Explain how controlled and uncontrolled components manage state.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Controlled components have state managed by React via props","isCorrect":true,"explanation":""},{"id":"o2","text":"Uncontrolled components manage state internally using refs","isCorrect":true,"explanation":""},{"id":"o3","text":"Controlled components are faster than uncontrolled in all cases","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Controlled components have state managed by React via props',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q52","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd5d78ce9-e96d-4599-adc8-86e786d8d08b',
          'What is Redux and when should you use it?',
          'Explain Redux for state management and use cases for global state.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Redux is a predictable state container for JavaScript apps, useful for managing global state shared across multiple components, especially in large or complex apps.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q53","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Redux is a predictable state container for JavaScript apps, useful for managing global state shared across multiple components, especially in large or complex apps."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c55b94d5-8ec3-47ce-8f0e-80e75d6746b6',
          'What are the differences between local state, global state, and server state?',
          'Explain how different state types are managed and synchronized.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Local state is component-specific","isCorrect":true,"explanation":""},{"id":"o2","text":"Global state is shared across multiple components","isCorrect":true,"explanation":""},{"id":"o3","text":"Server state comes from APIs and must be synchronized","isCorrect":true,"explanation":""},{"id":"o4","text":"All states are automatically synchronized with the server","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Local state is component-specific',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q54","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cf20ea05-8d7f-4da4-8406-b4ff2a0ca225',
          'How do you structure a component dependency graph from a Figma design?',
          'Describe the process of identifying components and their hierarchy from design files.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Analyze the design, identify repeated patterns, break down UI into smallest reusable components, map dependencies, and visualize parent-child relationships in a graph.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q55","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Analyze the design, identify repeated patterns, break down UI into smallest reusable components, map dependencies, and visualize parent-child relationships in a graph."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bc65107b-476d-443e-a1f1-15143685e267',
          'What are the best practices for designing reusable UI components?',
          'Discuss principles for making components modular and reusable.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Keep components focused on a single responsibility, accept props for configuration, avoid hardcoding styles or behavior, and make them testable and composable.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q56","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Keep components focused on a single responsibility, accept props for configuration, avoid hardcoding styles or behavior, and make them testable and composable."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '92a27336-3dca-4c8e-b289-733bd363e5cf',
          'What is the difference between REST and GraphQL when designing frontend APIs?',
          'Explain how each API style affects data fetching, over-fetching, and frontend flexibility.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"REST endpoints return fixed data structures","isCorrect":true,"explanation":""},{"id":"o2","text":"GraphQL allows querying only required fields","isCorrect":true,"explanation":""},{"id":"o3","text":"GraphQL eliminates the need for pagination","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: REST endpoints return fixed data structures',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q57","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd2489d75-13d2-4dc6-9fe2-3217049a6423',
          'How do you design a frontend data store for posts and comments?',
          'Explain the structure and normalization strategies for storing related entities in frontend state.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q58","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Normalize entities: store posts in a dictionary keyed by id, store comments separately keyed by id, reference relationships via ids to reduce duplication and simplify updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c013a83a-cdcb-4ddc-9c6d-80217e5c527b',
          'How do you handle data caching in frontend applications?',
          'Explain strategies for caching API responses and syncing with the server.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q59","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use in-memory stores, IndexedDB, or libraries like React Query / SWR to cache API responses, invalidate stale data, and optionally persist cache across sessions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f0f27b67-bd8a-4257-a1bb-3cc0407e527b',
          'What is the difference between localStorage, sessionStorage, and IndexedDB?',
          'Explain when to use each browser storage type for frontend data persistence.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"localStorage persists data indefinitely across sessions","isCorrect":true,"explanation":""},{"id":"o2","text":"sessionStorage persists data only for the session","isCorrect":true,"explanation":""},{"id":"o3","text":"IndexedDB is useful for storing large structured data","isCorrect":true,"explanation":""},{"id":"o4","text":"localStorage automatically syncs with the server","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: localStorage persists data indefinitely across sessions',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q60","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cfdf3fc6-932b-42a5-90df-1bcbdeba428c',
          'How do you measure frontend network performance?',
          'Explain tools and metrics used to analyze network requests in frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q61","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use browser dev tools, Lighthouse, or WebPageTest to measure TTFB, total request size, request count, and loading time for critical assets."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a1b05c02-a01b-48c0-b88c-980a5ae53400',
          'What is a frontend performance budget and why is it important?',
          'Describe the concept of a performance budget and how it helps maintain good UX.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q62","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["A performance budget sets limits on page weight, script size, or request counts to prevent regressions and maintain fast load times."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e10a7ac9-94eb-476a-8794-69c8816df58a',
          'How do you profile and optimize JavaScript performance?',
          'Explain techniques for identifying and fixing slow JS execution.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q63","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use Chrome DevTools Performance tab to record JS execution, identify long tasks, optimize loops, debounce/throttle events, and memoize expensive calculations."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1852280b-c16d-46ea-b392-940dd54aa6fd',
          'How do you profile rendering performance in a React app?',
          'Discuss tools and techniques for identifying re-render bottlenecks.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q64","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use React DevTools Profiler to measure component render times, identify unnecessary renders, optimize with memoization, lazy loading, and virtualization."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fd5de285-a82e-44b4-b56a-214d9e1f4d5c',
          'What are Lighthouse audits and how do they help in frontend system design?',
          'Explain the purpose of Lighthouse and its reports for performance and accessibility.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q65","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Lighthouse audits provide automated reports for performance, accessibility, best practices, SEO, and PWA compliance, helping developers optimize their apps."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6c768b85-d8ee-4ed7-9e97-242b3f438ff1',
          'How do you monitor accessibility issues in a frontend application?',
          'Describe tools and methods to detect and fix a11y problems.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q66","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use tools like Axe, Lighthouse, WAVE, or browser extensions to audit accessibility, detect color contrast issues, missing ARIA labels, and keyboard navigation problems."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fad56d4c-2709-42e4-8e84-e28496789570',
          'What is Time to Interactive (TTI) and why is it important?',
          'Explain the TTI metric and its significance for user experience.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q67","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["TTI measures the time until the page becomes fully interactive for users. Lower TTI improves perceived performance and UX."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5cf15b91-a6a1-4cc1-a61f-a0b8dc4f63b1',
          'What is Largest Contentful Paint (LCP) and how can you improve it?',
          'Explain LCP and strategies to reduce its value.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q68","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["LCP measures time for the largest visible element to load. Optimize by lazy loading images, compressing resources, using critical CSS, and serving assets via CDN."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2e89375a-5df2-476a-b710-03a7d3aeb8f4',
          'How do you detect memory leaks in frontend applications?',
          'Describe methods to identify and fix memory leaks in JavaScript apps.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q69","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use Chrome DevTools Memory tab, take heap snapshots, look for detached DOM nodes, and clean up event listeners or intervals to prevent leaks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '33421d52-b1ca-4396-85f1-1be56fd5de52',
          'What are some strategies to monitor frontend errors in production?',
          'Explain how to track and report frontend runtime errors effectively.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q70","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use services like Sentry, LogRocket, or Rollbar to capture uncaught errors, promise rejections, and user sessions. Include context and stack traces for debugging."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );