INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '04f5fccf-1c38-40b9-985e-648b572fa98a',
          'What is a signed URL and why is it important for security?',
          'Explain the purpose of signed URLs for accessing private resources.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q71","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Signed URLs provide temporary, time-limited access to private resources on a server or CDN. They prevent unauthorized access and allow caching while maintaining security."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ceb6f75e-9647-423e-97b0-23f5aa992885',
          'How do you prevent CSRF attacks in frontend applications?',
          'Describe techniques to protect against Cross-Site Request Forgery.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q72","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use anti-CSRF tokens in requests, ensure same-site cookies, validate origin headers, and use secure HTTP methods for state-changing requests."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '24f34983-3398-4f5c-a6f5-e7820ca29300',
          'How do you prevent XSS attacks in frontend applications?',
          'Explain strategies to mitigate Cross-Site Scripting vulnerabilities.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q73","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Escape or sanitize user-generated content, use Content Security Policy (CSP), avoid `innerHTML`, and validate input on both frontend and backend."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'eac0c641-9f3a-4291-a029-d6cf72a2dcce',
          'What are HTTP-only cookies and why are they important?',
          'Explain the role of HTTP-only cookies in frontend security.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q74","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["HTTP-only cookies cannot be accessed by JavaScript, reducing the risk of XSS attacks stealing session data."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '21c61aa3-9616-4199-a930-1d6280447f47',
          'How do you handle authentication in frontend applications?',
          'Discuss strategies for managing user authentication and session state.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q75","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use tokens (JWT or opaque), store securely in HTTP-only cookies or local storage, handle token refresh, and validate session on API requests."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '18ce1292-de87-4e63-97b9-f4998bca400d',
          'What is the difference between JWT and opaque tokens?',
          'Compare JWT and opaque tokens for frontend authentication.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"JWT is self-contained, includes claims, can be verified without server","isCorrect":true,"explanation":""},{"id":"o2","text":"Opaque tokens are random identifiers, require server to validate","isCorrect":true,"explanation":""},{"id":"o3","text":"JWT cannot be used in SPAs","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: JWT is self-contained, includes claims, can be verified without server',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q76","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7d512fd6-6a8c-4767-835c-2b0d1b1017f3',
          'What is CORS and why is it important in frontend apps?',
          'Explain Cross-Origin Resource Sharing and its relevance for security.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q77","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CORS is a browser security mechanism that controls which origins can access resources. It prevents unauthorized cross-origin requests."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e2f96c8b-d66c-40c8-914a-b875728d73fb',
          'How do you securely handle API tokens in frontend applications?',
          'Discuss best practices for storing and using API tokens in the browser.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q78","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Store tokens in HTTP-only cookies or in-memory storage, avoid localStorage for sensitive tokens, use short-lived tokens with refresh, and send via Authorization header."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ed9a87b2-1d0f-49c5-939c-7c8b5327b99d',
          'What is the difference between authentication and authorization?',
          'Explain the difference between verifying identity and granting access.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Authentication verifies user identity","isCorrect":true,"explanation":""},{"id":"o2","text":"Authorization determines access level or permissions","isCorrect":true,"explanation":""},{"id":"o3","text":"They are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Authentication verifies user identity',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q79","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '09816bc8-6b87-4434-b7a0-c70597cbc8f1',
          'How do signed URLs impact performance in frontend applications?',
          'Explain how using signed URLs can improve frontend loading and caching.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q80","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Signed URLs allow CDNs to cache private resources efficiently, reducing server load and latency, while ensuring secure time-limited access to assets."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd13d8ca6-e766-4ca9-a87e-b6c5408006ce',
          'What is web accessibility (a11y) and why is it important?',
          'Explain the concept of web accessibility and its significance in frontend design.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q81","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Web accessibility ensures that websites are usable by people with disabilities, providing equal access to content and functionality. It improves usability and inclusivity."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ed7602bf-89be-4db9-a4c1-39cac1087358',
          'What are ARIA roles and how do you use them?',
          'Explain ARIA roles and attributes to improve accessibility.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'ARIA roles and attributes provide semantic information for assistive technologies. Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q82","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["ARIA roles and attributes provide semantic information for assistive technologies. Use roles like `button`, `dialog`, and states like `aria-expanded` to convey meaning."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2ba4cdea-388e-47f1-98e1-a9891957332c',
          'How do you test accessibility in frontend applications?',
          'Describe tools and methods to verify a11y compliance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q83","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use browser extensions like Axe or WAVE, automated tools like Lighthouse, and manual testing with keyboard navigation and screen readers to ensure accessibility compliance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '98c4c76c-5136-40a8-854f-bc41b9391f92',
          'What are common accessibility mistakes in frontend apps?',
          'Identify frequent a11y issues and how to avoid them.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Missing alt text on images","isCorrect":true,"explanation":""},{"id":"o2","text":"Poor color contrast","isCorrect":true,"explanation":""},{"id":"o3","text":"Non-focusable interactive elements","isCorrect":true,"explanation":""},{"id":"o4","text":"Using semantic HTML","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Missing alt text on images',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q84","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e3f6200f-004a-4aca-8a8c-32db3dd40de6',
          'What is internationalization (i18n) in frontend applications?',
          'Explain the purpose of i18n and how it impacts frontend design.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q85","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Internationalization (i18n) is the process of designing a frontend app to support multiple languages, locales, and cultural conventions without changing code."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2ac5561f-aa4b-4724-9823-590780f34195',
          'What is the difference between i18n and l10n?',
          'Compare internationalization and localization in frontend development.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"i18n is the process of designing for multiple languages","isCorrect":true,"explanation":""},{"id":"o2","text":"l10n is the process of adapting content for a specific locale","isCorrect":true,"explanation":""},{"id":"o3","text":"i18n and l10n are the same","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: i18n is the process of designing for multiple languages',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q86","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4c9bc4ee-cf9f-4c94-b197-d168ad6688f7',
          'How do you handle right-to-left (RTL) languages in frontend apps?',
          'Explain strategies for supporting RTL layouts and text.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q87","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use CSS logical properties (`margin-inline-start`), direction attributes (`dir=''rtl''`), mirrored layout components, and test with RTL content to ensure proper alignment."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7348c169-31f3-41a9-ab53-8d29872da1c1',
          'What UX considerations should be taken for performance-sensitive pages?',
          'Discuss UX strategies to improve perceived performance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q88","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use skeleton loaders, progressive rendering, lazy load images and components, provide feedback for user actions, and prioritize above-the-fold content."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f4f870fc-d65b-47cf-a755-f451cd4d35ef',
          'What is the difference between progressive enhancement and graceful degradation?',
          'Explain these two strategies in frontend development.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Progressive enhancement starts with basic functionality and adds features for modern browsers","isCorrect":true,"explanation":""},{"id":"o2","text":"Graceful degradation starts with full features and reduces functionality for older browsers","isCorrect":true,"explanation":""},{"id":"o3","text":"They are exactly the same","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Progressive enhancement starts with basic functionality and adds features for modern browsers',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q89","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6d767bd7-6a91-4a6d-aa34-462da750a84a',
          'How do you ensure a frontend app is usable for all users, including those with disabilities?',
          'Describe strategies for inclusive frontend design.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q90","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Follow WCAG guidelines, use semantic HTML, ARIA roles, keyboard navigable interfaces, screen reader testing, color contrast compliance, and responsive layouts."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '504a9578-097f-4638-881b-ba9aa917f8a1',
          'What is WebSocket and when should you use it?',
          'Explain WebSocket protocol and its use cases in frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q91","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["WebSocket is a full-duplex, persistent connection between client and server for real-time communication. Use it for chat apps, notifications, and live feeds."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2ab492a7-437e-4be5-bcd5-f54b825267ae',
          'What is Server-Sent Events (SSE) and how does it differ from WebSocket?',
          'Compare SSE and WebSocket in terms of use cases and protocol features.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q92","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["SSE is a unidirectional protocol where server pushes updates to the client over HTTP. Use SSE for live feeds or notifications where the client doesn''t need to send frequent data."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '122d14d6-1579-4813-9a98-f273591eaee3',
          'What is long polling and when is it used?',
          'Explain long polling technique for real-time updates.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q93","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Long polling is a technique where the client sends a request and the server holds it until data is available. Use it when WebSocket or SSE is not possible."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e19679b7-9a2d-41b1-b409-8063fba95da5',
          'What are the pros and cons of WebSocket vs SSE vs long polling?',
          'Compare these real-time strategies in terms of latency, scalability, and complexity.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'WebSocket: low latency, bidirectional, more complex, heavier on server.
SSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.
Long Polling: compatible with HTTP, higher latency, server holds connections, less efficient.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q94","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["WebSocket: low latency, bidirectional, more complex, heavier on server.\nSSE: simple, unidirectional, uses HTTP, auto-reconnect, limited to text/event-stream.\nLong Polling: compatible with HTTP, higher latency, server holds connections, less efficient."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '990e708f-e9e2-4537-9f94-3c39efc46c6d',
          'How do you handle reconnection logic in real-time frontend apps?',
          'Describe strategies to maintain real-time connectivity.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q95","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Implement exponential backoff retry, detect disconnections, optionally queue messages during downtime, and re-subscribe to channels after reconnect."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '96cfd2cd-9108-43ea-918e-55d281408a64',
          'What are the best practices for handling high-frequency real-time data in the frontend?',
          'Explain strategies to manage performance when receiving frequent updates.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q96","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Throttle or debounce updates, batch multiple events into a single render, use virtualization for lists, and avoid unnecessary state updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a66e309a-a5fd-4b52-a487-f75fe74e0550',
          'How do you secure WebSocket connections in frontend apps?',
          'Discuss authentication and encryption for WebSocket connections.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q97","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use WSS (WebSocket over TLS), validate tokens or cookies on handshake, limit origin access, and avoid exposing sensitive data over the connection."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b0f6e80d-72df-43d2-ac1c-5ddf3f2eddbd',
          'How do you manage subscriptions to multiple real-time channels efficiently?',
          'Explain strategies for handling multiple feeds in frontend apps.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q98","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use a central subscription manager, reuse connections, dynamically subscribe/unsubscribe as needed, and debounce updates from high-frequency channels."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '83703498-4f24-4abc-92b9-3f7a5a1fac1a',
          'How do you handle fallback mechanisms if WebSocket or SSE fails?',
          'Describe strategies to maintain real-time updates when primary methods fail.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q99","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use long polling as a fallback, retry WebSocket connections periodically, or display stale cached data with visual indication until connection restores."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '75069ee7-5e86-4462-b49e-6b89844ae6b9',
          'When would you choose SSE over WebSocket in a frontend system?',
          'Explain scenarios where Server-Sent Events are more suitable than WebSocket.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q100","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use SSE for unidirectional updates like live feeds, notifications, or stock tickers where client doesn''t send frequent data and simplicity is preferred over bidirectional communication."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '85685273-b321-4148-8586-608825ec3f30',
          'What is the difference between browser cache and CDN cache?',
          'Explain how browser caching and CDN caching work and their differences.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q101","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Browser cache stores assets locally on the client device. CDN cache stores assets on edge servers closer to the user. CDN reduces network latency while browser cache reduces repeated downloads."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd777685b-4e9c-442a-83b2-689ec9e851a3',
          'What are cache-control headers and why are they important?',
          'Explain cache-control strategies for frontend assets.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Cache-control headers define how long and where a resource can be cached. Examples: `max-age`, `no-store`, `must-revalidate`. They help control freshness and prevent stale content.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q102","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Cache-control headers define how long and where a resource can be cached. Examples: `max-age`, `no-store`, `must-revalidate`. They help control freshness and prevent stale content."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c63b5840-7df9-4c9b-91e7-dc03b9ca2195',
          'What is a service worker and what role does it play in caching?',
          'Explain service workers and how they enable offline-first frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q103","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["A service worker is a script running in the background that intercepts network requests. It can cache assets, serve offline content, and enable push notifications for PWAs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8327e6a0-6eb2-4f7a-8904-0af3ab3fb057',
          'What is the difference between AppCache and Service Worker?',
          'Compare the deprecated AppCache and modern Service Worker approach.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"AppCache was limited and inflexible","isCorrect":true,"explanation":""},{"id":"o2","text":"Service Worker provides programmable caching and background sync","isCorrect":true,"explanation":""},{"id":"o3","text":"Both are actively supported","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: AppCache was limited and inflexible',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q104","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e85172bd-6def-40fd-b5ee-464f847551ce',
          'What is stale-while-revalidate caching strategy?',
          'Explain how stale-while-revalidate improves perceived performance.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q105","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Stale-while-revalidate serves cached content immediately while fetching a fresh version in the background. The user sees fast responses while data stays up-to-date."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3a53f66a-0454-4798-a69d-80f56d8a9153',
          'How does IndexedDB help with offline frontend applications?',
          'Explain the role of IndexedDB for client-side storage.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q106","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["IndexedDB is a low-level NoSQL database in the browser. It stores structured data, useful for offline applications where data must persist across sessions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd11d2128-243b-4c2d-9d47-48d405de2f1e',
          'How do you implement offline-first design in frontend apps?',
          'Describe strategies to make a web app work offline.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use service workers for caching, IndexedDB for persistent storage, queue requests for background sync, and gracefully degrade UI when offline.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q107","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use service workers for caching, IndexedDB for persistent storage, queue requests for background sync, and gracefully degrade UI when offline."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3f573d14-8049-4d5f-8d8a-379dafbc4d04',
          'What is background sync and how does it work with service workers?',
          'Explain background sync and its benefits for frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Background sync allows deferred actions like sending requests once connectivity is restored. Service workers handle queued tasks even when the app is closed.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q108","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Background sync allows deferred actions like sending requests once connectivity is restored. Service workers handle queued tasks even when the app is closed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '077a8336-d044-4c5e-a4e2-0126178a3ffe',
          'How do you cache API responses efficiently on the frontend?',
          'Discuss strategies for API caching in frontend applications.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'Use IndexedDB or in-memory caching, implement SWR/React Query strategies, leverage service workers for offline API responses, and use ETag headers to revalidate.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q109","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use IndexedDB or in-memory caching, implement SWR/React Query strategies, leverage service workers for offline API responses, and use ETag headers to revalidate."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '47e1109d-fea4-4f0a-be29-53e407bf584f',
          'What is the role of a Content Delivery Network (CDN) in caching?',
          'Explain how CDNs optimize asset delivery in frontend systems.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'A CDN caches static assets at edge servers near users, reducing latency and improving load times for global audiences.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q110","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["A CDN caches static assets at edge servers near users, reducing latency and improving load times for global audiences."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '383df2b1-4b85-45f6-8abc-797478be91e3',
          'What is the difference between authentication and authorization?',
          'Explain the roles of authentication and authorization in frontend applications.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Authentication verifies who the user is","isCorrect":true,"explanation":""},{"id":"o2","text":"Authorization decides what the user can access","isCorrect":true,"explanation":""},{"id":"o3","text":"They are the same thing","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Authentication verifies who the user is',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q111","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0e9f4dcc-d0ad-4a34-98ed-02cfd09b8e48',
          'What is OAuth2 and how is it used in frontend apps?',
          'Explain OAuth2 flow and its role in frontend authentication.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'OAuth2 is an authorization framework allowing apps to access resources on behalf of users. Frontend apps use it for social logins and delegated access with access tokens.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q112","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["OAuth2 is an authorization framework allowing apps to access resources on behalf of users. Frontend apps use it for social logins and delegated access with access tokens."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '37f6847e-af45-4a01-8f3f-aac58033166e',
          'What is the difference between JWT and opaque tokens?',
          'Compare JSON Web Tokens and opaque tokens in terms of usage and security.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'JWTs are self-contained tokens with claims, verifiable by signature, no DB lookup needed. Opaque tokens are random strings requiring server lookup. JWTs scale better but must be handled securely.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q113","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["JWTs are self-contained tokens with claims, verifiable by signature, no DB lookup needed. Opaque tokens are random strings requiring server lookup. JWTs scale better but must be handled securely."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '91d8b916-fd9a-466b-af2b-581a6c760375',
          'What are HttpOnly cookies and why are they important?',
          'Explain HttpOnly cookies and their role in frontend security.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'HttpOnly cookies cannot be accessed via JavaScript, preventing XSS attacks from stealing tokens. They are useful for securely storing session tokens.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q114","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["HttpOnly cookies cannot be accessed via JavaScript, preventing XSS attacks from stealing tokens. They are useful for securely storing session tokens."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a19da819-eb57-4253-bd82-4afe003708e8',
          'What is CSRF and how do you prevent it?',
          'Explain Cross-Site Request Forgery and prevention techniques.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'CSRF tricks users into executing actions unknowingly. Prevent it using SameSite cookies, CSRF tokens in forms, and double-submit cookie patterns.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q115","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CSRF tricks users into executing actions unknowingly. Prevent it using SameSite cookies, CSRF tokens in forms, and double-submit cookie patterns."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6d62fdd9-c58b-4a94-8366-74bd358e19d2',
          'What is XSS and how can frontend apps defend against it?',
          'Explain Cross-Site Scripting attacks and mitigation strategies.',
          'multiple-choice',
          'advanced',
          10,
          NULL,
          NULL,
          'XSS injects malicious scripts into webpages. Defenses include escaping user input, using CSP (Content Security Policy), sanitizing HTML, and avoiding `eval`.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q116","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["XSS injects malicious scripts into webpages. Defenses include escaping user input, using CSP (Content Security Policy), sanitizing HTML, and avoiding `eval`."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fbacdb97-1093-420b-880b-43b323a5fa88',
          'What is CORS and why does it matter in frontend apps?',
          'Explain Cross-Origin Resource Sharing and its impact on frontend development.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'CORS defines which domains can access APIs from a frontend app. It prevents malicious websites from making unauthorized requests on behalf of users.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q117","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CORS defines which domains can access APIs from a frontend app. It prevents malicious websites from making unauthorized requests on behalf of users."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2c4910b5-0b33-4138-aea3-f9f5c4dd5599',
          'What is the difference between SameSite=Lax, Strict, and None for cookies?',
          'Explain cookie SameSite attribute options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Strict: cookie only sent for same-site requests","isCorrect":true,"explanation":""},{"id":"o2","text":"Lax: cookie sent for same-site and top-level navigations","isCorrect":true,"explanation":""},{"id":"o3","text":"None: cookie sent in all requests but must be Secure","isCorrect":true,"explanation":""}]',
          NULL,
          'The correct answer is: Strict: cookie only sent for same-site requests',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q118","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5e4c1111-b03f-4948-ac51-e260560b5a13',
          'What are signed URLs and how do they improve security?',
          'Explain signed URLs in the context of serving private assets.',
          'multiple-choice',
          'intermediate',
          10,
          NULL,
          NULL,
          'Signed URLs include a token or signature allowing temporary access to private assets like images or videos. They protect resources without exposing them publicly.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q119","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Signed URLs include a token or signature allowing temporary access to private assets like images or videos. They protect resources without exposing them publicly."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );
INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fa86d89d-b086-4881-b134-8fd561174c4d',
          'How do you implement secure logout in a frontend application?',
          'Explain best practices for logging users out securely.',
          'multiple-choice',
          'beginner',
          10,
          NULL,
          NULL,
          'On logout, clear tokens from memory/storage, invalidate session cookies, revoke refresh tokens server-side, and redirect users to a safe page.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q120","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["On logout, clear tokens from memory/storage, invalidate session cookies, revoke refresh tokens server-side, and redirect users to a safe page."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );