INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0f6b3625-c8b6-42ae-89af-5d8e02d574f9',
          'True or False: DOM-based XSS only occurs on the server side.',
          'Evaluate whether this statement is true or false.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec21","original_type":"true-false","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:21:00.000Z',
          '2025-10-11T00:21:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c36bf45c-48a9-428b-aa25-75eb20e1f6fe',
          'Which practices reduce the risk of XSS in frontend frameworks like React?',
          'Select all that apply.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use React’s JSX variable escaping","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize any HTML before using dangerouslySetInnerHTML","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid inline event handlers","isCorrect":true,"explanation":""},{"id":"o4","text":"Store all sensitive data in localStorage","isCorrect":false,"explanation":""}]',
          NULL,
          'React escapes content by default. Using DOMPurify for dangerouslySetInnerHTML and avoiding inline JS reduces XSS risk. LocalStorage is vulnerable to XSS.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec22","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:22:00.000Z',
          '2025-10-11T00:22:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '63a6eafd-a72f-4bf8-9607-fddee96630ec',
          'What is a Man-in-the-Middle (MITM) attack?',
          'Explain what MITM attacks are and how they affect web communication.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec23","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":["A MITM attack occurs when an attacker intercepts communication between the client and server, potentially reading, modifying, or injecting data without either party noticing."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:23:00.000Z',
          '2025-10-11T00:23:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a2f0c118-f91b-4f11-9606-d2a131b64d16',
          'True or False: Using HTTPS prevents all types of MITM attacks.',
          'Evaluate this statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec24","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:24:00.000Z',
          '2025-10-11T00:24:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fa0a582f-72b9-4f6d-9e93-907aa7d611bb',
          'Which of the following improve web app security against MITM attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Enforce HTTPS and HSTS","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate SSL/TLS certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Use strong encryption algorithms","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on client-side validation","isCorrect":false,"explanation":""}]',
          NULL,
          'Proper HTTPS, certificate validation, and strong crypto protect against MITM; client-side validation alone is not sufficient.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec25","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:25:00.000Z',
          '2025-10-11T00:25:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '50e7a460-3035-4193-83ff-6bf37d0d3ec7',
          'What is the difference between stored and reflected XSS?',
          'Explain the differences between stored (persistent) and reflected (non-persistent) XSS attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-03-sec26","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["Stored XSS saves the malicious script on the server/database and executes when users visit the page. Reflected XSS occurs when the server reflects user input immediately without storing it, often via URL parameters."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:26:00.000Z',
          '2025-10-11T00:26:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '76ad63ba-7568-4a62-92e8-07811c69cfce',
          'What is CSRF (Cross-Site Request Forgery)?',
          'Explain what CSRF attacks are and how they affect web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec27","original_type":"open-ended","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":["CSRF occurs when an attacker tricks a logged-in user into submitting requests on a web application without their knowledge, performing actions like changing passwords or making transactions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:27:00.000Z',
          '2025-10-11T00:27:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '34bc57c1-3faa-4ec6-953d-b0df3d6c0f5c',
          'How can you prevent CSRF attacks?',
          'Select all correct methods to prevent CSRF.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use anti-CSRF tokens in forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookie attributes","isCorrect":true,"explanation":""},{"id":"o3","text":"Disable HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Validate origin and referer headers","isCorrect":true,"explanation":""}]',
          NULL,
          'Anti-CSRF tokens, SameSite cookies, and validating headers are standard defenses; disabling HTTPS weakens security.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec28","original_type":"multiple-choice","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:28:00.000Z',
          '2025-10-11T00:28:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9710fae4-25a9-4427-85b3-5ece7c20e63b',
          'True or False: XSS attacks can be used to bypass CSRF protections.',
          'Evaluate the statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','xss & csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec29","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"XSS & CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:29:00.000Z',
          '2025-10-11T00:29:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '347f2899-ee1c-4d12-bd38-ee63e7f110e8',
          'What is the role of Content Security Policy (CSP) in web security?',
          'Explain how CSP helps protect frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec30","original_type":"open-ended","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":["CSP defines allowed sources for scripts, styles, images, and other resources, mitigating XSS, clickjacking, and data injection by restricting what can be loaded or executed."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:30:00.000Z',
          '2025-10-11T00:30:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'acfac07e-0dfc-4c89-8568-8ec53a13db9b',
          'Select the correct ways to implement CSP.',
          'Choose all that apply.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use meta tag in HTML","isCorrect":true,"explanation":""},{"id":"o2","text":"Set HTTP response headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely solely on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Whitelist only trusted sources","isCorrect":true,"explanation":""}]',
          NULL,
          'CSP works via meta tags or headers, and whitelisting trusted sources restricts malicious content.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec31","original_type":"multiple-choice","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:31:00.000Z',
          '2025-10-11T00:31:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1bfbd399-4a8e-4197-9fce-c38ede1922c6',
          'What is the Same-Origin Policy (SOP) and why is it important?',
          'Explain SOP and its significance in web security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','sop','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec32","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"SOP","sample_answers":["SOP is a browser security feature that restricts scripts on one origin from accessing data from another origin, protecting sensitive data from unauthorized access."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:32:00.000Z',
          '2025-10-11T00:32:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '819d6142-a677-428b-a341-f544c92d6332',
          'True or False: Cross-Origin Resource Sharing (CORS) overrides the Same-Origin Policy.',
          'Evaluate this statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','cross-origin-resource-sharing-cors','cors','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec33","original_type":"true-false","topic":"Cross-Origin Resource Sharing (CORS)","subcategory":"CORS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:33:00.000Z',
          '2025-10-11T00:33:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '757fc5f9-95fd-4e15-9eab-c01dfae8b6d1',
          'Which practices improve frontend security regarding cookies?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Set HttpOnly flag","isCorrect":true,"explanation":""},{"id":"o2","text":"Set Secure flag for HTTPS","isCorrect":true,"explanation":""},{"id":"o3","text":"Use SameSite attribute","isCorrect":true,"explanation":""},{"id":"o4","text":"Store passwords directly in cookies","isCorrect":false,"explanation":""}]',
          NULL,
          'HttpOnly, Secure, and SameSite protect cookies from XSS, MITM, and CSRF. Storing passwords in cookies is insecure.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-04-sec34","original_type":"multiple-choice","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:34:00.000Z',
          '2025-10-11T00:34:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cf08abd3-751b-498c-a32b-9519936a05a1',
          'What is Clickjacking (UI Redressing)?',
          'Explain how clickjacking works and its impact on users.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec35","original_type":"open-ended","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":["Clickjacking tricks users into clicking hidden or disguised UI elements, performing unintended actions such as changing settings, submitting forms, or executing transactions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:35:00.000Z',
          '2025-10-11T00:35:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '89dc81b0-d03c-41b0-bc12-f6c55da7ecb2',
          'How can you prevent Clickjacking attacks?',
          'Select all correct mitigation strategies.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use X-Frame-Options header","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Obfuscate your buttons with CSS","isCorrect":false,"explanation":""},{"id":"o4","text":"Require user confirmation for critical actions","isCorrect":true,"explanation":""}]',
          NULL,
          'X-Frame-Options and CSP frame-ancestors prevent your site from being framed; additional user confirmation mitigates risk. CSS obfuscation is not a reliable defense.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec36","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:36:00.000Z',
          '2025-10-11T00:36:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6c9332b2-d031-43f9-b691-183c8f88dcf0',
          'What is MITM (Man-in-the-Middle) attack?',
          'Describe MITM attacks and their impact on frontend web security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec37","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":["MITM attacks intercept communication between a client and server, potentially stealing sensitive data like passwords, session tokens, or credit card info. It often occurs on unsecured networks or via malicious proxies."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:37:00.000Z',
          '2025-10-11T00:37:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9ee46dc2-2807-439d-9d31-172ded6d98bd',
          'How can HTTPS prevent MITM attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Encrypts traffic between client and server","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevents tampering of data in transit","isCorrect":true,"explanation":""},{"id":"o3","text":"Automatically detects phishing websites","isCorrect":false,"explanation":""},{"id":"o4","text":"Ensures integrity via TLS certificates","isCorrect":true,"explanation":""}]',
          NULL,
          'HTTPS (TLS) encrypts data, ensures integrity, and authenticates the server. It does not automatically detect phishing sites.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec38","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:38:00.000Z',
          '2025-10-11T00:38:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'dcbe2c96-4cc9-4b7d-860e-f50f0c9a201c',
          'What is the difference between Reflected, Stored, and DOM-based XSS?',
          'Explain the three main types of XSS attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec39","original_type":"open-ended","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":["Reflected XSS: Malicious input is reflected immediately in a response. Stored XSS: Malicious input is stored in the server (DB) and executed for all users. DOM-based XSS: Payload executes by manipulating the DOM on the client side."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:39:00.000Z',
          '2025-10-11T00:39:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5f65ea91-5cfb-4927-8d6c-22852f30a6f5',
          'Which of the following is the most dangerous type of XSS?',
          'Select the correct answer.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"DOM-based XSS","isCorrect":false,"explanation":""},{"id":"o2","text":"Reflected XSS","isCorrect":false,"explanation":""},{"id":"o3","text":"Stored XSS","isCorrect":true,"explanation":""},{"id":"o4","text":"All are equally dangerous","isCorrect":false,"explanation":""}]',
          NULL,
          'Stored XSS is persistent and can affect all users who visit the page, making it the most dangerous.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec40","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:40:00.000Z',
          '2025-10-11T00:40:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '330bef1c-9871-4295-8787-e2343350aeef',
          'What are common mitigation strategies against XSS?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Input validation and sanitization","isCorrect":true,"explanation":""},{"id":"o2","text":"Using HttpOnly cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Avoid inline scripts and use external scripts","isCorrect":true,"explanation":""},{"id":"o4","text":"Use eval() to encode input","isCorrect":false,"explanation":""}]',
          NULL,
          'Validating/sanitizing inputs, HttpOnly cookies, and avoiding inline scripts help prevent XSS. Using eval() is unsafe.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec41","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:41:00.000Z',
          '2025-10-11T00:41:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'defe0640-6797-449d-8963-8d51562f6781',
          'True or False: Using HTTPS alone fully protects against XSS attacks.',
          'Evaluate this statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-05-sec42","original_type":"true-false","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:42:00.000Z',
          '2025-10-11T00:42:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0a73004c-dcb6-4f6e-ac06-7d79298bd1e3',
          'What is CSRF (Cross-Site Request Forgery)?',
          'Explain how CSRF attacks work and why they are dangerous.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec43","original_type":"open-ended","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":["CSRF tricks a logged-in user’s browser into making unwanted requests to a web application, potentially changing account settings, making purchases, or performing administrative actions without the user''s consent."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:43:00.000Z',
          '2025-10-11T00:43:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '390b84ef-175b-46c0-8bca-5266af3d93a6',
          'How can you prevent CSRF attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use CSRF tokens in forms and API requests","isCorrect":true,"explanation":""},{"id":"o2","text":"Use SameSite cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Validate the origin or referer header","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on HTTPS","isCorrect":false,"explanation":""}]',
          NULL,
          'CSRF tokens, SameSite cookies, and header validation prevent CSRF. HTTPS alone does not protect against CSRF.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec44","original_type":"multiple-choice","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:44:00.000Z',
          '2025-10-11T00:44:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '55f6c56d-e322-49a0-9b01-8b967501e45d',
          'What are security headers and why are they important?',
          'Explain common security headers and their role in protecting frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security.',
          NULL,
          [],
          ARRAY['security','security-headers','headers','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec45","original_type":"open-ended","topic":"Security Headers","subcategory":"Headers","sample_answers":["Security headers protect users from XSS, clickjacking, and other attacks. Examples include Content-Security-Policy, X-Frame-Options, X-XSS-Protection, and Strict-Transport-Security."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:45:00.000Z',
          '2025-10-11T00:45:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8bccfc9c-46cd-44e7-947c-986c7bab7602',
          'Which HTTP header helps prevent Clickjacking?',
          'Select the correct answer.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"X-Frame-Options","isCorrect":true,"explanation":""},{"id":"o2","text":"Content-Security-Policy","isCorrect":false,"explanation":""},{"id":"o3","text":"Strict-Transport-Security","isCorrect":false,"explanation":""},{"id":"o4","text":"X-Content-Type-Options","isCorrect":false,"explanation":""}]',
          NULL,
          'The X-Frame-Options header prevents your site from being embedded in iframes, mitigating clickjacking.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec46","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:46:00.000Z',
          '2025-10-11T00:46:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4d8cfc0f-302c-4dd3-8b61-4f555c25373b',
          'What is the Content Security Policy (CSP) header?',
          'Explain how CSP helps prevent XSS and other attacks.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec47","original_type":"open-ended","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":["CSP allows developers to define which sources of scripts, images, and other resources are trusted. It blocks inline scripts and unauthorized domains, reducing the risk of XSS, clickjacking, and data injection attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:47:00.000Z',
          '2025-10-11T00:47:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7e081cf0-1ce8-4012-a54e-9fce3c25ee2a',
          'True or False: Using HttpOnly and Secure flags on cookies protects against XSS and MITM attacks.',
          'Evaluate the statement.',
          'true-false',
          'intermediate',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: True',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec48","original_type":"true-false","topic":"Session Management","subcategory":"Cookies","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:48:00.000Z',
          '2025-10-11T00:48:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b126e69c-3785-48bf-9412-bd9aa0c6bef7',
          'What is input validation and why is it important for security?',
          'Explain the role of input validation in preventing attacks like XSS and SQL Injection.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks.',
          NULL,
          [],
          ARRAY['security','input-validation-&-sanitization','input validation','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec49","original_type":"open-ended","topic":"Input Validation & Sanitization","subcategory":"Input Validation","sample_answers":["Input validation ensures that user-supplied data matches expected formats and content. It prevents malicious scripts or commands from being injected, mitigating XSS, SQL Injection, and other attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:49:00.000Z',
          '2025-10-11T00:49:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '936c91a7-3744-47cc-8efe-61f54ba14ef9',
          'Which is safer for sensitive data transmission: HTTP or HTTPS?',
          'Select the correct answer.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"HTTP","isCorrect":false,"explanation":""},{"id":"o2","text":"HTTPS","isCorrect":true,"explanation":""},{"id":"o3","text":"Both are equally safe","isCorrect":false,"explanation":""},{"id":"o4","text":"Depends on browser","isCorrect":false,"explanation":""}]',
          NULL,
          'HTTPS encrypts data in transit, ensuring confidentiality, integrity, and protection against MITM attacks, unlike HTTP.',
          NULL,
          [],
          ARRAY['security','https-&-ssl/tls','transport security','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-06-sec50","original_type":"multiple-choice","topic":"HTTPS & SSL/TLS","subcategory":"Transport Security","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:50:00.000Z',
          '2025-10-11T00:50:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e3bf5941-097c-4a13-a74a-d15a3f55f512',
          'What is a Man-in-the-Middle (MITM) attack?',
          'Explain how MITM attacks work and their potential impact on web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec51","original_type":"open-ended","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":["In a MITM attack, an attacker intercepts communication between a client and server, potentially stealing sensitive data like passwords, cookies, or session tokens, or modifying the communication without the user''s knowledge."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:51:00.000Z',
          '2025-10-11T00:51:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '20a059ac-0ed3-46fe-974c-637cfbeb3ce1',
          'How can HTTPS prevent MITM attacks?',
          'Select all correct options.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Encrypts data between client and server","isCorrect":true,"explanation":""},{"id":"o2","text":"Validates server identity using certificates","isCorrect":true,"explanation":""},{"id":"o3","text":"Blocks phishing emails automatically","isCorrect":false,"explanation":""},{"id":"o4","text":"Prevents cookie theft if Secure flag is set","isCorrect":true,"explanation":""}]',
          NULL,
          'HTTPS encrypts communication, validates the server''s certificate, and combined with Secure cookies, helps prevent MITM attacks.',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','mitm','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec52","original_type":"multiple-choice","topic":"Web Security Fundamentals","subcategory":"MITM","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:52:00.000Z',
          '2025-10-11T00:52:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '32d5354f-c6a7-437f-99b3-dad98e1bd11f',
          'What is CORS (Cross-Origin Resource Sharing)?',
          'Explain CORS and its role in web security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access.',
          NULL,
          [],
          ARRAY['security','cross-origin-resource-sharing-cors','cors','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec53","original_type":"open-ended","topic":"Cross-Origin Resource Sharing (CORS)","subcategory":"CORS","sample_answers":["CORS is a security feature implemented by browsers to restrict web pages from making requests to a different domain than the one that served the web page. Proper CORS headers allow safe cross-origin requests while preventing unauthorized access."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:53:00.000Z',
          '2025-10-11T00:53:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9109e38b-e215-44b3-a61b-04882a433be4',
          'How can you safely allow cross-origin requests?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Set Access-Control-Allow-Origin to a specific trusted domain","isCorrect":true,"explanation":""},{"id":"o2","text":"Use credentials (cookies) only when necessary","isCorrect":true,"explanation":""},{"id":"o3","text":"Set Access-Control-Allow-Origin to ''*''","isCorrect":false,"explanation":""},{"id":"o4","text":"Use server-side proxy to handle requests","isCorrect":true,"explanation":""}]',
          NULL,
          'Allow only trusted domains, use credentials carefully, and proxy requests server-side to control access. Using ''*'' allows any domain and is unsafe for sensitive data.',
          NULL,
          [],
          ARRAY['security','cross-origin-resource-sharing-cors','cors','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec54","original_type":"multiple-choice","topic":"Cross-Origin Resource Sharing (CORS)","subcategory":"CORS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:54:00.000Z',
          '2025-10-11T00:54:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1f4addbf-a9a5-49b6-be7b-664fd9aba2a6',
          'What is rate limiting and why is it important?',
          'Explain how rate limiting protects web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks.',
          NULL,
          [],
          ARRAY['security','api-security','rate limiting','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec55","original_type":"open-ended","topic":"API Security","subcategory":"Rate Limiting","sample_answers":["Rate limiting restricts the number of requests a client can make in a given time period, protecting the server from abuse, brute-force attacks, and denial-of-service attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:55:00.000Z',
          '2025-10-11T00:55:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2032a69b-a729-4b38-8319-495135d0440a',
          'True or False: All third-party libraries are safe by default.',
          'Evaluate the statement in terms of frontend security.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The correct answer is: False',
          NULL,
          [],
          ARRAY['security','web-security-fundamentals','third-party security','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec56","original_type":"true-false","topic":"Web Security Fundamentals","subcategory":"Third-Party Security","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:56:00.000Z',
          '2025-10-11T00:56:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a517f804-a021-4acc-a82f-31416130cd94',
          'What is JWT and how does it help with security?',
          'Explain JWT (JSON Web Token) and its use in authentication.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication.',
          NULL,
          [],
          ARRAY['security','authentication-&-authorization','authentication','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec57","original_type":"open-ended","topic":"Authentication & Authorization","subcategory":"Authentication","sample_answers":["JWT is a compact token used to securely transmit information between client and server. It ensures authenticity and integrity of the payload, commonly used for stateless authentication."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:57:00.000Z',
          '2025-10-11T00:57:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0822aaea-616d-4ed0-a31a-4df4b197a8a5',
          'How can you prevent XSS when displaying user-generated content?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Escape HTML before rendering","isCorrect":true,"explanation":""},{"id":"o2","text":"Sanitize input using libraries like DOMPurify","isCorrect":true,"explanation":""},{"id":"o3","text":"Use dangerouslySetInnerHTML without sanitization","isCorrect":false,"explanation":""},{"id":"o4","text":"Implement Content Security Policy (CSP)","isCorrect":true,"explanation":""}]',
          NULL,
          'Escape and sanitize user content, and enforce CSP. Avoid unsanitized dangerouslySetInnerHTML as it introduces XSS vulnerabilities.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec58","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:58:00.000Z',
          '2025-10-11T00:58:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'af6cf28d-c353-41b2-8e2d-cbccd8d440e2',
          'What is UI Redressing (Clickjacking)?',
          'Explain how clickjacking attacks manipulate user interface elements.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec59","original_type":"open-ended","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":["Clickjacking occurs when attackers overlay a transparent or disguised element over a legitimate UI element, tricking users into clicking it and performing unintended actions like submitting forms or changing settings."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T00:59:00.000Z',
          '2025-10-11T00:59:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c171f1db-0dfb-4ba7-a3a8-85e6e5b72b2d',
          'How do you prevent clickjacking attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use X-Frame-Options header to deny framing","isCorrect":true,"explanation":""},{"id":"o2","text":"Use Content Security Policy frame-ancestors directive","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely only on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Implement UI overlays as security measure","isCorrect":false,"explanation":""}]',
          NULL,
          'X-Frame-Options and CSP frame-ancestors prevent your site from being embedded in iframes, mitigating clickjacking attacks.',
          NULL,
          [],
          ARRAY['security','clickjacking','clickjacking','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-07-sec60","original_type":"multiple-choice","topic":"Clickjacking","subcategory":"Clickjacking","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:00:00.000Z',
          '2025-10-11T01:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '50ecf21e-994d-43c0-899d-b3f31b37c98e',
          'What is CSRF (Cross-Site Request Forgery)?',
          'Explain how CSRF attacks work and why they are dangerous.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec61","original_type":"open-ended","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":["CSRF attacks trick a user’s browser into making unwanted requests to a web application where they are authenticated. This can lead to unauthorized actions like changing account details, making purchases, or deleting content."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:01:00.000Z',
          '2025-10-11T01:01:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '863da1b7-2d18-4b28-a33a-bb020a79772d',
          'How can you prevent CSRF attacks?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use CSRF tokens for forms","isCorrect":true,"explanation":""},{"id":"o2","text":"Validate Origin and Referer headers","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely only on HTTPS","isCorrect":false,"explanation":""},{"id":"o4","text":"Use SameSite attribute on cookies","isCorrect":true,"explanation":""}]',
          NULL,
          'CSRF tokens, checking Origin/Referer, and setting cookies as SameSite help prevent CSRF attacks. HTTPS alone does not prevent CSRF.',
          NULL,
          [],
          ARRAY['security','cross-site-request-forgery-csrf','csrf','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec62","original_type":"multiple-choice","topic":"Cross-Site Request Forgery (CSRF)","subcategory":"CSRF","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:02:00.000Z',
          '2025-10-11T01:02:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '793fb0e3-1dee-4719-bb1f-e2024da03873',
          'What is the purpose of the SameSite cookie attribute?',
          'Explain how SameSite helps with web security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec63","original_type":"open-ended","topic":"Session Management","subcategory":"Cookies","sample_answers":["The SameSite attribute restricts how cookies are sent with cross-site requests. ''Strict'' blocks all cross-site cookie usage, ''Lax'' allows certain safe methods, helping prevent CSRF attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:03:00.000Z',
          '2025-10-11T01:03:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6e5b9e0a-74ee-4f7a-8211-84df53cba9eb',
          'What is token expiration and why is it important?',
          'Explain token expiration in authentication and session management.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period.',
          NULL,
          [],
          ARRAY['security','authentication-&-authorization','authentication','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec64","original_type":"open-ended","topic":"Authentication & Authorization","subcategory":"Authentication","sample_answers":["Token expiration limits how long an authentication token is valid. This reduces risk if a token is leaked or stolen and forces users to re-authenticate after a set period."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:04:00.000Z',
          '2025-10-11T01:04:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '616ab1a2-4805-4391-a056-af65bc7cfd5e',
          'How can you secure API endpoints in a frontend application?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use authentication tokens like JWT","isCorrect":true,"explanation":""},{"id":"o2","text":"Enforce HTTPS for all API requests","isCorrect":true,"explanation":""},{"id":"o3","text":"Validate all user inputs on the server","isCorrect":true,"explanation":""},{"id":"o4","text":"Rely only on client-side checks","isCorrect":false,"explanation":""}]',
          NULL,
          'Server-side validation, HTTPS, and token-based authentication are essential. Client-side checks alone cannot ensure security.',
          NULL,
          [],
          ARRAY['security','api-security','api security','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec65","original_type":"multiple-choice","topic":"API Security","subcategory":"API Security","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:05:00.000Z',
          '2025-10-11T01:05:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9612f921-118a-460b-99db-d5dc5e77e1a0',
          'What is OAuth 2.0?',
          'Explain OAuth 2.0 and its use in web applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration.',
          NULL,
          [],
          ARRAY['security','authentication-&-authorization','authentication','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec66","original_type":"open-ended","topic":"Authentication & Authorization","subcategory":"Authentication","sample_answers":["OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. It issues tokens with limited scope and duration."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:06:00.000Z',
          '2025-10-11T01:06:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'fd89745c-34e2-4bc8-a279-76ab60c9229e',
          'How does a Content Security Policy (CSP) improve security?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Restrict sources of scripts, styles, and media","isCorrect":true,"explanation":""},{"id":"o2","text":"Prevent inline script execution","isCorrect":true,"explanation":""},{"id":"o3","text":"Encrypt cookies automatically","isCorrect":false,"explanation":""},{"id":"o4","text":"Mitigate XSS attacks","isCorrect":true,"explanation":""}]',
          NULL,
          'CSP controls which sources are allowed for scripts and styles, blocks inline scripts, and helps mitigate XSS attacks. It does not encrypt cookies.',
          NULL,
          [],
          ARRAY['security','content-security-policy-csp','csp','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec67","original_type":"multiple-choice","topic":"Content Security Policy (CSP)","subcategory":"CSP","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:07:00.000Z',
          '2025-10-11T01:07:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '01caf750-83e0-42ca-a343-2c2de81317f3',
          'What is the purpose of HttpOnly cookies?',
          'Explain how HttpOnly cookies improve security.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks.',
          NULL,
          [],
          ARRAY['security','session-management','cookies','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec68","original_type":"open-ended","topic":"Session Management","subcategory":"Cookies","sample_answers":["HttpOnly cookies cannot be accessed via JavaScript in the browser, reducing the risk of session theft through XSS attacks."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:08:00.000Z',
          '2025-10-11T01:08:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '608aa85f-9328-4cd0-a71b-e15164ea7074',
          'What is the difference between stored and reflected XSS?',
          'Select the correct statements.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Stored XSS persists in the database and affects multiple users","isCorrect":true,"explanation":""},{"id":"o2","text":"Reflected XSS occurs immediately and is non-persistent","isCorrect":true,"explanation":""},{"id":"o3","text":"Reflected XSS stores payload in server database","isCorrect":false,"explanation":""},{"id":"o4","text":"Stored XSS is less dangerous than reflected XSS","isCorrect":false,"explanation":""}]',
          NULL,
          'Stored XSS is persistent and affects all users viewing the content; reflected XSS is immediate, targeting a single user through crafted requests.',
          NULL,
          [],
          ARRAY['security','cross-site-scripting-xss','xss','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec69","original_type":"multiple-choice","topic":"Cross-Site Scripting (XSS)","subcategory":"XSS","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:09:00.000Z',
          '2025-10-11T01:09:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd9e3587c-b121-4b27-a7b8-1ee35220c9c2',
          'What are the best practices for session management in frontend apps?',
          'Select all correct options.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Use short-lived tokens and refresh them securely","isCorrect":true,"explanation":""},{"id":"o2","text":"Store tokens in memory or HttpOnly cookies","isCorrect":true,"explanation":""},{"id":"o3","text":"Rely solely on localStorage for tokens","isCorrect":false,"explanation":""},{"id":"o4","text":"Invalidate sessions on logout and after inactivity","isCorrect":true,"explanation":""}]',
          NULL,
          'Use secure storage, short-lived tokens, refresh tokens carefully, and invalidate sessions properly. Avoid storing sensitive tokens in localStorage due to XSS risk.',
          NULL,
          [],
          ARRAY['security','session-management','session management','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"sec-08-sec70","original_type":"multiple-choice","topic":"Session Management","subcategory":"Session Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"Security"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-11T01:10:00.000Z',
          '2025-10-11T01:10:00.000Z'
        );;