INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '81015bc0-8e7b-4505-a057-c6756e1a1a49',
          'Do browsers understand JSX code?',
          'No. JSX must be transpiled to `React.createElement()` calls using Babel or similar tools.',
          'true-false',
          'beginner',
          3,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'Browsers only understand standard JavaScript; JSX is syntactic sugar transformed at build time.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','jsx','babel','transpilation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q225","original_type":"true-false","topic":"JSX","subcategory":"JSX","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '69a49016-b865-486d-903a-f861c1262960',
          'Describe data flow in React?',
          'React uses one-way data flow: data flows down from parent to child via props, making the data flow predictable and easier to debug.',
          'multiple-choice',
          'beginner',
          4,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Parents pass data to children via props; children communicate back via callback functions.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','props','one-way-data-flow','architecture']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q226","original_type":"open-ended","topic":"Data Flow","subcategory":"React Basics","sample_answers":["Data flows unidirectionally: parent components pass data to children via props, and children trigger updates by calling parent-provided callbacks.","This contrasts with two-way binding (e.g., AngularJS), where child changes automatically update parent state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5fddcf8a-4be2-4da4-b1f9-1961481e9783',
          'What is MobX?',
          'MobX is a state management library that uses observable state and reactive programming to automatically update UI when state changes.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It tracks which components depend on which state and re-renders them automatically when that state changes.',
          NULL,
          ARRAY[]::text[],
          ARRAY['mobx','state-management','react','observable']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q227","original_type":"open-ended","topic":"MobX","subcategory":"State Management","sample_answers":["MobX makes state observable and automatically re-renders components that use that state—no need for explicit selectors or reducers.","It’s often described as ''transparent reactivity''—you mutate state directly, and the UI updates magically."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '349106f2-54f9-4c7e-a06a-ff71b6ddfbf7',
          'What are the differences between Redux and MobX?',
          'Redux: single store, immutable, explicit updates. MobX: multiple stores, mutable, automatic updates via observables.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Redux uses observables; MobX uses reducers","isCorrect":false},{"id":"b","text":"Redux: single immutable store, explicit; MobX: multiple mutable stores, automatic","isCorrect":true},{"id":"c","text":"They are identical","isCorrect":false},{"id":"d","text":"MobX requires more boilerplate","isCorrect":false}]',
          NULL,
          'Redux is explicit and predictable; MobX is implicit and automatic. Redux scales better for large teams; MobX is simpler for small apps.',
          NULL,
          ARRAY[]::text[],
          ARRAY['redux','mobx','comparison','state-management']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q228","original_type":"multiple-choice","topic":"Redux vs MobX","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3b7c1d01-6f33-46cf-97d7-7cf849b55de2',
          'Should I learn ES6 before learning ReactJS?',
          'Not required, but helpful. React ecosystem heavily uses ES6 features like destructuring, spread operator, and arrow functions.',
          'true-false',
          'beginner',
          4,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'You can learn React without ES6, but most tutorials and codebases assume ES6 knowledge.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','es6','javascript','learning']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q229","original_type":"true-false","topic":"JavaScript Fundamentals","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b5969060-28d5-43dd-9743-71402a54f9ba',
          'What is Concurrent Rendering?',
          'Concurrent Rendering allows React to interrupt long renders to handle high-priority updates (e.g., user input), improving responsiveness.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It enables interruptible rendering, so the UI stays responsive during heavy updates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','concurrent','rendering','suspense']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q230","original_type":"open-ended","topic":"Concurrent Rendering","subcategory":"Concurrent React","sample_answers":["Concurrent Rendering lets React pause and resume work based on priority—e.g., user clicks are handled before finishing a low-priority background render.","It’s the foundation for features like Suspense and automatic batching."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd41949f7-b3fc-4e3c-8ae0-52dd16e7d47c',
          'What is the difference between async mode and concurrent mode?',
          'They are the same. ''Async Mode'' was the old name; ''Concurrent Mode'' is the current name to emphasize priority-based rendering.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The name changed to avoid confusion with other async patterns and to highlight the priority-based scheduling.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','concurrent-mode','async-mode','history']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q231","original_type":"true-false","topic":"Concurrent Rendering","subcategory":"Concurrent React","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '02f3a143-1a9e-4019-9ffa-4af7e627a68b',
          'Can I use javascript URLs in React 16.9?',
          'Yes, but it logs a warning because `javascript:` URLs are a security risk (XSS). Future versions will throw an error.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'React warns against `javascript:` URLs to prevent accidental injection of malicious code.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','security','xss','javascript-urls']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q232","original_type":"true-false","topic":"XSS Prevention","subcategory":"XSS (Cross-Site Scripting)","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8862ea4e-b6f3-4a43-bdaa-5f4f35641748',
          'What is the purpose of ESLint plugin for hooks?',
          'It enforces the Rules of Hooks: (1) call hooks at top level, (2) call hooks only from React functions.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The plugin prevents bugs by ensuring hooks are called consistently across renders.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','hooks','eslint','linting']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q233","original_type":"open-ended","topic":"Rules of Hooks","subcategory":"React Hooks","sample_answers":["The `eslint-plugin-react-hooks` enforces that hooks are called in the same order every render and only from function components or custom hooks.","It also includes `exhaustive-deps` to validate effect dependencies."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4f2648b0-e149-4af5-b9d6-03de0f79edbf',
          'What is the difference between Imperative and Declarative in React?',
          'Imperative: how to do it (step-by-step DOM manipulation). Declarative: what the UI should look like (describe state, React handles updates).',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React is declarative: you describe the UI for a given state, and React handles the DOM updates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','declarative','imperative','paradigm']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q234","original_type":"open-ended","topic":"Declarative UI","subcategory":"React Basics","sample_answers":["Imperative: ''If liked, remove grey class and add blue class.'' Declarative: ''If liked, render <BlueLike />; else render <GreyLike />.''","Declarative code is easier to reason about because it separates ''what'' from ''how''."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1fb6ae39-313d-44c6-b244-e7f28ba9d249',
          'What are the benefits of using TypeScript with ReactJS?',
          'Benefits: type safety, better IDE support, easier refactoring, interfaces for props/state, and fewer runtime errors.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Slower development","isCorrect":false},{"id":"b","text":"Type safety, IDE support, fewer bugs, better refactoring","isCorrect":true},{"id":"c","text":"Only for backend","isCorrect":false},{"id":"d","text":"Increases bundle size significantly","isCorrect":false}]',
          NULL,
          'TypeScript catches errors at compile time and provides excellent autocomplete and navigation in editors like VS Code.',
          NULL,
          ARRAY[]::text[],
          ARRAY['typescript','react','types','ide']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q235","original_type":"multiple-choice","topic":"TypeScript with React","subcategory":"TypeScript with React","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1afb9a9a-bd68-42a8-8e1b-53050fb0d595',
          'How to keep user authenticated on page refresh with Context API?',
          'Call `loadUser()` in `useEffect` in App.js, ensuring the AuthProvider wraps the entire app in index.js to persist auth state across refreshes.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'On page load, check for a token in storage and validate it to restore the user session.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','context-api','authentication','persistence']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q236","original_type":"open-ended","topic":"Context API","subcategory":"Authentication","sample_answers":["Wrap your app in an AuthProvider in index.js. In App.js, use `useEffect` to call `loadUser()`, which checks localStorage/sessionStorage for a token and validates it with the backend.","This ensures the user remains logged in after refresh, similar to how Redux would handle it with a root-level dispatch."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b885407b-907a-4dd9-8ffb-ebac1bd8707b',
          'What are the benefits of new JSX transform?',
          'Benefits: (1) no need to import React, (2) slightly smaller bundles, (3) simpler mental model for beginners.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Requires explicit React import","isCorrect":false},{"id":"b","text":"No React import needed, smaller bundles, simpler learning","isCorrect":true},{"id":"c","text":"Only works with class components","isCorrect":false},{"id":"d","text":"Increases bundle size","isCorrect":false}]',
          NULL,
          'The new transform compiles JSX to `_jsx()` calls from `react/jsx-runtime`, removing the need for React in scope.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','jsx','transform','babel']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q237","original_type":"multiple-choice","topic":"JSX","subcategory":"JSX","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '099c0782-cf17-407a-b30d-d4fe1add941e',
          'How is the new JSX transform different from old transform?',
          'Old: compiles to `React.createElement()`, requires `import React`. New: compiles to `_jsx()` from `react/jsx-runtime`, no React import needed.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The new transform reduces boilerplate and bundle size by using a dedicated runtime.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','jsx','babel','compilation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q238","original_type":"open-ended","topic":"JSX","subcategory":"JSX","sample_answers":["Old: `import React from ''react'';` and `<div />` → `React.createElement(''div'')`. New: no import needed; `<div />` → `_jsx(''div'', {})`.","You still need to import React to use Hooks, but not for JSX alone."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd44648e2-016d-401b-a3c0-93be940a6c43',
          'What are React Server Components?',
          'React Server Components render on the server, allowing direct data fetching and reducing client bundle size. Still experimental.',
          'multiple-choice',
          'advanced',
          9,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'They enable zero-bundle-size components that run only on the server, with automatic client hydration for interactivity.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','server-components','rsc','nextjs']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q239","original_type":"open-ended","topic":"React Server Components","subcategory":"React Server Components","sample_answers":["React Server Components run on the server, can access databases directly, and send only JSON to the client—reducing JavaScript bundle size.","They’re a key part of Next.js App Router and the future of React full-stack architecture."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5887f619-37e9-4cce-b96e-678c6eeace9c',
          'What is prop drilling?',
          'Prop drilling is passing data through multiple levels of components that don’t need it, just to get it to a deeply nested child.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It makes components tightly coupled and hard to refactor. Solutions: Context API or state management libraries.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','prop-drilling','context','anti-pattern']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q240","original_type":"open-ended","topic":"Props","subcategory":"React Basics","sample_answers":["Prop drilling occurs when you pass a prop through many intermediate components that don’t use it, just to reach a deep child.","This creates unnecessary dependencies. Use Context or Redux to avoid it."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c7a525dc-8096-4412-a1e0-458028ba0587',
          'What is the difference between useState and useRef hook?',
          '`useState` triggers re-renders on update; `useRef` holds a mutable value without causing re-renders.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Both cause re-renders","isCorrect":false},{"id":"b","text":"useState causes re-renders; useRef does not","isCorrect":true},{"id":"c","text":"useRef is only for DOM elements","isCorrect":false},{"id":"d","text":"useState cannot hold objects","isCorrect":false}]',
          NULL,
          '`useRef` is for persisting values across renders without triggering updates—ideal for timers, intervals, or DOM references.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','hooks','usestate','useref']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q241","original_type":"multiple-choice","topic":"useState vs useRef","subcategory":"React Hooks","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6ce90561-89f2-4283-8fe1-cfd646ef7e71',
          'What is a wrapper component?',
          'A wrapper component surrounds other components to add functionality, styling, or layout without modifying the wrapped components.',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It’s a form of composition that promotes reuse and separation of concerns.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','wrapper','hoc','composition']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q242","original_type":"open-ended","topic":"Component Composition","subcategory":"React Basics","sample_answers":["A wrapper component adds behavior or UI around children—e.g., a `Card` component that adds padding and a border.","Example: `<AuthWrapper><Profile /></AuthWrapper>` could check authentication before rendering the child."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '24260021-e13f-40b0-ac18-f597d9918774',
          'What are the differences between useEffect and useLayoutEffect?',
          '`useEffect` runs after browser paint; `useLayoutEffect` runs synchronously before paint, avoiding visual flicker for layout measurements.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"useEffect runs before paint; useLayoutEffect after","isCorrect":false},{"id":"b","text":"useEffect runs after paint; useLayoutEffect runs before paint synchronously","isCorrect":true},{"id":"c","text":"They are identical","isCorrect":false},{"id":"d","text":"useLayoutEffect is deprecated","isCorrect":false}]',
          NULL,
          'Use `useLayoutEffect` only when you need to measure or adjust layout before the user sees it.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','useeffect','uselayouteffect','performance']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q243","original_type":"multiple-choice","topic":"useLayoutEffect","subcategory":"React Hooks","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '79dea21a-c6a1-4e45-82f5-269259ab8514',
          'What are the differences between Functional and Class Components?',
          'Functional: simpler syntax, use Hooks for state/effects. Class: use lifecycle methods, `this.state`, and `this.props`. Both can use state and props now.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Functional components can''t use state","isCorrect":false},{"id":"b","text":"Functional use Hooks; Class use lifecycle methods and this","isCorrect":true},{"id":"c","text":"Class components are faster","isCorrect":false},{"id":"d","text":"Functional components can''t receive props","isCorrect":false}]',
          NULL,
          'With Hooks, functional components can do everything class components can, with less boilerplate.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','functional-components','class-components','hooks']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q244","original_type":"multiple-choice","topic":"Component Types","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ae4da5d2-8c6b-4e15-b316-c8ced035032a',
          'What is strict mode in React?',
          '`React.StrictMode` enables additional development-only checks for potential problems like unsafe lifecycles, legacy APIs, and side effects.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It helps catch bugs early by identifying unsafe patterns and legacy code.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','strict-mode','development','warnings']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q245","original_type":"open-ended","topic":"Strict Mode","subcategory":"React Basics","sample_answers":["`StrictMode` is a development tool that warns about deprecated APIs, unsafe lifecycle methods, and side effects in render.","It only runs in development and has no effect in production builds."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a0d4f5ff-212b-422a-b0f3-6bf47cadf151',
          'What is the benefit of strict mode?',
          'Benefits: detects impure renders, missing effect cleanup, unsafe lifecycles, legacy refs/context, and findDOMNode usage.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Improves production performance","isCorrect":false},{"id":"b","text":"Detects side effects, unsafe lifecycles, legacy APIs, and missing cleanup","isCorrect":true},{"id":"c","text":"Reduces bundle size","isCorrect":false},{"id":"d","text":"Only for class components","isCorrect":false}]',
          NULL,
          'It prepares your code for future React features like concurrent rendering by enforcing purity.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','strict-mode','debugging','best-practices']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q246","original_type":"multiple-choice","topic":"Strict Mode","subcategory":"React Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '390e530f-dbd6-4e35-ab83-63919bea51ef',
          'Why does strict mode render twice in React?',
          'In development, StrictMode renders components twice to detect accidental side effects in the render phase by exposing non-idempotent code.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'This double-invocation helps ensure components are pure and safe for concurrent features.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','strict-mode','side-effects','development']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q247","original_type":"open-ended","topic":"Strict Mode","subcategory":"React Basics","sample_answers":["StrictMode calls render and effect functions twice in development to reveal side effects that rely on single execution.","This prepares apps for concurrent rendering, where React may interrupt or re-run renders."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3c11b46c-ab86-44e0-9131-4a6d1d7c5713',
          'What are the rules of JSX?',
          'Rules: (1) return single root element, (2) all tags must be closed, (3) use camelCase for attributes (e.g., `className`).',
          'multiple-choice',
          'beginner',
          5,
          '[{"id":"a","text":"Tags don''t need to be closed","isCorrect":false},{"id":"b","text":"Single root, closed tags, camelCase attributes","isCorrect":true},{"id":"c","text":"Use class instead of className","isCorrect":false},{"id":"d","text":"Multiple roots are allowed","isCorrect":false}]',
          NULL,
          'These rules ensure JSX can be reliably transformed to JavaScript function calls.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','jsx','syntax','rules']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q248","original_type":"multiple-choice","topic":"JSX","subcategory":"JSX","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '799b96de-ec5b-4cd0-ad39-5390bb756a58',
          'What is the reason behind multiple JSX tags to be wrapped?',
          'JSX compiles to JavaScript function calls, and a function can only return one value—so multiple elements must be wrapped in a parent or Fragment.',
          'multiple-choice',
          'beginner',
          4,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Without a wrapper, the transpiler would produce invalid JavaScript (multiple return values).',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','jsx','fragments','compilation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q249","original_type":"open-ended","topic":"JSX","subcategory":"JSX","sample_answers":["JSX is compiled to `React.createElement()` calls, and a function can only return one value—so multiple elements need a common parent.","React 16+ introduced Fragments (`<>...</>`) to avoid unnecessary DOM wrappers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '03e6f60a-54ff-4a88-b4fe-cdaa7ddb47e5',
          'How do you prevent mutating array variables?',
          'Avoid mutation methods (`push`, `pop`, `sort`, `reverse`). Use non-mutating methods (`map`, `filter`, `slice`) or spread syntax to create new arrays.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React and Redux rely on immutability to detect changes via reference comparison.',
          NULL,
          ARRAY[]::text[],
          ARRAY['javascript','immutability','arrays','react']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q250","original_type":"open-ended","topic":"Immutable Data Structures","subcategory":"Shallow vs Deep Copy","sample_answers":["Instead of `arr.push(item)`, use `[...arr, item]`. Instead of `arr.sort()`, use `[...arr].sort()`.","Non-mutating methods like `map` and `filter` return new arrays, preserving immutability for state updates."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a0f3473a-4202-4892-8471-f5546b9d726d',
          'What are capture phase events?',
          'Capture phase events (e.g., `onClickCapture`) fire during the downward phase of event propagation, before the target and bubbling phases.',
          'multiple-choice',
          'advanced',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'They’re useful for analytics or global handlers that need to run before child event handlers.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','events','capture-phase','dom']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q251","original_type":"open-ended","topic":"Event Bubbling & Capturing","subcategory":"DOM Events","sample_answers":["`onClickCapture` fires from root to target during the capture phase, even if child events call `stopPropagation()`.","Order: capture handlers (top-down) → target handler → bubble handlers (bottom-up)."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6f1d6473-fd60-4c48-a990-86e86b90cc48',
          'How does React update the screen in an application?',
          'React updates the UI in three steps: (1) Triggering a render (initial or state update), (2) Rendering components recursively, (3) Committing minimal DOM changes.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React uses a render-commit cycle: it first computes what to render, then applies only necessary changes to the DOM for performance.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','rendering','dom','reconciliation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q252","original_type":"open-ended","topic":"Rendering","subcategory":"React Basics","sample_answers":["React triggers a render on mount or state change, recursively calls component functions to build a virtual DOM, then commits minimal real DOM updates.","This three-step process ensures efficient UI updates without unnecessary repaints or reflows."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4dae9f52-e19a-49bf-b573-e42d61e09ce4',
          'How does React batch multiple state updates?',
          'React groups multiple state updates in event handlers into a single re-render (batching). React 18 extends this to async code (automatic batching).',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Automatic batching in React 18 ensures that even async updates (e.g., in fetch callbacks) trigger only one re-render, improving performance.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','batching','state','performance']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q253","original_type":"open-ended","topic":"State Updates","subcategory":"State Management","sample_answers":["React batches multiple `setState` calls in the same event handler into one re-render. In React 18, this works even in promises and timeouts.","Example: calling `setA()` and `setB()` in a fetch callback causes only one re-render, not two."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8e13ec56-2814-4e6d-b036-6a481651042c',
          'Is it possible to prevent automatic batching?',
          'Yes, using `flushSync` from `react-dom` to force immediate DOM updates and disable batching for specific state changes.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '`flushSync` forces React to process state updates immediately, useful when you need DOM to reflect state before next line executes.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','flushsync','batching','dom']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q254","original_type":"open-ended","topic":"State Updates","subcategory":"State Management","sample_answers":["`flushSync(() => { setA(a+1); }); setB(b+1);` causes two re-renders: one after `setA`, another after `setB`.","Use sparingly—it defeats performance benefits of batching and should only be used when DOM measurement is required mid-update."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'cbea8afc-50e4-41bc-bcf1-a845b594f093',
          'What is React hydration?',
          'Hydration attaches event handlers and state to server-rendered static HTML, making it interactive on the client.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'After server sends pre-rendered HTML, `hydrateRoot` makes it interactive by attaching React event system and state.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','hydration','ssr','seo']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q255","original_type":"open-ended","topic":"Hydration","subcategory":"Server-Side Rendering","sample_answers":["Hydration is the process where React takes static HTML from the server and ''activates'' it by attaching event listeners and state.","It enables fast initial load (SEO-friendly) with full interactivity, bridging server and client rendering."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9caaba99-ce06-4b0c-b33c-bfe88cc7c3ce',
          'How do you update objects inside state?',
          'Never mutate state objects directly. Create a new object using spread syntax: `setUser({ ...user, name: ''New'' })`.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React relies on object reference comparison; mutating state directly won’t trigger re-renders.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','state','immutability','objects']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q256","original_type":"open-ended","topic":"Immutable State","subcategory":"State Management","sample_answers":["Use spread syntax to create a new object: `setUser({ ...user, firstName: e.target.value })` instead of `user.firstName = ...`.","Direct mutation bypasses React’s change detection, so the UI won’t update even if state changes."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6810dbea-a99b-4289-8a10-48da302f639c',
          'How do you update nested objects inside state?',
          'Use nested spread syntax: `setUser({ ...user, address: { ...user.address, country: ''Germany'' } })`.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Spread is shallow, so nested objects require spreading at each level to preserve immutability.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','nested-state','immutability','objects']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q257","original_type":"open-ended","topic":"Immutable State","subcategory":"State Management","sample_answers":["For `user.address.country`, update with: `setUser({ ...user, address: { ...user.address, country: ''Germany'' } })`.","This ensures a new reference for both the top-level object and the nested object, triggering re-renders correctly."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '0ab56ef8-1bc6-4463-8355-cfe2e3b779dc',
          'How do you update arrays inside state?',
          'Avoid mutating methods (`push`, `pop`). Use non-mutating methods (`filter`, `map`, spread) to create new arrays.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'React compares array references; mutating the original array won’t trigger a re-render.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','arrays','immutability','state']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q258","original_type":"open-ended","topic":"Immutable State","subcategory":"State Management","sample_answers":["To add an item: `setTodos([...todos, newItem])`. To remove: `setTodos(todos.filter((_, i) => i !== index))`.","Never use `todos.push()` directly—always create a new array instance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '680a7354-e552-4e95-b8f9-28d5a07c18eb',
          'How do you use immer library for state updates?',
          'Use `useImmer` to write mutable-style code that produces immutable updates via proxies.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Immer lets you write `draft.address.country = ''Germany''` while ensuring the final state is immutable.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','immer','immutability','state']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q259","original_type":"open-ended","topic":"Immer","subcategory":"State Management","sample_answers":["Install `use-immer`, then `const [user, setUser] = useImmer(initialState); setUser(draft => { draft.address.country = ''Germany''; });`","Immer uses proxies to track mutations and produce a new immutable state object automatically."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f4ec6f69-b39b-4b69-954f-6aa0d78232b3',
          'What are the benefits of preventing direct state mutations?',
          'Prevents bugs, enables predictable re-renders, supports time-travel debugging, and aligns with React’s declarative model.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Allows faster direct DOM manipulation","isCorrect":false},{"id":"b","text":"Enables predictable re-renders, debugging, and performance optimizations","isCorrect":true},{"id":"c","text":"Reduces bundle size","isCorrect":false},{"id":"d","text":"Makes code more verbose","isCorrect":false}]',
          NULL,
          'Immutability ensures React can detect changes via reference comparison, enabling performance optimizations and debugging tools.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','immutability','state','debugging']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q260","original_type":"multiple-choice","topic":"Immutable State","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6aa336f3-9ccd-4efd-a401-f4a5c57f5133',
          'What are preferred and non-preferred array operations for updating state?',
          'Preferred: `concat`, `...`, `filter`, `map`, `slice`. Non-preferred: `push`, `pop`, `splice`, direct assignment, `sort`, `reverse`.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Use `push` and `splice` for performance","isCorrect":false},{"id":"b","text":"Preferred: concat/spread/filter/map; Non-preferred: push/pop/splice/sort","isCorrect":true},{"id":"c","text":"All array methods are safe","isCorrect":false},{"id":"d","text":"Only `slice` is safe","isCorrect":false}]',
          NULL,
          'Non-mutating methods return new arrays, preserving immutability; mutating methods change the original array.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','arrays','immutability','state']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q261","original_type":"multiple-choice","topic":"Immutable State","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '756b91b4-3809-48f7-a834-218b8d3f5399',
          'What happens by defining nested function components?',
          'Defining components inside other components causes unnecessary re-renders and performance issues due to new identity on every render.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Nested components get a new identity each render, breaking memoization and causing child re-renders even when props haven’t changed.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','nested-components','performance','optimization']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q262","original_type":"open-ended","topic":"Component Definition","subcategory":"Performance Optimization","sample_answers":["Defining a component inside another creates a new function on every render, so `React.memo` won’t work and children re-render unnecessarily.","Always define components at the top level or outside the parent component to preserve referential identity."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'db02cc99-73d2-419b-884d-fc256cbb393a',
          'Can I use keys for non-list items?',
          'Yes. Keys help React identify components beyond lists, such as toggling between different component types.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'Keys are used whenever React needs to distinguish between elements of the same type, not just in lists.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','keys','components','reconciliation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q263","original_type":"true-false","topic":"Keys","subcategory":"Lists and Keys","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1ae04316-0251-4287-9e25-a15da075f497',
          'What are the guidelines for writing reducers?',
          '1. Reducers must be pure (no side effects). 2. Each action should represent a single user intent, even if it updates multiple state fields.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Reducers can make API calls","isCorrect":false},{"id":"b","text":"Reducers must be pure; actions should represent single user intents","isCorrect":true},{"id":"c","text":"Each state field needs its own action","isCorrect":false},{"id":"d","text":"Reducers should mutate state for performance","isCorrect":false}]',
          NULL,
          'Pure reducers ensure predictability and testability; single-intent actions improve debugging and time-travel.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','reducers','redux','pure-functions']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q264","original_type":"multiple-choice","topic":"Reducers","subcategory":"State Management","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '55c5b419-b344-4f9b-8ad8-6d3bee19c891',
          'How does ReactJS work behind the scenes?',
          'React uses Virtual DOM, Fiber architecture, reconciliation, and commit phases to efficiently update UI with minimal DOM changes.',
          'multiple-choice',
          'advanced',
          9,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Fiber breaks work into units, enables interruptible rendering, and uses scheduler for priority-based updates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','fiber','virtual-dom','reconciliation']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q265","original_type":"open-ended","topic":"Fiber Architecture","subcategory":"Virtual DOM","sample_answers":["React builds a Virtual DOM tree, reconciles it with the previous tree using a diffing algorithm, then commits minimal real DOM changes in the commit phase.","Fiber architecture allows React to pause, resume, and prioritize work, enabling concurrent features like Suspense and time-slicing."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '11fdd44b-14e9-4f45-b64d-6d3825fab8e3',
          'How is `useReducer` different from `useState`?',
          'useState: simple state, direct updates. useReducer: complex state, action-based updates, logic in reducer, more testable.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"useReducer is only for Redux","isCorrect":false},{"id":"b","text":"useState: simple state; useReducer: complex state with centralized logic","isCorrect":true},{"id":"c","text":"useState cannot hold objects","isCorrect":false},{"id":"d","text":"useReducer causes more re-renders","isCorrect":false}]',
          NULL,
          '`useReducer` centralizes update logic, making it ideal for complex state with multiple sub-values or dependencies.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','usereducer','usestate','hooks']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q266","original_type":"multiple-choice","topic":"useReducer","subcategory":"React Hooks","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '860b03c0-f2d5-416d-86f6-093d69331daa',
          'What is useContext? What are the steps to follow for useContext?',
          'Steps: (1) Create context with `createContext()`, (2) Wrap with `Provider`, (3) Consume with `useContext()` in child components.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          '`useContext` eliminates prop drilling by allowing components to access shared state from a Provider.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','context-api','usecontext','state-management']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q267","original_type":"open-ended","topic":"Context API","subcategory":"Context API","sample_answers":["1. `const ThemeContext = createContext();` 2. `<ThemeContext.Provider value=\"dark\"><App /></ThemeContext.Provider>` 3. `const theme = useContext(ThemeContext);`","This pattern is ideal for themes, auth, or any global state that many components need."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1c3d58b9-b84b-4e59-af28-9d178cd03ea8',
          'What are the use cases of useContext hook?',
          'Theme switching, auth state, localization, modal visibility, and global state when combined with useReducer.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Only for passing props to immediate children","isCorrect":false},{"id":"b","text":"Theme, auth, i18n, modals, and global state with useReducer","isCorrect":true},{"id":"c","text":"Replacing all useState calls","isCorrect":false},{"id":"d","text":"Only for class components","isCorrect":false}]',
          NULL,
          'Context is perfect for data that needs to be accessed by many components at different nesting levels.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','usecontext','global-state','theming']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q268","original_type":"multiple-choice","topic":"Context API","subcategory":"Context API","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2df893ef-e807-4270-b781-c6a412ad81b8',
          'When to use client and server components?',
          'Client: interactivity, state, effects, browser APIs. Server: data fetching, backend access, sensitive info, reducing JS bundle.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Use client components for all data fetching","isCorrect":false},{"id":"b","text":"Client: interactivity/state; Server: data fetching/sensitive logic","isCorrect":true},{"id":"c","text":"Server components can use useState","isCorrect":false},{"id":"d","text":"Client components are always faster","isCorrect":false}]',
          NULL,
          'Server Components run only on the server, have no interactivity, but can access databases directly and reduce client JS.',
          NULL,
          ARRAY[]::text[],
          ARRAY['nextjs','server-components','client-components','rsc']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q269","original_type":"multiple-choice","topic":"App Router","subcategory":"Next.js Basics","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '54ca0ad8-2e89-4697-82ec-e3e2a4c107ee',
          'What are the differences between page router and app router in Next.js?',
          'Pages Router: file-based, client-side navigation. App Router: React Server Components, nested layouts, streaming, and built-in Suspense.',
          'multiple-choice',
          'advanced',
          8,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'App Router is the modern Next.js architecture with server-first rendering, layouts, and better data fetching.',
          NULL,
          ARRAY[]::text[],
          ARRAY['nextjs','app-router','pages-router','routing']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q270","original_type":"open-ended","topic":"App Router vs Pages Router","subcategory":"Next.js Basics","sample_answers":["Pages Router uses `pages/` directory with client-side routing. App Router uses `app/` with server components, nested layouts, and streaming.","App Router supports React Server Components, Suspense for data, and automatic code splitting by route."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7b6abe44-844c-41c6-8202-aa28da6e08ca',
          'Can you describe the useMemo() Hook?',
          '`useMemo` caches expensive calculations and only recomputes when dependencies change.',
          'multiple-choice',
          'intermediate',
          7,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'It prevents unnecessary recalculations on every render, improving performance for derived data.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','usememo','performance','hooks']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q271","original_type":"open-ended","topic":"useMemo","subcategory":"React Hooks","sample_answers":["`const filteredUsers = useMemo(() => users.filter(u => u.name.includes(search)), [search]);` only filters when `search` changes.","Use `useMemo` for expensive operations like sorting, filtering, or complex computations that depend on props or state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7dc20802-7ff4-4cfd-936e-d9ae02c07dfa',
          'Can Hooks be used in class components?',
          'No. Hooks are only for function components. Class and function components can coexist in the same app.',
          'true-false',
          'beginner',
          4,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'Hooks rely on call order, which is only guaranteed in function components.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','hooks','class-components','function-components']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q272","original_type":"true-false","topic":"React Hooks","subcategory":"React Hooks","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a5d651b3-21d8-4f74-8658-518e0de69437',
          'What is an updater function? Should it be used in all cases?',
          'An updater function is `setState(prev => newValue)`. Use it when state depends on previous state; not needed for static values.',
          'multiple-choice',
          'intermediate',
          6,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Updater functions ensure you always have the latest state, avoiding stale closures in async or batched updates.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','setstate','updater-function','state']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q273","original_type":"open-ended","topic":"State Updates","subcategory":"State Management","sample_answers":["Use `setCount(c => c + 1)` when incrementing; use `setName(''John'')` for static values. The former avoids stale state issues.","In event handlers with multiple updates, updater functions guarantee correct sequencing: `setC(c=>c+1); setC(c=>c+1)` adds 2."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'e4895d2e-f3a6-4898-a07b-4a6b6a9a8c0d',
          'Can useState take a function as an initial value?',
          'Yes. `useState(() => expensiveComputation())` for lazy initialization—runs only once on mount.',
          'true-false',
          'intermediate',
          5,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'The initializer function runs only once, avoiding expensive computation on every render.',
          NULL,
          ARRAY[]::text[],
          ARRAY['react','usestate','lazy-initialization','hooks']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"q274","original_type":"true-false","topic":"useState","subcategory":"React Hooks","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"system","technology":"React"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2024-01-01T00:00:00.000Z',
          '2024-01-01T00:00:00.000Z'
        );;