INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'bc0fd15e-047b-494e-b6c4-038c9e9fc2dd',
          'What is the difference between vertical and horizontal scaling in frontend systems?',
          'Explain how vertical and horizontal scaling apply to frontend deployments.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Vertical scaling means adding more power (CPU/RAM) to a single server. Horizontal scaling means adding more servers and distributing traffic using load balancers or CDNs.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q121","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Vertical scaling means adding more power (CPU/RAM) to a single server. Horizontal scaling means adding more servers and distributing traffic using load balancers or CDNs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3d915897-9010-40bd-8d39-6192f2151067',
          'How do CDNs help with frontend scalability?',
          'Explain the role of Content Delivery Networks in frontend performance and scalability.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CDNs distribute static assets across global edge servers. This reduces latency, improves performance, and reduces load on origin servers.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q122","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CDNs distribute static assets across global edge servers. This reduces latency, improves performance, and reduces load on origin servers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'eacffa1d-9819-41b6-a1ff-ee96beecdc20',
          'What is edge computing and how can frontend apps benefit from it?',
          'Explain edge computing in the context of frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Edge computing runs code closer to users, reducing latency. Frontend apps benefit from edge functions for caching, authentication, and A/B testing.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q123","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Edge computing runs code closer to users, reducing latency. Frontend apps benefit from edge functions for caching, authentication, and A/B testing."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'eb39abd0-e8d6-4b6c-8d06-6da79cf47b68',
          'What is serverless frontend hosting?',
          'Describe serverless frontend hosting platforms like Vercel or Netlify.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Serverless hosting platforms automatically scale static sites and serverless functions, handling SSL, CDN, and caching without manual infrastructure setup.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q124","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Serverless hosting platforms automatically scale static sites and serverless functions, handling SSL, CDN, and caching without manual infrastructure setup."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'b2c16489-2808-4aa5-b4bd-074b8b25019d',
          'What is blue-green deployment and how does it apply to frontend apps?',
          'Explain blue-green deployment strategy in frontend deployments.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Blue-green deployment maintains two environments: blue (current) and green (new). After testing the green environment, traffic is switched with zero downtime.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q125","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Blue-green deployment maintains two environments: blue (current) and green (new). After testing the green environment, traffic is switched with zero downtime."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '8a781df3-bc12-48a5-9399-37bc460184ca',
          'What is canary release and why is it useful for frontend apps?',
          'Describe canary release strategy in frontend deployment.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Canary releases gradually roll out a new version to a small subset of users. If no issues arise, it expands to all users. Useful for catching bugs early.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q126","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Canary releases gradually roll out a new version to a small subset of users. If no issues arise, it expands to all users. Useful for catching bugs early."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '95d2d4eb-d642-4cc8-b53b-c066e2f9058b',
          'What are micro-frontends and how do they improve scalability?',
          'Explain the concept of micro-frontends and their trade-offs.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Micro-frontends split a large frontend into smaller, independently deployable apps. They improve scalability and team autonomy but add complexity in integration and shared state.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q127","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Micro-frontends split a large frontend into smaller, independently deployable apps. They improve scalability and team autonomy but add complexity in integration and shared state."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c3187cf5-1416-4619-87cf-9777a074b727',
          'What is SSR caching and why is it important for scaling Next.js apps?',
          'Describe server-side rendering (SSR) caching in frontend applications.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'SSR caching stores rendered HTML from server-side rendering, reducing repeated computations. It improves response times and scales Next.js apps under high traffic.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q128","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["SSR caching stores rendered HTML from server-side rendering, reducing repeated computations. It improves response times and scales Next.js apps under high traffic."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'f7aa0745-8334-4ccc-85da-de9386361d5b',
          'How does load balancing work for frontend applications?',
          'Explain load balancing strategies in frontend system design.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Load balancers distribute traffic across multiple servers. Strategies include round-robin, least connections, and geo-based routing. This improves reliability and scalability.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q129","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Load balancers distribute traffic across multiple servers. Strategies include round-robin, least connections, and geo-based routing. This improves reliability and scalability."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'adb5d0d2-86e3-4aea-98c6-f46e77a20bd6',
          'What is progressive rollout in frontend deployments?',
          'Describe progressive rollout strategy in frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Progressive rollout gradually releases new features to specific user groups, regions, or percentages of traffic. It minimizes risk and enables monitoring of issues before full release.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q130","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Progressive rollout gradually releases new features to specific user groups, regions, or percentages of traffic. It minimizes risk and enables monitoring of issues before full release."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '877bb83d-aac0-4060-930b-47bdb13b4ae2',
          'What is frontend observability and why is it important?',
          'Explain what observability means for frontend applications and how it differs from backend observability.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Frontend observability provides insights into client-side performance, errors, and user interactions. It''s important for detecting issues that backend monitoring cannot catch, like slow rendering or script errors in browsers.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q131","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Frontend observability provides insights into client-side performance, errors, and user interactions. It''s important for detecting issues that backend monitoring cannot catch, like slow rendering or script errors in browsers."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '97c952eb-79e8-486b-81ba-c51960172d7e',
          'What are Real User Monitoring (RUM) tools?',
          'Describe RUM and how it helps improve frontend system design.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'RUM tools capture real user interactions, measuring page load time, errors, and responsiveness directly from user devices, giving true performance insights.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q132","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["RUM tools capture real user interactions, measuring page load time, errors, and responsiveness directly from user devices, giving true performance insights."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '9dbd0595-5cfd-436f-a4a5-387e44a59471',
          'What is Synthetic Monitoring and how is it different from RUM?',
          'Compare synthetic monitoring with real user monitoring for frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Synthetic monitoring simulates user interactions with scripts","isCorrect":true,"explanation":""},{"id":"o2","text":"RUM measures actual user interactions","isCorrect":true,"explanation":""},{"id":"o3","text":"Synthetic monitoring always gives more accurate results than RUM","isCorrect":false,"explanation":""},{"id":"o4","text":"RUM does not work for frontend applications","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Synthetic monitoring simulates user interactions with scripts',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q133","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '68b7c5ae-5ef0-4a64-ac15-1f1642143721',
          'What are Core Web Vitals and why are they important?',
          'Explain Google''s Core Web Vitals and their impact on frontend design and SEO.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Core Web Vitals (LCP, FID, CLS) are user-focused performance metrics. They measure load speed, interactivity, and visual stability. They directly affect SEO rankings and user experience.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q134","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Core Web Vitals (LCP, FID, CLS) are user-focused performance metrics. They measure load speed, interactivity, and visual stability. They directly affect SEO rankings and user experience."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '530ecb01-6efa-4d42-baf3-8b6e679be4dd',
          'How can you capture and log JavaScript errors in production?',
          'Explain different ways to handle and log frontend errors.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Use `window.onerror` and `unhandledrejection` to capture errors, then send them to monitoring tools like Sentry, Datadog, or custom APIs for logging and alerting.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q135","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use `window.onerror` and `unhandledrejection` to capture errors, then send them to monitoring tools like Sentry, Datadog, or custom APIs for logging and alerting."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '2cefe52f-6283-49f8-9fc4-63e13748c40b',
          'What is distributed tracing and how does it apply to frontend apps?',
          'Explain distributed tracing in microservices and how frontend can participate.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Distributed tracing follows a request across multiple services. Frontend apps can pass trace IDs in headers, enabling correlation between frontend interactions and backend service performance.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q136","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Distributed tracing follows a request across multiple services. Frontend apps can pass trace IDs in headers, enabling correlation between frontend interactions and backend service performance."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6d2e940b-9097-4902-9e94-1580f78b2551',
          'How do you monitor frontend API calls?',
          'Discuss ways to track the performance and errors of API calls from the frontend.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'You can wrap fetch/axios calls to log response times, status codes, and errors. Monitoring tools can capture API latency and availability directly from the client side.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q137","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["You can wrap fetch/axios calls to log response times, status codes, and errors. Monitoring tools can capture API latency and availability directly from the client side."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'acded024-2216-4c32-bfc1-2cb48d221f4c',
          'What are common tools for frontend monitoring and logging?',
          'List and explain popular monitoring/logging tools used in frontend system design.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Sentry, LogRocket, Datadog, New Relic, Elastic APM, and OpenTelemetry are commonly used for frontend monitoring, logging, and observability.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q138","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Sentry, LogRocket, Datadog, New Relic, Elastic APM, and OpenTelemetry are commonly used for frontend monitoring, logging, and observability."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'a433aba8-39d3-4115-8dd0-a2beeab04f8b',
          'What is log aggregation and why is it useful in frontend observability?',
          'Explain the role of log aggregation in debugging frontend issues.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Log aggregation collects logs from multiple users and sessions into a central system. It helps identify patterns, diagnose errors, and analyze performance at scale.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q139","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Log aggregation collects logs from multiple users and sessions into a central system. It helps identify patterns, diagnose errors, and analyze performance at scale."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '3766a81d-02e3-4e6d-9b1b-6d8cdeb707a1',
          'What is the difference between proactive and reactive monitoring?',
          'Compare proactive and reactive monitoring in frontend system design.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Proactive monitoring aims to detect issues before users are impacted","isCorrect":true,"explanation":""},{"id":"o2","text":"Reactive monitoring only responds after an issue is reported","isCorrect":true,"explanation":""},{"id":"o3","text":"Proactive monitoring is not possible for frontend apps","isCorrect":false,"explanation":""},{"id":"o4","text":"Reactive monitoring uses tools like alerts and dashboards","isCorrect":false,"explanation":""}]',
          NULL,
          'The correct answer is: Proactive monitoring aims to detect issues before users are impacted',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q140","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '95b16fd0-ecd9-4655-ab57-ba780512607a',
          'What is XSS (Cross-Site Scripting) and how can frontend apps prevent it?',
          'Explain XSS attacks and mitigation techniques in frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'XSS allows attackers to inject malicious scripts. Prevention includes escaping user input, using Content Security Policy (CSP), and avoiding dangerous APIs like innerHTML.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q141","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["XSS allows attackers to inject malicious scripts. Prevention includes escaping user input, using Content Security Policy (CSP), and avoiding dangerous APIs like innerHTML."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '7f02eb54-346d-464f-839f-ddfa70c433e5',
          'What is CSRF and how can it be mitigated in frontend apps?',
          'Describe CSRF attacks and frontend strategies to prevent them.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CSRF tricks users into submitting malicious requests. Mitigation includes anti-CSRF tokens, SameSite cookies, and requiring re-authentication for sensitive actions.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q142","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CSRF tricks users into submitting malicious requests. Mitigation includes anti-CSRF tokens, SameSite cookies, and requiring re-authentication for sensitive actions."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4e9fa000-f4ac-4775-82e6-925c94d72ab3',
          'What is CORS and why is it important in frontend system design?',
          'Explain CORS and how it impacts frontend API calls.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'CORS (Cross-Origin Resource Sharing) controls how browsers allow cross-domain requests. It''s important to configure properly to prevent unauthorized access while enabling required integrations.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q143","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["CORS (Cross-Origin Resource Sharing) controls how browsers allow cross-domain requests. It''s important to configure properly to prevent unauthorized access while enabling required integrations."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1e34ce2a-b2db-4e1b-851e-9958b7a89209',
          'What is HTTPS and why is it critical for frontend apps?',
          'Explain how HTTPS secures frontend communication.',
          'true-false',
          'beginner',
          10,
          '[{"id":"true","text":"True","isCorrect":false},{"id":"false","text":"False","isCorrect":true}]',
          'false',
          'No explanation provided.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q144","original_type":"true-false","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd9d6c091-83f6-4ace-bddd-a0e07526811e',
          'What is JWT and how is it used in frontend authentication?',
          'Describe JSON Web Tokens (JWT) and their role in authentication.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'JWTs are stateless tokens used for authentication. The frontend stores and sends JWTs in headers or cookies to prove user identity when making API requests.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q145","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["JWTs are stateless tokens used for authentication. The frontend stores and sends JWTs in headers or cookies to prove user identity when making API requests."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '5086218f-42d5-4590-ac53-55411af6fdeb',
          'What are HttpOnly cookies and why are they important for frontend security?',
          'Explain how HttpOnly cookies protect authentication tokens.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'HttpOnly cookies cannot be accessed via JavaScript, protecting tokens from XSS attacks. They are recommended for storing session tokens securely.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q146","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["HttpOnly cookies cannot be accessed via JavaScript, protecting tokens from XSS attacks. They are recommended for storing session tokens securely."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4e49db82-c806-456c-95f7-07d90a48d5b2',
          'What is OAuth 2.0 and how is it used in frontend applications?',
          'Describe OAuth 2.0 flows and their relevance to frontend apps.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'OAuth 2.0 is an authorization framework. Frontend apps use flows like Authorization Code with PKCE to securely authenticate users and obtain tokens.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q147","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["OAuth 2.0 is an authorization framework. Frontend apps use flows like Authorization Code with PKCE to securely authenticate users and obtain tokens."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '43c1d9c5-047b-4003-8940-d5ce06744670',
          'What is multi-factor authentication (MFA) and how is it implemented in frontend apps?',
          'Explain MFA and how frontend applications can support it.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'MFA requires multiple verification factors (e.g., password + SMS code). Frontend apps can support MFA by integrating with APIs for OTPs, push notifications, or authenticator apps.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q148","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["MFA requires multiple verification factors (e.g., password + SMS code). Frontend apps can support MFA by integrating with APIs for OTPs, push notifications, or authenticator apps."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'ea7e3ef8-61c3-467a-8a7e-3ea0ad1e11af',
          'What are signed URLs and how do they enhance frontend security?',
          'Describe signed URLs and their use cases in frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Signed URLs provide temporary, secure access to protected resources like images or files. They include a signature and expiration time, preventing unauthorized access.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q149","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Signed URLs provide temporary, secure access to protected resources like images or files. They include a signature and expiration time, preventing unauthorized access."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '24cbc5fc-ce67-47f8-8cf6-fa8eb2877a94',
          'What is rate limiting and why is it important for frontend APIs?',
          'Explain rate limiting and how it protects frontend apps.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Rate limiting restricts the number of API calls per user or IP within a time window. It prevents abuse, brute-force attacks, and protects backend resources.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q150","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Rate limiting restricts the number of API calls per user or IP within a time window. It prevents abuse, brute-force attacks, and protects backend resources."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-01-08T00:00:00Z',
          '2025-01-08T00:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '62d2059f-c666-4625-8741-0933881f3607',
          'What are the main types of tests in frontend apps?',
          'Compare unit tests, integration tests, and end-to-end (E2E) tests: purpose, scope, and where they fit in the test pyramid.',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Unit tests: small, fast, isolated","isCorrect":true,"explanation":""},{"id":"o2","text":"Integration tests: verify modules working together","isCorrect":true,"explanation":""},{"id":"o3","text":"E2E tests: full system flows in browser","isCorrect":true,"explanation":""},{"id":"o4","text":"E2E tests should replace unit tests","isCorrect":false,"explanation":""}]',
          NULL,
          'Unit tests verify small units in isolation; integration tests verify interactions between modules; E2E tests verify full flows in a real browser environment.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q151","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:00:00Z',
          '2025-10-08T11:00:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6d00ed19-8915-4e13-b1f3-728ad5d3ed1a',
          'What is the test pyramid and why should you follow it?',
          'Explain the test pyramid concept and how it guides test investment for frontend applications.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'The test pyramid recommends many fast unit tests at the bottom, fewer integration tests in the middle, and even fewer E2E tests at the top. This balances speed, reliability, and coverage.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q152","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["The test pyramid recommends many fast unit tests at the bottom, fewer integration tests in the middle, and even fewer E2E tests at the top. This balances speed, reliability, and coverage."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:01:00Z',
          '2025-10-08T11:01:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'c462406e-91db-4418-a057-b6510fdd7046',
          'How do you test React components effectively?',
          'Describe practices and tools for testing React components (rendering, interactions, state, async behavior, accessibility).',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Use React Testing Library + Jest to test rendered output and user interactions, mock network calls, test accessibility using axe, avoid implementation-detail assertions, and use snapshots sparingly.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q153","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Use React Testing Library + Jest to test rendered output and user interactions, mock network calls, test accessibility using axe, avoid implementation-detail assertions, and use snapshots sparingly."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:02:00Z',
          '2025-10-08T11:02:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '52963977-08ef-4dd3-8b4f-0f169a5065de',
          'Which tools are commonly used for E2E testing in modern frontend apps?',
          'Select the commonly used E2E testing tools and one key advantage of each (Cypress, Playwright, Selenium).',
          'multiple-choice',
          'beginner',
          10,
          '[{"id":"o1","text":"Cypress: developer-friendly, great debugging UX","isCorrect":true,"explanation":""},{"id":"o2","text":"Playwright: cross-browser automation and parallelism","isCorrect":true,"explanation":""},{"id":"o3","text":"Selenium: mature but heavier and more complex to manage","isCorrect":true,"explanation":""},{"id":"o4","text":"None of the above are used for E2E","isCorrect":false,"explanation":""}]',
          NULL,
          'Cypress and Playwright are popular for modern apps; Selenium is older and broad but more complex.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','beginner']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q154","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:03:00Z',
          '2025-10-08T11:03:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1294c6b6-f0fd-4308-976c-5514a5057e1d',
          'What causes flaky tests and how do you fix them?',
          'Explain common causes of flaky tests (timing, network, order dependency) and strategies to make tests reliable.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Flakiness can be caused by race conditions, unstable selectors, reliance on real network, or shared state. Fix by using stable selectors, mock network calls, add deterministic waits or better synchronization, isolate tests, and reset environment between runs.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q155","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Flakiness can be caused by race conditions, unstable selectors, reliance on real network, or shared state. Fix by using stable selectors, mock network calls, add deterministic waits or better synchronization, isolate tests, and reset environment between runs."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:04:00Z',
          '2025-10-08T11:04:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '6351906b-0e8f-4411-a03c-e0ca3b8f6bed',
          'Which checks should run locally vs in CI?',
          'Decide which tasks are suitable for local developer runs and which should be enforced in CI (lint, unit tests, integration, E2E, build).',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Run lint and unit tests locally before PR","isCorrect":true,"explanation":""},{"id":"o2","text":"Run full E2E suite in CI (not required for every local dev run)","isCorrect":true,"explanation":""},{"id":"o3","text":"Skip build step in CI","isCorrect":false,"explanation":""},{"id":"o4","text":"Run heavy integration tests only in CI pipelines","isCorrect":true,"explanation":""}]',
          NULL,
          'Developers should run fast checks locally; heavier/integration/E2E tests and release builds should run in CI.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q156","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:05:00Z',
          '2025-10-08T11:05:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '47bd6e42-1b43-4607-be28-0f8f6377d376',
          'How do you design a CI pipeline for a frontend app?',
          'Outline a typical CI pipeline stages for frontend: install, lint, unit tests, build, integration/E2E, artifact publish, and deploy.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Typical pipeline: checkout -> install deps -> lint -> unit tests -> build -> static analysis/security scan -> run integration/E2E in parallel -> publish artifacts -> deploy to staging -> run smoke tests -> promote to production with deployment strategy (canary/blue-green).',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q157","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Typical pipeline: checkout -> install deps -> lint -> unit tests -> build -> static analysis/security scan -> run integration/E2E in parallel -> publish artifacts -> deploy to staging -> run smoke tests -> promote to production with deployment strategy (canary/blue-green)."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:06:00Z',
          '2025-10-08T11:06:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          'd8bd9966-8211-449b-b772-d3ae7a6a7387',
          'How can you speed up test suites in CI?',
          'Discuss techniques such as test parallelization, caching node_modules, test sharding, and running only affected tests.',
          'multiple-choice',
          'advanced',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Speedups: enable CI caching for dependencies, run tests in parallel across workers, shard E2E tests by test suites, run only affected tests using changed-file detection, and use lightweight mocked E2E for quick smoke.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','advanced']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q158","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Speedups: enable CI caching for dependencies, run tests in parallel across workers, shard E2E tests by test suites, run only affected tests using changed-file detection, and use lightweight mocked E2E for quick smoke."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:07:00Z',
          '2025-10-08T11:07:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '1fc31d39-d531-4af2-9ca6-086e8cc4b54c',
          'What is visual regression testing and when should you use it?',
          'Explain visual regression testing and tools for it (Percy, Chromatic, Playwright snapshot).',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
          'c',
          'Visual regression testing captures UI screenshots and compares diffs to detect unintended UI changes. Use for design-critical components, theming changes, or when CSS changes might break layouts.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q159","original_type":"open-ended","topic":"Frontend System Design","subcategory":"","sample_answers":["Visual regression testing captures UI screenshots and compares diffs to detect unintended UI changes. Use for design-critical components, theming changes, or when CSS changes might break layouts."],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:08:00Z',
          '2025-10-08T11:08:00Z'
        );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
          '4c1f5bc2-203f-4af5-bebd-cbc4d822c367',
          'How do you enforce quality gates in CI and integrate them with code review?',
          'Describe quality gates like test coverage thresholds, linting, security scans, and how to integrate results into pull requests and CI protections.',
          'multiple-choice',
          'intermediate',
          10,
          '[{"id":"o1","text":"Fail CI build on critical lint or test failures","isCorrect":true,"explanation":""},{"id":"o2","text":"Block merge unless coverage meets threshold (e.g., >80%)","isCorrect":true,"explanation":""},{"id":"o3","text":"Ignore E2E failures permanently","isCorrect":false,"explanation":""},{"id":"o4","text":"Publish test reports and comments on PR for visibility","isCorrect":true,"explanation":""}]',
          NULL,
          'Quality gates ensure that only PRs meeting minimum quality metrics are merged; surface results in PRs for reviewer context.',
          NULL,
          [],
          ARRAY['system-design','frontend-system-design','intermediate']::text[],
          '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
          '{"original_id":"system-design-q160","original_type":"multiple-choice","topic":"Frontend System Design","subcategory":"","sample_answers":[],"time_limit":120,"related_links":[],"created_by":"admin","updated_by":"admin","technology":"System Design"}',
          'db86beef-f5b8-4ffc-93b5-6ba95a360f58',
          true,
          '2025-10-08T11:09:00Z',
          '2025-10-08T11:09:00Z'
        );;