INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e2dbbceb-84aa-484e-b353-9690b745c664',
      'What is CSS?',
      'CSS stands for Cascading Style Sheets. It is used to define styles for web pages, including design, layout, and responsiveness across devices.',
      'multiple-choice',
      'beginner',
      3,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'CSS separates content (HTML) from presentation, enabling consistent, maintainable, and responsive designs.',
      NULL,
      NULL,
      ARRAY['css','css-fundamentals','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q1","original_type":"open-ended","topic":"CSS Fundamentals","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.359Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '6545ceb0-ecf8-4850-945c-fb4caba49643',
      'What is the use of CSS ruleset?',
      'A CSS ruleset consists of a selector and a declaration block. The selector targets HTML elements, and the declaration block contains property-value pairs that define styling.',
      'multiple-choice',
      'beginner',
      4,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Each ruleset applies styles to selected elements. Declarations must end with a semicolon (except the last one), and properties define visual characteristics.',
      NULL,
      NULL,
      ARRAY['css','css-fundamentals','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q2","original_type":"open-ended","topic":"CSS Fundamentals","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '68a1fe19-889c-4442-9378-1d6cd7b62420',
      'What are the possible ways to apply CSS styles to a web page?',
      'There are three primary methods: inline styles (via `style` attribute), internal/embedded styles (in `<style>` tag), and external stylesheets (via `<link>`).',
      'multiple-choice',
      'beginner',
      5,
      '[{"id":"a","text":"Inline, internal, and external","isCorrect":true,"explanation":""},{"id":"b","text":"Only external","isCorrect":false,"explanation":""},{"id":"c","text":"Only inline","isCorrect":false,"explanation":""},{"id":"d","text":"CSS cannot be applied to HTML","isCorrect":false,"explanation":""}]',
      'c',
      'External stylesheets are preferred for maintainability, caching, and separation of concerns. Inline styles have highest specificity but hurt reusability.',
      NULL,
      NULL,
      ARRAY['css','css-fundamentals','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q3","original_type":"multiple-choice","topic":"CSS Fundamentals","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '8c9b03b0-5e21-4688-b81c-e8bc5498f070',
      'What does the cascading portion of CSS mean?',
      'Cascading refers to how CSS resolves conflicting rules by applying styles based on origin, specificity, and order—allowing author styles to override browser defaults.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Styles cascade from browser defaults → user styles → author styles. Higher-specificity or later-defined rules override earlier ones.',
      NULL,
      NULL,
      ARRAY['css','css-fundamentals','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q4","original_type":"open-ended","topic":"CSS Fundamentals","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'af5f8d07-9bf9-45bb-b93d-52ee74eb0ffe',
      'Explain new features in CSS3?',
      'CSS3 introduced selectors (`:nth-child`, `[attr^=]`), pseudo-classes (`:target`, `:not`), colors (RGBA, HSLA), rounded corners (`border-radius`), shadows (`box-shadow`, `text-shadow`), gradients, and multiple backgrounds.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"border-radius, box-shadow, gradients, RGBA, new selectors","isCorrect":true,"explanation":""},{"id":"b","text":"Only new color formats","isCorrect":false,"explanation":""},{"id":"c","text":"CSS3 removed all vendor prefixes","isCorrect":false,"explanation":""},{"id":"d","text":"CSS3 is not supported in modern browsers","isCorrect":false,"explanation":""}]',
      'c',
      'CSS3 modularized the spec and added powerful visual and layout capabilities without requiring JavaScript.',
      NULL,
      NULL,
      ARRAY['css','css3-features','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q5","original_type":"multiple-choice","topic":"CSS3 Features","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e7780465-742d-45c3-b6d0-beb02a8e0916',
      'What are the CSS selectors?',
      'CSS selectors target HTML elements for styling. Types include: universal (`*`), element (`p`), class (`.class`), ID (`#id`), attribute (`[type=''text'']`), pseudo-classes (`:hover`), pseudo-elements (`::before`), and combinators (`>`, `+`, `~`).',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Universal, element, class, ID, attribute, pseudo-classes, pseudo-elements, combinators","isCorrect":true,"explanation":""},{"id":"b","text":"Only class and ID","isCorrect":false,"explanation":""},{"id":"c","text":"Selectors are optional in CSS","isCorrect":false,"explanation":""},{"id":"d","text":"Pseudo-elements are the same as pseudo-classes","isCorrect":false,"explanation":""}]',
      'c',
      'Selectors form the foundation of CSS—they determine which elements receive which styles.',
      NULL,
      NULL,
      ARRAY['css','selectors','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q6","original_type":"multiple-choice","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'e9552ec4-52ac-4af6-83bc-19d7eb696a3a',
      'What is contextual selector?',
      'A contextual selector (or descendant selector) targets an element based on its ancestor context, e.g., `table p` selects `<p>` inside `<table>`.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'It styles elements only when they appear within a specific structural context in the HTML tree.',
      NULL,
      NULL,
      ARRAY['css','selectors','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q7","original_type":"open-ended","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'b3b16be2-ea25-4a3f-a031-44c45ef2bba4',
      'What is the difference between Pseudo-classes and pseudo-elements?',
      'Pseudo-classes (e.g., `:hover`, `:nth-child`) style elements in specific states. Pseudo-elements (e.g., `::before`, `::first-line`) style parts of an element that aren’t real HTML nodes.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Pseudo-classes: element states; Pseudo-elements: virtual parts of elements","isCorrect":true,"explanation":""},{"id":"b","text":"They are identical","isCorrect":false,"explanation":""},{"id":"c","text":"Pseudo-elements can’t insert content","isCorrect":false,"explanation":""},{"id":"d","text":"Pseudo-classes require double colons","isCorrect":false,"explanation":""}]',
      'c',
      'Pseudo-classes target existing elements in special states; pseudo-elements create virtual content or style subparts.',
      NULL,
      NULL,
      ARRAY['css','selectors','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q8","original_type":"multiple-choice","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '1b8f3d71-bcfb-4c8e-aae8-9b70ba5d5525',
      'What is Combinator selector?',
      'Combinators connect selectors to define relationships: descendant (space), child (`>`), adjacent sibling (`+`), and general sibling (`~`).',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Descendant ( ), child (>), adjacent (+), general sibling (~)","isCorrect":true,"explanation":""},{"id":"b","text":"Only child and descendant","isCorrect":false,"explanation":""},{"id":"c","text":"Combinators are deprecated","isCorrect":false,"explanation":""},{"id":"d","text":"Adjacent sibling selects all following siblings","isCorrect":false,"explanation":""}]',
      'c',
      'Combinators enable precise targeting based on element relationships in the DOM tree.',
      NULL,
      NULL,
      ARRAY['css','selectors','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q9","original_type":"multiple-choice","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'f6131892-a7fb-42eb-b021-c675f61ce9de',
      'What is the difference between class selectors and id selectors?',
      'Class selectors (`.class`) can be reused on multiple elements. ID selectors (`#id`) should be unique to a single element per page.',
      'multiple-choice',
      'beginner',
      5,
      '[{"id":"a","text":"Class is for one element; ID is for many","isCorrect":false,"explanation":""},{"id":"b","text":"Class can be reused; ID should be unique","isCorrect":true,"explanation":""},{"id":"c","text":"They are functionally identical","isCorrect":false,"explanation":""},{"id":"d","text":"ID selectors are faster in all browsers","isCorrect":false,"explanation":""}]',
      'c',
      'IDs have higher specificity than classes. While HTML allows duplicate IDs, it’s invalid and breaks accessibility and JavaScript.',
      NULL,
      NULL,
      ARRAY['css','selectors','beginner']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q10","original_type":"multiple-choice","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '39b3822b-b3b5-4c7d-bfb8-cf61c3592564',
      'What is the difference between the “nth-child()” and “nth-of-type()” selectors?',
      '`nth-child(n)` counts all siblings; `nth-of-type(n)` counts only siblings of the same element type.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      '`p:nth-of-type(2)` selects the second `<p>` among only `<p>` siblings, ignoring other elements.',
      NULL,
      NULL,
      ARRAY['css','selectors','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q11","original_type":"open-ended","topic":"Selectors","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '44de4f4d-7b4f-4814-90cc-bc665c006f63',
      'Explain CSS grid layout with example?',
      'CSS Grid is a two-dimensional layout system for rows and columns. Use `display: grid`, `grid-template-columns`, `grid-template-rows`, and `grid-area` for complex layouts.',
      'multiple-choice',
      'advanced',
      9,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Grid excels at page-level layouts with precise control over alignment, sizing, and layering.',
      NULL,
      NULL,
      ARRAY['css','css-grid','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q12","original_type":"open-ended","topic":"CSS Grid","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'eecb68aa-d2ae-4cfa-9365-e370d369a28d',
      'What is CSS flexbox? Write all the properties of the flexbox?',
      'Flexbox is a one-dimensional layout model for distributing space and aligning items in rows or columns. Key properties: `flex-direction`, `justify-content`, `align-items`, `flex-wrap`, `order`, `flex-grow`, `flex-shrink`.',
      'multiple-choice',
      'intermediate',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Flexbox simplifies alignment and distribution of space among items in a container, even when their size is unknown or dynamic.',
      NULL,
      NULL,
      ARRAY['css','css-flexbox','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q13","original_type":"open-ended","topic":"CSS Flexbox","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '6a601da2-bd4d-4765-942a-503045b49917',
      'When to use CSS grid and flexbox?',
      'Use Flexbox for one-dimensional layouts (rows OR columns). Use Grid for two-dimensional layouts (rows AND columns). Flexbox is content-first; Grid is layout-first.',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"Flexbox: 1D, content-first; Grid: 2D, layout-first","isCorrect":true,"explanation":""},{"id":"b","text":"Grid is only for mobile","isCorrect":false,"explanation":""},{"id":"c","text":"Flexbox replaces Grid","isCorrect":false,"explanation":""},{"id":"d","text":"They are identical","isCorrect":false,"explanation":""}]',
      'c',
      'Flexbox handles dynamic content in a single dimension; Grid handles complex, predefined layouts in two dimensions.',
      NULL,
      NULL,
      ARRAY['css','css-layout','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q14","original_type":"multiple-choice","topic":"CSS Layout","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'ca94bafb-fe5b-47d7-8739-7fbe4516e0e1',
      'What is CSS BEM?',
      'BEM (Block Element Modifier) is a naming convention: `.block`, `.block__element`, `.block__element--modifier` for maintainable, scoped CSS.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'BEM reduces specificity conflicts, improves readability, and enables reusable, modular components.',
      NULL,
      NULL,
      ARRAY['css','css-methodologies','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q15","original_type":"open-ended","topic":"CSS Methodologies","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'b14b1119-fff0-4bb9-9677-24f48eb6881d',
      'What are the benefits of using CSS sprites?',
      'CSS sprites combine multiple images into one to reduce HTTP requests, improving load performance (though less critical with HTTP/2).',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Sprites reduce network overhead by loading one image instead of many, especially useful for icon sets.',
      NULL,
      NULL,
      ARRAY['css','css-performance','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q16","original_type":"open-ended","topic":"CSS Performance","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'a28dcca1-b43e-4ecd-bf3e-b67e0d08bc67',
      'What is tweening in CSS?',
      'Tweening (in-betweening) is generating intermediate frames between two states for smooth animations, achieved via CSS `@keyframes` and `animation`.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'CSS animations automatically interpolate between keyframes to create fluid motion without JavaScript.',
      NULL,
      NULL,
      ARRAY['css','css-animations','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q17","original_type":"open-ended","topic":"CSS Animations","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      'd91454fd-440b-4288-8b35-4995ccb3819e',
      'Explain the difference between `visibility: hidden;` and `display: none;`?',
      '`visibility: hidden` hides the element but preserves its space in the layout. `display: none` removes it from the layout flow entirely.',
      'multiple-choice',
      'intermediate',
      6,
      '[{"id":"a","text":"`visibility: hidden` preserves space; `display: none` removes from flow","isCorrect":true,"explanation":""},{"id":"b","text":"They are identical","isCorrect":false,"explanation":""},{"id":"c","text":"`display: none` preserves space","isCorrect":false,"explanation":""},{"id":"d","text":"`visibility: hidden` triggers reflow","isCorrect":false,"explanation":""}]',
      'c',
      'Use `visibility: hidden` to hide but keep layout; use `display: none` to remove completely (triggers reflow).',
      NULL,
      NULL,
      ARRAY['css','css-box-model','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q18","original_type":"multiple-choice","topic":"CSS Box Model","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '3b827625-55fd-43c7-88b2-efb5a907b090',
      'What is the purpose of the `z-index` and how a stacking context is formed?',
      '`z-index` controls stack order of positioned elements. A stacking context is created by `position` (non-static), `opacity < 1`, `transform`, `z-index`, etc.',
      'multiple-choice',
      'advanced',
      8,
      '[{"id":"a","text":"Option A","isCorrect":false},{"id":"b","text":"Option B","isCorrect":false},{"id":"c","text":"Option C","isCorrect":true},{"id":"d","text":"Option D","isCorrect":false}]',
      'c',
      'Elements with higher `z-index` appear on top, but only within their stacking context. Nested contexts are isolated.',
      NULL,
      NULL,
      ARRAY['css','css-positioning','advanced']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q19","original_type":"open-ended","topic":"CSS Positioning","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );

INSERT INTO questions (id, title, content, type, difficulty, points, options, correct_answer, explanation, test_cases, hints, tags, stats, metadata, category_id, is_active, created_at, updated_at) VALUES (
      '8e5960de-169e-494a-84a0-4c195b487c03',
      'Explain CSS position Property?',
      '`position` values: `static` (default), `relative` (offset from normal position), `absolute` (relative to nearest positioned ancestor), `fixed` (relative to viewport), `sticky` (hybrid of relative and fixed).',
      'multiple-choice',
      'intermediate',
      7,
      '[{"id":"a","text":"static, relative, absolute, fixed, sticky","isCorrect":true,"explanation":""},{"id":"b","text":"Only absolute and relative","isCorrect":false,"explanation":""},{"id":"c","text":"`fixed` is relative to parent","isCorrect":false,"explanation":""},{"id":"d","text":"`sticky` doesn’t require a threshold","isCorrect":false,"explanation":""}]',
      'c',
      'Positioning controls how elements are placed in the document flow and relative to other elements or the viewport.',
      NULL,
      NULL,
      ARRAY['css','css-positioning','intermediate']::text[],
      '{"views":0,"attempts":0,"correct_attempts":0,"average_time":0}',
      '{"original_id":"css-1-css-q20","original_type":"multiple-choice","topic":"CSS Positioning","sample_answers":[],"time_limit":60,"related_links":[],"created_by":"system","updated_by":"system","technology":"CSS"}',
      '3bd9c23e-6e43-4234-b741-ef78955a90a0',
      true,
      '2025-10-21T22:01:49.363Z',
      '2025-10-21T22:01:49.363Z'
    );;
